### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by DicksHalfwayInn** [files-community/Files#3353] opened 2021-01-30 09:21 UTC
<!-- 
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

I downloaded the app upon to try when one of your contributors told me about it

one issue I encountered... If you rename a file in a directory and then try to rename a second, the program crashes

**Comment by gave92** [comment] 2021-01-30 12:33
We are having a little trouble understanding this issue report, please reopen this issue when you have filled out the issue template.

**Comment by gave92** [comment] 2021-01-30 19:34
@DicksHalfwayInn could you update the description with what you posted on Discord (video included)? It's just too difficult to keep track of issues on Discord ;)

**Comment by gave92** [comment] 2021-01-30 19:36
Likely duplicate of #3205

**Comment by yaichenbaum** [comment] 2021-02-07 20:49
@DicksHalfwayInn We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Closed by yaichenbaum** 2021-02-07 20:49 UTC
Labels: bug, more-info, needs-triage
