### ISSUE TITLE
I can't open my folder called "Proyectos"

### ISSUE THREAD

**Issue by kaname-png** [files-community/Files#3629] opened 2021-02-19 13:45 UTC
**Describe the bug**
I try to open my app project folder in NodeJs but the application closes instantly.

**To Reproduce**
1. Go to documents
2. Press the folder called "Proyectos"
3. See error

**Expected behavior**
Press the folder called "Proyectos"

**Screenshots**

![image](https://user-images.githubusercontent.com/56084970/108510825-9ec6a480-7284-11eb-87c0-a122467de8f9.png)

![image](https://user-images.githubusercontent.com/56084970/108510960-cfa6d980-7284-11eb-890e-cf2e2e13bb26.png)

![image](https://user-images.githubusercontent.com/56084970/108511365-6d9aa400-7285-11eb-8e2c-63f1aa866f3b.png)

![proof](https://user-images.githubusercontent.com/56084970/108511489-9c187f00-7285-11eb-8ec9-ecd3303564e8.gif)

**Desktop:**
 - OS Version: Windows 10 19042.804
 - App version: v1.2.2.0

**Additional context**
The problem persists no matter how many times you restart the application. I don't know if it's because those folders have a lot of files from nodeJs projects (node_modules).

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6010351/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6010352/debug.txt)

**Comment by d2dyno1** [comment] 2021-02-19 14:00
Duplicate of #3547

**Comment by gave92** [comment] 2021-02-19 16:22
Thanks for this report. The issue should be fixed in version 1.2.3 coming to the store in a few days.
In the meantime could you try enabling the "open items with one click" option k. Files settings?

**Closed by gave92** 2021-02-19 16:22 UTC
Labels: bug

**Comment by kaname-png** [comment] 2021-02-19 16:30
> Thanks for this report. Just this time node_modules is not to blame xD. The issue should be fixed in version 1.2.3 coming to the store in a few days.
> In the meantime could you try enabling the "open items with one click" option in Files settings?

I have activated the option you mention and the problem has been solved, the application no longer closes.
