### ISSUE TITLE
Thumbnails in File don't work properly

### ISSUE THREAD

**Issue by candrapersada** [files-community/Files#2861] opened 2021-01-06 10:09 UTC
Why don't Thumbnail in File work properly? like this picture
![awww](https://user-images.githubusercontent.com/36833664/103756342-d31e3280-5041-11eb-9ae6-b3bf6cc6394b.PNG)

**Comment by gave92** [comment] 2021-01-06 10:11
Duplicate of #2660, fixed

**Closed by gave92** 2021-01-06 10:11 UTC
