### ISSUE TITLE
Bug: High CPU Usage

### ISSUE THREAD

**Issue by atxfjrotc** [files-community/Files#12160] opened 2023-04-22 17:45 UTC
### Description

Within the last week, files has started to consume huge background resources. Regularly uses 30% of my CPU, often with one of the cores pegged to 100%.

### Steps To Reproduce

Open files and wait about a minute.

### Requirements

Files should have bascially nothing going on in the background, right? It's just a file system interface, it's not like I'm giving it a hundred tasks a second.

### Files Version

2.4.62.0

### Windows Version

Windows 11 Home 22H2 22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11301966/debug.log)

**Comment by yaira2** [comment] 2023-04-23 01:32
@atxfjrotc thank you for the report, I can reproduce this on my side as well. Do you know when this issue first started happening?

**Comment by yaira2** [comment] 2023-04-23 03:36
@atxfjrotc I just tested again and the issue is no longer present 🤔 

Can you reproduce this consistently?

**Comment by yaira2** [comment] 2023-04-23 03:38
@atxfjrotc is this specific to the home page? It seems that the CPU usage goes down after navigating to a different page.

**Comment by yaira2** [comment] 2023-04-23 13:58
A fix has been implemented and will be included in the next update.

**Closed by yaira2** 2023-04-23 13:58 UTC
Labels: bug
