### ISSUE TITLE
Bug: Creating, renaming, or deleting an item causes Files to select additional items

### ISSUE THREAD

**Issue by ggtylerr** [files-community/Files#11092] opened 2023-01-26 19:09 UTC
### Description

When creating a new folder and giving it a name (and using the preview version of Files), it instead makes a folder called "New Folder", and then selects other items.

https://user-images.githubusercontent.com/28498877/214926209-4850e2c7-5f17-4221-8ff5-8246e65a0c27.mp4

This issue is more apparent in bigger directories, as there's more files and folders to select.

### Steps To Reproduce

1. Use the preview version
2. Make a new folder
3. Try to name it
4. Confirm

### Steps to fix

- Actually name the folder
- Don't select other folders / items after confirmation (maybe it's tied to the feature where you press A and you select the first file / folder that starts with A)

### Files Version

2.4.24.0

### Windows Version

Windows 11 22H2 22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10512569/debug.log)

**Comment by Josh-65** [comment] 2023-01-26 19:17
The naming issue has been fixed and will be included in the next update

**Comment by yaira2** [comment] 2023-01-26 19:44
@Josh-65 does it fix the selection issue too?

**Comment by Josh-65** [comment] 2023-01-26 19:44
No

**Comment by yaira2** [comment] 2023-02-07 05:00
@Josh-65 I can't reproduce this anymore, can you check if it's still an issue?

**Comment by ggtylerr** [comment] 2023-02-07 05:04
I'm still able to on v2.4.31.0. Not sure when building from source (kinda don't want to reinstall visual studio rn.)
It's most noticeable on directories with lots of files.

**Comment by yaira2** [comment] 2023-02-07 05:06
That might be why, I was testing in a folder with three items.

**Comment by QuaintMako** [comment] 2023-02-08 08:27
It seems to be linked to a timing issue. When using breakpoints to debug, the issue seems to not reproductible. The selected additional items are also consistent regarding to the renamed item.

Might be linked to a fire and forget call, or an await that does not work properly.

**Comment by hishitetsu** [comment] 2023-02-09 11:17
I managed to find some strange behavior.
When I created a folder, multiple ContainerContentChanging events occurred. I found one of these events has different properties than expected.
![image](https://user-images.githubusercontent.com/66369541/217797053-a6f91ea2-00bc-46cc-a329-ce7bc986f048.png)
`Item` and `ItemContainer.Content` refer to different items. Because of this, it appears to select `Visual Studio 2022` with the intention of selecting `ggg`.
I have no idea why this would happen.

**Comment by yaira2** [comment] 2023-02-09 15:41
@chingucoding

**Comment by ggtylerr** [comment] 2023-02-09 20:46
After a bit of testing, I've noticed this also happens with files, meaning it's most likely tied to general item events. Updated the title to reflect this.

**Comment by hishitetsu** [comment] 2023-02-10 13:04
I managed to find a way to fix it! I will submit a PR later.

**Closed** 2023-02-10 15:40 UTC
Labels: bug

**Comment by hecksmosis** [comment] 2023-02-11 17:47
@yair100 You should probably unpin this

**Comment by yaira2** [comment] 2023-02-12 00:59
Will do, thank you.
