### ISSUE TITLE
Some files no sounds in preview.

### ISSUE THREAD

**Issue by kaifeng80** [files-community/Files#15673] opened 2024-06-25 06:01 UTC
### Description

Some files no sounds in preview.

### Steps To Reproduce

1 select the file attached.
https://github.com/files-community/Files/assets/11383698/237e84b6-ed07-4047-86f8-71e3cb0255a3
2 play it in preview window

no sound.

### Requirements

Fix it please

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3737

### Log File

[debug.log](https://github.com/user-attachments/files/15965569/debug.log)

**Comment by 0x5bfa** [comment] 2024-06-25 07:10
Thanks for the feedback!

Could you let us know:
- Type of the video
- Where did you download or produce?
- If this issue is still present in preview version https://files.community/download

**Comment by yaira2** [comment] 2024-06-25 14:35
@0x5bfa v3.5.0 is the latest version.

**Comment by kaifeng80** [comment] 2024-06-26 14:25
Type of the video?
mp4 video. I have uploaded it. 
the video play has sound in Chrome and other players.
I think you should find out why this kind of video has no sound in the preview window.

**Comment by Josh65-2201** [comment] 2024-06-26 14:32
I believe the issue is with Windows not supporting the Opus audio codec natively, that's why it doesn't play audio in preview pane, Same thing for Windows Media player.

**Comment by yaira2** [comment] 2024-06-26 14:34
Files uses the same media player as the Windows Media player, so that would help confirm.

**Comment by Josh65-2201** [comment] 2024-06-26 14:36
Just converted the video to use mp3 audio codec and audio plays. I think this can be closed as not supported by Windows.

**Comment by yaira2** [comment] 2024-06-26 14:54
Does it work in VLC? Theoretically we can support the shell preview for VLC if that'll help.

**Comment by Josh65-2201** [comment] 2024-06-26 14:56
It does in VLC, probably any external media player

**Comment by yaira2** [comment] 2024-08-22 01:22
@kaifeng80, it turns out this scenario isn’t natively supported by Windows, and therefore won’t work in Files either. However, you might find the QuickLook integration helpful, as it includes support for many non-native file formats. You can learn more about it on our documentation site https://files.community/docs/features/integrations.

**Closed by yaira2** 2024-08-22 01:22 UTC
Labels: bug, needs - additional info
