### ISSUE TITLE
Macos Finder Grid Style

### ISSUE THREAD

**Issue by khrmndgn** [files-community/Files#2258] opened 2020-11-07 15:34 UTC
a viewing option like in the photo would be great
![ColumnView640](https://user-images.githubusercontent.com/11201074/98445275-dd967b80-2127-11eb-8f8d-70ef127a7e78.jpg)

**Comment by duke7553** [comment] 2020-11-07 15:36
Duplicate of #147

**Closed by duke7553** 2020-11-07 15:36 UTC
Labels: feature_request
