### ISSUE TITLE
Bug: App crashes when opening excel file

### ISSUE THREAD

**Issue by chadiaboughayda** [files-community/Files#13609] opened 2023-10-30 13:05 UTC
### Description

Files crashing after minutes  .. Why?

### Steps To Reproduce

opening files
when opening an excel file 
files crashes

### Requirements

- e.g. Fix crash that occurs when...
reopen files the same happens 

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2506

### Log File

information to conTACT YOU WITH NOTIFICATION

**Comment by chadiaboughayda** [comment] 2023-10-30 13:13
[debug.log](https://github.com/files-community/Files/files/13205463/debug.log)

**Comment by Josh65-2201** [comment] 2023-10-30 13:16
Did you check if it's an issue in the preview build?

**Comment by chadiaboughayda** [comment] 2023-10-30 13:22
Please explain ..

I have send the log file

**Comment by Josh65-2201** [comment] 2023-10-30 13:25
Click this link https://files.community/download > Click `Download insider preview` > Open the file that was downloaded > Click install >  Look for `Files - Preview` in the start menu > see if you can reproduce your issue.

**Comment by yaira2** [comment] 2023-11-02 15:56
@chadiaboughayda is this always with an Excel file?

**Comment by chadiaboughayda** [comment] 2023-11-02 16:16
Yes its an excel file

**Comment by yaira2** [comment] 2023-11-02 16:21
Does it happen with any other file formats as well?

**Comment by chadiaboughayda** [comment] 2023-11-02 16:50
Yes

**Comment by chadiaboughayda** [comment] 2023-11-02 16:59
Pdf

**Comment by yaira2** [comment] 2023-11-12 01:49
@chadiaboughayda is this still happening in v3.0.3? If the issue is still occurring, can you upload the updated log file?

**Comment by chadiaboughayda** [comment] 2023-11-12 09:46
Yes it is still happening when using macro enabled excel file

**Comment by yaira2** [comment] 2023-11-12 15:32
Can you please upload the log file?

**Comment by yaira2** [comment] 2023-11-13 14:48
@chadiaboughayda I'm sorry if it's frustrating, we're trying to help but you haven't uploaded the log file from v3 (unless you attached it via email which doesn't work, it needs to be uploaded directly to GitHub). Normally the original log file is enough, but in this case we made improvements to the logging and need the updated file.

**Comment by chadiaboughayda** [comment] 2023-11-13 16:15
Please send the steps again

**Comment by yaira2** [comment] 2023-11-13 17:09
You can attach the log file by clicking the "attach" button.
![image](https://github.com/files-community/Files/assets/39923744/32ac44de-68dc-4203-8762-4f6afd1d7206)

**Comment by chadiaboughayda** [comment] 2023-11-13 17:18
How to get the log please

**Comment by Josh65-2201** [comment] 2023-11-13 17:21
You can get it in Files settings > About > Open log folder.

**Comment by chadiaboughayda** [comment] 2023-11-14 09:13
[debug.log](https://github.com/files-community/Files/files/13346839/debug.log)

**Comment by chadiaboughayda** [comment] 2023-11-14 09:14
major crashed happen on macro enable excel files

**Comment by yaira2** [comment] 2023-11-15 03:11
Thank you

**Comment by yaira2** [comment] 2024-01-23 18:16
@chadiaboughayda

**Comment by yaira2** [comment] 2024-01-28 16:33
This appears to be resolved in the preview version. If you're still able to repro the issue, please let us know and we'll take another look.

**Closed by yaira2** 2024-01-28 16:33 UTC
Labels: bug, help wanted, more-info, crash
