### ISSUE TITLE
 Changing theme enables the details panel

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3252] opened 2021-01-24 11:17 UTC
Changing the theme to light or dark causes the details pane to be enabled

![panel](https://user-images.githubusercontent.com/61259627/105628550-54d0d700-5e1c-11eb-8742-4a9bf49537d4.gif)

**Comment by tsvietOK** [comment] 2021-01-24 13:38
For me details panel enables when navigating to and from Settings page.

**Comment by tsvietOK** [comment] 2021-01-24 13:41
FYI: @winston-de

**Comment by winston-de** [comment] 2021-01-24 20:12
This issue seems to be caused by the bindings to the PreviewPaneEnabled throwing false positives after switching tabs or closing settings. I put a breakpoint on the setter, and the value is definitely not being changed. 
I'm unsure what's causing this behavior or how to fix it.
If anyone has any advice or ideas, I'd greatly appreciate it.

**Comment by yaichenbaum** [comment] 2021-01-25 14:19
@XPoppyX This issue should be resolved with #3284.

**Closed** 2021-01-25 14:18 UTC
Labels: bug, triage approved
