### ISSUE TITLE
Context menu sometimes closes when hovering over an item

### ISSUE THREAD

**Issue by padredalvi** [files-community/Files#6052] opened 2021-09-05 04:24 UTC
### Description

hovering over an option in context menu which has more options closes the menu

### Steps To Reproduce

1. right click to open the context menu
2. hover to any button that is expandable

### Expected behavior

more buttons should appear instead of context menu closing

### Files Version

v2.0.0.0

### Windows Version

Windows 11 Dev 22449.1000

### Relevant Assets

I'll put the link instead since the video recording was too big for github
LINK: https://drive.google.com/file/d/1gQpRGRmCw143VaVJaeZJ1_8kGJapnIL7/view?usp=sharing

**Comment by hez2010** [comment] 2021-09-07 10:17
This is possibly caused by the latest dev insider of Windows 11 (22449.1000).

**Comment by hez2010** [comment] 2021-09-11 04:01
This issue has been fixed since Windows 11 Dev Insider Build 22454

**Comment by Seraphim7** [comment] 2021-09-19 22:45
This same issue is happening to me with v2,0 but it is on Windows 11 build 22458

**Comment by hez2010** [comment] 2021-09-30 16:05
This issue has been fixed in Windows 11 Dev Insider Build 22468.

**Closed** 2022-10-03 06:27 UTC
Labels: bug
