### ISSUE TITLE
Takes forever to delete files

### ISSUE THREAD

**Issue by Shamatix** [files-community/Files#6502] opened 2021-10-14 16:42 UTC
### Description

Takes forever to delete files
If I try to delete a file, either by pressing delete or right click -> delete, the popup of "Are you sure you want to delete this file", rarely shows and when it does, it shows 5+ minutes later.
https://imgur.com/baj7dc5

### Steps To Reproduce

Try and delete a file

### Expected behavior

For the popup to show instantly so I can press yes im sure to delete the file without having to wait.
I recorded the gif and posted it in the files discord (same as posted in the description)
and the popup (https://i.imgur.com/wK4b127.png) showed 6 minutes later..

### Files Version

2.0.13

### Windows Version

Windows 11

**Comment by yaichenbaum** [comment] 2021-10-31 18:57
@gave92 are you able to reproduce this on `main`?

**Comment by gave92** [comment] 2021-10-31 19:01
Nope

**Comment by yaichenbaum** [comment] 2021-10-31 19:07
> Nope

Should have been fixed in v2.0.13, right? #6109

**Comment by gave92** [comment] 2021-10-31 19:34
#6109 fixed the delay in the delete dialog when deleting a lot of items, this issue report seem to involve deleting a single item.

**Comment by yaichenbaum** [comment] 2021-10-31 19:43
@Shamatix are you having this issue with all files or only specific file types?

**Comment by Shamatix** [comment] 2021-11-01 18:11
@yair100 I have tried .pdf, .xml, and .log files and neither works. It does not matter if I am deleting 1 or 100 files, takes 6-7 just for the popup to show every single time.

**Comment by Shamatix** [comment] 2021-11-01 18:12
Can I enable some debug mode or something to send you some logfiles of Files that may help you guys to solve this issue? Because right now I have completely stopped using Files altogether because of this issue.

**Comment by jdeloshoyos** [comment] 2021-11-19 19:00
I'm having the same issue when trying to delete a few files (<10) or even a single one. In my case, the delay is typically 5-10 seconds, and nowhere near minutes, but it's still annoying.

**Comment by Raithlin** [comment] 2021-12-07 21:35
Would a Parallel.For not be useful here? I'm willing to have a look at why this is occurring and how to improve on it.

**Comment by yaichenbaum** [comment] 2021-12-08 00:20
> Would a Parallel.For not be useful here? I'm willing to have a look at why this is occurring and how to improve on it.

@Raithlin I'm not very familiar with the code for the file operations but if you think that'll help, would love to get this fixed 🙂

**Comment by Raithlin** [comment] 2021-12-09 11:24
@jdeloshoyos @Shamatix Which version of WIndows are you using? I'm on Windows 11 and I can't replicate the issue. Also, does this happen in large folders or pretty much anywhere?

**Comment by jdeloshoyos** [comment] 2021-12-09 15:27
> @jdeloshoyos @Shamatix Which version of WIndows are you using? I'm on Windows 11 and I can't replicate the issue. Also, does this happen in large folders or pretty much anywhere?

Hi! I'm on Win11 21H2 build 22000.348. For me it happens pretty much on any folder, even ones with very few files. There's a very noticeable pause (typically between 5-10 seconds in my case) since I give the delete command (by highlighting files and pressing DEL key) and the dialog for confirmation appearing.

**Comment by Raithlin** [comment] 2021-12-10 08:33
> Hi! I'm on Win11 21H2 build 22000.348. For me it happens pretty much on any folder, even ones with very few files. There's a very noticeable pause (typically between 5-10 seconds in my case) since I give the delete command (by highlighting files and pressing DEL key) and the dialog for confirmation appearing.

Thanks for that. I'm on the same version and my pop-up is instant whether I hit the DEL button or use the UI. It takes milliseconds longer on a large folder - enough for me to notice the delay, but certainly not 5-6 seconds.

Is there perhaps something that you have installed that I don't that might be causing the delay? Obviously, it isn't affecting Explorer but may well be holding back Files. I'm not sure how else to troubleshoot the problem, and if I can't replicate it then I'll have to step back and let someone else try.

**Comment by yaichenbaum** [comment] 2022-10-13 16:46
Is this still an issue in the preview build? https://files.community/download/preview

**Closed** 2022-10-19 00:25 UTC
Labels: bug, more-info
