### ISSUE TITLE
Creating Bundle: Dialog shows incorrect localisation

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#3538] opened 2021-02-11 16:29 UTC
![image](https://user-images.githubusercontent.com/17484252/107666293-a4255d00-6c8e-11eb-8c3d-e152166c6b25.png)

The underlined text should use the same localisation key as in the "Rename Bundle" dialog.

**Comment by yaichenbaum** [comment] 2021-02-11 16:50
@R3voA3 Was this fixed in your pull request?

**Comment by R3voA3** [comment] 2021-02-11 16:54
No it wasn't.

**Comment by yaichenbaum** [comment] 2021-04-27 17:54
Fyi @d2dyno1

**Comment by yaichenbaum** [comment] 2021-05-23 04:32
@R3voA3 The different dialogs have different keys by design.

**Closed by yaichenbaum** 2021-05-23 04:32 UTC
Labels: bug, help wanted, localization, triage approved
