### ISSUE TITLE
Bug: Sorting preferences don't save when changed in the column layout

### ISSUE THREAD

**Issue by pbousquets** [files-community/Files#14801] opened 2024-02-21 13:45 UTC
### Description

When I use the details layout, my sorting preferences are kept. If I change to the column layout and change the preferences, the next time I open the folder it is back to the default state (sorted by name, ascending, no grouping). 

### Steps To Reproduce

1. Activate details layout and change the sorting preferences
2. Close the folder and open it back again. The sorting should be the same
3. Change the layout to "columns" and set different sorting preferences
4. Close the folder and open it back again. The sorting is the default one again. 

### Requirements

The sorting preferences should remain after closing the folder.

### Files Version

3.2.2.0

### Windows Version

10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/14360220/debug.log)

**Comment by 0x5bfa** [comment] 2024-02-21 15:51
Thanks for your feedback.

When you change layout, sort/group settings are also reflected?

**Comment by pbousquets** [comment] 2024-02-21 15:54
I can change to any other layout and the sort/group settings are kept. But as soon as I change to columns layout the settings are lost. If I change them manually again, they're lost as soon as I leave the folder or exit the program.

**Comment by Josh65-2201** [comment] 2024-02-21 16:11
Thanks for the report, I've added this to the project board.

**Comment by pbousquets** [comment] 2024-02-21 16:11
Thanks!

**Comment by 0x5bfa** [comment] 2024-02-22 08:42
Reproduced. I think this can be ready for build.

**Comment by yaira2** [comment] 2024-03-07 18:07
The underlying issue seems to be that we don't execute `InstanceViewModel.FolderSettings.GetLayoutType` from `ModernShellPage`.

**Comment by schristianlim** [comment] 2024-05-07 21:23
Would like to ask if there is any update on this bug. Many thanks

**Comment by Josh65-2201** [comment] 2024-05-07 21:26
no one has worked on this yet.

**Comment by yaira2** [comment] 2024-05-07 21:26
It's on the todo list and ready to build.

**Comment by yaira2** [comment] 2024-10-06 01:27
A fix will be included in the next update.

**Closed** 2024-10-06 01:27 UTC
Labels: bug
