### ISSUE TITLE
While selecting items, Shift and Control buttons does not work as expected

### ISSUE THREAD

**Issue by antnauman** [files-community/Files#2309] opened 2020-11-11 12:57 UTC
These are minor bugs:
1. If we keep the control button pressed and start to drag-select, it RESETS the current selection. In case of selecting individual item one by one, it works fine.
2. If we are on item A, press shift and select item N, it selects all items from A to N (as expected). But if we then select item F (which is between A and N), it does not unselect items G to N.

**Comment by Don-Vito** [comment] 2020-12-27 18:54
The first part (Ctrl) seems to be covered by https://github.com/files-community/Files/issues/2137 and will be hopefully resolved by https://github.com/files-community/Files/pull/2716 and https://github.com/files-community/Files/pull/2728.

I will try to take a look at Shift behavior.

**Comment by Don-Vito** [comment] 2020-12-27 19:25
@antnauman - I am trying to reproduce the shift issue, but cannot. This what I am doing:
![ShiftDecreaseSelection](https://user-images.githubusercontent.com/4639110/103178277-fef32880-4889-11eb-908f-0956b8d22ada.gif)

Can you please provide more details?

**Comment by antnauman** [comment] 2020-12-27 19:33
I have just checked, the mentioned fault is not in List view, but it is there in Tiles view and Grid views.

**Comment by yaichenbaum** [comment] 2021-04-27 04:35
@Don-Vito This appears to be resolved in `main`, can you check on your end?

**Comment by yaichenbaum** [comment] 2021-05-19 04:10
This issue appears to be resolved in `main`.

**Closed by yaichenbaum** 2021-05-19 04:10 UTC
Labels: bug, more-info
