### ISSUE TITLE
Renaming issue on search results

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5823] opened 2021-08-14 10:10 UTC
### Description

When searching something then trying to rename it, it will say the extensions has been changed (even though it doesn't show in name or renaming) and when clicking ok it wont rename it.

### Expected behavior

It should show the extension, not bring up the warning unless renaming the extension, rename the file.

### Files Version

1.9.23.0

### Windows Version

10.0.19043.1151

**Comment by gave92** [comment] 2021-08-14 10:40
> even though it doesn't show in name or renaming

Do yo mean that you don't see file extensions in the search results?

> when clicking ok it wont rename it

Could you confirm if it really does not rename it? In my testing you don't see the name change in the search page but if you go back and look for the file the name has changed.

**Comment by josh-65** [comment] 2021-08-14 10:45
The extension doesn't show up in the name/renaming part. but it does under for file type.
![image](https://user-images.githubusercontent.com/26977075/129443802-1b8feb6a-2eca-4d5d-a989-0a4bfa22895c.png)

Also I found when going to the end of the file with arrow keys it will cancel the rename and highlight the next file.

**Comment by gave92** [comment] 2021-08-14 10:47
Do you have the "Show file extensions for known types" enabled?

**Comment by josh-65** [comment] 2021-08-14 10:47
yes

**Comment by josh-65** [comment] 2021-08-18 21:03
This also happens for shortcuts too. They don't show the .ink file extension and renaming them makes then unusable.

**Comment by gave92** [comment] 2021-08-18 22:19
@winston-de can you reproduce?

**Comment by winston-de** [comment] 2021-08-18 23:28
I can't reproduce this in search results. With shortcuts, there isn't a .lnk shown even though showing file extensions is enabled, however renaming works as expected.

**Comment by josh-65** [comment] 2021-08-18 23:49
I haven't tested it with the improvements of search that might have fix that. But for shortcuts when I rename it, it becomes a blank file that when clicked on just bring up the open with application.
![image](https://user-images.githubusercontent.com/26977075/129986232-fcebca68-62ab-4f6e-95cc-303a16da470c.png)

**Comment by yaichenbaum** [comment] 2021-11-22 20:50
This issue should be resolved with #7015.

**Closed** 2021-11-22 20:49 UTC
Labels: bug, investigate
