### ISSUE TITLE
Not able to change view from column to detail view as the button three column button on the right hand top will not dropdown. 

### ISSUE THREAD

**Issue by MH-Sogeti** [files-community/Files#14647] opened 2024-02-05 07:54 UTC
### Description

Not able to change view from column to detail view as the button three column button on the right hand top will not dropdown. 

### Steps To Reproduce

View is columnar
Press the button (three column button) on the right to chang view doesn't dropdown the menu to make the change

### Requirements

- fix this as I cannot change my view and I can't see full filenames in column format

### Files Version

3.1.1.

### Windows Version

Win 11 Pro - 22H2 - 22621.3007

### Log File

[debug.log](https://github.com/files-community/Files/files/14161999/debug.log)

**Comment by Josh65-2201** [comment] 2024-02-05 12:16
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by MH-Sogeti** [comment] 2024-02-05 14:03
Hi Josh,

Most of the times it’s working but this time it crashed. I can’t download the community version as I’m not allowed to install outside the store on my work laptop.

Met vriendelijke groet/Kind regards,

Marco Hoppenbrouwers
Client Engagement Executive | Data & Integration Services

Mob.: +31 6 20 44 38 81
***@***.******@***.***>

**Comment by Josh65-2201** [comment] 2024-02-05 14:09
Thanks for the info. For now you can change the layout for all folders via `Files settings > Folder > Layout` then back in and out of the folders currently open to apply it.

**Comment by yaira2** [comment] 2024-02-05 15:31
@MH-Sogeti you can also switch layouts using the right click context menu

**Comment by MH-Sogeti** [comment] 2024-02-05 16:40
Hi there which right click context menu is meant. I tried a few in the browser but I don’t see the option to change the view. At this moment the view is changing again when pressing the three column button below the searchbar.

Met vriendelijke groet/Kind regards,

Marco Hoppenbrouwers
Client Engagement Executive | Data & Integration Services

Mob.: +31 6 20 44 38 81
***@***.******@***.***>

**Comment by yaira2** [comment] 2024-02-05 17:29
Do you see this menu?
![image](https://github.com/files-community/Files/assets/39923744/5493b626-bc44-458f-8254-d71d40fb40d1)

**Comment by MH-Sogeti** [comment] 2024-02-06 07:26
Hello yes I can see that one, that’s the three column button I was referring to which wasn’t working yesterday for a moment and caused the app crash.
***@***.***

Met vriendelijke groet/Kind regards,

Marco Hoppenbrouwers
Client Engagement Executive | Data & Integration Services

Mob.: +31 6 20 44 38 81
***@***.******@***.***>

**Comment by yaira2** [comment] 2024-02-06 15:28
Does the flyout open?

**Comment by MH-Sogeti** [comment] 2024-02-06 15:39
What do you mean with the flyout? The context menu opens
***@***.***
Met vriendelijke groet/Kind regards,

Marco Hoppenbrouwers
Client Engagement Executive | Data & Integration Services

Mob.: +31 6 20 44 38 81
***@***.******@***.***>

**Comment by yaira2** [comment] 2024-02-06 15:51
I'm having a hard time following the steps to repro this, can you upload a screen recording?

**Comment by MH-Sogeti** [comment] 2024-02-06 16:15
Hi Yair, I cannot create a recording as most of the times the application allows me to change the view from columnar to detailed, tiles etc. So the application crashed once which didn’t happen again.

Met vriendelijke groet/Kind regards,

Marco Hoppenbrouwers
Client Engagement Executive | Data & Integration Services

Mob.: +31 6 20 44 38 81
***@***.******@***.***>

**Comment by yaira2** [comment] 2024-02-06 17:11
> So the application crashed once which didn’t happen again

It sounds like you're experiencing a crash when switching layouts? If this is the case, the issue is already resolved in our dev branch, and it'll be included in the next release.

**Closed by yaira2** 2024-02-06 17:11 UTC
Labels: bug, more-info
