### ISSUE TITLE
After opening a file multiple times two, instances are opened at the same time.

### ISSUE THREAD

**Issue by ChelaruCatalin** [files-community/Files#794] opened 2020-05-17 01:21 UTC
After opening a file multiple times two instances are opened at the same time.
The problem "resets" if i go out of the folder and back in. But after 2-3 opening procedures of the same file the bug returns. 

Issue observed with pictures and text files. Not reproducible with windows media player classic. 

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Comment by Jaiganeshkumaran** [comment] 2020-05-28 09:24
By instance do you mean a separate window?

**Comment by ChelaruCatalin** [comment] 2020-05-28 10:08
No,i am referring to multiple instances of the program i use to open that file. For photos, two Photos apps will open at the same time.

**Comment by duke7553** [comment] 2020-06-18 09:49
Hmm... I cannot reproduce this one in v0.10.2 . 

It may be because I'm running a Windows Insider build

**Comment by yaichenbaum** [comment] 2020-11-20 03:38
@ChelaruCatalin Is this still an issue in v0.20?

**Comment by yaichenbaum** [comment] 2020-11-26 00:38
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 6+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Closed by yaichenbaum** 2020-11-26 00:38 UTC
Labels: bug, investigate, more-info
