### ISSUE TITLE
Unable to access system folders such as Appdata

### ISSUE THREAD

**Issue by ducky710** [files-community/Files#1413] opened 2020-07-13 01:15 UTC
**Describe the bug**
Files UWP is unable to reach system folders like "Appdata". It returns this error "Invalid Item: The item referenced is either invalid or inaccessible.
Message: Values does not fall within the expected range

**To Reproduce**
1. Click the address bar
2. Type the full path or %path%
3. Error presented

**Expected behavior**
Files UWP should open the directory.

**Screenshots**
https://i.imgur.com/cNCmZnq.jpg

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 10.0.19041 Build 19041]
 - App version: [v0.12.0]

**Comment by Jaiganeshkumaran** [comment] 2020-07-13 02:24
Files UWP doesn't support hidden folders yet.

**Comment by gave92** [comment] 2020-07-13 21:22
Also there are permission issues on AppData.
For this particular case, typing "C:\Users\USER\AppData\Local" works while "%LocalAppData%" won't.

**Comment by soumyamahunt** [comment] 2020-07-26 05:48
> Also there are permission issues on AppData (if you type the path you'll get AccessDenied).
> For this particular case, typing "C:\Users\USER\AppData\Local" works while "%LocalAppData%" won't.

That's because of environment variables weren't supported before, it works now.

**Comment by soumyamahunt** [comment] 2020-07-26 05:49
Duplicate of #177.

**Comment by Jaiganeshkumaran** [comment] 2020-07-26 06:31
@soumyamahunt It's not a duplicate since this a bug report and that's a feature request.

**Comment by XPoppyX** [comment] 2020-08-04 20:56
any updates about this bug after certain changes to the path bar?

**Comment by yaichenbaum** [comment] 2020-08-05 00:36
@XPoppyX Support for folders like AppData has not been added yet.

**Comment by yaichenbaum** [comment] 2020-11-22 17:18
Merging with #2303.

**Closed by yaichenbaum** 2020-11-22 17:18 UTC
Labels: bug, triage approved
