### ISSUE TITLE
Add support for opening archives inside Files

### ISSUE THREAD

**Issue by GameBoyYeet** [files-community/Files#2135] opened 2020-10-23 17:48 UTC
**Is your feature request related to a problem? Please describe.**
I can't open *.zip files in Files UWP.

**Describe the solution you'd like**
Add support for *.zip files

**Describe alternatives you've considered**
Use 7z, Explorer, etc.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
None

**Comment by XPoppyX** [comment] 2020-10-23 18:31
Duplicate of #45

**Comment by duke7553** [comment] 2020-11-12 18:03
@GameBoyYeet We're going to track this with issue #45 , so I'll close this now.

**Closed by duke7553** 2020-11-12 18:03 UTC
Labels: feature_request, triage approved
