### ISSUE TITLE
Search can't run on FilesUWP

### ISSUE THREAD

**Issue by XiaoLeCN** [files-community/Files#2329] opened 2020-11-14 00:44 UTC
Search can't run on FilesUWP
![image](https://user-images.githubusercontent.com/74437699/99133599-9e02ee80-2655-11eb-8b6a-44cfa0587287.png)

**Comment by XPoppyX** [comment] 2020-11-14 00:57
This feature is not implemented yet

**Comment by gave92** [comment] 2020-11-14 08:28
Duplicate of #333

**Closed** 2020-11-14 08:29 UTC
