### ISSUE TITLE
Bug: Sort does not work in Column View

### ISSUE THREAD

**Issue by yichenchong** [files-community/Files#12045] opened 2023-04-11 11:52 UTC
### Description

No matter the sort order selected, Column View sorts the files in the exact same way, with all the folders at the top in alphabetic order, followed by all files in alphabetic order. Clicking "Sort by..." and then any other order does nothing.

In the following example, I created the folders in reverse alphabetic order, but this is the order that shows up no matter the "Sort By" order.
![image](https://user-images.githubusercontent.com/40590448/231152669-57239266-fda3-4d21-8999-14e4f6e668b2.png)

### Steps To Reproduce

1. Go to any directory
2. Click on Layout > Columns
3. Click on Sort by > Date modified
4. No reordering is observed

### Requirements

- Fix "Sort by..." in Column View always shows up in alphabetic order

### Files Version

2.4.61.0

### Windows Version

Windows 11 22H2 22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11200015/debug.log)

**Comment by Josh65-2201** [comment] 2023-04-11 11:55
Have you tried enabling "List and sort directories alongside files" as that allowed folder and files to be mixed.

**Comment by yaira2** [comment] 2023-04-14 15:19
@yichenchong thank you for reporting this issue, we identified the cause and we're working on a fix

**Comment by yaira2** [comment] 2023-04-21 02:19
@yichenchong thank you for reporting this issue, it's been partially fixed in v2.4.66 but we're going this open as it's still an issue in certain scenarios.

**Comment by yaira2** [comment] 2023-11-30 18:09
@yichenchong Is this still an issue in the preview version? https://files.community/download/preview

**Closed** 2023-12-13 21:13 UTC
Labels: bug, more-info
