### ISSUE TITLE
Feature: Improve Tags/Keywords

### ISSUE THREAD

**Issue by RPanon666** [files-community/Files#16587] opened 2024-12-08 17:03 UTC
### What feature or improvement do you think would benefit Files?

Product Suggestion
Tags are nice but uselessly simple for me. Here are some suggestions for improvement.

I am a photographer and retired from tech industry after 50 years. I have almost 80,000 images. Finding photographs without Lightroom (Lr) is almost impossible. I am utterly dependent on Lr "Collections" which support limited Boolean logic. Similarly, my technology employers could not use shareware for risk mgt, statutory, regulatory reasons. The library of in-house/trusted, shared content was huge and maintained with a DB in 2 cases (unmanaged mess otherwise). I am sure there are other use cases. These use cases need sophisticated keywords with robust Boolean search support.

Ways To Make Money with this feature
1. Partner with every photo editing competitor (Topaz, DxO, On1, Capture One, Skylum, etc.) to Adobe.
2. Partner with SW developers, LSE providers, etc.
3. Partner with Legal Case management software
4. Your marketing team will probably think of others.

### Requirements

1. Expand the notion of Tags to include all file metadata (Name, Type, Path, Dates, KWs, EXIF (if photo), etc.). Index textual content subject to user setting. The first pass will be long - perhaps overnight. On-going might be done in the background, foreground if user is waiting.
2. -
3. Support sidecar files.
4. -
5. Add virtual-folders defined by a Boolean expression. The expression should support AND, OR, NOT, (), =, !=, <,<=, >, >=, etc. -- be really inclusive. 
6. - 
7. To make it easier for the general public, you might define after, before, IS IN (kw1, kw2...), IS NOT IN (kw1, kw2...), CONTAINS string_expr, STARTS WITH, ENDS WITH, etc.

### Files Version

3.8.0.0

### Windows Version

10.0.22631.4541

### Comments

I am retired from coding. I am willing to help with definition and testing.
Steve

**Comment by Lamparter** [comment] 2024-12-08 17:07
This looks like a duplicate of #11992

**Comment by Josh65-2201** [comment] 2024-12-08 17:37
Thanks for the feedback, Do you mean you want to search tagged with logic syntax or to tag files/folders when they match certain infomation

**Comment by RPanon666** [comment] 2024-12-08 20:30
Search with Boolean logic.

Virtual folders defined by a predicate are also important. They need to be searched too (nesting).

Thanks
s


-------------------

Steve Painter

6 Wildwood Ave

Kennebunkport  ME 04046-7425



H: 207 200 8218

M: 978 618 6529

W: S-Painter.art<http://s-painter.art/>



________________________________

**Comment by RPanon666** [comment] 2024-12-08 20:38
Similar, but different. Mine is about virtual folders base on a predicate.

 I had not thought of an action based on the predicate.

Some ideas for actions that come to mind.
Delete
Print
Physical copy (syncronize)
Physical move (archive)


The important thing is treating all the file metadata as keywords .



-------------------

Steve Painter

6 Wildwood Ave

Kennebunkport  ME 04046-7425



H: 207 200 8218

M: 978 618 6529

W: S-Painter.art<http://s-painter.art/>



________________________________

**Comment by Josh65-2201** [comment] 2024-12-09 04:45
Tags are can act like virtual folders, with https://github.com/files-community/Files/issues/11992 you would be able to add them based on file meta data. Searching is already possible using `tag:<name>` if you want to or you can do `tag:<name1>,<name2>`

More details on tags can be found here https://files.community/docs/features/tags

**Comment by RPanon666** [comment] 2024-12-09 12:09
Thanks for your reply. I have read the tags documentation page. I have experimented with tags. My suggestion stands. Please let me know if you decide to work on the suggestion if I can help. Please let me know if you implement the suggestion and I’ll reinstall Files and use it.

Good luck
Steve

**Comment by SyazaLayyina** [comment] 2024-12-13 16:41
i get simmiliarty tag error

**Comment by Josh65-2201** [comment] 2024-12-13 21:22
@SyazaLayyina This isn't about any errors/bugs, if you have an issue please open a new issue

**Closed** 2024-12-23 22:14 UTC
Labels: needs - additional info, area - tags
