### ISSUE TITLE
Bug: Incorrect window size on a vertical monitor

### ISSUE THREAD

**Issue by hiwer** [files-community/Files#16203] opened 2024-09-16 08:13 UTC
### Description

The window does not retain its size when reopened. It keeps getting bigger with each new opening.

https://github.com/user-attachments/assets/02661b3b-cb25-473e-a924-71652fe3dddd

### Steps To Reproduce

1. Vertical monitor (Portrait mode)
1. Set window size (Files)
2. Close window (Files)
3. Reopen windows again (Files)

### Requirements

- e.g. Fix crash that occurs when...
Fix window size

### Files Version

3.7.6.0

### Windows Version

11

### Log File

-

**Comment by 0x5bfa** [comment] 2024-09-16 08:14
Thanks for the report.

Can you share your screen's DPI?

**Comment by hiwer** [comment] 2024-09-16 08:17
> Thanks for the report.
> 
> Can you share your screen's DPI?

Yes.. No problem.

![image](https://github.com/user-attachments/assets/dfd7484b-a868-43b6-9454-e1c112ce6bd8)

**Comment by 0x5bfa** [comment] 2024-09-16 08:32
Window position is the same but window size is wrong.
@yaira2 Is your PC has 125% DPI? If so, can you check if this is reproducible?

**Comment by yaira2** [comment] 2024-09-16 14:15
I cannot reproduce but it might have something to do with their display orientation. @hiwer is this still an issue after restarting Windows?

**Comment by hiwer** [comment] 2024-09-17 18:28
> I cannot reproduce but it might have something to do with their display orientation. @hiwer is this still an issue after restarting Windows?

Hi.. restarting didn't solve my problem. The issue seems to be related to scaling changes in Windows. Check the video to reproduce the error.


https://github.com/user-attachments/assets/537350ef-47b3-42f3-89a6-c66dae068179

**Comment by yaira2** [comment] 2024-09-30 14:58
@hiwer Is this still an issue in the preview version? https://files.community/download/preview

**Comment by hiwer** [comment] 2024-10-01 07:49
> @hiwer Is this still an issue in the preview version? https://files.community/download/preview

@yaira2 Yes, the issue is still present in version 3.7.7

**Comment by 0x5bfa** [comment] 2024-10-01 08:23
Please check in 3.7.9

**Comment by Josh65-2201** [comment] 2024-10-01 08:31
Downloaded the preview version from the site

**Comment by hiwer** [comment] 2024-10-01 08:34
Ah.. sorry, 'Preview version'... I can't test it because when I open Files - Preview on the main monitor, move it to the second (secondary) monitor, close Files preview, and then reopen it, it appears on the main monitor again. It doesn't remember the move to the vertical, secondary monitor.

**Comment by 0x5bfa** [comment] 2024-10-01 08:50
AFAIK what we use to set window position and size persistence doesn't save window monitor index.

This issue is regarding whether the position and size are saved in the preview version of Files. How about that?

**Comment by yaira2** [comment] 2024-10-08 15:15
A potential fix will be included in the next update.

**Comment by hiwer** [comment] 2024-10-11 09:39
> A potential fix will be included in the next update.

@yaira2 It works well... Just this one last bug (https://github.com/files-community/Files/issues/15776) and it'll be great :) Good luck!

**Comment by yaira2** [comment] 2024-10-13 15:38
Glad this issue has been resolved.

> Just this one last bug (https://github.com/files-community/Files/issues/15776) and it'll be great :) Good luck!

One thing at a time 🙂

**Closed by yaira2** 2024-10-13 15:38 UTC
Labels: needs - additional info
