### ISSUE TITLE
Bug: Invalid Git Remote crashes app

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#13048] opened 2023-07-23 16:03 UTC
### Description

When a Git repository contains a remote that no longer is valid (e.g. repo deleted), the app crashes. Worst case is that the app tries to open the same folder on startup and crashes again.

Exception:

![Screenshot of debugger inspecting uncaught exception "... is not a valid remote"](https://github.com/files-community/Files/assets/16122379/6fbd0094-deaa-4834-b4f7-406cfbaace07)

### Steps To Reproduce

1. Open a repository with invalid Git Remotes

### Requirements

- e.g. Fix crash that occurs when...
Should not crash

### Files Version

Commit: 75e41fafe7099e089a30f5b325b617b09aab9d0e

### Windows Version

22621.1992

### Log File

I can send them if requested.

**Comment by yaira2** [comment] 2023-07-23 16:07
Thank you for reporting this issue.

**Comment by hishitetsu** [comment] 2023-07-24 15:05
@ferrariofilippo fyi
![image](https://github.com/files-community/Files/assets/66369541/41b77181-694b-4d80-8eb9-567c7d82fb25)

**Comment by ferrariofilippo** [comment] 2023-07-24 16:08
I'll try to fix this. 
Can you share some more details about how to reproduce the bug? I'm having some troubles with that

**Comment by hishitetsu** [comment] 2023-07-24 16:19
Sorry, I actually just looked for the same crash from App Center, I didn't reproduce it myself.

**Comment by ferrariofilippo** [comment] 2023-07-24 16:52
I marked the PR as a draft because there are some things we should discuss (see `Possible Improvements` section).
I'd like to hear your opinion

**Comment by chingucoding** [comment] 2023-07-24 17:45
@ferrariofilippo It seems that I can only reproduce this in a repo where a branch points to an invalid remote, if it helps I can share the git folder of that repo if that helps (though its quite a large git folder since its Files)

**Comment by ferrariofilippo** [comment] 2023-07-24 18:45
NVMD I found a way to reproduce it

**Comment by ferrariofilippo** [comment] 2023-07-25 20:29
> When a Git repository contains a remote that no longer is valid (e.g. repo deleted)

@chingucoding it seems that if the repo is deleted everything works fine (when you try to fetch/pull/push you get a 404 and Files doesn't crash).
Instead, the bug seem to be caused by something like this (`main` is invalid and `develop` is valid):
![image](https://github.com/files-community/Files/assets/102259289/32300467-53d2-417e-9927-e950f60d8cf3)

**Comment by yaira2** [comment] 2023-08-04 14:08
@chingucoding this issue should be resolved in `main`.

**Closed** 2023-08-04 14:08 UTC
Labels: bug
