### ISSUE TITLE
Quickview arrow navigation

### ISSUE THREAD

**Issue by hederaetype** [files-community/Files#2015] opened 2020-10-01 14:24 UTC
**Describe the bug**
Quickview not following selection navigation.

**To Reproduce**
1. while navigating folders with quickview and keyboard arrows, the mini window doesn't follow selection as in default explorer.
2. you must close the preview with spacebar and press again to preview the new file.

**Expected behavior**
The preview follows arrow navigation selection

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.508]
 - App version: [v0.15.0.0]

**Comment by yaichenbaum** [comment] 2020-10-01 20:43
Can you confirm if #792 is the same issue?

**Comment by generalguy41** [comment] 2020-10-01 21:28
@yair100 I think it's more likely a duplicate of #1373

**Comment by hederaetype** [comment] 2020-10-02 06:31
@generalguy41 you're right it is.

**Closed** 2020-10-02 15:19 UTC
Labels: duplicate
