### ISSUE TITLE
When I interact with Files it has a delay of around 5-20 seconds

### ISSUE THREAD

**Issue by Skelly1301** [files-community/Files#8882] opened 2022-04-08 09:59 UTC
### Description

So I downloaded files a few days ago. Now I open the app, and it works fine. But every time I click something, it takes around 10 seconds to process. This can be really annoying at times and never used to happen with the default file explorer.
I have a attached a video link to show you what I mean:

### Steps To Reproduce

N/A

### Expected behavior

N/A

### Files Version

Version: 2.1.24.0 OS Version: 10.0.19043.1586

### Windows Version

Windows 10 Home 19043.1586

### Relevant Assets/Logs

N/A

**Comment by Skelly1301** [comment] 2022-04-08 10:00
Video link 
https://streamable.com/4k17ww

**Comment by gave92** [comment] 2022-04-08 10:25
Thanks for the report. Could you upload the app's debug logs (from settings > about > open log location)?
You may want to try a reibstall, it looks like there is something wrong with the sidebar as well.

**Comment by Skelly1301** [comment] 2022-04-08 10:38
> Thanks for the report. Could you upload the app's debug logs (from settings > about > open log location)? After you upload the logs, you may want to try a reinstall, it looks like there is something wrong with the sidebar as well.
[debug.log](https://github.com/files-community/Files/files/8451087/debug.log)

**Comment by Skelly1301** [comment] 2022-04-08 10:38
> Thanks for the report. Could you upload the app's debug logs (from settings > about > open log location)? After you upload the logs, you may want to try a reinstall, it looks like there is something wrong with the sidebar as well.

Here is my [debug.log](https://github.com/files-community/Files/files/8451089/debug.log)

**Comment by gave92** [comment] 2022-04-08 11:41
Thanks same location there should be also a second debug log (debug_fulltrust.log). Could you upload the too?

**Comment by yaichenbaum** [comment] 2022-04-08 15:47
Is this an issue in the preview version of Files (make sure to remove the current version of Files before installing the preview version)?

**Comment by Skelly1301** [comment] 2022-04-11 09:17
> Thanks same location there should be also a second debug log (debug_fulltrust.log). Could you upload the too?

Sorry for the late reply, here it is:
[debug_fulltrust.log](https://github.com/files-community/Files/files/8462760/debug_fulltrust.log)

**Comment by Skelly1301** [comment] 2022-04-11 09:19
> Is this an issue in the preview version of Files (make sure to remove the current version of Files before installing the preview version)?

No, I made sure to download the sideload package, not the sideload package preview

**Comment by yaichenbaum** [comment] 2022-04-12 03:34
@Skelly1301 is it an issue in the preview version?

**Comment by yaichenbaum** [comment] 2022-04-12 14:36
Closing this for now but feel free to reopen if you can reproduce in the preview version.

**Closed by yaichenbaum** 2022-04-12 14:36 UTC
Labels: bug, more-info
