### ISSUE TITLE
Behavior of the latest version

### ISSUE THREAD

**Issue by fox62843** [files-community/Files#14997] opened 2024-03-19 15:26 UTC
### What feature or improvement do you think would benefit Files?

(1) There used to be a beautiful animation effect when zooming in and out, but it is gone. If so, please restore the animation effect.

(2) When zooming in and out, I was able to go back and forth between all layouts, but after the update, it is limited to the selected layout. Is this also a specification? It is very difficult to use.

I don't feel that the display speed of thumbnails has increased.

### Requirements

Filesバージョン3.3.0.0にて、ピクチャフォルダ内で「Ctrl＋ホイール上下」でサムネイルの拡大縮小操作

### Files Version

3.3.0.0

### Windows Version

10.0.22621.3296

### Comments

https://github.com/files-community/Files/assets/62488858/c13d4d22-7c51-4615-a1e6-7acc0c1d2215

**Comment by Josh65-2201** [comment] 2024-03-19 15:39
Thanks for the feedback, What do you mean by the seconding point? There's a slider in the layout menu to change the size and the keyboard shortcuts still work the same

**Comment by yaira2** [comment] 2024-03-19 15:42
Thank you for your feedback, this reflects some changes that were made in the latest release (v3.3).

> There used to be a beautiful animation effect when zooming in and out, but it is gone. If so, please restore the animation effect.

This is probably because we previously had to reload the view when changing the grid view size, in v3.3 we  update the size dynamically without reloading the whole layout.

> (2) When zooming in and out, I was able to go back and forth between all layouts, but after the update, it is limited to the selected layout. Is this also a specification? It is very difficult to use.

With v3.3, we introduced the ability to adjust the size in the Details, List, & Grid layouts so we felt that it's best to align with File and only adjust the item size when zooming in or out. To switch between layouts, you can use the `ctrl` + `shift` + `1` shortcut (change the value of "1" to the corresponding layout).

**Comment by fox62843** [comment] 2024-03-20 04:51
Thank you for your reply.

>>This is probably because we previously had to reload the view when changing the grid view size, in v3.3 we update the size dynamically without reloading the whole layout.

I understand the above. However, I don't seem to be able to benefit from the change to that specification. Obviously, the previous view reload works faster.

>>With v3.3, we introduced the ability to adjust the size in the Details, List, & Grid layouts so we felt that it's best to align with File and only adjust the item size when zooming in or out. To switch between layouts, you can use the ctrl + shift + 1 shortcut (change the value of "1" to the corresponding layout).

I understand that there is a shortcut key for this matter. However, it is rather inefficient since Ctrl+wheel operation is by far more intuitive to begin with. Please, please consider reverting to the previous specification.

**Comment by yaira2** [comment] 2024-03-20 14:51
> I understand that there is a shortcut key for this matter. However, it is rather inefficient since Ctrl+wheel operation is by far more intuitive to begin with. Please, please consider reverting to the previous specification.

Initially, our layout was designed for rapid cycling through views such as details, list, tiles, and grid. However, we soon realized that this setup was no longer efficient. With the recent changes, transitioning from details to grid view would take at least ten scrolls and potentially more for those preferring larger icons. Additionally, cycling through the different layouts and sizes would inadvertently reset the saved size settings for each layout.

We're open to the idea of adding a shortcut specifically for cycling between layouts, but it'll need to wait until we add a UI for customizing actions.

**Comment by yaira2** [comment] 2024-03-25 22:38
Once again, I want to thank you for your feedback. We're going to close this issue for now but we'll continue tracking for similar feedback and we'll keep your use case in mind.

**Closed** 2024-03-25 22:38 UTC
Labels: more-info, feature request
