### ISSUE TITLE
Alt+enter moves cursor down

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2870] opened 2021-01-06 18:51 UTC
**Describe the bug**
When I select an item, then press alt+enter, the properties dialog opens. In addition to that, the cursor moves down to the next item in the list as well, which isn't supposed to happen.

**To Reproduce**
1. Select an item.
2. Press alt+enter
3. Notice how the cursor moves down an item in the list.

**Expected behavior**
I expected the properties dialog to open _without_ moving the cursor down as well.

**Screenshots**
https://user-images.githubusercontent.com/76794507/103800530-883cf480-501a-11eb-94a1-7b6b09a4d727.mp4

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Even after restarting the app, the issue is still present.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5777194/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5777195/debug_fulltrust.txt)

**Comment by gave92** [comment] 2021-01-06 18:54
Duplicate of #2463

**Closed by gave92** 2021-01-06 18:54 UTC
Labels: bug
