### ISSUE TITLE
Can't hide check box in the folder settings.

### ISSUE THREAD

**Issue by chrisli6867** [files-community/Files#12209] opened 2023-04-26 08:24 UTC
### Description

When deactivate showing chek box when select, it doesn't works.

### Steps To Reproduce

1. seetings button in the right up corner.
2. click "folder" tab
3. select display part, then navigate to "shwo check boexes when selecting items" 

### Requirements

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.69.0

### Windows Version

win 11 professional, 22H2, 22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11330660/debug.log)

**Comment by Josh65-2201** [comment] 2023-04-26 12:37
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- Did you turn the option off?
- Is this in certain layouts?
- Are you hovering over the selected item? As the option is so it only shows on hover.

**Comment by yaira2** [comment] 2023-04-27 14:41
@chrisli6867 is this the same issue #12181?

**Comment by yaira2** [comment] 2023-05-04 03:30
@chrisli6867 assuming this is the same issue, it'll be resolved in v2.5.

**Closed by yaira2** 2023-05-04 03:30 UTC
Labels: bug, more-info
