### ISSUE TITLE
I want different sorts and layout modes in every page.

### ISSUE THREAD

**Issue by Xiaoice001** [files-community/Files#2567] opened 2020-12-09 11:03 UTC
I want different sorts and layout modes in every page.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Dylan-Osborne** [comment] 2020-12-09 11:21
Duplicate of #530

**Closed** 2020-12-09 11:30 UTC
Labels: feature_request
