### ISSUE TITLE
Bug: Create file button is disabled when using Chinese input flyout

### ISSUE THREAD

**Issue by KingRayCao** [files-community/Files#9563] opened 2022-07-14 02:50 UTC
### Description

When I try to create a folder or file and try to type the name in Chinese, I can't create it immediately(the button below remains grey.).
Rather, I have to delete one character to make the ‘create’ button available.

### Steps To Reproduce

1. Use input flyout to enter text into the name field without actually typing with the keyboard
2. See that the create file button is disabled

### Expected behavior

- Enable create file button no matter the input type

### Files Version

Version: 2.3.3.0 OS Version: 10.0.22000.795

### Windows Version

Windows 11 21H2 22000.795

### Relevant Assets/Logs

![problem](https://user-images.githubusercontent.com/38076465/178888032-1736a373-4ba5-4d50-8b62-0c38bdce6b76.gif)

**Comment by yaichenbaum** [comment] 2022-07-14 05:02
I think it has to do with the fact that you aren't typing the name into the text box. Does it work if you type the text directly?

On our end, this can be resolved by adding a text changed event.

**Comment by Octoowner88** [comment] 2022-07-14 13:52
This has to do don't write the code write actual text

**Comment by KingRayCao** [comment] 2022-07-14 13:56
Well, typing in English works totally fine, for the text is directly typed in.
I've also discovered that if you first type in some Chinese charactors, and then a space, the button will become available.

**Comment by Antony-Jia** [comment] 2022-09-09 01:39
I met same question and I'll type space to fix it

**Comment by andrewruales** [comment] 2022-09-29 23:24
Is this still an issue? I am new to open source contributions but I would like to try and tackle this issue!

**Comment by Antony-Jia** [comment] 2022-09-30 00:35
Yes, the problem still exists

**Comment by andrewruales** [comment] 2022-09-30 02:37
Any advice for where I could find this issue in code?

**Comment by Antony-Jia** [comment] 2022-09-30 02:59
I thought
`// Create file based on dialog result
            (ReturnResult Status, IStorageItem Item) created = (ReturnResult.Failed, null);
            switch (itemType)
            {
                case AddItemDialogItemType.Folder:
                    userInput = !string.IsNullOrWhiteSpace(userInput) ? userInput : "NewFolder".GetLocalizedResource();
                    created = await associatedInstance.FilesystemHelpers.CreateAsync(
                        StorageHelpers.FromPathAndType(PathNormalization.Combine(currentPath, userInput), FilesystemItemType.Directory),
                        true);
                    break;

                case AddItemDialogItemType.File:
                    userInput = !string.IsNullOrWhiteSpace(userInput) ? userInput : itemInfo?.Name ?? "NewFile".GetLocalizedResource();
                    created = await associatedInstance.FilesystemHelpers.CreateAsync(
                        StorageHelpers.FromPathAndType(PathNormalization.Combine(currentPath, userInput + itemInfo?.Extension), FilesystemItemType.File),
                        true);
                    break;
            }`
may not can't tell if it's over when met special characters

**Comment by andrewruales** [comment] 2022-09-30 03:53
Awesome, which file should I make this addition to?

**Comment by yaichenbaum** [comment] 2022-10-02 21:54
@andrewruales this issue is a result of custom logic that handles unlocking the create button when input is entered, should be pretty simple to fix.

**Comment by hecksmosis** [comment] 2023-01-19 17:47
What app are you using?

**Comment by jiejasonliu** [comment] 2023-01-20 07:14
@yair100 I actually can't reproduce this; was this maybe unintentionally fixed? could also just be my machine...

**Closed** 2023-01-22 16:36 UTC
Labels: bug, good first issue
