### ISSUE TITLE
Bug: Unable to delete folders with the "Delete" key

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#12127] opened 2023-04-20 08:08 UTC
### Description

I'm just testing out the preview version for some bug fixes and noticed an issue with deleting folders. It seems like I can't delete folders with the "Delete" key (even though the key works fine on regular files), however the "Backspace" key works for deleting folders (but not regular files), while it also goes back to the previous folder.

https://user-images.githubusercontent.com/2331058/233301673-e5d3cc28-11e3-4189-8c69-c3bac2b11286.mp4

### Steps To Reproduce

1. Enter a folder that contains both files and subfolders.
2. Try to delete a file with the Delete key, it will work.
3. Try to delete a folder with the Delete key, it should work but it doesn't.
4. Try to delete such folder with the Backspace key, it **shouldn't** work but it does.

### Requirements

- Fix delete hotkeys.

### Files Version

2.4.66.0

### Windows Version

10.0.19044.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11283885/debug.log)

**Comment by rafaskb** [comment] 2023-04-20 14:22
I do have macro and key redirect programs (PowerToys and AutoHotKeys), but even with all of them disabled I continue to have the same issue. None of them touch delete or backspace keys though, they're mostly for remapping function keys and giving me accents for the Portuguese language.

I use an Apple extended keyboard, US layout.

Been using this setup for quite a few years actually (including the software end) without issues.

Please let me know if I can run any other tests on my end to help narrow down the issue.

**Comment by rafaskb** [comment] 2023-04-20 18:26
Oh interesting. I pressed delete but nothing happened (at least apparently), then I switched directories and went back to the directory where I pressed delete on the folder, and to my surprise the folder was no longer there, so "delete" in fact worked, however no conformation popup showed up, and the folder didn't update after the action. Selecting the "Refresh" option from the context menu makes the deleted folder disappear as well.

I also have the following setting set up, so this issue might just be a matter of refreshing the current view after the delete action.
![image](https://user-images.githubusercontent.com/2331058/233454268-cccf20dc-48a4-4d68-8b2e-ba71ebf3e3d9.png)

If I set that setting to "Always" though, then as soon as I change directories the popup confirmation shows up.

**Comment by ferrariofilippo** [comment] 2023-04-20 19:28
What you reported seems to be the same as #11501 but I'd like to know more so that we can better figure out where's the cause
Does that happen with all of your folders or just with that specific one? I'd like to understand if there's something specific with that folder (is it a huge folder? does it contain a specific type of files?)

**Comment by rafaskb** [comment] 2023-04-20 19:40
Uh oh I can't seem to replicate the bug anymore, that's really weird. I'll keep trying and report back with more info once it happens again.

In any case the folder I was trying to delete in the video up there is really small, it contains only 3 screenshots of 2 MB each. When I commented an hour ago I was testing with a different folder as well, completely unrelated to the first one (while the first one was in C: AppData, the second one was on my A: drive, a completely different disk), and was also small in content.

The one thing in common is that both only contained .png files, and both times I was using the column view layout.

Perhaps the issue is just that the folder deletion took too long and I didn't wait long enough? That could be.

**Comment by ferrariofilippo** [comment] 2023-04-20 20:13
> Perhaps the issue is just that the folder deletion took too long and I didn't wait long enough? That could be.

I think that's the case, but still it's a bug and should be fixed

**Comment by yaira2** [comment] 2023-04-30 17:44
Merging with #11501

**Closed by yaira2** 2023-04-30 17:44 UTC
Labels: bug, more-info
