### ISSUE TITLE
Why is there's a duplicate folder on the home page of my files APP? AND when I  change  my files tag , Files APP crash.

### ISSUE THREAD

**Issue by rospirit** [files-community/Files#15370] opened 2024-05-11 06:52 UTC
### Description

![螢幕擷取畫面 2024-05-10 144216](https://github.com/files-community/Files/assets/81501083/14370a9e-eec0-4a71-b5fc-3008139ec627)
AND when I  change  my files tag , Files APP crash.

AND...
The function of searching files is very unstable.
I have a file P in my folder A. I type P in the search box.
I can't find the file in Files APP, and the text "File does not exist" is displayed.
But when I search again and wait for 1 minute, I can find the file again.

The above problem has always existed, but it has worsened since this update.

### Steps To Reproduce

1. open FilesApp
2. duplicate folders on the home page, double.
3. Refresh Page
3.  duplicate folders on the home page, triple.
---
1. change file tags.
2. crash and APP closed.
---
1. key in some words in search bar
2. cannot find the files that files name include words.

### Requirements

Fix crash that occurs when go to homepage.
Fix crash that occurs when change tags.

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[
[debug.log](https://github.com/files-community/Files/files/15281894/debug.log)
[debug_server.log](https://github.com/files-community/Files/files/15281895/debug_server.log)
](url)

**Comment by 0x5bfa** [comment] 2024-05-11 07:38
Thanks for the feedback, we have a similar issue we're working on, while we cannot reproduce yet. #14555

@Josh65-2201 Do you think we can merge?

**Comment by rospirit** [comment] 2024-05-11 07:41
0x5bfa ***@***.***>於 2024年5月11日 週六，15:39寫道：

**Comment by Josh65-2201** [comment] 2024-05-11 15:13
Would it be the same cause? This one is home page drives the linked one is for quick access. If so then yeah I think it can be merged

**Comment by 0x5bfa** [comment] 2024-05-11 23:00
The same logic, which insert new items that are not in previous collection without emptying and inserting everything. It’s asynchronous operation and so maybe the changed event is called twice or more and finish differently.

**Comment by 0x5bfa** [comment] 2024-05-11 23:02
Do you think this would be fixed by using Semophore? @hishitetsu

**Comment by hishitetsu** [comment] 2024-05-12 01:11
Since such collections should already be thread-safe, I don't think Semaphore will fix the issue. It is simply a matter of not adding the same item if it already exists. In any case, I think it can be fixed once the procedure to reproduce the issue is clarified.

**Comment by rospirit** [comment] 2024-05-12 13:40
### **Description**

When I **change** my files tag , Files APP crash **immediately**.

![螢幕擷取畫面 2024-05-12 213622](https://github.com/files-community/Files/assets/81501083/d9188dae-97a7-43e4-b24e-3e7121e6f9a0)

![螢幕擷取畫面 2024-05-12 212823](https://github.com/files-community/Files/assets/81501083/cec49ffd-947a-44db-b227-06619013509f)
![螢幕擷取畫面 2024-05-12 212802](https://github.com/files-community/Files/assets/81501083/253fd898-8ffe-4318-9f23-e1d8013b15a3)

### ** Steps To Reproduce**

open FilesApp
duplicate folders on the home page, double.
Refresh Page
duplicate folders on the home page, triple.
change file tags.
APP crash and  closed.

### **Requirements**

### **Files** Version
3.4.0.0

Windows Version
10.0.22631.3527

### **Log** File

[debug.log](https://github.com/files-community/Files/files/15286416/debug.log)
[debug_server.log](https://github.com/files-community/Files/files/15286417/debug_server.log)

**Comment by 0x5bfa** [comment] 2024-05-12 14:00
Please open an issue per issue.
Can you open new one for it?

**Comment by Josh65-2201** [comment] 2024-05-12 15:06
Since it the same cause we can track this in #14555 and update the title. You can check there or click subscribe in the right sidebar for updates.

**Closed by Josh65-2201** 2024-05-12 15:06 UTC
Labels: bug, needs-reproducing
