### ISSUE TITLE
Bug: Can't create a shortcut to a folder

### ISSUE THREAD

**Issue by hishitetsu** [files-community/Files#15975] opened 2024-08-08 04:14 UTC
### Description

If I try to create a shortcut to a folder, a dialog that says it requres administrator privileges appears and I can't create the shortcut even if I choose creating the shortcut on the desktop instead.

### Steps To Reproduce

1. Select New -> Shortcut on the toolbar.
2. Enter the location of a folder.
3. Press Create. A dialog that says it requres administrator privileges will appear.
4. Press Create again. No shortcuts will be created.

### Requirements

The shortcut should be created with no warnings.

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4651

### Log File

[debug.log](https://github.com/user-attachments/files/16537586/debug.log)

**Comment by yaira2** [comment] 2024-08-08 04:17
Is this an issue before #15934?

**Comment by hishitetsu** [comment] 2024-08-08 04:19
> Is this an issue before #15934?

Yes

**Comment by 0x5bfa** [comment] 2024-08-08 04:47
Fyi ~~I an planning to remove UIFilesystemHelpers and create IStorageShortcutService and service.CreateNormalLink/Async/(string path, string arguments).~~
It's totally up to someone who work on though.

**Comment by 0x5bfa** [comment] 2024-08-08 04:50
@hishitetsu this functionality looks totally malfunctioning because you can't also target to drive root. Do you think those fixes would require major change on shortcutting abilities and it worth having a service  IStorageShortcutService?

**Comment by salihselimsekerci** [comment] 2024-08-09 15:06
To resolve the issue with the drag-and-drop functionality in the Files app:

Update the App: Ensure you are using the latest version of the Files app.
Run as Administrator: Try running the Files app as an administrator to grant necessary permissions.
Check Windows Settings: Verify that no Windows settings, especially User Account Control (UAC), are blocking the functionality.
These steps might resolve the problem.

**Comment by Josh65-2201** [comment] 2024-08-09 15:07
Drag and drop doesn't work when Files is running as admin

**Comment by salihselimsekerci** [comment] 2024-08-09 15:14
Problem Description:
When trying to create a shortcut to a folder using the "New -> Shortcut" option, a dialog requesting administrator privileges appears, and the shortcut cannot be created, even when selecting the desktop as the destination.

Steps to Reproduce:

Select "New -> Shortcut" on the toolbar.
Enter the folder location.
Press "Create" (a dialog requesting administrator privileges appears).
Press "Create" again; the shortcut isn't created.
Solution:

Run as Administrator: Try running the application as an administrator to bypass the permission issues.
Change Folder Permissions: Ensure that the folder's permissions allow shortcut creation without requiring elevated privileges.

**Comment by Josh65-2201** [comment] 2024-08-09 15:20
This is an issue with the code base. Hishitetsu is a developer of Files and Yair who owns the project has approved this. Creating a shortcut should work like Windows File Explorer and not required the user to change folder security options either.

**Comment by salihselimsekerci** [comment] 2024-08-09 15:31
### English

**To resolve the shortcut creation issue in the Files application:**

1. **Identify the Problem Area**: Focus on the part of the code responsible for handling the shortcut creation process.
2. **Modify the Code**: Adjust the logic to avoid requiring administrator privileges when creating shortcuts, similar to how Windows File Explorer handles it.
3. **Testing**: Test the changes locally to ensure that the shortcut creation works without security prompts.
4. **Submit a Pull Request**: After testing, submit the changes via a pull request on GitHub for review.

**Example Code Snippet:**

```javascript
// Hypothetical example: Ensure the shortcut creation doesn't require elevated privileges
function createShortcut(targetPath) {
    if (!isElevated()) {
        // Standard shortcut creation process
        createLink(targetPath, getUserDesktopPath());
    } else {
        // Handle scenarios requiring elevation differently
        requestAdminPrivileges();
    }
}
```

### Türkçe

**Files uygulamasındaki kısayol oluşturma sorununu çözmek için:**

1. **Sorunlu Alanı Belirle**: Kısayol oluşturma sürecinden sorumlu olan kod bölümüne odaklan.
2. **Kodu Değiştir**: Kısayol oluştururken yönetici ayrıcalıkları gerektirmeyen bir mantık oluştur, tıpkı Windows Dosya Gezgini'nde olduğu gibi.
3. **Test Etme**: Yapılan değişiklikleri yerel olarak test ederek, kısayol oluşturmanın güvenlik uyarısı olmadan çalıştığından emin ol.
4. **Pull Request Gönder**: Testlerden sonra, değişiklikleri inceleme için GitHub üzerinden bir pull request ile gönder.

**Örnek Kod Parçası:**

```javascript
// Örnek: Kısayol oluşturmanın yükseltilmiş ayrıcalık gerektirmemesini sağla
function createShortcut(targetPath) {
    if (!isElevated()) {
        // Standart kısayol oluşturma işlemi
        createLink(targetPath, getUserDesktopPath());
    } else {
        // Yükseltme gerektiren durumları farklı şekilde ele al
        requestAdminPrivileges();
    }
}
``` 

Bu adımları izleyerek sorunu çözebilir ve katkıda bulunabilirsin.

**Comment by hishitetsu** [comment] 2024-08-10 06:05
> @hishitetsu this functionality looks totally malfunctioning because you can't also target to drive root. Do you think those fixes would require major change on shortcutting abilities and it worth having a service IStorageShortcutService?
> 
> Also, I think shortcut creation needs a COM 'IShellLink' interface.

I haven't had time to work on Files for a while and haven't checked it out yet, but I'm sure there are all sorts of problems with creating shortcuts.
But this is a basic feature, so if there is a way to fix it quickly before taking the time to completely rewrite it, I'd like to fix it quickly first.

**Comment by jross11211** [comment] 2024-08-18 23:34
Same. Was it working before? I'm might try to check past versions and report on it. If I'm in the mood later I might try and fix it myself, but no promises.

Maybe this is a good repo for learning the windows side of things. I mainly do Linux backend app development.

**Comment by jross11211** [comment] 2024-08-20 03:37
The bug happened in between "v3.3.1" and "v3.3.2". I might narrow it down more tomorrow.

**Comment by jross11211** [comment] 2024-08-20 04:52
I'm pretty sure this is the commit that broke it. https://github.com/files-community/Files/commit/7cde881b6aea31fb128781dbd802fb8778bfcfd9

**Comment by hishitetsu** [comment] 2024-08-20 11:08
@jross11211 are you working on this? I was going to fix it but will wait if you are working on it.

**Comment by jross11211** [comment] 2024-08-20 19:57
I have a very fast computer, like +/- 5% the fastest in the world. So it's relatively easy for me to identify when a feature broke.

For this I might need to let an established developer on this project take it. Personally, I just enjoy learning new stacks. Since this bug will require a dependency change, it may not be something I can do in a timely manner. I took a couple attempts, but it doesn't seem to build on the current version of main by simply changing the version.

FYI, make sure you do a full clean (only committed files) and uninstall the app in the start menu when reproducing it. I'm not familiar with this stack, so sorry if that was already obvious. I'm mostly here to learn about the C#,C++,Visual Studio 2022 stack because I've never used it before.

Note for the developer: The new Microsoft licensing agreement is kind of scary for American users. I'd happily pay $8, but I'm absolutely not trusting Microsoft with any payment information anymore.

**Closed** 2024-08-20 22:35 UTC
Labels: bug
