### ISSUE TITLE
Right click the selected tab bar for various options

### ISSUE THREAD

**Issue by Nuzza** [files-community/Files#2048] opened 2020-10-08 00:00 UTC
**Is your feature request related to a problem? Please describe.**
Feature Request: Basically, it would be a great productivity improvement if you were able to right click a tab in the tab bar for various options similar to Chrome or Microsoft Edge.

**Describe the solution you'd like**
Some examples/ideas for the various options could be as follows:
- New tab (Ctrl+T)
- Refresh (Ctrl+R)
- Duplicate tab (Ctrl+D)
- Move tab to new window
- Close tab (Ctrl+W)
- Close other tabs (Ctrl+Shift+W)
- Reopen closed tab (Ctrl+Shift+T)

**Describe alternatives you've considered**
Currently, the only way to duplicate a tab is by copying the address from the address bar, creating a new tab, pasting in the address, and pressing enter. By adding various options such as duplicate tab to the tab bar, this makes the process of duplicating a tab much simpler requiring 1 step instead of several steps.

**Comment by yaichenbaum** [comment] 2020-10-08 00:47
Duplicate of #260.

**Closed by yaichenbaum** 2020-10-08 00:47 UTC
Labels: feature_request
