### ISSUE TITLE
Crash after opening properties of the pinned to sidebar folder

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2608] opened 2020-12-15 12:10 UTC
**Describe the bug**
Apps crashed after I trying to open properties

**To Reproduce**
1. Click the right mouse on any sidebar folder
2. Click on 'properties.'
3. Wait until the app will try to open another window and crash

**Expected behavior**
Properties window should work without crashing
**Screenshots**
![crash_prop](https://user-images.githubusercontent.com/18252816/102213070-dc066300-3ede-11eb-9fc4-a9673c61cddc.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2020 20277]
 - App version: [v0.21.7]

**Log file**
2020-12-15 13:59:03.0372|ERROR|.ctor|The application called an interface that was marshalled for a different thread.

The application called an interface that was marshalled for a different thread.
|System.Exception: The application called an interface that was marshalled for a different thread.

The application called an interface that was marshalled for a different thread.

**Comment by yaichenbaum** [comment] 2020-12-15 14:16
Duplicate of #2537.

**Closed by yaichenbaum** 2020-12-15 14:16 UTC
Labels: bug
