### ISSUE TITLE
Tags reset everytime you restart app

### ISSUE THREAD

**Issue by pj815000** [files-community/Files#14362] opened 2024-01-06 04:03 UTC
### Description

just how the title states it, all tags reset whenever you restart the app. Im sure this is a bug not intentional

### Steps To Reproduce

1. edit tags to something personal
2. restart the app manually with either taskbar or task manager
3. watch as all your personalized tags disappear

### Requirements

- whenever the files app restarts, Make sure all tags stay the same with their respected color and name

### Files Version

3.1.0.0

### Windows Version

10.0.22631.2861

### Log File

[debug.log](https://github.com/files-community/Files/files/13848291/debug.log)

**Comment by Josh65-2201** [comment] 2024-01-06 12:05
Thanks for the report, Are you talking about added tags to file/folders being removed or what the tag text is in Files settings?

**Comment by arrhat** [comment] 2024-01-09 19:50
I believe I am having the same issue, and I have more details to add. Edits to existing tags (i.e. changes to the tag name and/or color) are being dropped on program exit, except _sometimes_ the first edit made is saved. Here's what happened:

- I started with a list of nine tags: Tag1, Tag2,... Tag9. (I don't assume that the exact number of tags does not matter, but I had nine when I encountered this.)
- Rename all tags: Tag1a, Tag2a,... Tag9a. 
- - Note that I closed the settings dialogue (but not Files) between each tag edit. This might explain some behavior encountered later on.
- Exit and reopen Files. Only the _first_ edit was saved! So I now have a list of tags: Tag1a, Tag2, Tag3,... Tag9. 
- - Note that it's the first _edit_ that's saved, not the first tag in the list. If I started renaming tags from the bottom of the list -- so that Tag9a was the first edit -- then I end up with a tag list like this: Tag1, Tag2,... Tag8, Tag9a.
- I then tried to edit just 2 tags at a time, with the same result. (That is, if I change Tag2 to Tag2a and Tag3 to Tag3a, then exit and reopen, then only that first edit is saved -- I end up with Tag2a and Tag3.) The only way to edit all the tags in the list was to rename one at a time and close/reopen Files between each edit.
- Next I tried to edit all the tag colors at once. I picked new colors for all nine tags, closed and reopen Files. _None_ of the edits were saved.
- Changing tag colors one at a time (closing and reopening Files between each edit), worked. 
- I don't know why it saved the first edit when I changed all the tag names at once and none of the edits when I was changing all the tag colors, but possibly it has to do with the fact that I closed the settings dialogue between each tag rename, but did the color changes all at once?

Running Files 3.1.1.0 on Windows 10.

I also encountered another tag-related issue, but I'm not totally certain, based on the documentation, what the intended behavior is, so I'm not sure whether it is a bug. But I'm reporting it here because it relates to how I encountered the above bug. If devs want to spin it off as a separate bug report, go ahead.

I recently did a fresh install of Files, uninstalling the old version (one of the 2.x versions, I didn't make a note of which) and installing 3.1.1.0. When I opened it up and started browsing through my files, all my tags were named Unknown. Based on the [documentation](https://files.community/docs/features/tags), I had expected tag names to carry over across installs since they are stored in the tagged files themselves. And they sort of did -- my files are all still tagged. But before the tags would display properly I had to select each Unknown tag, see what files were associated with it to figure out what the tag had been, and rename the tag in the tag settings. So, I'm not sure whether this is a bug (or whether it's replicable) but it was kind of a hassle (especially with the tag-edit bug).

**Comment by yaira2** [comment] 2024-07-21 15:32
We are planning to move away from our approach that relies on the Windows Search Index. This change aims to address the issue and enhance overall reliability. Please refer to https://github.com/files-community/Files/issues/15272 for further updates.

**Closed by yaira2** 2024-07-21 15:32 UTC
Labels: bug, needs - additional info
