### ISSUE TITLE
App crashed when copying many files, not all files are copied, slow file operation

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#1911] opened 2020-09-11 11:23 UTC
Steps to reproduce
1. Create a folder
2. Create a text file
3. Copy the text file a few times
4. Select the new text files
5. Copy the text files (Repeat 4 and 5) until you have like 50 files 
6. Press CTRL+V a few times rapidly

[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5208551/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5208552/debug.txt)

It also seems like Files UWP is not copying all files if I copy and paste  around 1100. (See video: https://youtu.be/25vWaXKKITQ)

Last but not least, the file operation is extremely slow compared to the default Explorer (See video:  https://youtu.be/Jcr4lRnnDpU)

**Comment by Jaiganeshkumaran** [comment] 2020-09-11 11:35
Related to #1222

**Comment by duke7553** [comment] 2020-09-12 20:59
Based on your log file, I've discovered the cause of a crash and made necessary improvements to fix it. We're hoping to get these changes out to testers soon. In the meantime, these changes landed in the StatusCenter branch.

I'll leave this open because there are other issues you reported here which may require additional validation.

**Comment by yaichenbaum** [comment] 2020-12-03 03:13
@R3voA3 Is this still an issue in v0.21.1?

**Comment by R3voA3** [comment] 2020-12-03 08:24
Yes, still the same issue.

**Comment by yaichenbaum** [comment] 2021-01-04 05:19
@R3voA3 This issue should be resolved in `master`.

**Closed by yaichenbaum** 2021-01-04 05:19 UTC
Labels: bug, triage approved
