### ISSUE TITLE
Open a dialog, like Windows Explorer, saying to insert a disc in the player

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#4550] opened 2021-04-11 14:51 UTC
Is your feature request related to a problem?
R: No, it's just a feature request.

Describe the solution
R: So, my idea would be to insert a resource that exists in Windows Explorer. Currently, Files, when opening the disc player, which does not have any disc inserted, says that the folder is empty. It would be a good idea to do what Windows Explorer does: open a dialog to insert a disc and even open the disc player automatically.

Additional comment
R: Here is an image of the dialog you do when ask to insert the disc. It's in portuguese from Portugal but you will be able to replicate that with your disc player and that there is no disc inserted.

![Captura de ecrã 2021-04-11 154910](https://user-images.githubusercontent.com/78214358/114309015-a7e22e00-9add-11eb-8ec7-93c56077330c.jpg)

**Comment by Jaiganeshkumaran** [comment] 2021-04-12 14:14
Duplicate of #1262

**Comment by nvi9** [comment] 2021-04-13 10:54
> Duplicate of #1262

We could have both the dialog showing up in this case with a button to open the disc tray.

**Comment by esibruti** [comment] 2021-04-13 11:25
![Concept BT 2](https://user-images.githubusercontent.com/78214358/114545004-50fe6500-9c53-11eb-8fc0-a31f4501e6f4.jpg)

This image above is a good concept of when we try to open the player when there is no disc inserted.

I even had an idea that we could make a Help button to explain that we can insert a CD / DVD or mount an ISO.

What do you think of the idea?

**Comment by esibruti** [comment] 2021-07-23 13:33
@yair100 In this new update, it still doesn't have that window (yes, I know that), but the problem is that it has options like paste or create new folder. It shouldn't let it do this on the empty disk player...


https://user-images.githubusercontent.com/78214358/126789322-29dbbe1f-3469-40f6-90b7-b71dfcd21655.mp4

**Comment by yaichenbaum** [comment] 2021-07-23 17:27
@esibruti Can you open a seperate issue for this?

**Comment by esibruti** [comment] 2021-07-23 17:31
> @esibruti Can you open a separate issue for this?

Yes, of course

**Comment by yaichenbaum** [comment] 2021-08-11 13:23
This issue should be resolved with #5740.

**Closed** 2021-08-11 13:22 UTC
Labels: enhancement, triage approved
