### ISSUE TITLE
Network Locations duplicate items on successive views

### ISSUE THREAD

**Issue by aaronbeecham** [files-community/Files#2923] opened 2021-01-11 22:36 UTC
**Describe the bug**
When viewing a network location, if I close and then open the location again, all items are listed an extra time.
Open a network location once and the files inside the location appear correctly.
Close and re-open, now all the items in the directory are doubled up.
Close and re-open a third time, now all the items in the directory are trippled. etc...

**To Reproduce**
1. Manually go to network location
2. View items
3. Close network location
4. Manually go to network location again

**Expected behavior**
Files should list accurately

**Screenshots**
https://i.imgur.com/rouD1PH.png

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.685
 - App version: 1.0.0.0

**Log file**
[debug.txt](https://hastebin.com/raw/agitexolog)
[debug_fulltrust.txt](https://hastebin.com/raw/faxapulowu)

**Comment by gave92** [comment] 2021-01-11 23:16
Could you try disabling "Cache files and folders for better performance" option in Files settings and see if the issue is fixed?
Duplicate of #2908

**Closed by gave92** 2021-01-11 23:16 UTC
Labels: bug

**Comment by aaronbeecham** [comment] 2021-01-12 00:02
This does "resolve" the issue. However performance is now obviously
significantly worse.

**Comment by gave92** [comment] 2021-01-12 00:06
Thanks for confirming this. The issue had been fixed and will ship with the next release
