### ISSUE TITLE
Bug: Inconsistency of properties window when drives are pinned

### ISSUE THREAD

**Issue by ZTL-UwU** [files-community/Files#14530] opened 2024-01-23 09:12 UTC
### Description

When a drives & libraries are pinned to the side bar, the properties window is inconsistent with the normalproperties window.

### Steps To Reproduce

1. pin a drive or library to the side bar
2. right click to open the properties window

### Requirements

- Make the properties window consistent

### Files Version

3.1.1.0

### Windows Version

22H2 1000.22681.1000.0

**Pinned**
![image](https://github.com/files-community/Files/assets/49156174/9950ce79-fdc8-43db-a1bf-186d27331821)

**Not pinned**
![image](https://github.com/files-community/Files/assets/49156174/76a07d2c-c7b0-4393-a774-42b7a15a09d8)

**Comment by ZTL-UwU** [comment] 2024-01-23 14:34
I'm trying to fix this right now.

**Comment by ZTL-UwU** [comment] 2024-01-23 23:30
> What's it inconsistent with? Some screenshots might help.

There are screenshots already at the end of the first comment. You can click to see them.

**Comment by yaira2** [comment] 2024-01-23 23:36
Ah, I missed them because they were collapsed. We're currently discussing this issue in #14522.

**Comment by 0x5bfa** [comment] 2024-02-13 08:10
I can repro and realize this is not the same issue as #14522.

Reopening and reviewing the PR.

**Comment by 0x5bfa** [comment] 2024-02-22 08:36
Duplicate of #14522. Further information, please subscribe or comment on that issue👍

**Closed by 0x5bfa** 2024-02-22 08:36 UTC
Labels: bug, more-info
