### ISSUE TITLE
Crash when deleting from custom library downloads folder

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5948] opened 2021-08-27 21:56 UTC
### Description

^

### Expected behavior

Shouldn't crash

### Files Version

1.9.27

### Windows Version

10.0.19043.1165

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7069567/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7069568/debug_fulltrust.log)

**Comment by gave92** [comment] 2021-08-28 07:35
Fixed by #5929 / Files 1.9.28.

**Closed** 2021-08-28 07:34 UTC
Labels: bug

**Comment by gave92** [comment] 2021-08-28 07:41
Hi @josh-65 this issue should be fixed in 1.9.28 (it's the same as #5927) but we haven't really understood the cause of it.
Did you happen to have installed some new program recently? Something that would qualify as a "shell extension"?

**Comment by josh-65** [comment] 2021-08-28 09:48
The closet one I downloaded was Mp3tag but it was the portable installation at first in downloads. Don't remember if it happen before or after I installed it system wide.
