### ISSUE TITLE
Bug: Folder size index shouldn't calculate the size of symlinks

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#8216] opened 2022-02-08 00:27 UTC
### Description

With the experimental option on i've noticed folders are report being double the size of my drive im looking though becuase it counting symlinks shortcuts.

### Steps To Reproduce
1. Turn on option to show folder sizes
2. Create a shortcut to large directory
3. Observe that the size of the shortcut destination is included in the folder size calculation 

### Requirements 
- Stop including symlinks in the folder size calculation

### Files Version

2.1.9.0

### Windows Version

10.0.19043.1503

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8019632/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8019633/debug.log)

**Comment by QuaintMako** [comment] 2022-12-03 22:05
Cannot reproduce the issue. Is it still true for you @Josh-65 ?

![8216](https://user-images.githubusercontent.com/110472580/205463940-2686ce05-4bcc-4d64-af90-573a933a890d.gif)

**Comment by Josh-65** [comment] 2022-12-04 12:20
Well it doesn't show the size but also no content. Shows them in File Explorer. Log doesn't show any error.
![image](https://user-images.githubusercontent.com/26977075/205490034-0cae81e0-acd3-49f2-add8-2f728cd0af4e.png)

**Comment by lukeblevins** [comment] 2023-03-26 22:24
@yair100 FYI

**Comment by yaira2** [comment] 2023-04-27 03:58
@Josh65-2201 this issue has been resolved and will be included in one of the next releases.

**Closed** 2023-04-27 03:58 UTC
Labels: bug
