### ISSUE TITLE
Create and editing tags.

### ISSUE THREAD

**Issue by sercanserdar** [files-community/Files#10989] opened 2023-01-12 07:07 UTC
### What feature or improvement do you think would benefit Files?

I think this feature is the most powerful feature of this application.
Therefore, I think that priority and importance should be given.

- Tag Creating
- Tag Editing
- Tag Icons

### Requirements

- Tags can be managed by settings menu or your own Ui. It doesn't matter.
- Tags can be added to files or folders by drag and drop.

### Files Version

Sürüm: 2.4.21.0

### Windows Version

Windows 10 22H2 OS Version: 10.0.19045.2486

### Comments

Tags cannot be created and edited in the current version. There are only default color tags. 
Is this feature available or will it come?

**Comment by ferrariofilippo** [comment] 2023-01-21 08:53
Duplicate of #9588 
BTW you can edit Tags' names and colors opening `Settings > Advanced > Edit Tags`

**Closed** 2023-01-21 11:34 UTC
Labels: feature request
