### ISSUE TITLE
Crashes when opening external drives

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#4439] opened 2021-04-03 17:01 UTC
**Explain the bug**
When I attempt to open a Git repository on an external drive, not only does it refuse to show it, but it also just crashes

**To reproduce**
1. Go to 'an external drive'
2. Click on 'the repos folder'
3. Scroll down to 'wait for it to load'
4. See it crash

**Expected behavior**
You would expect to see it open it fine, just like normal, but it crashes, and even when I try again, restart the computer, whatever, it still crashes. I've noticed it happens more in the latest updates. 

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6253065/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6253066/debug.txt)

**Screenshots**
Sorry, no screenshots

**System Information**
 - OS Version: Windows 10 20H2 19042.867
 - App version: 1.5.2.0

**Comment by gave92** [comment] 2021-04-03 17:35
Thanks for this report.
- Do you get a notification when the app crashes?
- Could you try the following?
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

**Comment by DeveloperWOW64** [comment] 2021-04-03 17:45
no, didn't get any notification
i. mostly works when i enable this, but stilll crashes

ii. dont thinks there's any difference

iii. here is a video of me opening it and it crashing: 
[Video of Files app crashing.zip](https://github.com/files-community/Files/files/6253141/Video.of.Files.app.crashing.zip)
i'll

**Comment by gave92** [comment] 2021-04-03 19:55
Mind trying this too?

- does it work if you disable these two settings (turn off caching) under Experimental?

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by kanetik** [comment] 2021-04-04 14:27
I've been seeing the same thing. In attempting to answer your questions, I was trying to get folders to all appear in tile or detail mode, and noticed that it was switching as I'd enter new folders. (Side note: after a crash, if you use the same folders to reproduce again, it works fine, so once it's cached, it seems to be fine.)

Anyhow, I set the "individual settings per folder" to off, and then tried to reproduce, both in detail and tile views, and could not. I wonder if the caching is having issues when the views differ between folder you are in and next level down folders?

**Comment by kanetik** [comment] 2021-04-04 14:29
Just found another issue which references the same discovery. 
Duplicate of https://github.com/files-community/Files/issues/4304#

**Comment by DeveloperWOW64** [comment] 2021-04-04 17:33
> (Side note: after a crash, if you use the same folders to reproduce again, it works fine, so once it's cached, it seems to be fine.)

No, because it crashed, then crashed again, then just kept on crashing and sometimes it would stop. I don't think caching has anything to do with it

**Comment by gave92** [comment] 2021-04-04 19:36
Merging with #4304.

**Closed** 2021-04-04 19:35 UTC
Labels: bug, more-info

**Comment by DeveloperWOW64** [comment] 2021-04-05 10:10
ok, but I don't think it is related to it being in tiles/grid mode or whatever, since it did crash when inside that mode
