### ISSUE TITLE
Improving the sidebar

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#692] opened 2020-04-25 02:25 UTC
**Original sidebar concepts:**

![sidebar concept](https://user-images.githubusercontent.com/61259627/84311910-1bb85080-ab32-11ea-933c-2d76c7becf47.png) ![84311910-1bb85080-ab32-11ea-933c-2d76c7b](https://user-images.githubusercontent.com/61259627/89138722-735bb280-d50a-11ea-89eb-5861b30b3f4b.png)

**Comment by duke7553** [comment] 2020-04-25 15:39
@xPoppyx That's an interesting take-having the drives go under This device. 

Originally, I was proposing something like this, with three sections: 
![image](https://user-images.githubusercontent.com/20365014/80283928-3bfa9000-86e9-11ea-99c1-ff13a18ec72d.png)
(Ignore the new tab page stuff for now)

**Comment by xPoppyx** [comment] 2020-04-25 15:48
It looks great, maybe with an option to choose the order? for example first "pinned items", then "This device" and "Drives"

**Comment by yaichenbaum** [comment] 2020-04-26 01:35
I don't know how hard it would be but ideally it should be possible to rearrange the items in the sidebar. Additionally home page shouldn't prevent improving the sidebar.

**Comment by Jaiganeshkumaran** [comment] 2020-06-23 05:21
@mdtauk There are native apps for iCloud and Dropbox. We can pin their folders if the native client is installed on the device.

**Comment by jayasio** [comment] 2020-07-01 02:23
@duke7553 I took the liberty to modify your idea to propose a slightly different version.

![80283928-3bfa9000-86e9-11ea-99c1-ff13a18ec72d](https://user-images.githubusercontent.com/34701149/86195360-5c721b00-bb6e-11ea-87fd-13238aafdc2a.png)
Idea

![Group 56](https://user-images.githubusercontent.com/34701149/86195369-61cf6580-bb6e-11ea-8dff-7de52a592bff.png)
Proposed

The sidebar looks streamlined and the blue marking is not floating far from the left edge. (important for quickly identifying which folder the user is currently in)
I feel having an icon in the sections is redundant because, for example, the drives section doesn't need a drive icon when all its children have the drive icon. 

Also, the spacing between sections improves the grouping a bit better; the extra space can be removed when the sections are minimized (as can be seen in the dummy section). Maybe the actual spacing can be tweaked to make it a little denser to fit more.

**Comment by XPoppyX** [comment] 2020-08-04 15:39
Option 2

![84311910-1bb85080-ab32-11ea-933c-2d76c7b](https://user-images.githubusercontent.com/61259627/89138722-735bb280-d50a-11ea-89eb-5861b30b3f4b.png)

**Comment by generalguy41** [comment] 2020-08-04 17:38
I like the idea of having a bit more separation like the previous concept, with either padded nesting for each header or space between headers. I think it makes a potential long list cleaner/easier to navigate.

**Comment by duke7553** [comment] 2020-08-04 17:54
Regardless, we'll be using the default hierarchical nav view design with little/no customizations to the padding or item indentations.

**Comment by generalguy41** [comment] 2020-08-04 18:55
> 
> 
> Regardless, we'll be using the default hierarchical nav view design with little/no customizations to the padding or item indentations.

Is that the design shown in "Option 2"?

**Comment by ArtexJay** [comment] 2020-11-17 00:52
Will there be an optional to disable Quick Access?

**Comment by XPoppyX** [comment] 2020-11-17 01:05
I think so

**Comment by yaichenbaum** [comment] 2020-12-18 19:53
The goal of the sidebar control is to access the most important directories on your device. The built in Files Explorer in Windows was designed a little differently and it blurs the lines between the navigation menu and the list of items. The new design we are looking at implementing in Files no longer pins all the library locations by default, instead the new design will only have four items pinned by default that will go under the favorites section.

Underneath the favorites section, there will be a collapsible section for your cloud storage, this section will be hidden if Files does not detect a cloud storage provider on your device.

The next section will be for devices, this section will only show if you connect removable drives. This section will be customizable and will have the option to show internal drives in case the user prefers to see their drives there.

As seen in the concepts, there will be a section for Network drives, and we can add a section for WSL drives as well once we add support for them.

![image](https://user-images.githubusercontent.com/39923744/102654607-d0b17280-413e-11eb-9b32-96da31eda68b.png)

**Comment by duke7553** [comment] 2021-01-24 06:13
I am planning on starting work on some of the pre-requisite tasks for enhancements to the sidebar.

In the meantime, we'd like to know:

- **If you had to pick, what set of 3-4 locations do you need quick access to the most?** For example, we know that the Desktop folder is far less important for immediate access than the Downloads folder in the collaborative world we live in. This is because the desktop is already visible by default in Windows providing users ample opportunity to access it. Conversely, we want to accommodate the users who would want the Desktop location easily accessible from the Sidebar. 
- **How many sidebar items do you typically have?** This count should include the default items. Please let us know if this can be improved.
- **How satisfied are you with the height of the sidebar items on both desktop and touch?**
- **If you could add one feature to the sidebar to improve your workflow, what would it be?**

**Comment by mdtauk** [comment] 2021-01-24 07:24
I hide my desktop icons, so when I dump something on the desktop, I access it via file explorer window

**Comment by generalguy41** [comment] 2021-01-24 15:32
- **If you had to pick, what set of 3-4 locations do you need quick access to the most?** 
Desktop and Downloads in the "quick access" location, as well as I guess the "Home" link, which in explorer I would equate to the "This PC" link. Though I assume that's not going anywhere haha.
- **How many sidebar items do you typically have?**
![image](https://user-images.githubusercontent.com/8879244/105634607-d7619280-5e2c-11eb-93ae-f864040bf94b.png) ![image](https://user-images.githubusercontent.com/8879244/105634611-dd577380-5e2c-11eb-98a4-e0ed7bc434eb.png)
I don't typically use the recycling bin, but I leave it there for occasional testing.
- **How satisfied are you with the height of the sidebar items on both desktop and touch?**
I'd like it (and the rest of the UI, eventually) to be more compact. Not necessarily to the same level as explorer, but just a bit more. You can see in the screenshots above the difference in space the same number of links takes up.
- **If you could add one feature to the sidebar to improve your workflow, what would it be?**
Dragging to reorder/place items, though I know that's being worked or planned on. I'd love to see coloured icons if that ever becomes possible.

**Comment by Tolo789** [comment] 2021-01-28 13:37
> If you could add one feature to the sidebar to improve your workflow, what would it be?

Just discovered `Files` so I'm probably wrong, but when reading this thread it seems to me that you are not planning on having an unlimited number of sections in the sidebar?

I would love to be able to create (and rename) as many sections as I like, and then freely move my pinned folders from one section to the other. Did I just missed it?
Of course I don't mind at all the automatically generated sections such as Drives, Devices and so on. And maybe we shouldn't be able to move a pinned folder in those sections, but I don't know how much more complexity it would add?

P.s: Since Slack [rework of their sidebar](https://www.theverge.com/2020/3/18/21184865/slack-redesign-update-sidebar-changes-available-now-download) I've seen a huge boost on how efficiently I can retrieve my pinned items and I can't wait to have the same for my PC folders :)

**Comment by ntillet** [comment] 2021-02-25 02:18
I can't use this explorer yet as we're missing the favorites part. Probably something very personal, or maybe not, who knows! But I'll be expecting this feature with eager!

**Comment by yaichenbaum** [comment] 2021-03-07 17:05
@XPoppyX This issue should be resolved with the latest in `main`.

**Closed** 2021-03-07 17:04 UTC
Labels: enhancement, triage approved
