### ISSUE TITLE
Files crashes when dragging a file from 7-Zip

### ISSUE THREAD

**Issue by sschr15** [files-community/Files#2198] opened 2020-11-01 19:07 UTC
**Describe the bug**
Dragging a file from 7-Zip File Manager will cause Files to crash upon entering the window's area.

**To Reproduce**
1. Open an archive using 7-Zip
2. Select a file
3. Drag it onto a Files window
4. See error toast

**Expected behavior**
The file shows as attempting to drag a file normally acts.

**Screenshots**
![Files has encountered an error upon dragging a file from 7-Zip to Files](https://user-images.githubusercontent.com/15277819/97811798-77e75280-1c42-11eb-8d6d-10366bf848a4.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 Build 19042.608
 - App version: v0.18.0.0

**Additional context**
Files forcefully closes, and this occurs on every attempt, no matter the archive opened by 7-Zip.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5471560/debug.txt)

**Comment by gave92** [comment] 2020-11-01 21:35
Thanks for opening this feedback item.
Closing as duplicate of #2023

**Closed by gave92** 2020-11-01 21:35 UTC
Labels: bug
