### ISSUE TITLE
Bug: Right clicking column layout crashes app

### ISSUE THREAD

**Issue by dmizz** [files-community/Files#16193] opened 2024-09-13 22:16 UTC
> [!Important]
> Current workaround
> Go to Files settings > Actions > Change the bindings for both Open Terminal and Open Terminal as Admin to something else (use a letter/number with as many modifiers as you wish; DO NOT use ~ or any of the keys to the right of P, L, M)

### Description

Experiencing overall stability issues. I LOVE this app, but to use it for mission critical work I need it to be way more stable. 

Main issues are:
Right clicking can cause a crash 25% of the time, especially in column mode it seems.
File transfers get hung up and cancel a ton.
Opening the app always lags and will fail sometimes.

### Steps To Reproduce

- Switch to Column View
- Right click empty space in last column

### Requirements

- Fix crash

### Files Version

3.7.0.0

### Windows Version

10.0.22631.4169

### Log File

[debug.log](https://github.com/user-attachments/files/16999828/debug.log)

**Comment by Josh65-2201** [comment] 2024-09-13 22:21
Thanks for the report, Please update to 3.7.6 https://files.community/download and see if this is still an issue

**Comment by alikhan134** [comment] 2024-09-14 11:41
Dude World Have change 
Do Chatgpt

**Comment by yaira2** [comment] 2024-09-15 01:01
@dmizz thank you for your feedback, we're constantly working to improve stability and will continue to so.

I'd like to try and track down the crash you mentioned with right clicking. If you open the settings file (Settings > Advanced > Edit settings file), there should be a value under userid. If you can send the value here, I can locate the crash in Sentry and do my best to debug this issue.

**Comment by dmizz** [comment] 2024-09-16 00:09
When I click 'edit settings file' nothing happens

**Comment by yaira2** [comment] 2024-09-16 02:15
That's odd, this could also be why Files has been acting up for you. Can you try to uninstall and reinstall Files?

**Comment by Josh65-2201** [comment] 2024-09-16 13:02
I think it more likely that no programs are set to open Json files, Please try going to Files settings > About > Open log location > open `settings` folder > open `user_settings.json`

**Comment by dmizz** [comment] 2024-09-16 15:40
Here you go

**Comment by Josh65-2201** [comment] 2024-09-16 15:41
Email attachments don't work. You will have to click the `View on GitHub` link at the bottom of the email > Copy and paste or click the add attachment button to select the file > Wait until you don't see `uploading` in the text > Click the green comment button.

**Comment by dmizz** [comment] 2024-09-16 15:42
[user_settings.json](https://github.com/user-attachments/files/17015815/user_settings.json)
k!

**Comment by yaira2** [comment] 2024-09-16 21:02
I located a crash related to drag & drop, can you confirm if that's the issue you were referring to?

**Comment by dmizz** [comment] 2024-09-16 21:08
I've had multiple crashes per day. I have
uninstalled/reinstalled/updated/tried the Preview version. The most common
crash is when I right click to make a new folder. It hangs up when the
right click menu is appearing and crashes. I have had some drag/drop
crashes as well.

**Comment by yaira2** [comment] 2024-09-16 21:11
Are you using v3.7.6?

**Comment by dmizz** [comment] 2024-09-16 21:12
3.7.7.0

**Comment by yaira2** [comment] 2024-09-16 21:14
If the issue doesn't show in the log file, you might get more info from Event Viewer.

**Comment by StampeSystem** [comment] 2024-09-17 14:57
I am facing exactly the same issues. Version 3.7.7.0. I am running in columns view. Every second time I am trying to open the context menu, the app is crashing. 

This is what I get from the event viewer:
Protokollname: Application
Quelle:        Application Error
Datum:         17.09.2024 16:48:29
Ereignis-ID:   1000
Aufgabenkategorie:Anwendungsabsturzereignisse
Ebene:         Fehler
Schlüsselwörter:
Beschreibung:
Name der fehlerhaften Anwendung: Files.exe, Version: 1.0.0.0, Zeitstempel: 0x666b0000
Name des fehlerhaften Moduls: Microsoft.UI.Xaml.dll, Version: 3.1.5.0, Zeitstempel: 0xcd7cc268
Ausnahmecode: 0xc000027b
Fehleroffset: 0x00000000004051c5
ID des fehlerhaften Prozesses: 0x0xEC4
Startzeit der fehlerhaften Anwendung: 0x0x1DB09048C41DD7A
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.7.7.0_x64__et10x9a9vyk8t\Files.App\Files.exe
Pfad des fehlerhaften Moduls: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.214.1843.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Berichtskennung: 1bc94954-9097-49a3-bcaf-ff231628f75f
Vollständiger Name des fehlerhaften Pakets: 49306atecsolution.FilesUWP_3.7.7.0_x64__et10x9a9vyk8t
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-17T14:48:29.8553468Z" />
    <EventRecordID>424249</EventRecordID>
    <Correlation />
    <Execution ProcessID="16960" ThreadID="25696" />
    <Channel>Application</Channel>
    <Security UserID="S-1-5-21-3480763896-15944912-731054092-1001" />
  </System>
  <EventData>
    <Data Name="AppName">Files.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">666b0000</Data>
    <Data Name="ModuleName">Microsoft.UI.Xaml.dll</Data>
    <Data Name="ModuleVersion">3.1.5.0</Data>
    <Data Name="ModuleTimeStamp">cd7cc268</Data>
    <Data Name="ExceptionCode">c000027b</Data>
    <Data Name="FaultingOffset">00000000004051c5</Data>
    <Data Name="ProcessId">0xec4</Data>
    <Data Name="ProcessCreationTime">0x1db09048c41dd7a</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.7.7.0_x64__et10x9a9vyk8t\Files.App\Files.exe</Data>
    <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.214.1843.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll</Data>
    <Data Name="IntegratorReportId">1bc94954-9097-49a3-bcaf-ff231628f75f</Data>
    <Data Name="PackageFullName">49306atecsolution.FilesUWP_3.7.7.0_x64__et10x9a9vyk8t</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

**Comment by dmizz** [comment] 2024-09-30 15:30
Yes I just installed Files Preview and gave it a shot. Crashed on my second right click.
[debug.log](https://github.com/user-attachments/files/17192462/debug.log)

**Comment by yaira2** [comment] 2024-09-30 15:42
When you right click, are you right clicking in the last column? Can you also confirm if you're right clicking an empty space?

**Comment by dmizz** [comment] 2024-09-30 15:57
Yes and yes.

Also if I click the "+New" button below the file path to create a new
folder it has not crashed for me.

**Comment by dmizz** [comment] 2024-10-03 20:11
just did a clean install of W11 for other reasons and was hoping this issue would sort of fix itself. Installed the latest Preview version. Crashed on right click immediately. 
[debug.log](https://github.com/user-attachments/files/17249600/debug.log)

**Comment by dmizz** [comment] 2024-10-16 05:50
any updates? this is driving me crazy

**Comment by yaira2** [comment] 2024-10-16 14:03
It's on our todo list

**Comment by Machaing** [comment] 2024-11-05 03:06
i met the similar issue and resolved it by myself, here is the course：

Files app log looks very clean, but i found “window event reporter” have some valuable info:
-----------------------------------------------------------------------------------------------------
错误应用程序名称: Files.exe，版本: 1.0.0.0，时间戳: 0x666b0000
错误模块名称: Microsoft.UI.Xaml.dll，版本: 3.1.5.0，时间戳: 0xc7b159d6
异常代码: 0xc000027b
错误偏移量: 0x0000000000405235
错误进程 ID: 0x0x5840
错误应用程序启动时间: 0x0x1DB2F2CEA2E8AED
错误应用程序路径: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.7.11.0_x64__et10x9a9vyk8t\Files.App\Files.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.275.500.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
报告 ID: 7ed953b6-216e-41d9-8df2-365054e7e7ff
错误程序包全名: 49306atecsolution.FilesUWP_3.7.11.0_x64__et10x9a9vyk8t
错误程序包相对应用程序 ID: App
-----------------------------------------------------------------------------------------------------

i search the key word "CoreMessagingXP.dll" "0xc000027b" in google, i found this error info of reason is that my machine miss .net sdk-6 
.NET 6.0 SDK, so i install it, restart app, and i didn't found the similar issue

[Reference]
https://learn.microsoft.com/en-us/answers/questions/868473/faulting-module-microsoft-ui-xaml-dll
[.NET 6.0 SDK]
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/sdk-6.0.427-windows-x64-installer

**Comment by dmizz** [comment] 2024-11-05 16:09
I installed .NET 6.0 SDK and the issue persists.

**Comment by asimhamid** [comment] 2024-11-18 15:12
Same! In Columns layout, right clicking on an item or blank area crashes the app every time, no exceptions.

**Comment by ferrariofilippo** [comment] 2024-11-19 21:55
**First, quick (& temp) fix:**
- Go to `Settings->Actions` 
- Change the bindings for both `Open Terminal` and `Open Terminal as Admin` to something else (use a letter/number with as many modifiers as you wish; DO NOT use `~` or any of the keys to the right of `P`, `L`, `M`)

**Cause of the crash:**
The context menu is implemented with `Microsoft.UI.Xaml.Input`, which uses the `VirtualKey` enum to specify the `KeyboardAccelerator`. The issue is that `VirtualKey` does not support `Oem` keys.

Concerned code:
`Files.App.Data.Models.ContextMenuFlyoutItemViewModelBuilder.Build()`
```
viewModel.KeyboardAccelerator = new Microsoft.UI.Xaml.Input.KeyboardAccelerator()
{
	Key = (VirtualKey)command.HotKeys[0].Key, // <------- This line here
	Modifiers = (VirtualKeyModifiers)command.HotKeys[0].Modifier
};
viewModel.KeyboardAcceleratorTextOverride = command.HotKeys[0].LocalizedLabel;
```

**Comment by Alovchin91** [comment] 2024-11-20 17:29
Same issue here. After using the workaround the app doesn't crash anymore, but the context menu flickers and doesn't appear sometimes. Also, in the Columns view there are constant unexpected scrolls to the left.

**Comment by Alovchin91** [comment] 2024-11-20 17:43
I've made a screen recording of the context menu flickering if it helps.

https://github.com/user-attachments/assets/c9dbfb9f-c185-4799-8fb9-6bf0f5601a67

**Comment by Josh65-2201** [comment] 2024-11-20 17:55
If you want it not required though

**Comment by yaira2** [comment] 2024-12-17 00:38
A fix will be included in the next update

**Closed** 2024-12-17 00:38 UTC
Labels: crash
