### ISSUE TITLE
Constantly crashing after pinning drive

### ISSUE THREAD

**Issue by Davikar** [files-community/Files#5955] opened 2021-08-28 23:43 UTC
### Description

So I was trying out the app for the first time and was fiddling around and testing stuff.
Then when I tried pinning a network drive to the sidebar the app just crashed.
After this the app just crashes every time I try to launch it.

### Steps To Reproduce

1. Try to pin a (network) drive to the sidebar. 
2. App crashes.
3. From now on the app crashes whenever you try to open it.

### Expected behavior

Does not crash, or at least not 

### Files Version

1.5

### Windows Version

Windows 10 21H1 19043.1165

### Relevant Assets

[debug.txt](https://github.com/files-community/Files/files/7071660/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/7071661/debug_fulltrust.txt)

**Comment by winston-de** [comment] 2021-08-29 06:16
Thanks for the feedback. As a workaround, can you please try resetting the app (Windows settings -> apps -> Files -> reset) and see if that helps?

**Comment by Davikar** [comment] 2021-08-29 14:54
Yeah, resetting worked.

**Comment by gave92** [comment] 2021-08-29 16:48
Glad the issue is solved. Closing as I cound not reproduce the issue in the preview  version of Files.

**Closed** 2021-08-29 16:47 UTC
Labels: bug
