### ISSUE TITLE
The replication function is defective

### ISSUE THREAD

**Issue by CrazyTomatoOo** [files-community/Files#2495] opened 2020-11-30 13:57 UTC
**Describe the bug**

Cannot copy recursively，Cannot overwrite copy

**To Reproduce**
1. Copy a folder with files.
2. Paste it into another directory.
3. Folders are not overwritten and files in folders are not copied

**Expected behavior**
Files in folders are copied
Folders with the same name will be overwritten

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 10.0.18362-SP0]
 - App version: [v0.21.0.0]

**Additional context**
This problem occur again after restarting the app.

**Log file**

**Comment by duke7553** [comment] 2020-11-30 22:22
Since we want to eventually support the full customizable overwrite experience, I'll close this in favor of: #1893 

Duplicate of #1893

**Closed by duke7553** 2020-11-30 22:22 UTC
Labels: bug, needs-triage
