### ISSUE TITLE
Files Constantly keeps having Unexpected crashes in certain folders 

### ISSUE THREAD

**Issue by DashCruft** [files-community/Files#4333] opened 2021-03-27 20:02 UTC
**Explain the bug**
Whenever I'm trying to go to some of my folders like folders inside of documents, the files app freezes and then crashes. It's a very annoying bug and it constantly keeps happening to me.

**To reproduce**
1. Go to Documents
2. Click on a folder (mine was github folder).
3. Crash occurs.

**Expected behavior**
Files app should work normally as excepted while opening folders.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6216328/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6216329/debug_fulltrust.txt)

**Screenshots**
https://youtu.be/EgUXYcoRWs4

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: v1.5.2
 
**Additional comment**
Does this problem happen again after restarting the app?
`This is a weird type of bug. It works fine sometimes but usually for me, it keeps crashing.`

**Comment by gave92** [comment] 2021-03-27 20:19
Looks like the same as #4304. This an annoying issue, even worse as it leaves no trace in the log files.
Could you try if the suggestion in the [comment](https://github.com/files-community/Files/issues/4304#issuecomment-807209691) works for you?

**Comment by emilnymann** [comment] 2021-03-27 20:51
I open #4304 and I can also reproduce the crash in several other folders, so maybe it should be merged with this issue as it seems to be broader than just AppData.

**Comment by gave92** [comment] 2021-03-27 20:52
Thanks @emilnymann, merging with #4304

**Closed by gave92** 2021-03-27 20:52 UTC
Labels: bug, help wanted, triage approved

**Comment by DashCruft** [comment] 2021-03-27 21:13
> Looks like the same as #4304. This is an annoying issue, even worse as it leaves no trace in the log files.
> 
> * Could you try if the suggestion in the [comment](https://github.com/files-community/Files/issues/4304#issuecomment-807209691) works for you?
> * Was it working ok in 1.5?

That suggestion still doesn't fix it.
Nope. I had this problem since v1.5

**Comment by gave92** [comment] 2021-03-27 21:28
What about this?
1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode
3. Try to trigger the crash

**Comment by DashCruft** [comment] 2021-03-27 21:33
That fixed it. I no longer crash 😳
