### ISSUE TITLE
New tab shortcuts

### ISSUE THREAD

**Issue by hederaetype** [files-community/Files#2014] opened 2020-10-01 14:18 UTC
**Is your feature request related to a problem? Please describe.**
It would be easier to navigate with some well-known functions in browsers

**Describe the solution you'd like**
Scrollwheel click to open a folder in a new tab

**Describe alternatives you've considered**
keyboard shortcut ctrl+t (similar to mac)

**Comment by yaichenbaum** [comment] 2020-10-01 20:40
Duplicate of #9.

**Closed by yaichenbaum** 2020-10-01 20:40 UTC
Labels: feature_request, needs-triage
