### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by marvalarva2929** [files-community/Files#2049] opened 2020-10-08 01:40 UTC
**Is your feature request related to a problem? Please describe.**

Im not sure if this is a bug or not, but I cant search through the different files in a specific folder or location. I asking this because their is a search icon, but no search capability.

**Describe the solution you'd like**

I'd like to know whether you are working on a search function or if it is just a bug on my side.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
![image](https://user-images.githubusercontent.com/56195553/95405397-a98c2880-08e5-11eb-882f-eabc64c9b61b.png)
The search icon is grayed out and does not let me click on it

**Comment by yaichenbaum** [comment] 2020-10-08 01:42
Duplicate of #333.

**Closed by yaichenbaum** 2020-10-08 01:42 UTC
Labels: feature_request
