### ISSUE TITLE
Desktop.ini data not being processed

### ISSUE THREAD

**Issue by HentaiOusama** [files-community/Files#2031] opened 2020-10-05 05:18 UTC
**Is your feature request related to a problem? Please describe.**
Chainging the folder icon from desktop.ini

**Describe the solution you'd like**
I used an script which changes the icon of sub-folders in a particular location by editing/creating desktop.ini file in each of the sub-folders. Now when I open that location in normal file explorers, the new icons shows up perfect. But in the Files Beta, it stays as the same default folder icon.

**Describe alternatives you've considered**
None.

**Additional context**
SS below :- 
[http://geekpic.net/pm-PYY7B5.html](http://geekpic.net/pm-PYY7B5.html)

In the above SS, I have opened the 1st folder (I.e. Conception) and below is the ss of the contents of this folder and the text in desktop.ini file :- 
[http://geekpic.net/pm-962KNI.html](http://geekpic.net/pm-962KNI.html)

Although I don't think it's necessay to mention which script I used as long as i have provided the content of the desktop.ini file, I'll mention the link of the tool i used just in case. : - [https://github.com/notdedsec/anicon](https://github.com/notdedsec/anicon)  <---  This app can also be seen in the first ss (named Anicon).

**Comment by yaichenbaum** [comment] 2020-10-05 13:51
Duplicate of #519.

**Closed by yaichenbaum** 2020-10-05 13:51 UTC
Labels: bug, feature_request
