### ISSUE TITLE
Different Layout at different locations

### ISSUE THREAD

**Issue by HentaiOusama** [files-community/Files#2028] opened 2020-10-04 21:57 UTC
**Is your feature request related to a problem? Please describe.**
In the new file explorer, when we change the layout mode, it get applied everywhere instead of just the current location.

**Describe the solution you'd like**
Just like the old file explorer, when we change the layout mode, it should only be applied to the specific location (I.e. the current location)
Additionally, Uses should have option to choose from :-
-> Apply Layout to All Locations
-> Apply Layout to Current Location ONLY
-> Apply Layout to current location and all the sub-folder

**Describe alternatives you've considered**
I don't think there is any alternative to this feature. It's just that current way makes up restricted in a sense. 

**Additional context**
version :- 0.15.4.0
Also, One reason to have such a request is that the list view looks super cool while the grid view sucks. But there are certain plaves where grid view is necessary/preferred. So Users would want to keep different layout at different locations.

**Comment by yaichenbaum** [comment] 2020-10-05 00:26
Duplicate of #530.

**Closed by yaichenbaum** 2020-10-05 00:26 UTC
Labels: feature_request
