### ISSUE TITLE
Bug: Focus is lost when changing tabs

### ISSUE THREAD

**Issue by MarathonMax** [files-community/Files#15288] opened 2024-05-02 14:02 UTC
### Description

I use the keyboard all the time. I like to use the down arrow to, well, move down a file/folder list. I also use the ctrl-tab/shift-ctrl-tab to move between opened tabs. When doing so and when getting back to a tab where I was down a list, the "cursor" position is not maintained; further more, I cannot use the down arrow to move down unless I use the mouse to click where I want to be.

### Steps To Reproduce

1. Open two tabs
2. Move cursor to the center of the app window
3. Used `ctrl` + `tab` to switch to the second tab & `ctrl` + `shift` + `tab` to move back to the first tab
4. The cursor position moved

### Requirements

Keep cursor in the same position

### Files Version

3.1

### Windows Version

W11 23H2

### Log File

[debug.log](https://github.com/files-community/Files/files/15189392/debug.log)

**Comment by yaira2** [comment] 2024-05-02 14:17
I'm having trouble reproducing this issue, this is what I tried
1. Opened two tabs
2. Moved cursor to the center of the app window
3. Used `ctrl` + `tab` to switch to the second tab & `ctrl` + `shift` + `tab` to move back to the first tab
4. The cursor position is still in the center

**Comment by Josh65-2201** [comment] 2024-05-02 16:16
It might be from them being on 3.1. Can you also see if this is an issue in the preview version. https://files.community/download

**Comment by MarathonMax** [comment] 2024-05-03 14:14
see video

https://photos.app.goo.gl/r6MC5H9APEDJKzG16


Maxime

**Comment by yaira2** [comment] 2024-05-03 14:17
I'm having a hard time following that, can you confirm if the repro steps I followed are correct?

**Comment by MarathonMax** [comment] 2024-05-03 17:36
The issue is the same with the preview version

here's a take 2 video

https://photos.app.goo.gl/mrG9sY6WmE31rokr8



Maxime

**Comment by yaira2** [comment] 2024-05-05 02:47
@MarathonMax I watched the video, but it seems like the cursor position stays the same when your switching tabs.

It's possible I misunderstood what the issue is, so further clarification would be appreciated. It looks like we're both following the same steps, but it'll help if you can confirm either way.

1. Opened two tabs
2. Moved cursor to the center of the app window
3. Used `ctrl` + `tab` to switch to the second tab & `ctrl` + `shift` + `tab` to move back to the first tab
4. The cursor position is still in the center

**Comment by MarathonMax** [comment] 2024-05-05 04:17
Yes "grey area" stays the same but I can no longer use keyboard to go up or
down

**Comment by Josh65-2201** [comment] 2024-05-06 15:01
Yes, The tab selection moves to the tabs rather than the select file in that tab and stops triggering file navigation when using the arrow keys.

**Comment by yaira2** [comment] 2024-05-06 15:10
I see, I can't reproduce the focus issue either but at least that points us in the right direction.

**Comment by MarathonMax** [comment] 2024-05-06 15:32
Yes. You should have received the video.

**Comment by MarathonMax** [comment] 2024-05-06 15:32
I am glad that you could reproduce the issue

Le lun. 6 mai 2024, 11 h 01, Josh65-2201 ***@***.***> a
écrit :

**Comment by yaira2** [comment] 2024-06-02 15:21
A fix will be included with v3.5.

**Closed** 2024-06-02 15:20 UTC
Labels: bug, good first issue
