### ISSUE TITLE
Operation progress

### ISSUE THREAD

**Issue by WadeRK** [files-community/Files#11764] opened 2023-03-19 12:08 UTC
### What feature or improvement do you think would benefit Files?

Progress when moving/deleting/copying items, pretty self-explanatory. 

### Requirements

Let's you know where the operation is so far.

### Files Version

2.4.40.0

### Windows Version

Windows 10 Pro 21H2 19044.2486

**Comment by ferrariofilippo** [comment] 2023-03-19 14:46
@yair100 this one is actually a duplicate of #10755

**Closed** 2023-03-19 14:50 UTC
Labels: feature request
