### ISSUE TITLE
Bug: Missing icons on Windows 10

### ISSUE THREAD

**Issue by littlewhitecloud** [files-community/Files#10783] opened 2022-12-20 23:41 UTC
### Description

The icons do not display well like:
![image](https://user-images.githubusercontent.com/71159641/208786657-d15514ea-470c-478d-bc5a-53bcb625bca1.png)
![image](https://user-images.githubusercontent.com/71159641/208786756-7bdf82d3-5b6c-4268-9269-ce93216964d0.png)

Some icons turn into garbled......
I changed my language but it still show garbled
![image](https://user-images.githubusercontent.com/71159641/208786842-d929e664-03ca-44d6-842b-d2ef5bea36e6.png)

### Steps To Reproduce

Open Files App
Click Settings button
And you can see the icon don't display will.

### Steps to fix

Check the icons?

### Files Version

2.4.2.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 22H2 19045.2364

### Relevant Assets/Logs

[Uploading debug.log…]()

**Comment by yaira2** [comment] 2022-12-20 23:47
Can you create a list of which icons are missing?

**Comment by littlewhitecloud** [comment] 2022-12-20 23:50
How do I create a list of miss icons?
Can you give me an exmaple?

**Comment by littlewhitecloud** [comment] 2022-12-20 23:50
example

**Comment by littlewhitecloud** [comment] 2022-12-20 23:52
BTW, why I can't find some theme like: Glass, Acrylic……?

**Comment by yaira2** [comment] 2022-12-21 00:02
A list of the places in the app where the icons are missing, screenshots could work as well.

**Comment by littlewhitecloud** [comment] 2022-12-21 00:33
![image](https://user-images.githubusercontent.com/71159641/208793008-d2feaebe-91a6-481b-990e-bbd60569e213.png)
![image](https://user-images.githubusercontent.com/71159641/208793020-78cb6c8a-65aa-4e33-ba5a-ed9c2477e1c4.png)
![image](https://user-images.githubusercontent.com/71159641/208793025-4570d872-d191-4ebb-8856-fde5a5ff913d.png)
![image](https://user-images.githubusercontent.com/71159641/208793029-a7561018-c814-4bc5-be3b-7d72bdcb010a.png)
![image](https://user-images.githubusercontent.com/71159641/208793035-21ed5b68-cc4b-4e17-91ab-349a7f7d16bc.png)
![image](https://user-images.githubusercontent.com/71159641/208793043-ebb7c1d5-b2e1-4ee4-b0a0-6f4738ee6e8f.png)
![image](https://user-images.githubusercontent.com/71159641/208793054-77fa7536-13a2-4c5d-8461-a3a1928d5de8.png)
![image](https://user-images.githubusercontent.com/71159641/208793057-111acc4a-4602-42bf-8a4b-39d1d7eda660.png)
![image](https://user-images.githubusercontent.com/71159641/208793061-107918c1-78e3-4107-8718-9d051335b2f5.png)

**Comment by littlewhitecloud** [comment] 2022-12-21 00:35
My Microsoft store just update Files, the version is:
Version: 2.4.3.0
OS Version: 10.0.19045.2364

**Comment by yaira2** [comment] 2022-12-29 04:22
Do you have the `Segoe UI` fonts installed?

**Comment by littlewhitecloud** [comment] 2023-01-03 23:33
Is this font?
![image](https://user-images.githubusercontent.com/71159641/210458619-8a3f6051-5f30-4a31-8864-ad70f05a01aa.png)

**Comment by littlewhitecloud** [comment] 2023-01-03 23:37
By the way,
my "Files" version is still 
2.4.8.0

**Comment by yaira2** [comment] 2023-01-04 00:32
Segoe UI Symbol is correct but it's possible that it's an older version of the font. I'm not sure if there is a way to update it.

**Comment by hez2010** [comment] 2023-01-04 03:48
Maybe you can copy the font from a machine that has Windows 11 installed.

**Comment by littlewhitecloud** [comment] 2023-01-12 09:31
... I don't have any computer installed Windows 11...

**Comment by DMorest** [comment] 2023-01-23 10:03
You might use a VMWare virtual PC to install Windows 11 and copy that font LOL

**Comment by DMorest** [comment] 2023-01-23 10:04
I tried but didn’t work
BTW a small number of other UWP apps have this icon missing problems too

**Comment by yaira2** [comment] 2023-01-24 16:43
Can you give an example? Might help isolate the issue.

**Comment by kannogu** [comment] 2023-01-26 00:49
I had a similar problem on microsoft Power Toys and part of them are now fixed.
> https://github.com/microsoft/PowerToys/pull/19311
> https://github.com/microsoft/PowerToys/issues/10331

**Comment by DMorest** [comment] 2023-01-28 11:30
I had the problem on Fluent Flyout App and Microsoft PowerToys before (but it's fixed now)
The problem came with the version 2.4.8.0 update, the original version should be 2.3 or maybe earlier and it didn't have that problem
I think this should be caused by the app...
BTW the garbled character I had is EXACTLY same as the op showed ( I don't know if this is useful...)

**Comment by littlewhitecloud** [comment] 2023-01-29 00:25
Yes, On my another computer, "Files" doesn't updated yet. The "Files" on that computer doesn't have this bug. And the version is low than 2.4.8.0... But it updated automatic...

**Comment by littlewhitecloud** [comment] 2023-01-29 00:36
I even want to roll back the version of the "Files"🤣

**Comment by DMorest** [comment] 2023-02-03 04:59
yeah it auto updates and that SUCKS

**Comment by DMorest** [comment] 2023-02-03 05:02
either they fixes this bug in version2.5, or im gonna get an older version of the msixbundle + stop it from using the internet to update...
although its might be a small bug but it makes me confused sometimes.....

**Comment by yaira2** [comment] 2023-02-03 14:27
If that offer to open a PR?

**Comment by habaneraa** [comment] 2023-02-23 03:19
Hi. I have exactly the same issue and I believe that this bug is related to Windows system language. 
Here is my temporary fix (especially for Chinese Windows users): 

- Open Windows's settings > Time and Language. 
- Find an option called "Language for non-unicode programs" (非 Unicode 程序的语言 in Chinese) in Region Settings. 
- Click "change system locale..." (更改系统区域设置 in Chinese) to set it from "Chinese" to "English". 
- Restart Windows.

Then those icons in Files App are displayed correctly!

Hope you can resolver this bug asap :)

**Comment by Jay-o-Way** [comment] 2023-03-21 22:29
OMG @yair100 Who is in charge here? I know exactly what the cause of this issue is. @kannogu is on the right track - see also issue https://github.com/microsoft/PowerToys/issues/10331 to learn more.

![image](https://user-images.githubusercontent.com/65828559/226755938-8968f86b-90d6-4c90-94a5-de8e2bf99c29.png)

The problem is that a load of **deprecated** icons is being use throughout the code. They must have been deprecated for years now. Thing is - in most (western) languages, this is hardly noticable, but in CJK context, **this** happens.
Quick example:
![image](https://user-images.githubusercontent.com/65828559/226755509-5468b177-72a5-40e0-bead-730b99c615cd.png)

I emhpasize that this should be checked and fixed as broadly as possible.

**Comment by Josh65-2201** [comment] 2023-03-21 22:32
If you can fix it you can open a PR doing so.

**Comment by Jay-o-Way** [comment] 2023-03-21 22:32
To anybody whom it may concern: Recent version of **WinUI 3 Gallery** now has an awesome page to search for icons (and other resources). I suggest to drop any third-party tools and use this from now on! :)
![WinUI3 Gallery icons](https://user-images.githubusercontent.com/65828559/225639245-a4b41c8c-e163-48d1-acc6-410b058ef092.png)

**Comment by yaira2** [comment] 2023-03-21 23:02
I'm still not able to reproduce this issue.

**Comment by Jay-o-Way** [comment] 2023-03-21 23:11
@yair100 As I said, it depends on context. In a CJK environment, this is the result. In Western display languages, it looks fine. What does your system use?

**Comment by Jay-o-Way** [comment] 2023-03-22 07:08
@yair100 trust me. Open WinUI Gallery, update the icons, and you will make many people in Asia happy 🙂

**Comment by DMorest** [comment] 2023-03-22 12:17
I don't know if using English(USA) as my non-Unicode language will make something else garble. And I don't understand, what icons are deprecated? Why it work well on latin-based languages? Is the icons of my device outdated? **PLEASE HELP!!!**

**Comment by DMorest** [comment] 2023-03-22 12:21
![image](https://user-images.githubusercontent.com/103618181/226903411-0fbef8cd-4193-4eeb-9c1a-ff992c297519.png)
Gosh look at this mess

**Comment by DMorest** [comment] 2023-03-22 12:27
![image](https://user-images.githubusercontent.com/103618181/226903561-2a399034-4079-4780-a424-ed8941c26743.png)
![image](https://user-images.githubusercontent.com/103618181/226903787-f895a6b1-f5c7-41ad-85f3-a6fe15afb2d5.png)
![image](https://user-images.githubusercontent.com/103618181/226903834-1def38b2-2a8b-466e-b1be-48012cbba30a.png)
![image](https://user-images.githubusercontent.com/103618181/226903975-90fe45c6-c050-4881-b978-cf9ff0608f2f.png)
![image](https://user-images.githubusercontent.com/103618181/226904042-7328c0fc-d58b-4532-9e6d-ac4230e76c3b.png)
![image](https://user-images.githubusercontent.com/103618181/226904500-b88370c4-7fdc-47dc-b6f3-41c60be37dfb.png)
![image](https://user-images.githubusercontent.com/103618181/226904613-199d9b23-ceec-4f97-b5a2-ca51bdf2c80a.png)
these are all the icons missing there
Is it possible to track these icons and fix the problem?

**Comment by Jay-o-Way** [comment] 2023-03-22 13:12
@DMorest don't panic, haha. It's about the Glyph codes. Microsoft has this message:

> Range from E0** to E5** is deprecated.

So, `E112` - or `&#xE112;` - is bad, `E713` is good. Also note that _some_ of the Symbol Icons can be defined by their name, for example `Icon="Setting"`.

That's why I recommend WinUi 3 Gallery. If you know what the icon should be, you can search by name and you'll see the correct code on the right.

@yair100 Example:
![image](https://user-images.githubusercontent.com/65828559/227250070-7822d801-5959-49d4-ad07-070cd9db3567.png)

**Comment by Jay-o-Way** [comment] 2023-03-22 18:13
> If you can fix it you can open a PR doing so.

That goed for everybody. I'm just passing by. I rather see the maintainers work on this, so that they **know**, to prevent them doing the same thing in the future.

**Comment by Jay-o-Way** [comment] 2023-03-23 15:23
@yaira2 can you assign me?

**Comment by yaira2** [comment] 2023-03-23 16:06
Just a heads up that we're redoing the icons in the settings navigation menu so you can leave those alone.

**Comment by Jay-o-Way** [comment] 2023-06-23 13:15
FYI; a pr in the MS ui-xaml repo, addressing "**native**" controls, has just been merged, so it's a matter of time that the next version of the SDK is released, and then it's a matter of time to include that in \<any app>.

**Comment by littlewhitecloud** [comment] 2023-06-23 13:20
![image](https://github.com/files-community/Files/assets/71159641/1ba04d9c-d732-47ec-811e-1ea55eb9b699)
![image](https://github.com/files-community/Files/assets/71159641/a5e8d5ac-be3d-4ed8-8ded-141caeb655d9)
![image](https://github.com/files-community/Files/assets/71159641/75fc1fcd-cd40-44c1-a75d-900bbd878014)
![image](https://github.com/files-community/Files/assets/71159641/fdc62fe1-2292-4ce9-84b9-71610c389b23)
![image](https://github.com/files-community/Files/assets/71159641/526da6be-1941-4501-b298-1b74809915a9)
![image](https://github.com/files-community/Files/assets/71159641/f7c7c7d4-02c3-43ac-8521-ebefd1768d9b)
![image](https://github.com/files-community/Files/assets/71159641/d058d2ae-b81c-4efb-8e43-d81d761ec358)

**Comment by littlewhitecloud** [comment] 2023-06-23 13:21
Still have these icons need to fix.

**Comment by Jay-o-Way** [comment] 2023-06-23 14:07
Yeah, I suppose my comment is a bit off-topic, sorry

**Comment by littlewhitecloud** [comment] 2023-06-24 10:29
> Yeah, I suppose my comment is a bit off-topic, sorry

?

**Comment by DMorest** [comment] 2023-07-15 03:56
Up till now, part of the issue has been fixed: like the 'tag' icon - it's originally garbled and now it looks fine. However still some icons refuse to be corrected...
BTW, changing the '非 Unicode 程序的语言'(Language for non-Unicode programs) works because it makes the program use UTF-8 instead of GBK (a way of character coding for Chinese). However, changing that will make you unable to read Chinese characters correctly in cmd.exe and Windows Powershell. 
![image](https://github.com/files-community/Files/assets/103618181/e602aea4-be60-48d6-8bf5-403bdea685cc)

**Comment by Jay-o-Way** [comment] 2023-07-15 08:03
Yes, there are a couple left over. @yaira2 have a plan? Who would you want to work on this?

**Comment by yaira2** [comment] 2023-07-16 17:43
@Jay-o-Way can you compile a list or open a PR that addresses this?

**Comment by Jay-o-Way** [comment] 2023-07-18 11:53
![image](https://github.com/files-community/Files/assets/65828559/91ee57ba-96df-4d13-91de-1ef76ff8a0f7)
![image](https://github.com/files-community/Files/assets/65828559/e42179ca-6568-49ea-b8c5-7b283b8fc3e9)

**Closed** 2023-07-24 18:26 UTC
Labels: bug
