### ISSUE TITLE
Scaling changes behavior of bundles

### ISSUE THREAD

**Issue by 01-1** [files-community/Files#4708] opened 2021-04-22 22:23 UTC
**Explain the bug**
Using multiple monitors with different scaling, a larger (150%) scaling will cause bundles to display vertically and have 1 column but a normal scaling will allow for 2 columns.

**To reproduce**
1. Have multiple monitors with different scaling
2. Create bundles with multiple files/folders
3. Move windows between monitors

**Expected behavior**
Either it should have only one of the two behaviors or have an option in settings to choose the behavior.

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6361566/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6361567/debug.txt)
also i had a crash earlier idk why, probably unrelated

**Screenshots**
Add screenshots to help explain your problem if needed.
![image](https://user-images.githubusercontent.com/33045716/115791320-3dab7200-a396-11eb-9ed6-dff00583c45b.png)
![image](https://user-images.githubusercontent.com/33045716/115791337-4308bc80-a396-11eb-972e-58952c57f765.png)

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)
Version	10.0.19041 Build 19041
App Version 1.5.0.0

**Additional comment**
none

**Comment by yaichenbaum** [comment] 2021-12-13 17:28
@01-1 this is the intended behavior. Regarding the multiple monitors, I recommend opening an issue on the feedback hub as that's an OS behavior and something that should be resolved by the Windows team.

**Closed by yaichenbaum** 2021-12-13 17:28 UTC
Labels: bug, investigate
