### ISSUE TITLE
Breaking the Tabs

### ISSUE THREAD

**Issue by RadioActiveEssence** [files-community/Files#2024] opened 2020-10-03 16:21 UTC
I broke the tabs when playing around with your app. Upon fullscreening the app again, the tabs decide to show themselves under the close and minimize buttons. IMPORTANT: Like I said, it only happens after fullscreening the app again. I have uploded a video of how to do it:
[Video.zip](https://github.com/files-community/Files/files/5321966/Video.zip)
OS: Windows 10 Pro 10.0.19042 Build 19042(I am in the Windows Beta Insider programme).
App Version: 0.15.4.0

**Comment by Jaiganeshkumaran** [comment] 2020-10-04 02:31
@RadioActiveEssence This is intended and not a bug if you select the 'Adaptive' option in multitasking. When in a small window size, you can access the tabs by pressing the button next to the disabled search box.

**Comment by RadioActiveEssence** [comment] 2020-10-04 08:48
@Jaiganeshkumaran So you intend for the tabs to show below the close buttons making them hard to reach?
![Files - Preview 04_10_2020 09_47_35](https://user-images.githubusercontent.com/70538199/95011175-bc250a00-0626-11eb-9d57-c319e96a2e56.png)

**Comment by Jaiganeshkumaran** [comment] 2020-10-04 11:42
@RadioActiveEssence That shouldn't happen.

**Comment by RadioActiveEssence** [comment] 2020-10-05 16:54
Here is a better video of how it happens. My OBS Studio wasn't working so I used a different recording software.
[Uploading Vid.zip…]()

**Comment by yaichenbaum** [comment] 2021-03-21 21:15
@RadioActiveEssence This issue appears to be resolved in `main`.

**Closed by yaichenbaum** 2021-03-21 21:15 UTC
Labels: bug, triage approved
