### ISSUE TITLE
Right Click to Change Properties of New Library causes Files to crash

### ISSUE THREAD

**Issue by jonnypjohnston** [files-community/Files#4613] opened 2021-04-15 02:04 UTC
Right Click to Change Properties of New Library causes Files to crash

**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. I create Custom Library called "Rocketry"...
2. Right Click on Custom Library...
3. Click on "Properties" in dialog...
4. Crashes.
[debug.txt](https://github.com/files-community/Files/files/6314744/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6314745/debug_fulltrust.txt)
![files-crash-jpjohnston](https://user-images.githubusercontent.com/3137489/114803265-27d1f780-9d6d-11eb-946a-9e7503f28937.png)

**Expected behavior**
I expected the Properties Dialog to open so I could change the Icon for the Custom Library

**Logfile**
##ATTACHED##

**Screenshots**
##ATTACHED##

**System Information**
OS-Ver: [Microsoft Windows 10 Pro Insider Preview Version 2004 Build 21359.co_release.210409-1536]
AppVer: [Dev-v1.5.12/Preview-v1.5.2]
Email:  [jonnypjohnston@gmail.com/jonny@roguextech.com/jonny@jpparametrics.com]

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by yaichenbaum** [comment] 2021-04-15 04:04
Duplicate of #4591.

**Closed by yaichenbaum** 2021-04-15 04:04 UTC
Labels: bug
