### ISSUE TITLE
High size folder access in list view mode

### ISSUE THREAD

**Issue by frbona** [files-community/Files#2604] opened 2020-12-14 17:30 UTC
Hi,

Issue i am facing is related to high size folder access (via tactile mode) in list view mode.

Selection is not directly effective and i have to switch from another folder to make it work.

Thx

**Comment by duke7553** [comment] 2020-12-15 16:28
@frbona This sounds like a bug, but can you please elaborate on what you're unable to do that you should be able to? We normally expect issue templates to be filled out completely.

**Comment by frbona** [comment] 2020-12-15 17:03
Describe the bug
Access high size folders in list view mode is not effective on first selection. Selection is not possible anymore when issue occurs and refresh is needed to make it work. This issue occurs in tactile mode by controlling application by tactile way.

To Reproduce
Try to open by tactile way a high size folder in list view mode

Screenshots
![image](https://user-images.githubusercontent.com/76003831/102246760-61017480-3eff-11eb-8bf8-9e7acd9a7726.png)

Desktop (please complete the following information):

OS: [Windows 10 20H2 19042.685]
App version: [v0.21.1.0]
Additional context
--

Log file
[debug.txt](https://github.com/files-community/Files/files/5697411/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5697412/debug_fulltrust.txt)

**Comment by duke7553** [comment] 2020-12-17 16:51
@frbona Thanks for getting back to us. Is the issue involving touch input only?

**Comment by frbona** [comment] 2020-12-17 20:02
Yes, only in touch mode

**Comment by duke7553** [comment] 2020-12-17 22:22
@frbona Since we already have an issue open for this, please follow #2279 .

Duplicate of #2279

**Closed by duke7553** 2020-12-17 22:22 UTC
Labels: bug, needs-triage
