### ISSUE TITLE
Contextual menus on left pane and drop-down lists are dark/shadowed with light theme

### ISSUE THREAD

**Issue by NinjaCross** [files-community/Files#7478] opened 2022-01-06 12:17 UTC
### Description

As per title, the Contextual menus of the left pane and drop-down lists are dark/shadowed when using the light theme.
See the screenshots below.

![image](https://user-images.githubusercontent.com/5829421/148380855-5a816753-1476-4f3e-978b-cd965ce96c2c.png)

![image](https://user-images.githubusercontent.com/5829421/148381011-ff85c08a-4974-4f2a-97f0-07a17ed4c841.png)

### Expected behavior

A white-ish, non-shadowed menu/list is expected

### Files Version

Version: 2.0.34.0 

### Windows Version

Windows 10  10.0.19042.1415

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7821656/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7821657/debug_fulltrust.log)

**Comment by gave92** [comment] 2022-01-06 12:30
This is an OS bug in Windows 10, they only fixed in Windows 11.

**Closed by gave92** 2022-01-06 12:30 UTC
Labels: bug

**Comment by NinjaCross** [comment] 2022-01-06 13:56
> This is an OS bug in Windows 10, they only fixed in Windows 11.
Tnx for the fast response.
Are you aware of a workaround for Windows 10?

**Comment by gave92** [comment] 2022-01-06 14:00
Unfortunately I don't know any (I'm on Windows 10 too). Only for me is a pretty rare occurrence and an app restart usually fixes it. When it happens the problem is attenuated if you disable Transparency in Windows Settings > Personalization > Colors.
