### ISSUE TITLE
This PC shortcut open old explorer.exe when Files is set as default explorer app.

### ISSUE THREAD

**Issue by koubafire** [files-community/Files#7145] opened 2021-11-29 17:15 UTC
### What's the Problem?

This PC shortcut open old explorer.exe whe Files is set as default explorer app.

### Solution/Idea

Replace Files as default explorer everywhere. When I open This PC shortcut or if try attach file to Outlook email message it open small window of old explorer. Is it possible? 

### Alternatives

Make some link between explorer.exe and new explorer if is it possible.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.36.0

### Windows Version

22000.348

**Comment by gave92** [comment] 2021-11-29 17:47
This is currently by design. To open files when clicking on This PC or recyclebin, the reg files included below should do the trick but there may be undesired consequences.

To do:
1. Extract the two files from this archive [SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip) and place them *on the desktop*
2. Run `SetFilesAsDefault_Bad.reg`

**Comment by gave92** [comment] 2021-11-29 17:51
Closing this for now, this is something we're working on but still too experimental to ship publicly :)

**Closed** 2021-11-29 17:50 UTC
Labels: feature request

**Comment by koubafire** [comment] 2021-11-29 18:28
Great it works :-) Thanks

**Comment by gave92** [comment] 2021-11-29 18:40
@koubafire glad it works. If you could provide feedback about how well it works if would be great. E.g if you find it causes issues opening the Control Panel etc.

**Comment by koubafire** [comment] 2021-11-29 18:43
Control Panel works, but it crash when I try open Network drives. I have Czech version of windows 11
