### ISSUE TITLE
Folders in the recycle in lose there original names

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#3907] opened 2021-03-09 15:36 UTC
**Describe the bug**
When going to the recycle bin most folders will lose the name an be replace with some random key that the recycle bin properly uses. When pressing refresh the actual names quickly appear then disappear

**Expected behaviour**
Original folder names should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/110496056-07b77480-80ed-11eb-8bcb-3e1eb6581420.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.844
 - App version: v1.3.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6109638/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6109639/debug_fulltrust.txt)

**Comment by gave92** [comment] 2021-03-09 18:20
[internal comment]
Due to showing folders "dispayname" instead of name.

**Comment by gave92** [comment] 2021-03-09 21:27
Confirmed to be fixed in the development version. Thanks for the report.

**Closed** 2021-03-09 21:27 UTC
Labels: bug, triage approved
