### ISSUE TITLE
Search Folder Crash

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12715] opened 2023-06-24 10:59 UTC
### Description

When you search for a folder and click on the folder while it showing up in the popup, it crashes.

### Steps To Reproduce

1. From the Home page click on the search bar
2. Start searching for a folder
3. Press the folder that popups up

### Requirements

It should open the folder

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[Uploading debug.log…]()

**Comment by IlyaSulli** [comment] 2023-06-24 11:00
[debug.log](https://github.com/files-community/Files/files/11856528/debug.log)

**Comment by Josh65-2201** [comment] 2023-06-24 15:41
Thanks for the report, I've added this to the project board.

**Comment by GeeWi1** [comment] 2023-06-24 17:24
I find that search in general does not work

**Comment by Lukiluc29** [comment] 2023-06-24 17:40
I also think that the search function is somewhat faulty and needs to be reevaluated to come back stronger because when I initiate a search to find multiple files, nothing happens or it takes forever, whereas in the file explorer, within a minute, it finds everything I need.

**Comment by hishitetsu** [comment] 2023-06-25 11:45
It may be fixed by #12700.

**Comment by Lukiluc29** [comment] 2023-06-25 11:55
> It may be fixed by #12700.

No because I am with Files dev so with the latest modifications and I manage to reproduce this error despite several times

**Comment by hishitetsu** [comment] 2023-06-25 12:02
@Lukiluc29 what errors do you see in the logs?
I can only find NullReferenceException in the attached debug.log.

**Comment by Lukiluc29** [comment] 2023-06-25 12:12
> @Lukiluc29 what errors do you see in the logs? I can only find NullReferenceException in the attached debug.log.

I apologize. Actually, I thought that nothing would appear because I left my computer running for 10 minutes last time without any changes and still with the loading logo. So, I think that in order to avoid falling into the same trap as me, it would be necessary to implement a loading bar like Windows Explorer.

**Comment by Lukiluc29** [comment] 2023-06-25 12:15
And for the folders that do not open, I had forgotten to check Files as the default explorer which may also be related to the fact that the search did not work.

**Comment by yaira2** [comment] 2023-09-03 20:45
@IlyaSulli thank you for the feedback, can you check if this is fixed in the latest preview build? You can download the preview version from https://files.community/download.

**Closed** 2023-09-26 16:14 UTC
Labels: bug, more-info
