### ISSUE TITLE
Collapsible sidebar should remember collapsed state of sub entries

### ISSUE THREAD

**Issue by R3voA3** [files-community/Files#4163] opened 2021-03-18 22:39 UTC
**Describe the solution you'd like**
When I collapse the side bar and expand it again, all subentries are collapsed. Ideally, the state should be remembered and reset when expanding it again.

**Additional context**
1.4.42.2

Before collapsing:
![image](https://user-images.githubusercontent.com/17484252/111706773-27644080-8843-11eb-8783-ef5c977c4750.png)

After expanding:
![image](https://user-images.githubusercontent.com/17484252/111706784-2df2b800-8843-11eb-96b8-c51244db8516.png)

**Comment by XPoppyX** [comment] 2021-03-18 22:58
Duplicate of #4128

**Closed** 2021-03-18 23:30 UTC
