### ISSUE TITLE
Bug: No task icon

### ISSUE THREAD

**Issue by IviriusMain** [files-community/Files#16320] opened 2024-10-07 21:40 UTC
### Description

There's no icon for the Files task in Task Manager

### Steps To Reproduce

1. Open Files
2. Open Task Manager
3. No icon

### Requirements

There should be the current icon of Files in Task Manager

### Files Version

3.7.7.0

### Windows Version

10.0.22631.4249

### Log File

[debug.log](https://github.com/user-attachments/files/17284793/debug.log)

**Comment by IviriusMain** [comment] 2024-10-07 21:40
I have fixed this issue in a fork and I'm ready to make a pull request.

**Comment by yaira2** [comment] 2024-10-07 22:23
I can't reproduce this issue in the latest preview build. Can you check if it's resolved on your end as well?
![Image](https://github.com/user-attachments/assets/6f3b6020-f9b6-43d8-8f1f-df5257c64238)

**Comment by IviriusMain** [comment] 2024-10-07 22:28
It's not resolved - above is the latest Insider build, and below is the updated version in this pull request.

![Image](https://github.com/user-attachments/assets/dbdf0eee-0557-4672-bf6a-37057b5cb4b4)

**Comment by IviriusMain** [comment] 2024-10-07 22:29
![Image](https://github.com/user-attachments/assets/29158aaa-1ee8-4a24-8882-0c7ce0892e59)

(What they look like in the taskbar)

**Comment by IviriusMain** [comment] 2024-10-07 22:30
![Image](https://github.com/user-attachments/assets/9c9e4524-7cb0-44c7-9e92-1da9fd6752a2)

Expanded view for better reference

**Comment by Josh65-2201** [comment] 2024-10-08 01:41
I can reproduce this on 3.7.7 and 3.7.10
![Image](https://github.com/user-attachments/assets/fc31ff15-a70e-4504-bc9b-0680f9b99e15)

**Comment by yaira2** [comment] 2024-10-08 03:07
We're already using the WinUIEx SetAppIcon method.

**Comment by 0x5bfa** [comment] 2024-10-08 03:36
I think that is for window icon. We haven't added an exe/process icon and as a result sometimes it causes the issue

**Comment by IviriusMain** [comment] 2024-10-08 05:04
Pretty much, yeah.

**Comment by yaira2** [comment] 2024-10-09 14:23
This will be included in the next update.

**Comment by 0x5bfa** [comment] 2024-10-09 14:25
Resolved by #16321

**Closed by 0x5bfa** 2024-10-09 14:25 UTC
Labels: needs - additional info, needs - reproducing
