### ISSUE TITLE
Add a recent items section to the sidebar

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#947] opened 2020-06-08 07:30 UTC

**Comment by TailyFair** [comment] 2020-06-08 07:55
Maybe they should not be pinned in Sidebar, but in New Tab page instead similar as in Explorer's `Quick access` page?

**Comment by XPoppyX** [comment] 2020-08-03 01:44
I think this could be implemented after adding the "Quick Access" section first.

**Comment by yaichenbaum** [comment] 2020-11-17 03:28
Duplicate of #1805.

**Closed by yaichenbaum** 2020-11-17 03:28 UTC
Labels: discussion, enhancement
