### ISSUE TITLE
Problem with sidebar when it was minimized and Files is restarted.

### ISSUE THREAD

**Issue by Fantazyjny** [files-community/Files#4329] opened 2021-03-27 13:45 UTC
**Explain the bug**

https://user-images.githubusercontent.com/8149819/112722462-04ecba00-8f0a-11eb-9e58-57dde5bdf6c6.mp4

**To reproduce**
1. Minimize sidebar
2. Close Files
3. Start Files

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6215736/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6215737/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 Pro 20H2 19042.867
 - App version: 1.5.2.0

**Comment by nvi9** [comment] 2021-03-28 19:29
Might be caused by the changes in #4209

**Comment by yaichenbaum** [comment] 2022-05-16 13:53
@Fantazyjny this issue should be resolved in the preview version. http://files.community/download/preview

**Closed by yaichenbaum** 2022-05-16 13:53 UTC
Labels: bug, triage approved
