### ISSUE TITLE
Bug: Startup settings are not followed when opened via explorer

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#11894] opened 2023-03-29 16:38 UTC
### Description

Typing File explorer or setting as default then opening file location using another program, startup settings are ignored.

### Steps To Reproduce

1. Set Files as default
2. Set Start up to open a specific page
3. Close Files
4. Open File explorer from start menu or other program (Open file location)
5. See startup settings ignored

### Requirements

- Follow startup settings when opened from explorer call

### Files Version

2.4.58.0

### Windows Version

10.0.22621.1345

### Log file

[debug.log](https://github.com/files-community/Files/files/11103192/debug.log)

**Comment by hishitetsu** [comment] 2023-03-29 23:22
I believe this is not a problem; it is the intended behavior.
If an open location is specified, it should open that location regardless of the startup settings.

**Comment by Josh65-2201** [comment] 2023-03-30 03:12
That doesn't make sense. If and open location is specified it should really open a new tab with it (This is what browsers do). It also makes continue where you left off quite useless as I have to open any tabs that were there before to come back to it later every time.

**Comment by hishitetsu** [comment] 2023-03-30 03:50
I see, so if the startup setting is not "Open a new tab", not only the specified location should be opened but also the same tab that would be opened if the location were not specified.
Is this correct?

**Comment by Josh65-2201** [comment] 2023-03-30 03:52
Yeah start up settings are following just with the new tab that would be opened.

**Comment by yaira2** [comment] 2023-04-16 15:12
@Josh65-2201 a fix has been implemented and will be included in one of the next feature releases.

**Closed** 2023-04-16 15:11 UTC
Labels: bug
