### ISSUE TITLE
Colored folder and file icons

### ISSUE THREAD

**Issue by Pietro228** [files-community/Files#2270] opened 2020-11-08 14:45 UTC
**Is your feature request related to a problem? Please describe.**
There are only one colored icons.

**Describe the solution you'd like**
I would like colored moder icons. Something like in Win File Explorer

**Describe alternatives you've considered**
Add selecting which type of icons you want.

**Comment by yaichenbaum** [comment] 2020-11-08 15:24
Duplicate of #1015.

**Closed by yaichenbaum** 2020-11-08 15:24 UTC
Labels: feature_request
