### ISSUE TITLE
Alt+W Close Prompt System Error

### ISSUE THREAD

**Issue by JEAMLEAN** [files-community/Files#12993] opened 2023-07-20 09:19 UTC
### Description

Alt+W Closing the window will prompt Exception Processing Message 0xc000000 5- Unexpected
Parameters

### Steps To Reproduce

1. Run Files
2. Alt+W

### Requirements

- e.g. Fix crash that occurs when...
Alt+W

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

2023-07-20 17:18:36.5970|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-07-20 17:18:36.9381|Information|Adding cloud provider "OneDrive" mapped to D:\LiShaoJun\OneDrive
2023-07-20 17:18:37.4571|Information|Drive added: A:\, Network
2023-07-20 17:18:37.8626|Information|Drive added: C:\, Fixed
2023-07-20 17:18:38.0237|Information|Drive added: D:\, Fixed
2023-07-20 17:18:38.0551|Information|Drive added: E:\, Fixed
2023-07-20 17:18:39.6626|Information|STORE: Checking for updates...
2023-07-20 17:18:40.2857|Information|Running on ARM: False

**Comment by Josh65-2201** [comment] 2023-07-20 09:22
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by SirEthanator** [comment] 2023-07-20 23:15
I have found that I have the same problem. I am using the latest preview version and when I press ctrl + W to close a tab when only one tab is open, it will close the tab and open an error message even though nothing has gone wrong. Here's a screenshot of the error:
![image](https://github.com/files-community/Files/assets/130725768/fac37b50-70d3-40a7-ab73-d23b68a9b3e6)

**Comment by Josh65-2201** [comment] 2023-07-30 16:02
@JEAMLEAN Can you see if this is an issue in 2.5.21.0

**Comment by SirEthanator** [comment] 2023-07-31 05:14
> @JEAMLEAN Can you see if this is an issue in 2.5.21.0

I personally still have the issue in this version.

**Comment by yaira2** [comment] 2023-08-29 02:26
@JEAMLEAN @SirEthanator I can't repro this in the latest preview, can you confirm if the issue is resolved in the latest preview build?

**Comment by SirEthanator** [comment] 2023-08-29 04:52
The issue no longer occurs for me.

**Closed** 2023-08-29 12:24 UTC
Labels: bug, more-info
