### ISSUE TITLE
Files should bring support for file and directory labels a la Finder.app (MacOS)

### ISSUE THREAD

**Issue by carlosvsilva** [files-community/Files#3379] opened 2021-01-31 23:40 UTC
**Is your feature request related to a problem? Please describe.**
Files can only be organized in directories, there is no support for file/directory labels/tags that can differentiate between files and directories with different status (Done/NotDone), (Reviewed/ToReview), (Processed/ToProcess), etc

**Describe the solution you'd like**
I think Files is in a privileged place to bring support for file/directory labels allow the user to associate chosen files/folders to different colored custom labels, with a default collection (Red/Yellow/Green/Blue/etc) available, ready to be customized by the user to associate each file/folder color to a specific label keyword.

**Describe alternatives you've considered**
I think this innovation would be a first in Windows file managers. MacOS Finder.app does this since forever, and it allows advanced features such as sidebar pinned searches for specific strings, always up to date. It's one of those user friendliness things Macs are known for and they excel in file categorization that everyday people need, something that should be possible in Windows alike. People switching from Mac to Win 10 really miss this feature
![tags](https://user-images.githubusercontent.com/40889421/106401714-87cb2a00-641d-11eb-83d1-94a809b86821.png)

**Additional context**
This would be a nice starting point:
https://en.wikipedia.org/wiki/NTFS#Attribute_lists,_attributes,_and_streams

**Thanks**

**Comment by R3voA3** [comment] 2021-01-31 23:47
I absolutely agree!

**Comment by carlosvsilva** [comment] 2021-02-01 16:19
Apparently Windows Explorer already supports labels (etiquetas) and ratings (classificação) alike (another useful feat) and those columns can be selected from the list of available columns to display. Maybe these properties in Files can be stored in the same place of Windows Explorer. Thanks.

![ratings](https://user-images.githubusercontent.com/40889421/106485817-e8ec0f80-64a8-11eb-8cb2-be99eb6f1290.png)

**Comment by KristofKekesi** [comment] 2021-02-04 15:27
Duplicate of #1161. I don't know it is still in the pipeline. The last comment was 28 days ago.

**Comment by yaichenbaum** [comment] 2021-06-17 02:36
Merging with #1161.

**Closed** 2021-06-17 02:35 UTC
