### ISSUE TITLE
Improving touch support for Files UWP

### ISSUE THREAD

**Issue by PeterStrick** [files-community/Files#734] opened 2020-05-02 14:10 UTC
**Describe the bug**
Files UWP is not really Touch friendly. Things like double tapping or tap and hold to get the context menu don't work for touchscreens.

**To Reproduce**
Try opening a folder/file or opening the context menu in Files UWP with a Touchscreen. Works fine with mouse\Keyboard.

**Expected behavior**
Double tap to open the File/Folder, tap and hold to bring up the context menu of said folder/file.

**Screenshots**
The Screen Capture is compressed in a zip archive as a Windows Media Video File (.WMV)
[ScreenCapture.zip](https://github.com/duke7553/files-uwp/files/4567865/ScreenCapture.zip)

**Desktop:**
 - OS Version: Windows 10 1909
 - App version: v0.7.8.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? : Yes. Restarting App/Device doesn't help at all.

**Comment by yaichenbaum** [comment] 2020-05-03 02:01
I cannot reproduce the touch issues you mentioned in either of the layout modes. @duke7553 Can you try to reproduce this on your end?

**Comment by Mahan3340** [comment] 2020-05-03 06:55
@yair100  I have the same issues, clicking and opening menus are not working properly with a touch screen, I will record my screen later and post it here.

**Comment by Mahan3340** [comment] 2020-05-03 07:26
@yair100 As you can see in the video, there are a lot of issues while using the touch screen (finger, not pen or mouse). To reproduce the problems you can do as follows (use just your finger):

Issue 1: Select All from The menu, Click somewhere blank to clear the selection, now nothing is clickable or long-pressable or double-clickable, and you have to close the app to be able to click again

Issue 2: The double click to open a file/folder with a finger only works when the item is not already highlighted (does not have the focus). To reproduce, just click a file/folder to highlight it. Then, keep double-clicking or clicking, and it's not going to work (you can see this at the end of the video). If a file is highlighted, you can double click another file/folder to open, but not the highlighted file/folder itself. To click that file, you have to click another file/folder, and double click the file you wanted to open it

Issue 3: Open a menu for a file or folder by long-press. Then, dismiss the menu by clicking somewhere blank or perform an action (select properties for example). That folder/file is not longer clickable/double-clickable, ... anymore unless you click another file to remove the focus from the current file/folder.

I suggest you remove your keyboard and try to work with the app using just your finger to find the issues and shortcomings. When there is a keyboard you have certain shortcuts but while using touch-screen those are not available and thus make the app very hard to work with. I guess having shortcut icons for copy/paste/selection/multiselection (making the files and folders to have a checkbox or something like that to be selected),... on top or bottom of the app would also be useful when there's no keyboard.

[https://gofile.io/?c=mWqdrW](url)

**Comment by yaichenbaum** [comment] 2020-05-03 12:50
The issue with double clicking to open a selected file is an issue with mouse usage as well. Issue 3 is also an issue with the mouse as well.

**Comment by Mahan3340** [comment] 2020-05-03 13:27
@yair100 So is there a way to fix these issues?

**Comment by yaichenbaum** [comment] 2020-05-03 15:16
Absolutely, the data grid issue should be fixed when WinUI releases a new DataGrid control. The other issues are things we need to look into.

**Comment by RoderickQiu** [comment] 2020-05-31 07:16
This happens for me too, both long press and double press on my finger is not working. 
Also, after a double press, the app stops responding.

**Comment by duke7553** [comment] 2020-06-18 09:43
Thank you for reporting this. I think to solve these issues quickly, it's important that they are grouped separately. @PeterStrick and @Mahan3340 , can you please open each issue you find in the latest stable version as a separate feedback item?

This will really help us track them

Thanks again.

**Comment by duke7553** [comment] 2020-06-18 09:43
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.

**Comment by RoderickQiu** [comment] 2020-06-19 13:43
> 
> 
> Thank you for reporting this. I think to solve these issues quickly, it's important that they are grouped separately. @PeterStrick and @Mahan3340 , can you please open each issue you find in the latest stable version as a separate feedback item?
> 
> This will really help us track them
> 
> Thanks again.

Hey @duke7553 it's apparent that this issue belongs to @PeterStrick so that it's of no reason to close this issue and let Peter to create another issue of the same problem.

With my Huawei Matebook X Pro's touchscreen not working on these stuff for the same problem, I've long been following this issue, and I really hope some real progress can be made on that. (I don't know a thing about UWP sadly, so that I cannot help on this)

**Comment by yaichenbaum** [comment] 2020-06-19 14:17
@RoderickQiu Files UWP does work on touch screens, common actions such as long press to open a context menu are supported. Is there a place where that is not working for you?

**Comment by RoderickQiu** [comment] 2020-06-20 00:00
> 
> 
> @RoderickQiu Files UWP does work on touch screens, common actions such as long press to open a context menu are supported. Is there a place where that is not working for you?

It doesn't work for me even for version 0.10.2 which is the newest release. Both long press and doubleclick (for homepage and sidebar doubleclick works) is not working for me, and when doubleclicking there is even a probability to let the software crash...

**Comment by yaichenbaum** [comment] 2020-06-21 16:11
I have reopened this issue under "Improving touch support for Files UWP".

**Comment by PeterStrick** [comment] 2020-06-23 06:21
The issue seems somewhat fixed with the new versions but still occurs sometimes. It just appears less frequent with the new version. Rightclicking on the touchscreen also works now.

**Comment by yaichenbaum** [comment] 2020-11-30 16:03
@PeterStrick If you notice any other issues with touch screen usage, please open a new issue for each area.

**Closed by yaichenbaum** 2020-11-30 16:03 UTC
Labels: bug, triage approved
