### ISSUE TITLE
Freeze on folder right-click

### ISSUE THREAD

**Issue by aerogems** [files-community/Files#12819] opened 2023-07-01 17:27 UTC
### Description

Whenever right-clicking on a directory or file, the app stops refreshing the display and becomes unresponsive. Cannot interact with UI at all or even move window around on desktop.

Does not happen on top level drives, only items (files and directories) underneath. Same behavior on a clean install of Files app.

### Steps To Reproduce

1. Open files app
2. Navigate to a folder such as C:\Users
3. Right-click on folder such as user directory

### Requirements

App should not freeze, or become unresponsive, when right-clicking a folder.

### Files Version

2.5.10

### Windows Version

Windows 11 Ver. 10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11926757/debug.log)

**Comment by Josh65-2201** [comment] 2023-07-01 22:09
Thanks for the report, I've added this to the project board.

**Comment by smogzinn** [comment] 2023-07-08 19:28
I ran into this same problem and, at least for me, it seems to have been caused by MS Powertoys File Explorer add-ons. I had Files App working fine, I installed PowerToys and the first time I right clicked on something Files App stopped responding and I had to manually end the process. After some testing I found that disabling File Explorer add-ons in Powertoys and rebooting fixed the problem. Some more testing will need to be done, but it seems a good place to start.

**Comment by aerogems** [comment] 2023-07-08 21:41
> I ran into this same problem and, at least for me, it seems to have been caused by MS Powertoys File Explorer add-ons. I had Files App working fine, I installed PowerToys and the first time I right clicked on something Files App stopped responding and I had to manually end the process. After some testing I found that disabling File Explorer add-ons in Powertoys and rebooting fixed the problem. Some more testing will need to be done, but it seems a good place to start.

A good thought, and something I probably never would have considered. Unfortunately, no luck for me. I turned off all the file explorer settings in power toys and symptoms still persist pre and post-reboot.

**Comment by yaira2** [comment] 2023-08-31 14:08
This issue appears to be resolved in our dev branch.

**Closed by yaira2** 2023-08-31 14:08 UTC
Labels: bug
