### ISSUE TITLE
SFTP/FTP

### ISSUE THREAD

**Issue by Torikkusu** [files-community/Files#7178] opened 2021-12-01 11:13 UTC
### What's the Problem?

I don't wanna use a "Third-Party" programm to connet to my server, instant i wanna have it in my file manger, like one drive 

### Solution/Idea

add a FTP/SFTP to file manger like FileZilla or winSCP

### Alternatives

-

### Priorities

- 

### Files Version

Version: 2.0.34.0 OS Version: 10.0.19043.1348

### Windows Version

Windows 10 Pro 21H1 19043.1348

**Comment by RickeyWard** [comment] 2021-12-01 15:22
I'm not against adding a more robust integration (I'd love something like winscp that supports scp and browsing remote linux shares from my windows pc) but I'd like to point out FTP is already available.

FTP is a standard windows feature for mapped drives via the "network" section. expand network drives, right click on "network" and choose "map network drive" which supports FTP.


![image](https://user-images.githubusercontent.com/342468/144261586-04d2b62e-6816-4df0-9372-605ccc3d4c1d.png)
![image](https://user-images.githubusercontent.com/342468/144261736-e7c5405f-a84f-45b7-b0a5-c167fa56c724.png)

**Comment by gave92** [comment] 2021-12-01 18:07
Alternatively you can paste the Ftp path in the address bar and then pin the directory to favourites.
Instead SFTP is not yet supported.

**Comment by MrPeanut12** [comment] 2021-12-10 14:01
Is this a duplicate of #2407?

**Comment by gave92** [comment] 2021-12-10 17:26
Looks like, thank you. Merging with #2407.

**Closed by gave92** 2021-12-10 17:26 UTC
Labels: feature request
