### ISSUE TITLE
Would be cool, but crashes alot

### ISSUE THREAD

**Issue by speedjay** [files-community/Files#3583] opened 2021-02-15 09:53 UTC
Using it on a hp Pavilion Gaming Laptop. Crashes, when opening big folders or going back to previous folder. Other than that great explorer!

**Comment by gave92** [comment] 2021-02-15 12:44
@speedjay thanks for the feedback. If the app is crashing please share the app version and the log files so we can fix the  issue.

**Comment by Ein-Tim** [comment] 2021-02-15 17:06
Since the latest update I also experience a lot of crashes, 2 alone today. Logs will follow.

**Comment by gave92** [comment] 2021-02-15 17:29
@Ein-Tim version 1.2.2 has known issues that should be fixed in 1.2.3 (now in beta testing). In the meantime if you can share your log files it's always useful ;9

**Comment by Ein-Tim** [comment] 2021-02-15 17:33
@gave92 Thanks for the update (:

Here are my log files: 
[debug.txt](https://github.com/files-community/Files/files/5983192/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5983194/debug_fulltrust.txt)

**Comment by philippschalau** [comment] 2021-02-15 17:33
i'm quite new but i experience the same problem

where do i get the "log" and where do i post them?

**Comment by Ein-Tim** [comment] 2021-02-15 17:35
@philippschalau 

>Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

You can post them here.

**Comment by philippschalau** [comment] 2021-02-15 17:37
@Ein-Tim 

Thanks :-)

[debug.txt](https://github.com/files-community/Files/files/5983221/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5983222/debug_fulltrust.txt)

**Comment by gave92** [comment] 2021-02-15 17:46
@philippschalau i think the issue you're experiencing is fixed in 1.2.3 which should go public in a few days 👍

@Ein-Tim yours is new xD could you move it to a new issue, specifying how did you get it to crash? (i can see pressing spacebar and opening the context menu maybe?) Thanks

**Comment by Ein-Tim** [comment] 2021-02-15 17:56
@gave92 

Thank you. I will try to reproduce this first, when I've found the pattern I will open a new issue.

**Closed** 2021-02-18 00:10 UTC
Labels: bug, more-info
