### ISSUE TITLE
Right click menu has a visual glitch when shown

### ISSUE THREAD

**Issue by Neoran01** [files-community/Files#5555] opened 2021-07-26 13:36 UTC
**Explain the bug**
Right click menu has a visual glitch when shown. The glitch can occur multiple times and it happens regardless if the app is maximized or not. A restart does not fix the issue, both temporarily and permanently.

**To reproduce**
1. Open the Files app
2. Go to any directory (ex. the C: directory)
3. Right click on an item or empty space 
4. A glitched right click menu will be shown.

**Expected behavior**
The right click menu should be displayed correctly with no visual glitch.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6878471/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6878475/debug_fulltrust.log)

**Screenshots**
Unmaximized:
![Screenshot 2021-07-26 210810](https://user-images.githubusercontent.com/87983083/126994762-7793aec0-04a6-4364-af3e-03b3fe0370df.png) 

Maximized:
![Screenshot 2021-07-26 210847](https://user-images.githubusercontent.com/87983083/126995004-4e905bd7-08a8-46f6-9c19-fc37dcf2bc9e.png)

**System Information**
 - OS Version: Windows 11 Home 21H2 (10.22000.100) 
 - App version: Version: 1.9.14.0

**Additional comment**
Does this problem happen again after restarting the app? _Yes_

**Comment by gave92** [comment] 2021-07-26 18:17
Thanks for the report. Closing this as caused by a WinUI issue.

**Closed** 2021-07-26 18:16 UTC
Labels: bug

**Comment by gave92** [comment] 2021-07-26 18:20
@winston-de currently the Commandbarflyout does not seem to grow in width when items are added dynamically. I'm pretty sure this was asked on the WinUI repo but as feature request not bug so I'm not sure if/when they're going to fix it.
Hopefully we can find a workaround, e.g trying setting a MinWidth or something?

**Comment by winston-de** [comment] 2021-07-26 23:25
> @winston-de currently the Commandbarflyout does not seem to grow in width when items are added dynamically. I'm pretty sure this was asked on the WinUI repo but as feature request not bug so I'm not sure if/when they're going to fix it.
> Hopefully we can find a workaround, e.g trying setting a MinWidth or something?

I think settings min width would probably fix it.

**Comment by yaichenbaum** [comment] 2021-08-02 21:22
This issue should be resolved with #5622.
