### ISSUE TITLE
Downloads directory not displaying items when grouping is turned on

### ISSUE THREAD

**Issue by CessnaBroon** [files-community/Files#7396] opened 2022-01-01 08:16 UTC
My Downloads directory is located at d:\<user>\Downloads, which I set up through Windows, and has worked since September with this application, but all of a sudden, it refuses to display any of the files and folders in the directory, despite recognising they exist. I've tried reinstalling the app, but it has the same issue.
![image](https://user-images.githubusercontent.com/94312908/147846755-4213da96-c61f-419c-9dd9-b5f4b7c2ee49.png)

**Comment by gave92** [comment] 2022-01-01 15:55
Does pressing "F5" make the folder items appear?

**Comment by CessnaBroon** [comment] 2022-01-01 16:52
> Does pressing "F5" make the folder items appear?

It does not.

**Comment by rafifos** [comment] 2022-01-01 17:54
I can confirm that this is happening on Windows 11 (21H2, build 22000.376) as well. My Downloads directory is in the default location (`%USERNAME%\Downloads`).

**Comment by gave92** [comment] 2022-01-01 17:55
Could you confirm Files version? Is it 2.0.34?

**Comment by rafifos** [comment] 2022-01-01 17:56
Hi, @gave92.

**Comment by rafifos** [comment] 2022-01-01 17:57
A (probably) cached version of the directory is shown when creating a new folder/file inside it, but it doen't shows the actual folder content, only what was there before it stopped working.

**Comment by Duckloveshack** [comment] 2022-01-01 21:09
Can confirm it affects other folders too, **only if** the items are grouped in that specific folder. Once you group by none, all the files are shown. May have to open a separate issue because it doesn't just stick to a single folder. Version 2.0.34.0 btw

**Comment by md1440** [comment] 2022-01-01 23:24
Having the same issue on version Version: 2.0.34.0 OS Version: 10.0.19044.1415 when files are grouped...

**Comment by yaichenbaum** [comment] 2022-01-02 05:13
This issue is reported to have been fixed in v2.0.43.

**Comment by CessnaBroon** [comment] 2022-01-02 08:13
> Can confirm it affects other folders too, **only if** the items are grouped in that specific folder. Once you group by none, all the files are shown. May have to open a separate issue because it doesn't just stick to a single folder. Version 2.0.34.0 btw

This is correct for my issue too.

**Comment by gave92** [comment] 2022-01-03 13:45
Could you check if the items appear if you change your system date to February? (not kidding)

**Comment by Duckloveshack** [comment] 2022-01-03 15:05
> Could you check if the items appear if you change your system date to February? (not kidding). Maybe introduced in #6134.

Checked it now and actually it did temporarily fix it until Windows changed the date back.

**Comment by gave92** [comment] 2022-01-03 15:07
Thanks for confirming 👍

**Comment by CessnaBroon** [comment] 2022-01-03 16:09
> Could you check if the items appear if you change your system date to February? (not kidding). Maybe introduced in #6134.

Fixes for me.

**Comment by yaichenbaum** [comment] 2022-01-03 16:10
This issue should be resolved with #7423

**Closed** 2022-01-03 16:09 UTC
Labels: bug, triage approved

**Comment by CessnaBroon** [comment] 2022-01-03 16:16
> This issue should be resolved with #7423

Any idea when it will be in a release?

**Comment by yaichenbaum** [comment] 2022-01-03 16:17
> > This issue should be resolved with #7423
> 
> Any idea when it will be in a release?

Insider build is compiling now
