### ISSUE TITLE
Bug: Info pane doesn't adjust to size changes

### ISSUE THREAD

**Issue by adamjameskramer** [files-community/Files#16271] opened 2024-09-27 16:14 UTC
### Description

Preview panel dimensions wont change or move when clicking the slider. When you click from details to preview the entire window then crashes. 
![Screenshot 2024-09-27 121329](https://github.com/user-attachments/assets/f5d37896-24bc-44ed-89da-6dacad0b1fa4)

### Steps To Reproduce

Open folders. 

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.6.0

### Windows Version

10.0.19045.4894

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17166894/debug.log)

**Comment by Josh65-2201** [comment] 2024-09-27 17:09
Try closing Files from the system tray and reopening

**Comment by adamjameskramer** [comment] 2024-09-27 17:54
Issue continues. 
"preview" mode - still crashed with no preview panel open. 
[debug.log](https://github.com/user-attachments/files/17167836/debug.log)

**Comment by Josh65-2201** [comment] 2024-09-27 17:59
The crashing issue is being tracked in #16226. Are the toolbar buttons still missing for you?

**Comment by adamjameskramer** [comment] 2024-09-27 18:02
Yes, those side buttons are still missing. 
And when clicking to re-size the panel its locked and wont move.

**Comment by Josh65-2201** [comment] 2024-09-27 18:03
Can you send a screenshot of the full window

**Comment by adamjameskramer** [comment] 2024-09-27 18:08
See attached.

![Screenshot 2024-09-27 140728](https://github.com/user-attachments/assets/75ceea9c-4610-417c-9838-dce396ccd115)
.

**Comment by yaira2** [comment] 2024-09-29 06:13
Does reinstalling Files solve the issue?

**Comment by 0x5bfa** [comment] 2024-09-30 15:18
Can you attach and send your settings json file when that weird info pane rendering happened?

Also I'm seeing the crash log in your log file
```
System.ComponentModel.Win32Exception (31): An error occurred trying to start process 'the-pdf-file.pdf' with working directory 'C:\WINDOWS\system32'. A device attached to the system is not functioning.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Files.App.Utils.Shell.LaunchHelper.<>c__DisplayClass3_0.<<HandleApplicationLaunch>b__0>d.MoveNext()
```

But I feel like this is caused by your previewer. What's previewer did you have installed? And can you try with other file types than pdf, such as docx and ai?

**Comment by adamjameskramer** [comment] 2024-09-30 16:17
@0x5bfa - I don't have the log file, if you go back to the first comment - I had uploaded it. (https://github.com/user-attachments/files/17166894/debug.log) 
Since uninstalled and re-installing its be corrected and no come back. 

Stable - Crashes with other files too, ai and dwg. 
[debug.log](https://github.com/user-attachments/files/17192897/debug.log)

Previewer - currently working without issues.

**Comment by 0x5bfa** [comment] 2024-09-30 16:23
I'm seeing a bunch of crunches related to pdf only. Not to ai or dwg.
Which version of Files Preview (blue icon) do you use now?

**Comment by adamjameskramer** [comment] 2024-09-30 17:15
Previewer - 3.7.9.0

**Comment by 0x5bfa** [comment] 2024-09-30 17:19
@yaira2 This means WinAppSdk 1.6 PR would fix this?

@adamjameskramer info pane works for you now? If not please send your Files settings json file.

**Comment by adamjameskramer** [comment] 2024-09-30 17:21
@0x5bfa - the panel controls are back and working. Just the crashing issue is outstanding.

**Comment by yaira2** [comment] 2024-09-30 17:23
> This means WinAppSdk 1.6 PR would fix this?

v3.7.9 is WinAppSdk 1.6, in any event, we can close this issue considering the reported issue has been resolved.

**Closed by yaira2** 2024-09-30 17:23 UTC
Labels: bug, needs - additional info, needs - reproducing, area - info pane
