### ISSUE TITLE
Files freeze and crashes after short use, no related info/error in debug.log

### ISSUE THREAD

**Issue by imhe6** [files-community/Files#11714] opened 2023-03-14 12:11 UTC
### Description

![image](https://user-images.githubusercontent.com/95729258/224996957-7a8c67a1-e909-4739-bbf1-6006ec0976ec.png)

Just as title, and the system "Not responding" popup. What's weird, debug.log is too _ brief_ that it only logged info till checking updates, and there are no ERROR or FATAL.
P.S. Same thing happens on release version 2.4.40, but the release more frequently and its logs contain related errors. Because of this I turned to preview version, hoping that was fixed. But unfortunately it's not.

### Steps To Reproduce

Open Files app and do something like clicking left panel items in settings. After a random time Files will crash.

### Requirements

Fix freeze and crash

### Files Version

2.4.51.0 (Preview)

### Windows Version

Windows 11 22H2 10.0.22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/10968443/debug.log)

**Comment by yaira2** [comment] 2023-03-28 19:56
Is this still an issue in the latest preview version? https://files.community/download/preview

**Comment by yaira2** [comment] 2023-04-19 00:31
@imhe6 we're going to close this for now since we can't reproduce the issue in v2.4.62, but please let us know if it's still an issue for you.

**Closed by yaira2** 2023-04-19 00:31 UTC
Labels: bug, more-info
