### ISSUE TITLE
Crash when opening ongoing tasks while deleting hidden folder

### ISSUE THREAD

**Issue by Pelmenner** [files-community/Files#3959] opened 2021-03-11 07:42 UTC
**Describe the bug**
I try to delete a hidden folder (in my case it was .vs, but as I checked, it happens with all hidden folders). I choose permanently delete in dialog. Then if I try to open ongoing tasks (right bottom corner), it crashes. 
When I open Files later the folder is deleted.

**To Reproduce**
1. Go to any folder
2. Make an hidden folder
3. Delete it permanently
4. While the folder is being deleted click on ongoing tasks
5. Watch how it crashes🔥

**Expected behavior**
Expected not to crash

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.804
 - App version: 1.3.0.0

**Additional context**
I can easily reproduce this bug. Also while I was reproducing it I saw another crash, but I didn't understand what happened.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6121138/debug.txt)

**Comment by gave92** [comment] 2021-03-11 19:23
Thanks for this report. I'm closing this since the issue is fixed in the development branch. The fix will ship with the next public version.

**Closed by gave92** 2021-03-11 19:23 UTC
Labels: bug
