### ISSUE TITLE
Dynamic Grid View & Preview Row Height

### ISSUE THREAD

**Issue by trulko** [files-community/Files#4703] opened 2021-04-22 17:48 UTC
**Is your feature request related to a problem?**
In grid view, thumbnails which don't have a square aspect ratio have lots of wasted space and are very far away from the file name. This is also the case in the preview pane by default, unless you manually move the details text up with the slider -- see the picture below:
![image](https://user-images.githubusercontent.com/81886277/115761666-9700aa80-a370-11eb-8023-348ef80a5eac.png)

**Describe the solution**
Dynamically adjust grid row height to the minimum height for the tallest item in the tow. Also dynamically adjust the default height of the division between the preview and details panels in the preview pane based on thumbnail aspect ratio. Classic file explorer has implemented this solution already -- see picture below. In this example all the pictures are panoramic, and in File Explorer row height for that row is decreased so that there isn't too much blank space.
![image](https://user-images.githubusercontent.com/81886277/115761645-91a36000-a370-11eb-8c47-0f3a6d45dcb2.png)

**Describe alternatives you've considered**
None.

**Additional comment**
Files 1.5.0.0 on Windows 10 20H2

**Comment by yaichenbaum** [comment] 2021-04-27 04:23
Duplicate of #997.

**Closed by yaichenbaum** 2021-04-27 04:23 UTC
Labels: enhancement, triage approved
