### ISSUE TITLE
Drives not listed

### ISSUE THREAD

**Issue by TRAMAduck** [files-community/Files#13258] opened 2023-08-27 11:36 UTC
### Description

The drives section is completely empty. My two installed hard drives do not show and even the network drives that I mapped don't show.

### Steps To Reproduce

Open files
View no drives listed
![Capture](https://github.com/files-community/Files/assets/118639944/3c0fd48c-21ca-4ce1-a4aa-c6a3253dd748)

### Requirements

Be able to see my drives

### Files Version

2.5.21.0

### Windows Version

22H2 (19045.3393)

### Log File

[debug.log](https://github.com/files-community/Files/files/12447847/debug.log)

**Comment by Josh65-2201** [comment] 2023-08-27 14:07
Thanks for the report, can you send a screen shot of Window File Explorer drive list.

**Comment by TRAMAduck** [comment] 2023-08-27 17:49
![Capture](https://github.com/files-community/Files/assets/118639944/ea85b2c2-c8ec-4860-bf93-786053125f06)

**Comment by Josh65-2201** [comment] 2023-08-27 17:51
Can you see if this is an issue in the preview version. https://files.community/download

**Comment by TRAMAduck** [comment] 2023-08-27 17:55
It is not an issue in the preview, all drives are showing.

**Comment by TRAMAduck** [comment] 2023-08-27 17:55
![Capture](https://github.com/files-community/Files/assets/118639944/7365ed7d-85f7-44a9-9a28-47261c4e2f9e)

**Comment by Josh65-2201** [comment] 2023-08-27 17:56
Great, since the issue is fixed in preview it should be fix with the next stable update. There no timeline for this but you can continue to use preview in the mean time.

**Closed by Josh65-2201** 2023-08-27 17:56 UTC
Labels: bug, more-info
