### ISSUE TITLE
Blurry Icons

### ISSUE THREAD

**Issue by prakharsinghal001** [files-community/Files#2528] opened 2020-12-03 19:31 UTC
Firstly, I am very thankful to you guys for bringing a nice file explorer app. I hoped Microsoft would take the initiative but its nice to see an excellent app of yours in the store.

Problem: Icons appear blurry. I have attached the screenshot, you can compare it.
![Screenshot 2020-12-04 005613](https://user-images.githubusercontent.com/75448234/101077973-8de28d00-35cb-11eb-9bb4-73063c79dfde.png)

**Comment by XPoppyX** [comment] 2020-12-03 19:38
Duplicate of #1152

**Closed** 2020-12-03 20:45 UTC
Labels: feature_request
