### ISSUE TITLE
Bug: System crash (BSOD) after attempting to close a tab (NFS issue?)

### ISSUE THREAD

**Issue by tacogerbil** [files-community/Files#12985] opened 2023-07-20 00:37 UTC
### Description

I copied some files over to a network share and proceeded to close a tab in files.  This led to an unrecoverable BSOD.

### Steps To Reproduce

Not directly reproduceable.  It's random.  It's happened about 5 times now in less than a week.  Just a random crash while interacting with some part of files.

### Requirements

- e.g. Fix crash that occurs when...
random interaction.  Closing tab, clicking on a button, moving files.

### Files Version

2.5.10.0

### Windows Version

10.0.22000.2176

### Log File

[debug.log](https://github.com/files-community/Files/files/12101053/debug.log)
![image](https://github.com/files-community/Files/assets/12961907/92990c75-149f-4001-b8e9-d0699c6ac11a)

**Comment by tacogerbil** [comment] 2023-07-20 02:22
I Uninstalled the microsoft store version and installed this version.  I'll
let you know! :)

**Comment by tacogerbil** [comment] 2023-07-20 02:33
That was short lived.  It won't run.  It comes up momentarily and the closes.  Sorry.
[debug.log](https://github.com/files-community/Files/files/12101566/debug.log)

**Comment by Josh65-2201** [comment] 2023-07-30 16:04
@tacogerbil Can you see if this is an issue in 2.5.21.0

**Comment by tacogerbil** [comment] 2023-07-30 16:11
Will do.  Just installed and set it as my primary.

**Comment by tacogerbil** [comment] 2023-07-31 02:35
It crashed again, while clicking on an icon @Josh65-2201 
![crash](https://github.com/files-community/Files/assets/12961907/1fe83ca5-ca1d-44d1-aa07-9edf555a0e66)
[debug.log](https://github.com/files-community/Files/files/12210961/debug.log)

**Comment by Josh65-2201** [comment] 2023-07-31 13:45
What icon did you click on?

**Comment by Josh65-2201** [comment] 2023-07-31 15:28
I see, I'm uncertain this is an issue Files can fix as it seems more like an issue with your Windows install or the WinAppSDK Files uses to run.

**Comment by tacogerbil** [comment] 2023-08-29 13:05
I just downloaded and set it as my default :)
I'll let ya know :)

**Comment by tacogerbil** [comment] 2023-08-29 13:51
Didn't take long.
Using 2 pinned shortcuts.. pressing on the icons to access them, one then the other (before the link has a chance to actually load up the pinned folder) goes straight to a BSOD.  I tried it a second time and it crashed again.
Now I've booted up and proceeded to go to the logs by hoping to use the links in the app... but I get this.. 
![image](https://github.com/files-community/Files/assets/12961907/b03239b0-6ecf-4fe3-b466-c06b51fdd792)
Looks like I killed it lol
Unfortunately I couldn't get to the log files.  I couldn't open explorer.  I ended up going to the app store and downloading files and accessing the about tab --> Open log location.  The only log was generated by this new install of files.

**Comment by tacogerbil** [comment] 2023-08-29 16:21
@yaira2 
K.. Uninstalled all versions of the app.  I had to uninstall the preview version completely as it wouldn't work anymore.. The included image above is all I got.
I installed a fresh copy and didn't modify any settings from default.
[debug.log](https://github.com/files-community/Files/files/12466954/debug.log)

I quickly clicked between 2 pinned links and it BSOD.
![image](https://github.com/files-community/Files/assets/12961907/7fd1aa16-9886-4a3f-8ae9-5eeda435c38d)

**Comment by yaira2** [comment] 2023-09-12 21:14
@tacogerbil thank you for the response, we still haven't been able to reproduce this issue, but we'll continue investigating.

**Comment by hishitetsu** [comment] 2023-09-13 00:29
@tacogerbil are you using NFS for network sharing? It appears so from the blue screen information.

**Comment by tacogerbil** [comment] 2023-09-13 01:23
> @tacogerbil are you using NFS for network sharing? It appears so from the blue screen information.

Oddly enough.. I stopped using NFS on my win 11 machine shortly after upgrading to the 22H2 version.  NFS isn't as good on it as it is in the unix world... kinda stinks.  I just re-installed and went nuts trying to make it blie screen...  Stayed stable 💯🔥😎

**Comment by hishitetsu** [comment] 2023-09-13 02:08
> I just re-installed Files and went nuts trying to make it blue screen... Stayed stable 💯🔥😎

@tacogerbil Great! When you were using NFS, did you also get BSODs when you were operating with File Explorer instead of Files? If so, then this is not a Files problem, but a Windows or NFS server problem.

**Comment by tacogerbil** [comment] 2023-09-13 02:13
@hishitetsu  No, never once.  It was klunky and slower but never BSOD.

**Comment by hishitetsu** [comment] 2023-09-13 02:27
Okay, so there is some kind of problem between Files and NFS. But I can't test it because I don't use NFS...

**Comment by tacogerbil** [comment] 2023-09-13 03:13
I'm more than willing.  I'm just connecting via smb3 to my shares for my
sanity.  NFS is actually still installed and running on my machine.

**Comment by Josh65-2201** [comment] 2024-02-14 18:15
@tacogerbil Is this still an issue in 3.2.0.0?

**Comment by Josh65-2201** [comment] 2024-04-27 15:11
@tacogerbil Can you see if this is still an issue in the preview version. https://files.community/download

**Comment by 0x5bfa** [comment] 2024-07-10 06:39
If you’re seeing this issue even the latest build, please try to:

- Find any logs related that BSOD in Event Viewer.
- Paste ‘%SystemRoot%memory.dmp’ to analyze your BSOD.

Processes in the user-mode cannot produce BSOD by its design (exceptions that cause a BSOD come from processes that run in kernel-mode). The system file producing this BSOD is a driver for NFS connection. This is just my guess but maybe your NFS driver is malfunctioning, corrupted or outdated. You can also do driver update in Device Manager or fix the whole system via ‘sfc /scannow’ in command prompt.

Interestingly, Atom had the same issue when closing a tab of a file from NFS server: https://github.com/atom/atom/issues/3010

**Comment by 0x5bfa** [comment] 2024-07-10 07:22
If you’re seeing this issue even the latest build, please try to:

- Find any logs related that BSOD in Event Viewer.
- Paste ‘%SystemRoot%memory.dmp’ to analyze your BSOD for the future reference.
- Run ‘sfc /scannow’ to fix all malfunctions within your system

For devs:
Processes in the user-mode cannot produce BSOD by its design (BSOD screen is implemented in `ntoskrnl.exe` which runs in kernel mode), which means Files or WinAppSdk itself cannot cause BSOD. More deeply, drivers call kernel-mode API `KeBugCheck()` in `ntoskrnl.exe` (the core kernel routine) when it encounters a serious issue that the driver cannot recover from.

Interestingly, Atom had the same issue when closing a tab of a file from NFS server: https://github.com/atom/atom/issues/3010

- [SYSTEM_THREAD_EXCEPTION_NOT_HANDLED bug check code](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7e--system-thread-exception-not-handled)
- [KeBugCheck function](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-kebugcheck)

**Closed** 2024-08-29 17:41 UTC
Labels: bug, help wanted, needs - additional info, crash, needs - reproducing
