### ISSUE TITLE
Connect to Sharepoint Sites

### ISSUE THREAD

**Issue by ruben-conesa** [files-community/Files#3185] opened 2021-01-20 09:42 UTC
**Is your feature request related to a problem? Please describe.**
I can't see Sahrepoint sites connected to Windows Explorer
![Captura de pantalla 2021-01-20 103739](https://user-images.githubusercontent.com/77723051/105156363-08c81e80-5b0c-11eb-956c-44a317750828.jpg)

**Describe the solution you'd like**
Please I would to like connect Sharepoint sites like I can do in Windows Explorer. See the screenshot.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by gave92** [comment] 2021-01-20 12:24
Duplicate of #1310

**Closed by gave92** 2021-01-20 12:24 UTC
