### ISSUE TITLE
Bug: Right-click menu issues when using two panes

### ISSUE THREAD

**Issue by nesretep** [files-community/Files#12013] opened 2023-04-07 17:01 UTC
### Description

When using two panes in the same tab, the right-click menus in each pane disappear as soon as they appear.  This doesn't seem to happen when only one pane is used in a tab.

### Steps To Reproduce

1. Open Files
2. Right-click on a folder to open it in a new pane.
3. In either pane, right-click to open the context menu

### Requirements

Right-clicking to open the context menu should allow the menu to persist until an option in the menu is chosen.

### Files Version

Files version 2.4.61.0

### Windows Version

Windows 11 22H2 OS Build: 22621.1265

### Log file

[debug.log](https://github.com/files-community/Files/files/11180282/debug.log)

**Comment by yaira2** [comment] 2023-04-09 03:34
> In either pane, right-click to open the context menu

This is working as expected for me but perhaps I misunderstood the issue, what happens when the menu opens?

**Comment by nesretep** [comment] 2023-04-09 15:45
The menu appears for maybe a second, I think I can see something about the
menu change and then it disappears completely without me having
left-clicked on any of the options.  The computer I was seeing this on was
running Windows 11.  When I tested in Windows 10 the issue did not occur.
It worked as expected.  I will repeat the test again on the Windows 11
computer and let you know what I find.

**Comment by yaira2** [comment] 2023-04-14 21:16
@nesretep I can't reproduce this on my end, but I wonder if the issues were resolved in the preview build, can you install the preview version and see if it's still an issue? https://files.community/download

**Comment by yaira2** [comment] 2023-04-21 00:35
@nesretep thank you for your feedback, this issue appears to be resolved in v2.4.66 but please let us know if it's still an issue after updating.

**Closed by yaira2** 2023-04-21 00:35 UTC
Labels: bug, more-info
