### ISSUE TITLE
Empty Recycle Bin not working in sidebar context menu

### ISSUE THREAD

**Issue by MattBDev** [files-community/Files#4244] opened 2021-03-23 16:43 UTC
**Explain the bug**
When clicking the "Empty Recycle Bin" button in the context menu from the sidebar, nothing happens. None of the files in the Recycle Bin are deleted. I refreshed the folder after a couple of minutes but all the files were still there.

**To reproduce**
1. Click on Recycle Bin
2. Right click Recycle Bin in the sidebar.
3. Click Empty Recycle Bin.
3. Files will not be deleted.

**Expected behavior**
All files in the Recycle Bin should be deleted. 

**Logfile**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6191307/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6191308/debug.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/4009945/112198121-2cc6df80-8be3-11eb-9925-ef61140c61cc.png)

**System Information**
 - OS Version: Windows 10 Version 21H1 build 19043.899
 - App version: 1.5.0.0

**Additional comment**
Restarting the app does not fix the problem. I haven't tried rebooting my system yet but the next time I do I will reply to share whether or not that will fix it.
Let me know if I need to provide any additional information or if there is anything I can do to fix this issue.

**Comment by gave92** [comment] 2021-03-23 18:02
@MattBDev actually a screenshot of the context menu would be helpful.

**Comment by MattBDev** [comment] 2021-03-23 18:21
> @MattBDev actually a screenshot of the context menu would be helpful. Are you right clicking on the sidebar? Does it work if you right click on the "empty space" of the filelist instead?

![image](https://user-images.githubusercontent.com/4009945/112197773-d194ed00-8be2-11eb-8e45-48dece6f02ca.png)

I am using the context menu in the sidebar as pictured above. I did try using the context menu in the file list like you suggested and it did work successfully. I'll update the title of the issue accordingly.

**Comment by suhailmahmood** [comment] 2021-09-07 08:19
I was about the report this bug, and then I saw this. Yes, I can confirm that the issue still exists.

**Comment by BanCrash** [comment] 2021-09-07 08:24
> I was about the report this bug, and then I saw this. Yes, I can confirm that the issue still exists.

Do you have v1.5?

**Comment by suhailmahmood** [comment] 2021-09-07 08:32
@BanCrash Yes, I have v1.5.0.0

**Comment by BanCrash** [comment] 2021-09-07 08:35
> @BanCrash Yes, I have v1.5.0.0

Thanks for letting me know!

This issue seems to be solved on v2.0, which will be released on October. 

@yair100

**Closed by BanCrash** 2021-09-07 08:35 UTC
Labels: bug, triage approved
