### ISSUE TITLE
Files preview

### ISSUE THREAD

**Issue by DanRotaru** [files-community/Files#2696] opened 2020-12-25 00:07 UTC
Video preview bug 
![image](https://user-images.githubusercontent.com/7759507/103111391-36c55a80-4655-11eb-9495-71585faa8f34.png)

Here we have 2 bugs (or flaws):
1) Video preview is not displayed
2) App preview icon is in very bad resolution
How look app icon in default explorer (if video preview isn't displayed) (Very good quality)
![image](https://user-images.githubusercontent.com/7759507/103111462-e8fd2200-4655-11eb-8542-dfa1e86985b8.png)
And how look in Files app
![image](https://user-images.githubusercontent.com/7759507/103111475-1b0e8400-4656-11eb-9a9f-a97a680321e8.png)

I have alternative video player (PotPlayer) (and set it for default), in windows explorer all looks good (previews are visible), but in this app, I see app icon (+ in bad resolution)

How this folder looks in default explorer: 
![image](https://user-images.githubusercontent.com/7759507/103111430-8f94f300-4655-11eb-8857-20cf4d26c54a.png)

Latest updated version (0.23.0.0)

**Comment by gave92** [comment] 2020-12-25 07:20
Duplicate of #2660

**Closed by gave92** 2020-12-25 07:20 UTC
Labels: bug

**Comment by DanRotaru** [comment] 2020-12-25 12:41
> Duplicate of #2660

How it's fixed if I see that?

**Comment by gave92** [comment] 2020-12-25 13:08
"Fixed" as in "it's fixed in the internal development version and will roll out to users in the next public release"
