### ISSUE TITLE
Issues with Drag and drop to Desktop in File

### ISSUE THREAD

**Issue by ZCRP** [files-community/Files#12136] opened 2023-04-21 08:28 UTC
### Description

One Issues is with about "file" there is a very bad Bugs problem About the thing with Drag & drop, when i ever drag a selected Folder or a file it does not working when i drop it to my Desktop something, this issues only relates in this Advanced Explorer like "File" it will be very welcomed when this last bug be fixed and I will recommend it just everywhere!

with best regrads

ZRP.

### Steps To Reproduce

1. Just Try drag a File or a folder and drop it to the Desktop and than you will see why. not all is good enough now

### Requirements

idk i have for coding currently noo any ideas how it work. but i wanna that your fix it no matter how you do it.

### Files Version

2.4.66.0

### Windows Version

Windows 11 22H3

### Log file

[debug.log](https://github.com/files-community/Files/files/11293815/debug.log)

**Comment by Josh65-2201** [comment] 2023-04-21 12:36
Thanks for the report. I am unable to reproduce this, can you give the following information.
- Does this happen every time?
- Can you confirm your Windows build as I can't find 22H3 as a build. You can type `winver` into the start menu to see the build number

**Comment by ZCRP** [comment] 2023-04-21 18:25
1. its happend pernamently i have this mentioned issues still.
2. i have windows 11 Home

**Comment by yaira2** [comment] 2023-04-23 15:36
@ZCRP thank you for reporting this issue, can you confirm if it's the same as #6309?

**Comment by ZCRP** [comment] 2023-04-30 15:15
Yes i confirm it.

**Comment by yaira2** [comment] 2023-04-30 15:17
@ZCRP thank you, we're going to close this issue but you can subscribe to #6309 to be notified of updates.

**Closed by yaira2** 2023-04-30 15:17 UTC
Labels: bug, more-info
