### ISSUE TITLE
Encrypted archives does not work

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10376] opened 2022-11-01 19:23 UTC
### Description

Extracting an encrypted archive does not require the password. The files are created but empty.

### Steps To Reproduce

- Select a encrypted archive (.zip)
- Click on Extact in a folder
- The files are created but empty.

### Steps to fix

- Before extraction, detect if the archive is encrypted.
- In this case, ask for the password in a dialog and use it to correctly extract the content.

### Files Version

Version: 2.3.57.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 22621.674

### Relevant Assets/Logs

None.

**Comment by ferrariofilippo** [comment] 2022-11-01 20:38
I think this issue is a duplicate of #9948

**Closed** 2022-11-01 21:54 UTC
Labels: bug
