### ISSUE TITLE
Disc drive shows contents of last inserted disc even if drive is empty

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2916] opened 2021-01-11 13:34 UTC
**Describe the bug**
When an optical disc is removed from the disc drive, the contents of the last disc inserted still remain in that path.

**To Reproduce**
1. Insert an optical disc into the CD/DVD drive.
2. Open the disc in Files.
3. Close Files and eject the disc.
4. Open Files and navigate to your disc path.
5. The contents are still there, even though the disc is ejected.

**Expected behavior**
I would expect nothing to be there. "This folder is empty."

**Screenshots**
![image](https://user-images.githubusercontent.com/76794507/104188653-8f338080-53e7-11eb-90e4-b25ba220acfe.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.685)
 - App version: 1.0.0.0

**Additional context**
After restarting the app, the issue is still present.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5796008/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5796010/debug_fulltrust.txt)

**Comment by gave92** [comment] 2021-01-11 15:38
Could you try disabling "Cache files and folders for better performance" option in Files settings and see if the issue is fixed?

**Comment by Tech-How** [comment] 2021-01-11 15:56
Oh, that makes sense. They disappear when I eject the disc now :)

**Comment by gave92** [comment] 2021-01-11 16:25
@Tech-How thanks a lot for the confirmation. Still something we should fix.

**Comment by gave92** [comment] 2021-06-03 18:12
Fixed in latest code.

**Closed** 2021-06-03 18:12 UTC
Labels: bug, triage approved
