### ISSUE TITLE
Bug: Can't display content of Android devices

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#11942] opened 2023-04-02 14:13 UTC
### Description

Normally when connecting Android devices to PC, users could view files from internal storage (and installed SD card).
But when using Files, the app will display a strange error saying "Network folder error" ( more on the following part ).

### Steps To Reproduce

*The following tests are based on my personal phone, which is Asus ZenFone 9*
1. Connect an Android phone to PC, make sure choosing "File transfer" on the phone's USB preferences.
2. Open Files and click on the phone, which will bring up available storage space to view.
![image](https://user-images.githubusercontent.com/8479301/229358193-79624386-741f-4224-82e2-bf65a5680997.png)
3. Click any of the storage and see the error.
![image](https://user-images.githubusercontent.com/8479301/229358243-b3af1007-b69b-4331-9334-fd44fb9b221f.png)

### Requirements

Files should be able to view the content of the storage, just as Windows Explorer does.

### Files Version

2.4.40.0

### Windows Version

10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11132418/debug.log)

**Comment by yaira2** [comment] 2023-04-02 14:14
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment] 2023-04-03 19:32
For what it's worth, I'm having a lot of issues connecting to Android devices as well.

**Comment by alexkuznetsov** [comment] 2023-04-06 07:41
Faced with that issue too, my tablet Galaxy Tab had connected, but i coluldn't access to the contents of drive.

Checked in Files and in default file manager too (same behaviour).

For current moment, only total commander can help, but it looks like sothing from deeep past :-D

**Comment by ferrariofilippo** [comment] 2023-07-20 15:10
Is this still an issue? 
It seems the same as #11413 which has been fixed

**Comment by Josh65-2201** [comment] 2023-07-30 15:46
@jh961202 Can you please see if this is an issue in 2.5.21?

**Comment by yaira2** [comment] 2023-08-01 20:37
@jh961202 we can't reproduce this issue in our dev branch but if it's still occurring for you, please let us know and we'll reopen this issue.

**Closed by yaira2** 2023-08-01 20:37 UTC
Labels: bug, more-info
