### ISSUE TITLE
Incorrect file size unit of measure (or whatever these are)

### ISSUE THREAD

**Issue by SOI7** [files-community/Files#1638] opened 2020-08-03 13:10 UTC
**Describe the bug**
Instead of showing files size in KBs, MBs etc. Files UWP shows them in... "knowledge gase"? I don't even know what that is, nor I know if it's exclusive to the italian localization.

**To Reproduce**
Just open the app, you see these basically anywhere, no matter which layout. Even in Properties, you see these weird strings.

**Expected behavior**
Files size should be displayed in bytes and their multiples (KB, MB etc.)

**Screenshots**
![image](https://user-images.githubusercontent.com/50930970/89185792-1825d080-d59b-11ea-9c55-b0eccb6a7ff2.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.12.0

**Comment by gave92** [comment] 2020-08-04 09:22
Nice case of automatic translation 😁. The issue is now fixed but not yet released to the store.

**Comment by jonaskohl** [comment] 2020-08-06 16:41
Also happens for German language: It says "MF" (how inappropiate 😅) instead of "MB" (also happens for KB (KF), GB (GF) etc.)

**Closed** 2020-10-13 17:31 UTC
Labels: bug, fixed
