### ISSUE TITLE
Paste Crash

### ISSUE THREAD

**Issue by vaimalaviya1233** [files-community/Files#2102] opened 2020-10-16 00:45 UTC
**Describe the bug**
When i cut using windows explorer and pasting  using files app I think more than 6 GB files it crashed

**To Reproduce**
1. Go to ' it doen't matter if multiple file add up to make more or 6GB'
2. "cut all those files using explorer and open folder in files app"
3. "right click and paste and sometime after it crashed"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
all the files's size add up to 6 GB 

**Log file**
I didn't know which log file to upload so i uploded both
[debug.txt](https://github.com/files-community/Files/files/5388567/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5388568/debug_fulltrust.txt)

**Comment by Jaiganeshkumaran** [comment] 2020-10-16 01:46
@vaimalaviya1233 Duplicate of #1222

**Closed** 2020-10-16 02:52 UTC
Labels: bug
