### ISSUE TITLE
Bug: App crashes when dragging a file while app is running with a high integrity level

### ISSUE THREAD

**Issue by bhw777** [files-community/Files#13394] opened 2023-09-18 20:25 UTC
### Description

Crashed after opening app and draging a file. No other actions. App is not running as admin, and is not set as the default file manager. Sometimes it happened to work well with no crash for drag & drop but I am not sure about the reason.

- [ ] 

### Steps To Reproduce

1. open Files with a high integrity level
2. drag a file or tab
3. the app crashes

### Requirements

- Detect and disable drag & drop on all trust levels that don't support it

### Files Version

2.5.29.0

### Windows Version

10.0.19045.3448

### Log File

[debug.log](https://github.com/files-community/Files/files/12653254/debug.log)

**Comment by Josh65-2201** [comment] 2023-09-19 12:40
Thanks for the report, Where are you dragging too? (Local, network, ftp, cloud, etc)

**Comment by bhw777** [comment] 2023-09-19 21:45
Local. Actually it crashed immediately after I dragged a file.
![1](https://github.com/files-community/Files/assets/126988961/34ac5fa8-1700-4f15-9e15-46192884fdfc)

**Comment by yaira2** [comment] 2023-10-25 16:53
Does it happen consistently?

**Comment by bhw777** [comment] 2023-10-26 15:46
Almost everytime.

**Comment by yaira2** [comment] 2023-11-01 16:34
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment] 2023-11-02 21:27
Can you also check what happens if you try dragging a tab?

**Comment by bhw777** [comment] 2023-11-02 21:36
Just tried and still crashed in the latest preview version including dragging a tab.

**Comment by yaira2** [comment] 2023-11-03 00:15
@bhw777 thanks for checking, can you upload the log file for that? If it's affect tabs as well, I'm starting to think it might be a platform issue but perhaps we can come up with a workaround.

**Comment by bhw777** [comment] 2023-11-03 00:54
I figured it out. I think it has been successfully fixed in the latest preview version because it won't crash if I open it directly or set as the default file manager. It only crashes if I open it using another app (there is an app that helps me open it conveniently, like a shortcut). Maybe there are some conflicts between them.

**Comment by yaira2** [comment] 2023-11-03 00:55
Do you have the stable version of Files installed? It's possible the other app is opening the stable version of Files which still has this issue.

**Comment by bhw777** [comment] 2023-11-03 00:58
No, I only have the preview version.

**Comment by yaira2** [comment] 2023-11-03 00:59
Can you check if the process is elevated (you can check in Task Manager)?

**Comment by bhw777** [comment] 2023-11-03 01:06
I can not drag file or tab if I open as admin. No response for that.

**Comment by yaira2** [comment] 2023-11-03 01:11
We disable drag & drop on admin because of a platform limitation, but it seems very similar to this issue. Which app are you using to launch Files?

**Comment by bhw777** [comment] 2023-11-03 01:17
Everything is good if it is not elevated, and I used [Quicker](https://getquicker.net/) to open it.

**Comment by yaira2** [comment] 2023-11-03 01:32
Can you try launching Windows Terminal thought Quicker and check if dragging a tab causes a crash?

**Comment by bhw777** [comment] 2023-11-03 01:42
No crash for Windows Terminal.

**Comment by yaira2** [comment] 2023-11-03 01:59
@bhw777 what username name is displayed next to the Files process in Task Manager? I think what's happening is that the process is being launched with higher trust, but we currently only check to disable drag and drop as admin.

**Comment by yaira2** [comment] 2023-11-03 02:03
On second thought, Task Manager might not show this information.

**Comment by bhw777** [comment] 2023-11-03 02:15
I saw username both in Task Manager and Process Explorer. The username shown next to Files is my computer's name (there are other username like SYSTEM and LOCAL SERVICE, not sure if I that's what you are looking for).

**Comment by yaira2** [comment] 2023-11-03 02:30
I think it's the integrity level, not the username.

**Comment by bhw777** [comment] 2023-11-03 02:35
The integrity level is high for admin and medium for not admin.

**Comment by yaira2** [comment] 2023-11-03 02:36
What about when you launch through Quicker?

**Comment by bhw777** [comment] 2023-11-03 02:43
Oh, I got it. When I launch through Quicker it is in high because Quicker is in high and the Files process is under Quicker even if I don't launch any of them as admin.

**Comment by yaira2** [comment] 2023-11-03 02:51
Thanks for sticking with me through all this 😄 
Now that we know the cause, we can look into a fix. Unfortunately drag & drop will have to be disabled, but at least it won't crash.

**Comment by bhw777** [comment] 2023-11-03 02:57
No problem. I haven't use Files for a long time because of this problem.Thanks for helping me know what happened. Looks like I can start using it again. 😄

**Comment by bhw777** [comment] 2023-11-23 21:04
@yaira2 Still crashed through Quicker. No problem when launched directly.

**Comment by yaira2** [comment] 2024-07-24 02:22
@bhw777 can you confirm if this is resolved in the v3.5.17 preview version? https://files.community/download

**Comment by bhw777** [comment] 2024-07-27 07:03
@yaira2 Tested and no crash. I believe it is resolved.

**Comment by 0x5bfa** [comment] 2024-07-27 07:20
Thank you for checking!

**Closed by 0x5bfa** 2024-07-27 07:20 UTC
Labels: bug, needs - additional info, crash

**Comment by yaira2** [comment] 2024-07-28 02:21
@0x5bfa nice work!
