### ISSUE TITLE
Files automatically removes the final letter of files and folders when creating them

### ISSUE THREAD

**Issue by DeveloperWOW64** [files-community/Files#8765] opened 2022-03-25 14:31 UTC
### Description

In files, if you create a file or folder with the 'New' button and type in the file name of the creation, Files will create a file/folder with the same name subtracted the final character. An example of this is this:
User creates `example` folder
Folder created: `exampl`
This also counts for file extensions. This makes it impossible to create 1-letter files/folders

### Steps To Reproduce

1. Create a file/folder
2. Name it
3. See Bug

### Expected behavior

You would expect to see the folder/file with its named name.

### Files Version

Version: 2.1.29.0 OS Version: 10.0.22000.556

### Windows Version

22000.556

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8351400/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8351401/debug_fulltrust.log)

**Comment by yaichenbaum** [comment] 2022-03-25 14:52
This appears to have been introduced in #8204. @szabolcstarnai can you take a look?

**Comment by jiejasonliu** [comment] 2022-03-25 23:43
Likely caused by the change to `BeforeTextChanging` instead of `TextChanged` which makes `dialog.ViewModel.AdditionalData = textBox.Text` give stale text (precisely, the text prior to the most recent change). 

I think changing this to use `args.NewText` should fix it.

**Comment by yaichenbaum** [comment] 2022-03-27 01:07
@jiejasonliu would you be interested in opening a pull request?

**Comment by jiejasonliu** [comment] 2022-03-27 01:50
@yair100 sure! i'll get one up by tomorrow

**Comment by yaichenbaum** [comment] 2022-03-27 21:42
This issue should be resolved in `main`.

**Closed** 2022-03-27 21:41 UTC
Labels: bug, triage approved

**Comment by DeveloperWOW64** [comment] 2022-03-28 17:00
> This issue should be resolved in `main`.

Thanks
