### ISSUE TITLE
Submit to Winget as a part of CI

### ISSUE THREAD

**Issue by heftymouse** [files-community/Files#12099] opened 2023-04-17 06:08 UTC
### What feature or improvement do you think would benefit Files?

Currently the winget version of Files is very outdated and must be submitted manually each time it needs to be updated. This can be automated using Azure Pipelines or GitHub Actions to automatically submit a PR to microsoft/winget-pkgs every time a new release is made.

### Requirements

- New releases are automatically submitted to winget 

### Files Version

Does not apply

### Windows Version

Does not apply

### Comments

A GitHub bot will likely need to be made for this

**Comment by QuaintMako** [comment] 2023-04-17 12:04
If it's not a high priority issue, I'd like to try my hands to it to learn a bit more about GitHub Actions!

**Comment by JaiganeshKumaran** [comment] 2023-04-18 04:00
WinGet should already support installing any free Store app.

**Comment by heftymouse** [comment] 2023-04-18 05:53
The issue is that Files is no longer free on the store

**Comment by yaira2** [comment] 2023-04-18 18:02
Closing as discussed with @heftymouse, our solution for now is to update the package on WinGet and rely on auto update for keeping users up to date.

**Closed by yaira2** 2023-04-18 18:02 UTC
Labels: feature request

**Comment by dougg0k** [comment] 2023-04-27 00:36
It seems that both options supposedly available are not longer working or available.
![files](https://user-images.githubusercontent.com/10801221/234730725-02937cf6-4043-429a-b645-a4b67c855e2a.png)

**Comment by yaira2** [comment] 2023-04-27 00:39
@dougg0k the Winget package needs to be updated but we haven't had the time to do this.

**Comment by dougg0k** [comment] 2023-04-27 00:41
Cant that be automated as suggested by the issue?

**Comment by yaira2** [comment] 2023-04-27 00:45
@dougg0k the app auto updates itself so it's not normally an issue. The reason the Winget version no longer works is that we forgot it was being used by Winget and we deleted the package from our server.

**Comment by dougg0k** [comment] 2023-04-27 00:46
I see, will you be adding it again?

**Comment by DanielHabenicht** [comment] 2023-11-04 20:26
I would like to voice my support for adding the version to winget. As the only Version currently available is from random publisher: https://github.com/microsoft/winget-pkgs/pull/91910 but as I've seen @yaira2 already tried to resubmit under the `FilesCommunity` name (https://github.com/microsoft/winget-pkgs/pull/93758). Should I try to file two separate PRs for changing the name?

Would it be possible to automate the release afterwards with winget-release?

**Comment by Josh65-2201** [comment] 2023-11-04 20:34
The issue is the manifest would have to be updated manually on each update of Files. There also isn't one on the repo as the PRs you link were merge and at some point removed.

**Comment by DanielHabenicht** [comment] 2023-11-04 22:33
Ahh, alright. I was actually looking at another issue, as I was not using the winget cli but an online repository: https://github.com/omaha-consulting/winstall/issues/125
So there currently is only the `Files` from the Windows Store.

Are the Release Versions available somewhere or only the latest release?
If, then we could run an action on every release like PowerToys is doing: https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml

**Comment by yaira2** [comment] 2023-11-05 00:01
> Should I try to file two separate PRs for changing the name?

That would be helpful 👍

> Would it be possible to automate the release afterwards with winget-release?

The app auto updates so as long as we keep the initial version our our servers, we shouldn't have to update WinGet.
