### ISSUE TITLE
Elevating app to admin does not work correctly

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#9177] opened 2022-05-15 14:20 UTC
### Description

Im try to edit system32 files and i carnt do anything but copy file out. Even with admin accses files will say it doesnt have permistion. File explorer works fine just showing and admin promt.

### Expected behavior

Files/folders should be made

### Files Version

2.2.5.0

### Windows Version

10.0.19043.1685

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8695146/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8695147/debug_fulltrust.log)

**Comment by Josh-65** [comment] 2022-05-15 14:33
Seems to be fixed after Killing all files process and reopening. im going to keep it open for now if the logs indercate anything different.

**Comment by gave92** [comment] 2022-05-15 14:33
Could you try again after reopening the app? Also this one from the logs looks like a transient issue.
If issue still present, could you:
- check if a "shield" icon appears in the lower right corner of the app
- upload the new log files

**Comment by Josh-65** [comment] 2022-05-15 14:34
The shild icon was there and i did it reigh before the other issue

**Comment by gave92** [comment] 2022-05-15 14:36
The fulltrust component crashed while restarting as administrator, curious if you can repeat it.

**Comment by Josh-65** [comment] 2022-05-15 14:53
Tried copying into System32 folder again got the same admin request, a failed copy opration and now can't add anything like before. Sheild Icon is there. Tried on Windows 11 and 2.2.8.0 this time.
[debug_fulltrust.log](https://github.com/files-community/Files/files/8695221/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8695222/debug.log)

**Comment by gave92** [comment] 2022-05-15 16:58
Great, different error this time 😅

**Comment by gave92** [comment] 2022-05-15 17:02
Unrelated but: did you recently get a crash trying to create a new Library from the sidebar?

**Comment by Josh-65** [comment] 2022-05-15 17:03
yep though there was already an issue for it

**Comment by gave92** [comment] 2022-05-15 17:04
There is not, but the issue is already fixed on main. I wanted to make sure it was the same thing.

**Comment by yaichenbaum** [comment] 2022-05-15 18:04
@Josh-65 can you try reinstalling the preview?

**Comment by Josh-65** [comment] 2022-05-15 18:15
Seem to work now with 2.2.9.0

**Closed** 2022-05-15 18:18 UTC
Labels: bug, triage approved
