### ISSUE TITLE
Drive widget: Caption trimmed

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#2720] opened 2020-12-27 04:16 UTC
**Describe the bug**
Caption for a drive widget item is not displayed correctly and half the line is trimmed in some languages

**To Reproduce**
1. Go to Files
2. See error

**Expected behavior**
Text should be fully wrapped

**Screenshots**
![திரைப்பிடிப்பு (210)_LI](https://user-images.githubusercontent.com/45227503/103163779-9fb0fc00-4828-11eb-8903-823abae45546.jpg)

**Desktop (please complete the following information):**
 - OS Version: 20H2 Pro
 - App version: 0.23.1.0

**Comment by yaichenbaum** [comment] 2020-12-27 14:01
@Jaiganeshkumaran I can't reproduce this issue with the latest from `master`, can you check if it's only an issue with some localizations?

**Comment by yaichenbaum** [comment] 2020-12-30 04:42
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._

**Closed by yaichenbaum** 2020-12-30 04:42 UTC
Labels: bug, more-info, triage approved, widget
