### ISSUE TITLE
Seletected Items Should Show More Distinctions

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#5293] opened 2021-06-21 09:02 UTC
**Is your feature request related to a problem?**
A clear description of what the problem is.

> Selecting folder or/and files should be more distinctive, in light mode, grey shades almost doesn't have contrast background ​

> ![image](https://user-images.githubusercontent.com/58063311/122737123-ee58c380-d2aa-11eb-8ba0-262b6b22546d.png)

**Describe the solution**
A clear description of what you want.

> Using Windows accent color would be a good solution similar to native file manager
> ![image](https://user-images.githubusercontent.com/58063311/122735850-9b324100-d2a9-11eb-9ccb-cbb9f1f3e3dc.png)

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish better UX | Could |

**System Information**
​- OS Version: [Windows 10 21H1 19043.1052]
​- App version: [1.5.46]

**Comment by Rasmagoric** [comment] 2021-06-21 19:42
Yes, a border would be great.

**Comment by BanCrash** [comment] 2021-06-22 12:27
I think this is a bug. In last release it's fine. I think it's showing the dark colour instead the light colour.

This is the colour for selected items in the last release:

![image](https://user-images.githubusercontent.com/11770760/122923150-aa29f980-d364-11eb-9ce2-4d9fb1ed14ff.png)

**Comment by BanCrash** [comment] 2021-06-23 16:52
I try to find the cause of this bug, but I didn't have luck.

However I found that column view is working as expected on the Column View:

![image](https://user-images.githubusercontent.com/11770760/123137272-16375b00-d454-11eb-9b17-43ea13ec2b46.png)

All the others view are facing this issue.

**Comment by BanCrash** [comment] 2021-06-26 11:18
They talked about this on #4643 , so it's something they are aware off.

**Comment by yaichenbaum** [comment] 2021-08-17 19:58
This issue should be resolved with #5844.

**Closed** 2021-08-17 19:58 UTC
Labels: enhancement, triage approved
