### ISSUE TITLE
Move Folder from Desktop to a OneDrive crashes Files

### ISSUE THREAD

**Issue by spssoftie** [files-community/Files#11624] opened 2023-03-09 03:36 UTC
### Description

Moving a folder from the Desktop to a OneDrive crashes Files. It's not happen every time I move one Folder to OneDrive.

### Steps To Reproduce

Pick one folder from Desktop with mouse, drag and drop to OneDrive root.

### Steps to fix

Fix crash that occurs when moving Folder from Desktop to a OneDrive.

### Files Version

2.4.40.0

### Windows Version

Windows 10 Enterprise 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/10927417/debug.log)

**Comment by hishitetsu** [comment] 2023-03-09 03:53
I found the cause of the error. I'll fix it later.

**Comment by hishitetsu** [comment] 2023-03-09 04:06
This can occur when trying to move items from the desktop to Files, not just to OneDrive.
This bug should be fixed extremely urgently as the items could be lost forever.

**Closed** 2023-03-09 04:32 UTC
Labels: bug
