### ISSUE TITLE
Problem with copying and pasting

### ISSUE THREAD

**Issue by Obianuju7** [files-community/Files#3128] opened 2021-01-18 02:16 UTC
I believe that Files is an amazing application. However, it is quite different, in some ways, better than File Explorer. A major problem with the application is that it is so hard to copy and paste between applications. Please fix this issue. Thank you.

**Comment by ellipticview** [comment] 2021-03-14 07:43
I would expect Ctrl-Drag to copy a file, rather than move the file. Because that is the way the Windows Explorer behaves.

**Comment by yaichenbaum** [comment] 2021-04-27 17:46
@Obianuju7 Is this still an issue in v1.5?

**Comment by Obianuju7** [comment] 2021-05-02 00:56
I don't know, I changed back to File Explorer.

**Comment by yaichenbaum** [comment] 2021-05-02 01:35
@Obianuju7 Thanks for the update, I'll close this issue since we can't reproduce it anymore.

**Closed by yaichenbaum** 2021-05-02 01:35 UTC
Labels: bug, more-info
