### ISSUE TITLE
Onedrive folder not present on the sidebar

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [files-community/Files#3659] opened 2021-02-20 23:00 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by AisinGioroKiIoi** [comment] 2021-02-20 23:00
希望能在侧边栏显示OneDrive。望采纳，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by hez2010** [comment] 2021-02-21 11:38
~OneDrive directories are already being displayed in side bar.~
Can repro it.
@gave92 @yair100 Seems that there's a regression since v1.3 which causes OneDrive directories not being displayed.

**Comment by gave92** [comment] 2021-02-21 11:46
@hez2010 I can't repro this exactly. It just takes several seconds for the Onedrive (personal) folder to be displayed on the sidebar

**Comment by AisinGioroKiIoi** [comment] 2021-02-21 11:53
您好。
侧边栏只有iCloud，没有OneDrive

[cid:image001.png@01D7088B.431F7390]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Steve<mailto:notifications@github.com>
发送时间: 2021年2月21日 19:38
收件人: files-community/Files<mailto:Files@noreply.github.com>
抄送: 爱新觉罗启钰<mailto:kiiui@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [files-community/Files] 使用反馈 (#3659)


OneDrive directories are already being displayed in side bar.

―

**Comment by hez2010** [comment] 2021-02-21 11:56
> @hez2010 I can't repro this exactly. For me it "just" takes several seconds for the Onedrive (personal) folder to be displayed on the sidebar

I waited for several minutes but still nothing showing up.
Note: I have multiple OneDrive folders.

**Comment by gave92** [comment] 2021-02-21 12:16
@AndyMDoyle could you check?

**Comment by boscorelly** [comment] 2021-02-22 08:47
> ~OneDrive directories are already being displayed in side bar.~
> Can repro it.
> @gave92 @yair100 Seems that there's a regression since v1.3 which causes OneDrive directories not being displayed.

no problem in v1.3 with onedrive.
![image](https://user-images.githubusercontent.com/3873787/108684208-e5213b00-74f2-11eb-8179-42095cfaa501.png)

as he said, it may be an icloud drive problem.

**Comment by AisinGioroKiIoi** [comment] 2021-02-22 08:52
您好，22日我在两台新设备上安装该应用，已正常显示。21日那一台不在身边，我没法确认。

**Comment by AndyMDoyle** [comment] 2021-02-22 08:55
OneDrive and SharePoint are okay here.
With the right empty iCloudDrive folder in place iCloud appears in the sidebar as expected as well.

**Comment by boscorelly** [comment] 2021-02-22 08:56
> 您好，22日我在两台新设备上安装该应用，已正常显示。21日那一台不在身边，我没法确认。

please write in english...

**Comment by hez2010** [comment] 2021-02-22 09:15
That's weird...
I'll investigate on my machine later.

![image](https://user-images.githubusercontent.com/14960345/108687269-79aa8e00-7531-11eb-8524-3170e22dba0e.png)

**Comment by boscorelly** [comment] 2021-02-22 09:17
which version of windows 10 ?

**Comment by hez2010** [comment] 2021-02-22 09:18
dev insider 21318

**Comment by boscorelly** [comment] 2021-02-22 09:47
i am in 20h2 / 19042.804 in insider. I am currently upgrading to 21h1. Maybe the problem is only in the most recent insider branch

**Comment by yaichenbaum** [comment] 2021-02-22 16:26
@gave92 This should be resolved in `main`, right?

**Comment by gave92** [comment] 2021-02-22 21:08
@yair100 not sure, I haven't done anything for this as I can't reproduce this issue.

**Comment by boscorelly** [comment] 2021-02-23 11:31
problem not present in 21h1 19043.844

**Comment by yaichenbaum** [comment] 2021-02-24 04:41
@gave92 I can reproduce this on my device, it seems like the FullTrustProcess isn't working at all.

**Comment by gave92** [comment] 2021-02-24 12:37
@yair100 great news -.- I'll need some help to solve this as I can't reproduce it at all.

**Comment by hez2010** [comment] 2021-02-24 13:05
On my device FullTrustProcess just being terminated after launch

**Comment by gave92** [comment] 2021-02-24 13:32
Thanks @hez2010 are you getting anything in the debug_fulltrust.txt? Does it crash also in Debug? Could you debug with VS and see what's the issue?

**Comment by AisinGioroKiIoi** [comment] 2021-02-24 13:39
> > 您好，22日我在两台新设备上安装该应用，已正常显示。21日那一台不在身边，我没法确认。
> 
> 请用英语写字。。。

很抱歉，能力有限，也不懂什么英语，就浏览器翻译的各位的文字，由于是机器翻译，有些语句也看不懂表达的啥。ᠪᠠᠨᡳᡥᠠ

**Comment by hez2010** [comment] 2021-02-24 13:52
> Thanks @hez2010 are you getting anything in the debug_fulltrust.txt? Does it crash also in Debug? Could you debug with VS and see what's the issue?

It turns out that FullTrustProcess does nothing after launch, even no logs produced in debug_fulltrust.txt.

**Comment by hez2010** [comment] 2021-02-24 14:02
It seems that FullTrustProcess can start and initialize connection with no issue, but there're no messages being received at all.

**Comment by yaichenbaum** [comment] 2021-03-07 05:44
@hez2010 After additional testing with @gave92, we have confirmed that this is an issue with the recent Windows Insider builds.

**Comment by hez2010** [comment] 2021-03-07 05:47
@yair100 Maybe we should report it via Feedback app to Microsoft.
If they didn't recognize the problem before shipping the next stable version of Windows, it will be frustrating.

**Comment by pratyakshm** [comment] 2021-03-09 07:41
can confirm that the issue persists, 
Windows: Insider Dev 21327.1000
![image](https://user-images.githubusercontent.com/54220235/110435329-e64c8d80-80d8-11eb-8ff3-06f59985ca0c.png)

**Comment by pratyakshm** [comment] 2021-03-09 07:46
Heads up: I have reported this bug in Feedback Hub, please upvote: https://aka.ms/AAbgec7

**Comment by yaichenbaum** [comment] 2021-03-15 23:28
This issue should be resolved in `main`.

**Closed by yaichenbaum** 2021-03-15 23:28 UTC
Labels: bug, triage approved

**Comment by mbuschagen** [comment] 2021-03-23 17:29
I just updated my OS to: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎11/‎2020
OS build	19042.870
Experience	Windows Feature Experience Pack 120.2212.551.0

I also updated the Files App to v1.5, and now my Work OneDrive is showing up in the Sidebar as it should. Thanks for getting this bug fixed!
![Files3-23-21](https://user-images.githubusercontent.com/80843256/112190834-9be00c00-8bc2-11eb-93f1-ff03cb1ad848.png)
