### ISSUE TITLE
Re-order pinned sidebar folders by dragging

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2779] opened 2020-12-30 23:04 UTC
**Is your feature request related to a problem? Please describe.**
I like to keep my files nice and organized, so I pin folders I use frequently to the sidebar. But when I want to pin a new folder, I wish I could choose _where_ on the sidebar I wanted it.

**Describe the solution you'd like**
I think it would be nice if you could drag the folders on the sidebar to re-order them.

**Describe alternatives you've considered**
The only other option for me was to painstakingly unpin **all** of the folders, and then memorize and re-pin them in the order I like.

**Additional context**
I am on a desktop; the app version is 0.23.1.0

**Comment by XPoppyX** [comment] 2020-12-30 23:10
Duplicate of #1069

**Closed** 2020-12-30 23:39 UTC
Labels: feature_request
