### ISSUE TITLE
Accessing the file system of an installed WSL distribution

### ISSUE THREAD

**Issue by NikolaDjokic271** [files-community/Files#2544] opened 2020-12-05 20:03 UTC
I use Windows Subsystem for Linux a lot for several personal projects of mine and have been able to access the linux file system from the default windows explorer. However, on this Files app, in the usual place where I expect the linux files, I just see a hard disk image (.vhdx) file. Opening it results in an error (screenshot included). I suppose the app doesn't know how to read or write to linux's ext4 file system so the support for that is the feature I'd like to request.

![Screenshot 2020-12-05 205111](https://user-images.githubusercontent.com/75543742/101262029-c5704700-373b-11eb-92b9-a09b9fe0e489.png)

![Screenshot 2020-12-05 205355](https://user-images.githubusercontent.com/75543742/101262058-05cfc500-373c-11eb-9a12-ab500e697a40.png)

Ideally, the solution would be something like the way the default file explorer handles the linux file system, where it operates seamlessly and the end user doesn't really notice that they are inside a linux space. Though, something like a subtle indicator, like a "[Linux]" string being added on the tab's name or something like that would be really nice in my opinion. Maybe an option in the app's settings to turn it on and off would be the best way to go about that.

I don't mind using a terminal to access WSL files so this isn't super critical to implement. It'd just be really nice.

Currently running version 0.21.1.0 on the Windows 10 Pro 20H2

**Comment by gave92** [comment] 2020-12-05 22:56
Hi @NikolaDjokic271 does typing "\\wsl$" in the Files address bar work?

**Comment by NikolaDjokic271** [comment] 2020-12-06 11:13
@gave92 It does work. I didn't even know WSL file system could be accessed like that. The files take a tiniest bit longer to load but it does work as expected. I guess this is just me not knowing enough about WSL.

Although, having access to the WSL distro's file system via a shortcut in the side bar in the same way OneDrive can be accessed or on the home page might have prevented this.

**Comment by gave92** [comment] 2020-12-06 13:46
Glad it works, closing this as a duplicate of #295

**Closed by gave92** 2020-12-06 13:47 UTC
Labels: feature_request, more-info
