### ISSUE TITLE
The "WSL" section is not showing

### ISSUE THREAD

**Issue by DiegoMagdaleno** [files-community/Files#5486] opened 2021-07-23 00:01 UTC
**Explain the bug**
The WSL section on the sidebar, is not showing, meaning we can't access WSL folders.

This also includes placing the absolute address for WSL folders in the adress bar, for example: `\\wsl.localhost\openSUSE-Tumbleweed` shows: 
![image](https://user-images.githubusercontent.com/38844659/126723202-e34a4084-2226-45a0-a9eb-683367fcc217.png)

**To reproduce**
1. Install a WSL Distro 
2. Try to browse it in files 

**Expected behaviour**
It should show the WSL folders and allow accessing them and manipulating them 

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6865985/debug.txt)
[debug.log](https://github.com/files-community/Files/files/6865986/debug.log)

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
- OS Version: Windows Version 21H2 OS Build 22000.71
-  App Version: 1.9

**Comment by gave92** [comment] 2021-07-23 00:11
It only works of you open WSL before opening Files. Could you confirm?

**Comment by DiegoMagdaleno** [comment] 2021-07-23 00:43
What do you mean opening wsl?

**Comment by gave92** [comment] 2021-07-23 05:08
Opening "bash" for example

**Comment by DiegoMagdaleno** [comment] 2021-07-23 14:21
Um, no, in fact I left them running while writting this issue, and they still dont show up.

**Comment by DiegoMagdaleno** [comment] 2021-07-23 14:22
![image](https://user-images.githubusercontent.com/38844659/126796023-6550c1ed-428d-47a4-8c07-44e38f94e521.png)
Here is an example, I opened WSL terminal first

**Comment by gave92** [comment] 2021-07-23 16:14
What do you see if you navigate to this folder? ""\\wsl$\"

**Comment by DiegoMagdaleno** [comment] 2021-07-23 16:17
I see this: 
![image](https://user-images.githubusercontent.com/38844659/126811644-96a06508-a7bb-46b7-a90b-5a829fc4ea1d.png)

**Comment by gave92** [comment] 2021-07-23 16:24
And is it the same from explorer?

**Comment by DiegoMagdaleno** [comment] 2021-07-23 21:47
Yeah it works properly on explorer.exe it just doesn't work in files

**Comment by gave92** [comment] 2021-07-23 21:49
In explorer that folder contains a subfolder named like your running distribution right? If you open that subfolder, does it show the Linux files?

**Comment by gave92** [comment] 2021-07-23 21:50
Also this setting under Files Settings > Sidebar is enabled, right? =)
![image](https://user-images.githubusercontent.com/9673091/126844851-079261c9-191c-4ab2-a47b-2e608c885bfc.png)

**Comment by DiegoMagdaleno** [comment] 2021-07-23 21:50
Thats right: 
![image](https://user-images.githubusercontent.com/38844659/126844881-dc038dae-8c33-48ca-ae32-272905e3038e.png)

And thats right too: 
![image](https://user-images.githubusercontent.com/38844659/126844902-80c82fdc-2ca5-4570-8752-c6f653e9ae73.png)

**Comment by gave92** [comment] 2021-07-25 10:42
Wait, in the explorer's screenshot you clicked on the Linux sidebar entry right?
- What is the actual path explorer navigates too when you click that entry?
- What happens if you type in explorer address bar: `\\wsl$\`?

Thanks for the help

**Comment by DiegoMagdaleno** [comment] 2021-07-25 16:19
Okay so if I click that entry the path the explorer gives is: `wsl.localhost\Arch`

While, if I input \\wsl$\, it the Network section on the explorer sidebar gets selected 
![image](https://user-images.githubusercontent.com/38844659/126906040-2881c30d-b702-4f39-b060-225d4b223c03.png)

**Comment by gulshanmudgal** [comment] 2021-08-07 00:32
I'm also facing this same issue.
Windows 11 OS build 22000.120.

In the first preview, it was working.

**Comment by euamotubaina** [comment] 2021-08-19 16:55
same here

**Comment by yaichenbaum** [comment] 2021-09-06 21:09
I can reproduce this issue as well.

**Comment by myfix16** [comment] 2021-11-15 13:25
Same issue on:
Windows 11 Pro 22000.346
Files 2.0.34.0

**Comment by yaichenbaum** [comment] 2021-11-15 14:22
@myfix16 I was able to workaround the issue by reinstalling Windows, I'm not saying to do the same but perhaps reinstalling WSL will do the same.

**Comment by gave92** [comment] 2021-11-15 19:03
On Discord it was also reported that the problem is fixed on newer windows 11 builds.

**Closed** 2021-11-15 19:04 UTC
Labels: bug, triage approved

**Comment by ferrazpedro** [comment] 2022-06-01 22:08
@yair100 just reinstalled the newest version of Files here (2.3) and I'm having this same bug with my Windows 11 up to date.
Edit: I have reinstalled WSL and the distro I use to no avail, this section doesn't appear in Files, and when I try to copy the adress to it, I get the same error:
![image](https://user-images.githubusercontent.com/37643357/171512803-7acd346c-1db0-431e-b2bb-18bdde6456c0.png)

**Comment by yaichenbaum** [comment] 2022-06-01 22:57
It requires a clean install of Windows for some reason.

**Comment by ferrazpedro** [comment] 2022-06-01 23:00
Sorry if I didn't understand right, but do you mean a clean install of Windows 11? Because I already did it last week...

**Comment by yaichenbaum** [comment] 2022-06-01 23:25
Which distro?
