### ISSUE TITLE
Select current open pages as launch pages on startup.

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#3696] opened 2021-02-23 10:53 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no way to select the home page as a launch page alongside other ones in the "On startup" settings page.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/58466626/108833530-3f8eca00-75cd-11eb-9cd2-601fbbb0b1f7.png)
As selecting "add" will open the regular file explorer to select a folder to start at, thus eliminating the option to select Files's "Home Page", I would suggest adding a "Use Current Pages" button (naming can be different ofc) to also eliminate the need to navigate the file explorer again.

**Comment by nvi9** [comment] 2021-02-23 15:25
Would "Add current pages" be better (appending currently opened pages) or "Use current pages", where the previously added pages in the list are overwritten?

**Comment by crashmit** [comment] 2021-02-23 15:41
Yes, appending the current pages looks good to me! In any case, you wouldn't overwrite stuff by accident. I like that better.

**Comment by yaichenbaum** [comment] 2021-02-23 16:25
This feature is already implemented with "Continue where you left off", can you clarify if this is what you are looking for?

**Comment by crashmit** [comment] 2021-02-23 16:29
No, I think you understood me wrong. I thought of a simpler way to select pages for the "Open a specific page or pages" option, that also included Files's "Home" page, that currently can't be selected there right now.

**Comment by yaichenbaum** [comment] 2021-02-23 16:41
@crashmit So you are looking for a way to set the home page as one of the launch pages?

**Comment by crashmit** [comment] 2021-02-23 16:42
Yes that's the main goal.

**Comment by yaichenbaum** [comment] 2021-02-23 16:47
@crashmit Thanks for clarifying, what I had in mind to solve this was to have a text box where users could enter the path (entering "home" would work as well). There would also be a browse button to open the file picker for easier navigation. What are your thoughts on this solution?

**Comment by nvi9** [comment] 2021-02-23 16:51
Also dual panes make it a bit more complicated 🤔 
What if we just have an "Add home" button, or a context menu on "Add button" with the sidebar items listed?

**Comment by yaichenbaum** [comment] 2021-02-23 16:55
@nvi9 I don't know if we want to add UI to the settings page to adjust this setting for the dual pane feature. We should definitely support command line arguments for this, and we already support this with the continue where you left off feature. Regarding a button for the home page, it would work, but it seems like a lazy solution.

**Comment by crashmit** [comment] 2021-02-23 17:06
> @crashmit Thanks for clarifying, what I had in mind to solve this was to have a text box where users could enter the path (entering "home" would work as well). There would also be a browse button to open the file picker for easier navigation. What are your thoughts on this solution?

That's where the other part of my suggestion comes in. If you had a "Add current windows" button, you could just add the ones you currently have opened. That way there is no need to enter any file paths or hassle with the win32 explorer. The question here is, if people have the journey "Those windows i have opened right now are really useful / I open them quite a lot, let's add them so my startup pages" . I can totally see if this is too much of an edge case, but perhaps that's something people would use. 

Suggestion here: What do you think of adding a polling bot with a dedicated channel to the discord server? I think the "help wanted" or "discussion" tags don't reach as many people as a Discord poll might. In this case, we could post a poll to get the communities opinion? I think approaching this proactively would get more response, than a github issue does. But again, if you think that would be too much effort, I understand that.

**Comment by yaichenbaum** [comment] 2021-02-23 17:11
@crashmit We can definitely do a poll once we have options to choose between, I think we should continue discussing them a bit to have a polished idea to present when we ask users for their preference. The reason I hesitate to add a button to add the current tabs is because the settings UI shouldn't have access to the open tabs. It's a disconnected UI and I would prefer if it stayed that way.

**Comment by nvi9** [comment] 2021-02-23 17:14
> or a context menu on "Add" button with the sidebar items listed?

Actually I have made some trials with this as well:

![image](https://user-images.githubusercontent.com/42123156/108880732-daee6200-7602-11eb-8ace-617b2f4587db.png)

This way it would be a bit hidden feature, but maybe a bit different approach would help to solve the add home issue

**Comment by yaichenbaum** [comment] 2021-02-23 17:25
@nvi9 A menu like that seems like the best idea so far, what if there was an option to browse as well as a submenu to view recent locations?

**Comment by crashmit** [comment] 2021-02-23 18:17
Sounds good! So "Browse" and "Recent Location"?

**Comment by nvi9** [comment] 2021-02-23 21:03
I've made this progress so far:

![image](https://user-images.githubusercontent.com/42123156/108907028-deddac80-7621-11eb-9e44-82263eccf718.png)

Clicking on "Add" button opens a MenuFlyout and you can either pick a directory with the usual dialog or select an item from the sidebar or from the recently opened directories.

However it has some design issues because items of MenuFlyout control are not bindable for some reason by design. I need a bit more time for investigating a fully MVVM solution in case you don't have suggestions for a better control for this purpose.

**Comment by yaichenbaum** [comment] 2021-02-23 23:58
@nvi9 I am not sure about the sidebar menu item, but everything else there is looking good. About MVVM, is there an ItemsSource for the MenuFlyout?

**Comment by nvi9** [comment] 2021-02-24 05:11
@yair100 there is [no ItemsSource](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/75e116f8-386b-49d7-9370-fd634af0fc13/why-isnt-there-an-itemsource-property-on-the-menuflyout?forum=w81prevwCsharp), so I've tried to create an attached property, but for the first trial without datatemplates. I'll try to work on that a bit more today or tomorrow and try out some things.

I've added the sidebar item because currently it's the only way I can have Home item, browse opens the win32 dialog and the recents submenu contains directory entries of `StorageApplicationPermissions.MostRecentlyUsedList` in this initial implementation.

**Comment by yaichenbaum** [comment] 2021-02-24 15:41
@nvi9 What about adding the home item to the recent items menu?

**Comment by nvi9** [comment] 2021-02-24 16:32
> @nvi9 A menu like that seems like the best idea so far, what if there was an option to browse as well as a submenu to view recent locations?

Always on the top right?

![image](https://user-images.githubusercontent.com/42123156/109032706-36cdef00-76c6-11eb-824d-d9b390f3b634.png)

**Comment by nvi9** [comment] 2021-02-24 16:54
Btw [here is](https://github.com/files-community/Files/compare/main...nvi9:startup_pages_from_sidebar) what I've done so far, @yair100 if you think it is worth merging, I can create a PR

**Comment by yaichenbaum** [comment] 2021-02-24 17:04
> Always on the top, right?

Looks good, can you create a PR?

**Comment by yaichenbaum** [comment] 2021-02-26 16:01
@crashmit This issue should be resolved with #3715.

**Closed** 2021-02-26 16:23 UTC
Labels: Implemented, enhancement
