### ISSUE TITLE
Dropping a file from Your Phone app crashes Files UWP

### ISSUE THREAD

**Issue by JavkhlanK** [files-community/Files#2160] opened 2020-10-27 18:07 UTC
**Describe the bug**
Trying to drop a file (I tried a video and a photo) from your phone's mirrored screen on the Your Phone app on Files UWP crashes the app (A box with the No-Icon appears for a while and then a notification pops up that says Files crashed)

**To Reproduce**
1. Mirror your phone's screen on the Your Phone app (Samsung-device required) and open the My Files app.
2. Select a file and long click on it, you should be able to move a small square preview of it.
3. Hover your mouse pointer over the Files UWP app (don't release the mouse)

**Expected behavior**
A preview or just text saying the name of the file.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20241.1005]
 - App version: [v0.18.0.0]

**Additional context**
None

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5447204/debug.txt)

**Comment by gave92** [comment] 2020-10-27 20:12
Thanks for reporting this.
Reading [around](https://docs.microsoft.com/en-us/answers/questions/38974/how-to-drag-and-drop-image-from-wpf-application-to.html) it appears to be a known uwp limitation. UWP can only receive files if they point to physical location on disk.
I'm not sure if we'll be able to solve this :(
(We can for sure handle the error to avoid the crash and show an error message instead)

**Comment by gave92** [comment] 2020-10-27 22:02
Duplicate of #2003

**Closed by gave92** 2020-10-27 22:02 UTC
Labels: bug, triage approved
