### ISSUE TITLE
Crash when opening a folder

### ISSUE THREAD

**Issue by Lost-n-thought** [files-community/Files#3504] opened 2021-02-09 12:03 UTC
**Describe the bug**
Crash when opening a folder inside a drive

**To Reproduce**
1. Go to any drive 
2. click on any folder in it

**Expected behavior**
Folder should open.

**Screenshots**
https://user-images.githubusercontent.com/48401945/107360877-8b853d80-6afc-11eb-9cba-7cdb565afd79.mp4

**Desktop (please complete the following information):**
 - OS Version: 19042.746
 - App version: [v1.2.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Do not have any more context. Happens on app restart and also system restart

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5951183/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5951184/debug.txt)
it happened last at 17:27 time

**Comment by yaichenbaum** [comment] 2021-02-09 15:46
@gave92 Any chance this bug is already fixed in `main`?

**Comment by gave92** [comment] 2021-02-09 17:24
@yair100 no, I have a possible fix for it in the latest commit of #3295. It should be made into it's own PR.
Are you able to reproduce it? If so, can you verify that with #3295 the issue is fixed?

**Comment by gave92** [comment] 2021-02-09 17:30
@Lost-n-thought could you check whether the issue is present if you change the folder layout mode to GridView?

**Comment by Lost-n-thought** [comment] 2021-02-09 17:46
@gave92 it is not crashing when in tiles or grid view. it is only crashing when in details view

**Comment by yaichenbaum** [comment] 2021-02-09 21:35
@Lost-n-thought This issue should be fixed with #3511.

**Closed** 2021-02-09 21:35 UTC
Labels: bug, fixed
