### ISSUE TITLE
Bug: Issue with file preview in column layout

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12227] opened 2023-04-28 14:30 UTC
### Description

When in column view mode with the preview pane enabled, clicking on the first file displays its characteristics, folder logo, etc. However, when I click on the next file or folder, nothing appears and I have to click on another folder or in the blank space for the preview to display properly again.

### Steps To Reproduce

Open "Files"
Choose a test category, such as "Documents"
Set the view to "Columns"
Enable the preview pane
Click on a folder, and then on a second one

### Requirements

1. Fix the issue with the preview not displaying correctly when switching from one file/folder to another in column view mode.
2. Ensure that the preview displays smoothly and successfully for each selected file/folder without any interruption.

### Files Version

Version : 2.4.70.0

### Windows Version

Windows 11 22H2 22621.1635

### Log file

No need.

**Comment by Josh65-2201** [comment] 2023-04-28 14:31
Thanks for the report, I was able to reproduce this.

**Comment by ZLAllen** [comment] 2023-05-03 03:53
@Lukiluc29 Just to make sure I am reproducing the issue correctly based on your description:

1) Open "Files"
2) Select "Documents"
3) Change View Layout to "Columns"
4) Enable Preview Panel
5) Click any items in the first level, the detail shows up correctly in the preview.
6) Select a folder and click on an item at the second level, the preview is not rendered. Select a different item or lose focus of the current selection and reselect the item will cause it to render correctly in the preview.

Does this match the issue you observed?

On a separated note, if you are at a lower-level (e.g. subfolder) and you try to select any folder on the upper level, the preview is also not rendered unless you select a different item or refocus the item. Is this the intended behavior?

**Comment by yaira2** [comment] 2023-05-07 14:50
This issue will be fixed in v2.5.

**Closed** 2023-05-07 14:49 UTC
Labels: bug
