### ISSUE TITLE
Bug: App crashes

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10271] opened 2022-10-21 18:41 UTC
### Description

Occurs once when I tried to toggle the "**Calculate Folder Sizes**" but I'm not sure because it didn't crash again after reproducing.

### Steps To Reproduce

Might not be these steps but for me, it happened this way:

1. Go to settings
2. Turn on Calculate Folder Sizes,

### Steps to fix

- Prevent app crash

### Files Version

2.3.51.0

### Windows Version

10.0.22623.870

### Relevant Assets/Logs

```log
2022-10-22 02:35:38.5439|ERROR|AppUnhandledException|An item with the same key has already been added. Key: C:\
	System.ArgumentException: An item with the same key has already been added. Key: C:\
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Files.Backend.Services.SizeProvider.DrivesSizeProvider.CreateProvider(String driveName)
   at Files.Backend.Services.SizeProvider.DrivesSizeProvider.UpdateAsync(String path, CancellationToken cancellationToken)
   at Files.App.ServicesImplementation.UserSizeProvider.UpdateAsync(String path, CancellationToken cancellationToken)
   at Files.App.Filesystem.StorageEnumerators.Win32StorageEnumerator.ListEntries(String path, IntPtr hFile, WIN32_FIND_DATA findData, NamedPipeAsAppServiceConnection connection, CancellationToken cancellationToken, Int32 countLimit, Func`2 intermediateAction, Dictionary`2 defaultIconPairs)
   at Files.App.ViewModels.ItemViewModel.<>c__DisplayClass155_1.<<EnumerateItemsFromStandardFolderAsync>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Files.App.ViewModels.ItemViewModel.EnumerateItemsFromStandardFolderAsync(String path, CancellationToken cancellationToken, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollection(String path, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollectionAsync(String path, String previousDir, Action postLoadCallback)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at WinRT.EventSource__EventHandler`1.EventState.<GetEventInvoke>b__1_0(Object obj, T e)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
 ```

**Comment by Josh-65** [comment] 2022-10-22 05:37
@cinqmilleans could this be from the recent drive's changes?

**Comment by cinqmilleans** [comment] 2022-10-22 09:28
@Josh-65 I cannot reproduce the issue. I will analyze your logs to try to understand.

**Comment by gave92** [comment] 2022-10-23 17:31
Might just be a concurrency issue. e.g replacing DriveSizeProvider's Dictionary with ConcurrentDictionary (or adding some locks) could fix this.

**Comment by yaichenbaum** [comment] 2022-11-01 05:51
Can anyone reproduce this?

**Comment by yaichenbaum** [comment] 2022-11-06 10:31
Closing for now, please let us know if it happens again.

**Closed by yaichenbaum** 2022-11-06 10:31 UTC
Labels: bug
