### ISSUE TITLE
Renaming files causes serious lag

### ISSUE THREAD

**Issue by ijac1** [files-community/Files#9794] opened 2022-08-22 14:14 UTC
### Description

Renaming a file causes serious lag and unresponsiveness.  I can't rename other files.  And some folder appear to have nothing in them even though I know there are files in there.  I have to shutdown and restart the app.

### Steps To Reproduce

1. Rename a file
2. Immediately try to rename another file
3. App is unresponsive
4. Wait 30 seconds or so for the app to become responsive again

### Expected behavior

Should be able to rename a file and see the result immediately without any lag in the app

### Files Version

2.3.7.0

### Windows Version

Windows 11

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9395090/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9395091/debug_fulltrust.log)

**Comment by ZaLiTHkA** [comment] 2022-08-24 05:45
I've also noticed a delay in both renaming and deleting files, but nowhere near as long as this... for me, the delay is only about 2 to 3 seconds.

running Win11 Pro `10.0.22000` on an Asus laptop with an i7-1065G7 and 16GB RAM.

**Comment by QuaintMako** [comment] 2022-09-16 13:18
Couldn't reproduce it Win11 Pro OS build `22000.978`, x64 with i7-1165G7 and 16 GB RAM.

There are exceptions in the logs though, not sure they are linked to the issue.

**Comment by yaichenbaum** [comment] 2022-10-13 17:16
This appears to be resolved in the preview build https://files.community/download/preview

**Closed** 2022-10-13 20:41 UTC
Labels: bug

**Comment by ZaLiTHkA** [comment] 2022-10-14 07:56
using "Files (Preview)" version `2.3.48.0`, I don't see any noticable delay with renaming files or folders anymore..

I do still get a _slight_ delay with "Files" version `2.3.12.0`, but even that seems to be quicker than the experience I was having on version `2.3.7.0`. not sure if that's related to any code changes or just the whims of my laptop though.

---

@yair100, are you perhaps tracking any issues relating to file _deletion_ specifically? I just ran a few "delete" tests with a 450Mb-odd `node_modules` folder that I would like to share with you.

I didn't find one from searching the issue list now, but there are a few hundred to look through.. and a great many of the ones I have seen have spelling errors.. which doesn't help with regards to GitHub text search. 🤔

**Comment by yaichenbaum** [comment] 2022-10-14 14:41
There are a couple issues regarding deleting items, but I haven't been able to reproduce any. If you are able to put together exact steps to reproduce them, it would be great if you can open another issue.

**Comment by ZaLiTHkA** [comment] 2022-10-14 17:06
> There are a couple issues regarding deleting items, but I haven't been able to reproduce any. If you are able to put together exact steps to reproduce them, it would be great if you can open another issue.

I can't say I've found reproducible issues as such, `2.3.48.0` was spontaneous crashing earlier today, but I haven't dug into that one properly yet.. with that said, I _do_ enjoy pushing every button I find in every way possible, so I'll let you know if I do find anything useful. 👍🏼 

but, before I derail _this_ issue comment stream too badly.. I'm not finding any other issues with renaming files, but it would be best to get feedback from @ijac1 as well first.

**Comment by yaichenbaum** [comment] 2022-10-14 17:12
Keep the feedback coming!
