### ISSUE TITLE
Bug: Cannot open password-protected 7-Zip files

### ISSUE THREAD

**Issue by username-is-not** [files-community/Files#12105] opened 2023-04-17 18:01 UTC
### Description

Files version 2.4.62.0 cannot open (encrypted) 7-Zip files, but it registers itself as the default opener on install? 

GLHF

![tfLOL](https://user-images.githubusercontent.com/80984663/232569902-99db4658-5cd5-4a09-b6d1-69d7d8eaf555.png)

### Steps To Reproduce

1. Double-click on a password-encrypted 7-Zip file.

### Requirements

Fix crash that occurs when... double-clicking a password-encrypted 7-Zip file
Correct action happens... never

### Files Version

2.4.62.0

### Windows Version

Windows 10 Enterprise LTSC Version 19044.2846

### Log file

[debug.log](https://github.com/files-community/Files/files/11254011/debug.log)

**Comment by yaira2** [comment] 2023-04-17 18:02
Does it work to extract it?

**Comment by username-is-not** [comment] 2023-04-17 18:06
No, the right-click context menu has no such action. It can only "Show more options", and then send it to 7-Zip.

**Comment by yaira2** [comment] 2023-04-17 18:09
I meant when you right click the parent directory

**Comment by heftymouse** [comment] 2023-04-25 00:41
I tested this myself, and extracting the archive works as intended, but double-clicking it to browse does not prompt for the password and instead shows this error. It only seems to occur when the Encrypt File Names option is enabled (as is the case when creating archives from Files). There's some more strange behaviour when this is disabled which I'll detail in another issue.

**Comment by yaira2** [comment] 2023-04-25 14:58
@heftymouse thanks for checking, I added this to the project board.

**Comment by yaira2** [comment] 2023-07-09 16:41
@username-is-not this issue will be resolved in the upcoming v2.5.20 release.

**Closed** 2023-07-09 16:41 UTC
Labels: bug
