### ISSUE TITLE
app preview shows media playback controls

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4255] opened 2021-03-23 19:37 UTC
**Explain the bug**
as titled

**To reproduce**
hover mouse above the launched app icon

**Expected behavior**
no controls

**Logfile**
n/a

**Screenshots**
actual

![actual](https://user-images.githubusercontent.com/39104740/112207661-74bc2580-8c28-11eb-93bb-4e81fc31b7f2.png)

expected

![expected](https://user-images.githubusercontent.com/39104740/112207557-535b3980-8c28-11eb-9e31-f80095cb78ce.png)

**System Information**
 - OS Version:  Windows 10 2004 19041.867
 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment] 2021-03-23 20:50
Duplicate of #3827.

**Closed by yaichenbaum** 2021-03-23 20:50 UTC
Labels: bug
