### ISSUE TITLE
Files repeatedly crashing during attempts to view "Details" pane of "Properties" window if "View Hidden" === yes

### ISSUE THREAD

**Issue by killshot13** [files-community/Files#3674] opened 2021-02-22 08:17 UTC
>I acknowledge receipt of the submission disclaimers. ⬆
>@killshot13

---

**Describe the bug**

The Files application is repeatedly crashing when the user attempts to view the "Properties" window >> "Details" pane. The bug is contingent upon the following parameters: "View Hidden" checkbox is ticked -- AND -- Filetype is '.exe'.

The behavior is consistent regardless of whether the "Show Hidden Files & Folders" and/or "Hide protected operating system files (Recommended)" radio buttons are toggled on or off.

**To Reproduce**

1. Go to Files
2. Locate a file with the '.exe' filetype within the file system.
3. Right-click on the file, and select the Properties tab.
4. If not checked, tick the View Hidden checkbox on the General tab
5. Attempt to view the Details tab by clicking on the menu bar.
6. Files should encounter a fatal error and crash almost instantly.

**Expected behavior**

I expected the Properties view window to display the information under the Details tab just as it does for the General tab, to include any metadata or other information that would otherwise be hidden.

**Screenshots**

I'll raise you one narrated video re-creation.
![Full Video Walkthrough](https://user-images.githubusercontent.com/47695475/108679829-b2575280-74b2-11eb-907a-eba2ce57b4b4.mp4)

**Desktop (please complete the following information):**

 - OS Version: Microsoft Windows 10 Education Version 10.0.19043 | Build 19043
 - App version: 1.2.2.0
 [sys_build_specs.txt](https://github.com/files-community/Files/files/6020473/sys_build_specs.txt)

**Additional context**

Yes, the issue is recurring and consistent across a sampling of five unrelated '.exe' files.

**Logfile**

[debug.txt](https://github.com/files-community/Files/files/6020483/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6020484/debug_fulltrust.txt)

**Comment by boscorelly** [comment] 2021-02-22 09:46
hi,

i cannot reproduce it with v1.3. Maybe it is fixed in this version

**Comment by gave92** [comment] 2021-02-22 10:59
Yeah I confirm this has been fixed in 1.3.  Thanks for the report.

**Closed** 2021-02-22 10:58 UTC
Labels: bug

**Comment by killshot13** [comment] 2021-02-22 14:38
Thanks for the follow-up. I installed my build through the Microsoft Store because I didn't have time to build it myself. So I just right now got the message that a major update had pushed.

**Comment by boscorelly** [comment] 2021-02-22 21:14
What is your files version ?

**Comment by killshot13** [comment] 2021-02-24 08:46
@boscorelly Now it's 1.3.0.0. I have been using the Windows Store for updates and I had to check again two or three times before it showed up. Prior to updating, the version with the bug was 1.2.2.2.
