### ISSUE TITLE
Bug: Failing to eject mounted iso

### ISSUE THREAD

**Issue by chkarsten** [files-community/Files#10719] opened 2022-12-15 06:35 UTC
### What feature or improvement do you think would benefit Files?

Hi

I noticed that when mounting an .iso image, you cannot remove the iso image disc when clicking eject. There should be an option to remove the image mount disc permanently.

This is the only concern I have when working with iso images using files.

### Steps to repro

1. Right click iso to mount it
2. Right click the mounted drive in the sidebar and click eject
3. Observe that the drive isn't ejected

### Files Version

4.5.21

### Windows Version

Windows 11 22H2 22621.963

**Comment by carlosvsilva** [comment] 2023-02-25 16:51
I suggest this should merge with the complete bug report: #11466

**Comment by Josh-65** [comment] 2023-02-25 16:55
Your issue isn't relevant to this one

**Comment by yaira2** [comment] 2023-10-10 15:04
I can reproduce this issue in v2.5.29

**Comment by mkikets99** [comment] 2023-12-18 19:54
Hi. Still reproducable in version 3.0.15.0

**Comment by SerhiiHarashchenko** [comment] 2024-02-23 14:52
Hi, I tried to reproduce it, but I don't see a mount option when right click an .iso file.
![image](https://github.com/files-community/Files/assets/64438069/5548f0c9-8aad-4789-9c55-71f8858ecc5e)

**Comment by SerhiiHarashchenko** [comment] 2024-02-23 14:58
Sorry, I can't still see it. I use the latest version from the source code.
![image](https://github.com/files-community/Files/assets/64438069/07685fd4-8f02-476d-8804-a10fed69270b)

**Comment by 0x5bfa** [comment] 2024-02-26 04:26
@SerhiiHarashchenko Ejecc option is not available in that context flyout. After you maunted iso file, the maounted drive will be shown on the sidebar and Eject button will apear in the right side of the item.

**Comment by 0x5bfa** [comment] 2024-02-26 04:26
@SerhiiHarashchenko Ejecc option is not available in that context flyout. After you mounted iso file, the mounted drive will be shown on the sidebar and Eject button will apear in the right side of the item.

**Comment by 0x5bfa** [comment] 2024-02-26 05:12
I found that the flag IOCTL_STORAGE_EJECT_MEDIA we are using has been deprecated. Instead, should use CM_Request_Device_Eject.

**Comment by TcPirate1** [comment] 2024-05-19 21:41
Hi all!

I'm new to this repo but would like to give this a go, where should I look in the repo for this issue?

I'm also able to build the project and reproduce this issue.

**Comment by 0x5bfa** [comment] 2024-05-20 02:00
I guess this issue is too complex for new bee because this requires kernel mode win32 api, not user mode.

**Comment by 0x5bfa** [comment] 2024-05-20 02:04
But you can find the problem code in EjectAsync in RemovableDevice in Files.App.Data.Models.

**Comment by TcPirate1** [comment] 2024-05-20 21:18
I see, I did not realize it would be like that. I shall leave it in more experienced hands as I do not have experience with lower layer APIs.

Thanks for the response anyways!

**Comment by yaira2** [comment] 2024-09-03 01:58
This should be resolved in the next update.

**Closed** 2024-09-03 01:58 UTC
Labels: bug, area - file operations
