### ISSUE TITLE
Files app 3.7.0.0 crash Windows 11

### ISSUE THREAD

**Issue by Luke717** [files-community/Files#16161] opened 2024-09-09 06:08 UTC
### Description

Installed Files app from Windows Store. Exited, started again. Clicked on a folder link in toolbar, app crashed. Debug log attached plus report from Win11 Event Viewer.

### Steps To Reproduce

Unable to reproduce.

### Requirements

Identify cause of crash and then fix it.

### Files Version

3.7.0.0

### Windows Version

Windows 11 Pro Version	23H2 OS build	22631.4112 Windows Feature Experience Pack 1000.22700.1034.0

### Log File

[debug.log](https://github.com/user-attachments/files/16926044/debug.log)
[Win11 Event Viewer - Files Application.txt](https://github.com/user-attachments/files/16926040/Win11.Event.Viewer.-.Files.Application.txt)

**Comment by Luke717** [comment] 2024-09-09 06:11
Additional info from Event Viewer:

Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x666b0000
Faulting module name: Microsoft.UI.Input.dll, version: 10.0.26105.1006, time stamp: 0x6636f93c
Exception code: 0xc0000409
Fault offset: 0x00000000000c6572
Faulting process id: 0x0x7AD0
Faulting application start time: 0x0x1DB027BBAC15652
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.7.0.0_x64__et10x9a9vyk8t\Files.App\Files.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.214.1843.0_x64__8wekyb3d8bbwe\Microsoft.UI.Input.dll
Report Id: 7c7f8c95-2f06-4870-a36f-077e6207ee60
Faulting package full name: 49306atecsolution.FilesUWP_3.7.0.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

**Comment by Josh65-2201** [comment] 2024-09-09 06:12
Thanks for the report, there is no crash logged. Please says what you were doing before Files crashed

**Comment by Luke717** [comment] 2024-09-09 06:16
Well, it looked like a crash in that when I clicked on the folder link, the Files app windows literally vanished. No icon in the system tray, gone. I looked at Event Viewer and saw multiple entries describing a fault (it didn't say 'crash') mentioning Files app. Immediately before that click on a folder, I was in Settings customising the appearance and selecting a theme. Closed the Settings popup and clicked the folder I mentioned.

**Comment by Luke717** [comment] 2024-09-09 06:19
Clarity: "there no folders to click on in the toolbar" My bad. I mean the column on the left showing pinned items.

**Comment by 0x5bfa** [comment] 2024-09-09 07:07
The crash seems to be STATUS_STACK_BUFFER_OVERRUN and the error code originates from native API. Can this issue be reproducible constantly doing what you did (changing personalization settings and click a folder immediately afterwards)?

**Comment by yaira2** [comment] 2024-09-09 14:15
@Luke717 in the setting file, there should be a value for `UserId`. This is random value that we generate and can be used to locate crashes in Sentry. Can you send the value here?

**Comment by Luke717** [comment] 2024-09-09 15:08
@yaira2 I don't see that value in either the user_settings .json or .db files. Where should it be?

**Comment by Luke717** [comment] 2024-09-09 15:24
@yaira2 also, I'm seeing this error in a number of error reports in Event Viewer along with specific error reports mentioning Files: "Google Drive registry key for key name 'Software\Google\DriveFS' not found." Shows source as .NET Runtime.

**Comment by yaira2** [comment] 2024-09-09 15:32
It should be under `user_settings .json`
![image](https://github.com/user-attachments/assets/5694460b-d344-43fc-89ab-2510c3f3e1f3)

**Comment by Luke717** [comment] 2024-09-09 15:48
I've searched the user_settings.json file line by line, and that value is not listed! Would you like me to share the actual file?

**Comment by yaira2** [comment] 2024-09-09 15:49
How are you opening the setting file?

**Comment by Luke717** [comment] 2024-09-09 15:56
Yes, it shows the file location as \AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\user_settings.json

**Comment by yaira2** [comment] 2024-09-09 16:00
Can you close Files, delete the settings file and restart the app?

**Comment by Luke717** [comment] 2024-09-09 16:21
Well, this is weird. I went to the file location in Files, clicked once on the settings file to make it show in preview, adjusted width of panes - and got this .NET 'unhandled exception' error (screenshot).
![filesapp-unhandledexception-2024-09-09_17-16-15](https://github.com/user-attachments/assets/b05a17fc-bf13-41f0-8a3b-ccce3bcd8309)

**Comment by yaira2** [comment] 2024-09-09 16:30
That's very strange, can you try downloading the sideload version from https://files.community/download and check if the value is there?

**Comment by Luke717** [comment] 2024-09-09 16:46
I uninstalled the current install, and installed Files again from the file I downloaded at that link. Checked the user_settings file - and no UserId value shown.

I noticed that the new install has all my settings, file history, intact. I wasn't expecting that - I imagined I'd have to start over with user settings. Is there another settings file somewhere that wasn't removed when I uninstalled the original Files app?

Also noticed that .NET errors mentioning Files still occur.

**Comment by yaira2** [comment] 2024-09-09 17:01
I should have just looked at the log you uploaded from event viewer as it clearly states the issue 😂. The good news is this issue is already fixed in our preview version and will be released to stable in a few days. Sorry for all the confusion! As for the value not showing in the settings file, I think it's because it's only create when we're able to catch an exception and report it to Sentry.

**Comment by yaira2** [comment] 2024-09-09 17:01
> @yaira2 also, I'm seeing this error in a number of error reports in Event Viewer along with specific error reports mentioning Files: "Google Drive registry key for key name 'Software\Google\DriveFS' not found." Shows source as .NET Runtime.

This can be ignored

**Closed** 2024-09-09 17:21 UTC
Labels: bug, needs - additional info, crash

**Comment by Luke717** [comment] 2024-09-09 18:27
> I should have just looked at the log you uploaded from event viewer as it clearly states the issue 😂. The good news is this issue is already fixed in our preview version and will be released to stable in a few days. Sorry for all the confusion! As for the value not showing in the settings file, I think it's because it's only create when we're able to catch an exception and report it to Sentry.

Glad to hear it! I've just installed the Preview version, and you might be pleased to know that Event Viewer reports no events at all with this version. Looking forward to seeing the release version soon.

**Comment by yaira2** [comment] 2024-09-09 19:51
Thanks! We're currently working on a couple of other fixes but it shouldn't be long.
