### ISSUE TITLE
Better multi-selection using touch

### ISSUE THREAD

**Issue by rachiwicks** [files-community/Files#2067] opened 2020-10-11 08:05 UTC
Right now, can only select multiple files/folders only by holding CTRL. Need better touch support in tablet mode/ when no keyboard attached to select without a keyboard

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment] 2020-10-11 18:51
Duplicate of #2008

**Closed by duke7553** 2020-10-11 18:51 UTC
Labels: feature_request
