### ISSUE TITLE
Tick-boxes to select multiple items

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#2906] opened 2021-01-10 21:10 UTC
**Is your feature request related to a problem? Please describe.**
Allow tick boxes to select multiple items similar to the File Explorer in Windows. 

**Describe the solution you'd like**
Tick-boxes similar to File Explorer. Allow the feature to be enabled or disabled from settings. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/58662575/104135408-2bc63600-5388-11eb-9982-aceee6589f41.png)

**Comment by yaichenbaum** [comment] 2021-01-10 21:23
Duplicate of #290.

**Closed by yaichenbaum** 2021-01-10 21:23 UTC
