### ISSUE TITLE
Overlapping library widgets on hovering

### ISSUE THREAD

**Issue by MBuelowius** [files-community/Files#2812] opened 2021-01-01 17:45 UTC
**Describe the bug**
The library widgets grow underneath each other on 4k

**To Reproduce**
1. Open files on a 4k monitor.
2. Hover over a library widget.

**Expected behavior**
The widget should expand over other widgets while hovering and not expand behind other widgets.

**Screenshots**
![image](https://user-images.githubusercontent.com/53919796/103443530-7a752100-4c60-11eb-9674-77b13fa66ce7.png)
![image](https://user-images.githubusercontent.com/53919796/103443562-c922bb00-4c60-11eb-9788-bc0330bac557.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20h2 19042.685]
 - App version: [v0.24.1]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5759221/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5759222/debug.txt)

**Comment by yaichenbaum** [comment] 2021-01-01 18:25
Duplicate of #2246.

**Closed by yaichenbaum** 2021-01-01 18:25 UTC
Labels: bug
