### ISSUE TITLE
Bug: Pinned section is empty

### ISSUE THREAD

**Issue by smokelore** [files-community/Files#13116] opened 2023-08-01 20:46 UTC
> [!important]
> A potential fix is available in the preview builds https://files.community/download. Please comment if it worked or not for you.
> If not you can try clear recent folders in Windows File Explorer settings > ... > Options > Clear and disabling `show recent folders` in > that same menu.

### Description

![image](https://github.com/files-community/Files/assets/1188899/ec104937-3cfa-4241-b774-600f32b5754a)

I installed Filed Preview by accident and it was working quite well until I realized that the Favorites dropdown in the Sidebar is always empty. I uninstalled Files Preview and installed Files Stable and the problem remains. If I add more items to Favorites they do not show up. They're also not present in the Quick Access section of the Home page. I've tried hiding the Favorites section and unhiding it but that didn't resolve it either.

![image](https://github.com/files-community/Files/assets/1188899/767f42e1-3380-47ad-8d02-bb49c26614e4)

Really like this software so far and would love to continue using it if I can get this working. Thanks everyone!

### Steps To Reproduce

Use Files Preview as normal, moving files, renaming folders, running applications, adding and removing Favorites. Favorites then became empty. I really don't know what else I might have done.

### Requirements

Expected behavior is that I'm able to see my Favorites in the sidebar, and remove them, add more of them, and reorder them as normal.

### Files Version

2.5.21.0

### Windows Version

Edition: Windows 11 Pro, Version: 21H22, OS Build: 2000.2245

### Log File

[debug.log](https://github.com/files-community/Files/files/12233858/debug.log)

**Comment by Josh65-2201** [comment] 2023-08-01 20:47
Thanks for the report, Can you send what in your favorites from Windows File Explorer.

**Comment by smokelore** [comment] 2023-08-02 07:16
Here you go, @Josh65-2201. Thanks for the prompt reply.

![image](https://github.com/files-community/Files/assets/1188899/c4a0d4f6-1827-4b28-b219-c02280872c64)

**Comment by smokelore** [comment] 2023-08-02 07:17
This install of Windows is only a couple days old so my Favorites menu hasn't gotten cluttered yet, haha

**Comment by yaira2** [comment] 2023-08-03 15:33
@smokelore can you see what happens if you remove Google Drive from Quick Access in File Explorer?

**Comment by smokelore** [comment] 2023-08-04 08:29
![image](https://github.com/files-community/Files/assets/1188899/ff8dd998-c016-440a-9b8f-1711af9f869a)

Good idea, but it didn't fix it even when I removed everything except for Downloads and Desktop from Quick Access.

**Comment by smokelore** [comment] 2023-08-04 08:31
I also tried removing Downloads from Quick Access within Explorer, and then adding it to Favorites via Files. That wasn't successful either.

**Comment by sdmtr** [comment] 2023-08-04 12:52
I'm experiencing the same issue, favourites and quick access are normal in Explorer but missing in Files. The problem suddenly appeared today after several months without issues; none of the suggestions I've tried from any of the various threads about it have fixed it.

**Comment by yaira2** [comment] 2023-08-04 14:10
@smokelore did you restart Files after removing the pinned items from File Explorer? I think there might be a permission issue with trying to access one of the items and it's causing the rest of the favorites to not load.

**Comment by smokelore** [comment] 2023-08-04 14:23
@yaira2 Yes, I've restarted Files multiple times since then because I use it often. Still no Favorites, unfortunately!

**Comment by sdmtr** [comment] 2023-08-05 05:37
> @smokelore did you restart Files after removing the pinned items from File Explorer? I think there might be a permission issue with trying to access one of the items and it's causing the rest of the favorites to not load.

Interesting that you should mention a permissions issue, I just realised that my problems began at around the same time as I was struggling to use Files to change permissions on a file in `C:\Program Files` so that I could overwrite it. I had to launch Explorer to get the credential changes to actually stick. It wasn't until sometime later that I noticed the Quick Access, Favourites, and Recent Files sections in Files were empty, so I didn't put two and two together until just now.

I've just gone back into Explorer and emptied out the Recent Files section, and when I restarted Files the Quick Access, Favourites and Recent Files sections appeared properly, so I can confidently say that my particular problem was definitively caused by a permissions issue. 

If anyone else is experiencing the same issue, try selecting everything in Explorer's Recent Files section and right-clicking to remove them; bear in mind they'll be replaced by older files you accessed previously which may also have the same permissions issue, so you may need to do this several times to make sure you've removed any and all files that could have issues.

**Comment by smokelore** [comment] 2023-08-06 15:17
Thanks so much, @sdmtr, your fix worked for me! My favorites returned after I cleared my Recent Files section in Explorer.

Going to leave this Issue open because it's still an unresolved bug but will leave it to the developers to decide how to proceed.

**Comment by yaira2** [comment] 2023-08-06 15:19
This has been very helpful in narrowing down the issue to the recent folders list, we're going to leave this issue open until it's resolved.

**Comment by yaira2** [comment] 2023-08-06 21:50
@sdmtr which permissions did you change? I'm trying to repro this on my side.

**Comment by sdmtr** [comment] 2023-08-07 04:33
I granted myself write permission on a particular file which was in a sub-directory of `C:\Program Files` (not the `(x86)` version of Program Files, although it shouldn't matter either way since both grant the same limited permissions to non-elevated accounts by default) so that I could overwrite a portion of the contents.

To be clear, I don't think the act of _changing_ the permissions is what caused the problem; after all, I gave myself _more_ permissions than I had previously. I think it was merely navigating to a directory that I didn't have execute or write permissions for that caused Files to choke when it encountered that directory in my Recent Files list.

That is to say, I think the same problem would have occurred even if I'd just navigated to that directory and opened the file that was in it for viewing, and then immediately left without changing either the permissions or the contents of the file. Just opening that file in, say, Notepad would have been enough to put both the file and the directory it was contained in into my Recent Files list, so I don't think the permission change was a factor. Unfortunately I can't test that theory since I'm currently about a thousand kilometres away from my PC and won't be back for a few days, but I'll have a tinker when I'm home and see if I can reproduce the issue.

**Comment by sdmtr** [comment] 2023-08-07 04:36
> @sdmtr which permissions did you change? I'm trying to repro this on my side.

I granted myself write permission on a particular file which was in a sub-directory of `C:\Program Files` (not the `(x86)` version of Program Files, although it shouldn't matter either way since both grant the same limited permissions to non-elevated accounts by default) so that I could overwrite a portion of the contents.

To be clear, I don't think the act of _changing_ the permissions is what caused the problem; after all, I gave myself _more_ permissions than I had previously. I think it was merely navigating to a directory that I didn't have execute or write permissions for that caused Files to choke when it encountered that directory in my Recent Files list.

That is to say, I think the same problem would have occurred even if I'd just navigated to that directory and opened the file that was in it for viewing, and then immediately left without changing either the permissions or the contents of the file. Just opening that file in, say, Notepad would have been enough to put both the file and the directory it was contained in into my Recent Files list, so I don't think the permission change was a factor. 

Unfortunately I can't test that theory since I'm currently about a thousand kilometres away from my PC and won't be back for a few days, but I'll have a tinker when I'm home and see if I can reproduce the issue.

**Comment by Likqez** [comment] 2023-08-12 09:53
This may be irrelevent:

But is there a way to disable windows from adding frequently used folders to quick-access?
Or, since Files is only showing the pinned quick-access ones, could the normal ones just be ignored?

Because this is causing me the lag the OP described, favourites aswell as quickaccess (in files) are empty until they finally load. In my case because Windows itself adds a network drive which i use frequently.

**Comment by Josh65-2201** [comment] 2023-08-12 15:41
You can disable recent folder in Windows File Explorer options window under the privacy section. This will apply to Files too.

**Comment by Likqez** [comment] 2023-08-13 11:34
But does this also affect the reccent files widget from Files?

**Comment by Josh65-2201** [comment] 2023-08-13 11:35
There's a separate option for hiding recent files

**Comment by Likqez** [comment] 2023-08-13 15:16
Yes, and sorry for keeping this thread alive, but i think you misunderstand my question.

If i turn of recent files in the Windows Explorer, then it will also be disabled in Files.
Which is not what i try to achieve. I was wondering if there is a way to stop windows to automatically pinning recent files to the quick access bar. Cause this will slow down using Files even when its not showing the Home Page (where the Recent Files would be loaded).

I understand that this is not a Issue of the Files App, thus this will be the last comment regarding this topic.

**Comment by yaira2** [comment] 2024-04-07 14:14
Has anyone found a solution that works for this?

**Comment by electricsteve** [comment] 2024-04-21 21:00
Just sharing my experience:
It happens to me too, idk when, but it happens every time at random. I fix it by closing files in system tray and the pinned items will appear again, still quite annoying tho.
(Also, is there an issue that files doesn't open on top when opened by another app?)

**Comment by Josh65-2201** [comment] 2024-04-21 21:02
Are you on 3.3.4.0? If not please try it by installing preview from https://files.community/download
If it still doesn't work please try the work around at the top.

**Comment by yaira2** [comment] 2024-04-21 21:03
There is a potential fix in the preview build, can anyone confirm if this issue is less common in v3.3.4?

**Comment by electricsteve** [comment] 2024-04-23 18:52
> Are you on 3.3.4.0? If not please try it by installing preview from https://files.community/download If it still doesn't work please try the work around at the top.

No, I'm not on 3.3.4, I'll update to it

**Comment by BridgeSenseDev** [comment] 2024-04-27 12:04
> There is a potential fix in the preview build, can anyone confirm if this issue is less common in v3.3.4?

It seems to still happen after restarts for me on v3.3.5

**Comment by SentryTheDefiant** [comment] 2024-04-29 23:36
Just started happening to me again on 3.3.5.0 as well. Having the current release build installed as well shouldn't affect the preview build at all, should it?

**Comment by yaira2** [comment] 2024-05-01 02:28
Another potential fix will be included in the next preview build.

**Comment by yaira2** [comment] 2024-05-01 18:36
v3.3.6 is now available for preview, please let us know if this helped.

**Comment by yaira2** [comment] 2024-05-02 14:18
That's great to hear! Let's try to get a few more confirmations before closing this issue.

**Comment by yaira2** [comment] 2024-05-07 23:41
This appears to be resolved in v3.4 but we'll keep an eye out for additional reports.

**Closed by yaira2** 2024-05-07 23:41 UTC
Labels: bug, help wanted, needs-reproducing

**Comment by SentryTheDefiant** [comment] 2024-05-15 13:16
I have 3.4.1 preview (the blue one) and Pinned items are still missing.

**Comment by SentryTheDefiant** [comment] 2024-07-01 15:49
I ultimately noticed (Once I finally gave up and went back to File Explorer full time) that my Pins were not showing there either. I followed the following guide to clear the Quick Access panel and Pinned items returned in both File Explorer and Files. [https://www.winhelponline.com/blog/fix-quick-access-reset-pinned-shortcuts-stuck-not-working-windows-10/#:~:text=To%20resolve%20the%20issue%2C%20reset%20Quick%20access%20%28Pinned,file%20named%20f01b4d95cf55d32a.automaticDestinations-ms%20in%20the%20following%20folder%3A%20%25AppData%25MicrosoftWindowsRecentAutomaticDestinations](https://www.winhelponline.com)

**Comment by yaira2** [comment] 2024-07-01 15:54
Great to hear!

**Comment by SentryTheDefiant** [comment] 2024-07-05 14:43
Unfortunately, I have to report that the Pins are missing again, but only in Files, not File Explorer... I no longer get any error message, but I'm unable to add pins again.

**Comment by Josh65-2201** [comment] 2024-07-05 14:58
Unfortunately there's a new issue https://github.com/files-community/Files/issues/15410. There a workaround to try there.
