### ISSUE TITLE
QuickLook not working in 1.1.5

### ISSUE THREAD

**Issue by KibSquib48** [files-community/Files#3230] opened 2021-01-22 17:13 UTC
**Describe the bug**
Pressing space and using the quicklook context menu option do nothing.

**To Reproduce**
1. Go to a file/folder
2. Click on it once
3. Press space bar
4. No QuickLook :(

**Expected behavior**
A QuickLook window with a preview of the file should show up.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.782
 - App version: 1.1.5.0

**Additional context**
I have tried terminating, using the Settings app and restarting both Files and QuickLook

**Log file**
I'm not sure if a log file would be useful here but I'll post it in case it is
[debug.txt](https://github.com/files-community/Files/files/5857409/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5857410/debug_fulltrust.txt)

**Comment by Ein-Tim** [comment] 2021-01-22 19:29
As described in #3233, I am using version 1.1.0.0 (QuickLook version 3.6.10.0 - downloaded from Microsoft Store) and QuickLook does not work.

**Comment by gave92** [comment] 2021-01-22 19:30
@AndyMDoyle could you check the error reported in debug_fulltrust? Looks related to OneDrive detection

**Comment by Ein-Tim** [comment] 2021-01-22 19:32
Looking at my debug_fulltrust.txt log I see the first entry says: 
`2020-12-21 22:05:35.8272|INFO|FilesFullTrust.QuickLook|QuickLook detected: False|`.
This is wrong. I have QuickLook installed. I will try the version which is available here on GitHub, maybe it is a problem with the Microsoft Store Version

**Comment by Ein-Tim** [comment] 2021-01-22 19:48
@KibSquib48 Did you install QuickLook from the Microsoft Store? If yes, you could try to install it from [here](https://github.com/QL-Win/QuickLook/releases) and see if it is working. I did this and it worked for me. Then I deinstalled the QuickLook from GitHub again and installed it from the Microsoft Store again. Now it is working 🤷‍♂️

**Comment by KibSquib48** [comment] 2021-01-22 19:53
> @KibSquib48 Did you install QuickLook from the Microsoft Store? If yes, you could try to install it from [here](https://github.com/QL-Win/QuickLook/releases) and see if it is working. I did this and it worked for me. Then I deinstalled the QuickLook from GitHub again and installed it from the Microsoft Store again. Now it is working 🤷‍♂️

Not working with .msi or .zip from there, also uninstalled and then reinstalled from MS store, still nothing...

**Comment by gave92** [comment] 2021-01-22 19:58
@KibSquib48 from the log file it looks like the issue is not just with wuicklook. For example I'm guessing that context menu should be not working for you as well?

**Comment by KibSquib48** [comment] 2021-01-22 19:59
> @KibSquib48 from the log file it looks like the issue is not just with wuicklook. For example I'm guessing that context menu should be not working for you as well?

yeah, I have another issue for that too

**Comment by AndyMDoyle** [comment] 2021-01-22 21:03
> @AndyMDoyle could you check the error reported in debug_fulltrust? Looks related to OneDrive detection
> 
> @KibSquib48 do you have OneDrive installed and connected to an account?

@gave92 PR with a fix: #3234

**Comment by KibSquib48** [comment] 2021-01-22 21:44
> @KibSquib48 do you have OneDrive installed and connected to an account?

I don't, the very first thing I uninstalled on this was OneDrive

**Comment by gave92** [comment] 2021-01-22 21:52
@KibSquib48 From the stacktrace it looks like that would solve the context menu & quicklook issues. Anyway we're working on a fix in #3234 which will be included in the next release.

**Comment by KibSquib48** [comment] 2021-01-22 22:03
> @KibSquib48 From the stacktrace it looks like that would solve the context menu & quicklook issues. Anyway we're working on a fix in #3234 which will be included in the next release.

yep installing OneDrive fixed it, glad to hear that a fix is coming!

**Comment by Cyberdroid1** [comment] 2021-01-23 05:47
I had also uninstalled Onedrive from my PC, and facing same issue. Looking forward for a fix 😄

**Comment by StLa1** [comment] 2021-01-23 09:25
Works for me, weird

**Comment by yaichenbaum** [comment] 2021-01-24 00:07
@KibSquib48 This issue should be resolved with #3234.

**Closed** 2021-01-24 00:07 UTC
Labels: bug
