### ISSUE TITLE
Bug: CPU increases when opening the settings dialog

### ISSUE THREAD

**Issue by ahuihub** [files-community/Files#12172] opened 2023-04-23 15:54 UTC
### Description

Why does the CPU usage immediately surge when the setting in the upper right corner is turned on, leading to lag. I did not open the calculation file size in the folder.

### Steps To Reproduce
1. Open Task Manager
2. Open Files
3. Click on the settings button
4. Notice that the CPU jumps for a couple of seconds

### Requirements

- Fix issue where the CPU usage jumps

### Files Version

5.4.67.0

### Windows Version

10.0.19045.2846

### Log file

123

**Comment by Josh65-2201** [comment] 2023-04-23 15:55
This has been fixed and will be available for the next update.

**Comment by yaira2** [comment] 2023-04-23 15:56
@ahuihub the settings UI is almost like another app, loading all the UI controls is expensive but the CPU usage should go down within a second or two. Can you confirm that it goes down after a few seconds?

**Comment by yaira2** [comment] 2023-04-23 15:57
> This has been fixed and will be available for the next update.

@Josh65-2201 that was a different issue that affected the home page.

**Comment by ahuihub** [comment] 2023-04-23 16:00
Excuse me, when is the next update expected to come out? Currently, this bug is quite affecting usage.

**Comment by yaira2** [comment] 2023-04-23 16:01
@ahuihub can you please confirm the steps to reproduce this issue and that the CPU usage goes down once the settings UI finishes loading?

**Comment by yaira2** [comment] 2023-04-23 16:07
I think this has to do with the way we load the startup page settings in the constructor of the ViewModel.

**Comment by ahuihub** [comment] 2023-04-23 16:14
I just recorded a video about this issue。https://internet.lanzouo.com/iQN6M0tsviuh

**Comment by yaira2** [comment] 2023-04-23 16:17
The video isn't loading for me, it might be better if you upload directly to GitHub but either way, I think I was able to reproduce the issue (I updated the issue description with the steps to reproduce it).

**Comment by ahuihub** [comment] 2023-04-23 16:26
Thank you. I have just learned how to use GitHub and some of the operations are still pending. I will go to bed first.

**Comment by hishitetsu** [comment] 2023-04-24 00:26
Isn't it the same issue as #12160? When I opened the settings dialog from other than the home page, I can't reproduce it.

**Comment by yaira2** [comment] 2023-04-24 00:45
> Isn't it the same issue as https://github.com/files-community/Files/issues/12160? When I opened the settings dialog from other than the home page, I can't reproduce it.

It's separate, I can reproduce this from other locations as well.

**Comment by hishitetsu** [comment] 2023-04-24 01:31
The CPU settles down after a few seconds, but is it a problem that the CPU soars so high in the beginning?

https://user-images.githubusercontent.com/66369541/233879432-1a650369-93c8-4af2-b669-24f6b796e7b0.mp4

**Comment by yaira2** [comment] 2023-04-24 01:40
@hishitetsu the main issue is that we have some heavy code in the constructer of the general page (in the view model), we can't eliminate it completely, but we can reduce the impact by creating a separate method to initialize the code.

**Comment by yaira2** [comment] 2023-09-28 22:44
> The CPU settles down after a few seconds, but is it a problem that the CPU soars so high in the beginning?

@hishitetsu a small increase is okay, but in my case it's increasing to as much as 40%.

**Comment by yaira2** [comment] 2023-10-13 20:06
@ahuihub thank you for your feedback, this issue was fixed in the latest preview build https://files.community/download.

**Closed by yaira2** 2023-10-13 20:06 UTC
Labels: bug
