### ISSUE TITLE
Can't focus on any data grid item with keyboard navigation

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#3557] opened 2021-02-13 05:19 UTC
When using keyboard navigation, items list in list view layout mode is completely inaccessible.

**Comment by yaichenbaum** [comment] 2021-02-14 00:36
@Jaiganeshkumaran I can't reproduce this issue in v1.2.2, what version of Files do you have?

**Comment by Jaiganeshkumaran** [comment] 2021-02-14 03:59
Ok I can access it but unlike File Explorer it doesn't highlight focus so I didn't know

**Comment by yaichenbaum** [comment] 2021-02-14 04:07
@Jaiganeshkumaran This should be fixed once WinUI creates the new DataGrid control.

**Closed by yaichenbaum** 2021-02-14 04:07 UTC
Labels: more-info
