### ISSUE TITLE
Opening downloads saves scroll location

### ISSUE THREAD

**Issue by gkkirilov** [files-community/Files#5819] opened 2021-08-14 06:06 UTC
### Description

Every time I open downloads it saves the scroll position and doesn't show me the top of the folder, I have used the group by date modified setting.

So after a while, it opens on "Last month" group scroll position and not "Today"

I would be happy if I knew how to reset the scroll position also

### Steps To Reproduce

1. Open downloads
2. Select Group By Date modified
3. Come back tomorrow and will save scroll position for tomorrow and you have to scroll up for today.

### Expected behavior

1. Open downloads
2. Select Group By Date modified
3. Come back tomorrow and scroll position should be on top

### Files Version

1.9.23

### Windows Version

Windows 11  Build 132

**Comment by Darhagonable** [comment] 2021-08-30 20:48
Possibly it's related to this:

For some folders one will unexpectedly start in the middle of the directory instead of the top if one has sorting set to date modified, descending.
Personally this happens for my downloads folder which becomes a bit of a problem since its a very commonly used folder and i used this sorting setting for it.

### Steps to reproduce
1. Go to System32
2. Sort by date modified, descending
3. Refresh
4. See how one is now in the middle of the directory

### Files version
v1.9.32

**Comment by d2dyno1** [comment] 2021-08-30 21:04
@Darhagonable if the following is the case:
![image](https://user-images.githubusercontent.com/53011783/131405315-dd47787b-3ffe-4f09-b4ed-5c81290e3357.png)

Then it should be already fixed by #5952

**Comment by Darhagonable** [comment] 2021-08-30 21:08
> @Darhagonable if the following is the case:
> ![image](https://user-images.githubusercontent.com/53011783/131405315-dd47787b-3ffe-4f09-b4ed-5c81290e3357.png)
> 
> Then it should be already fixed by #5952

I thought that was part of v1.9.32?
I could also reproduce this without any file containing readme existing.

**Comment by yaichenbaum** [comment] 2021-12-23 18:11
Merging with #6186

**Closed by yaichenbaum** 2021-12-23 18:11 UTC
Labels: bug, triage approved
