### ISSUE TITLE
Disk free capacity won't update until I kill the app

### ISSUE THREAD

**Issue by erayrafet** [files-community/Files#2514] opened 2020-12-02 08:32 UTC
**Describe the bug**
Once I do changes on, let's say drive C:, after I delete a few files and go back to the home page, the changes in free space capacity aren't being reflected.

**To Reproduce**
1. Go to 'C:/~Downloads/.'
2. Delete a file.
3. Click on 'the home button.'
4. Compare the free space on the C: drive reported by Files.
5. Kill Files and compare again.

**Expected behavior**
Drive capacity / free space to be refreshed after changes are made.

**Screenshots**
![image](https://user-images.githubusercontent.com/34194191/100847959-24f2fc00-3489-11eb-973a-48ed29138286.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20262]
 - App version: [v0.21.2]

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5627886/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5627887/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment] 2020-12-02 13:32
Duplicate of #2242.

**Closed by yaichenbaum** 2020-12-02 13:32 UTC
Labels: bug
