### ISSUE TITLE
Bug: Browser crash, preview, PDF, clicking the arrows

### ISSUE THREAD

**Issue by chezfo** [files-community/Files#12037] opened 2023-04-10 07:16 UTC
### Description

When a PDF is previewed, when you click the arrows to move from page to page, the browser crashes.
![1אנימציה](https://user-images.githubusercontent.com/85172877/230847891-a0bb08ac-22eb-43a2-bd40-13d253a4ddb6.gif)

### Steps To Reproduce

1. Stand on a PDF file
2. work for preview
3. Click the arrows to move between pages

### Requirements

Fix crash when clicking arrows.

### Files Version

Browser crash, preview, PDF, clicking the arrows

### Windows Version

11

### Log file

[debug.log](https://github.com/files-community/Files/files/11188494/debug.log)

**Comment by Josh65-2201** [comment] 2023-04-14 13:46
Can you see if this is an issue in 2.4.62.0 https://files.community/download (Select preview) and post the updated log if it happens.

**Comment by yaira2** [comment] 2023-04-14 15:23
@0x5bfa is this the same error you reported in #10280?

**Comment by chezfo** [comment] 2023-04-16 09:24
> Can you see if this is an issue in 2.4.62.0 https://files.community/download (Select preview) and post the updated log if it happens.

For several hours now, I have not been able to install the program in preview.
 Is there another way to install?

**Comment by Josh65-2201** [comment] 2023-04-16 09:39
You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller```

**Comment by 0x5bfa** [comment] 2023-04-16 09:43
> @0x5bfa is this the same error you reported in https://github.com/files-community/Files/issues/10280?

Looks another one.

**Comment by 0x5bfa** [comment] 2023-04-16 09:44
@chezfo Can you write 'Step To Reproduce' and 'Requirements' in English?

**Comment by yaira2** [comment] 2023-04-16 22:08
@chezfo Thank you for bringing this to our attention, we've added it to our project board for tracking.

**Comment by chezfo** [comment] 2023-04-20 12:51
> Can you see if this is an issue in 2.4.62.0 https://files.community/download (Select preview) and post the updated log if it happens.
The problem continues, at 66
 But the browser does not crash but reopens.
[debug.log](https://github.com/files-community/Files/files/11286342/debug.log)


By the way, I installed a browser that is not from the Windows store, and the browser is significantly faster.  Is it because of the version or because I installed without Windows Store?

**Comment by Josh65-2201** [comment] 2023-04-20 13:04
Files uses Webview2 which is built in to Widows for the browser.

**Comment by yaira2** [comment] 2023-05-01 18:42
@chezfo is this only with certain pdf documents?

**Comment by Krytan** [comment] 2023-05-01 18:54
That's what I am thinking the issue might be related to the pdf being in hebrew normally the arrow starts in the right side but here the arrow starts in the left in this case the left arrow might be trying to go back instead of going forward  like it should and causing the crash

**Comment by yaira2** [comment] 2023-05-01 19:55
I don't think that's the cause but we can verify if @chezfo can still reproduce this after setting the app to English.

**Comment by chezfo** [comment] 2023-05-01 20:32
Indeed, I set the app to English and there is no change.
 Still the browser crashes

**Comment by Krytan** [comment] 2023-05-02 04:31
@chezfo when you go to a pdf file where is the arrow first located for you? in the left side or right side also do you also crash when clicking on the small circles bellow the pdf or is it just when clicking the arrows?

**Comment by chezfo** [comment] 2023-05-02 05:17
> @chezfo when you go to a pdf file where is the arrow first located for you?

on the left side.  As in the animation I uploaded.

By clicking on the circles under the file there is no problem.

**Comment by chezfo** [comment] 2023-05-02 16:34
First, it makes sense that when programming in Hebrew, Hitz would be on the left side. 
 This is how it is read in rtl languages.

 What is really incomprehensible, why when I transfer the software to English, the arrow remains on the left side.
 Maybe there is a bug, that if the first installation is in Hebrew, the arrow will always be on the left?

**Comment by Krytan** [comment] 2023-05-02 19:15
@chezfo 
![crash](https://user-images.githubusercontent.com/42214331/235762442-b991de09-1226-4202-974e-ccacc62ab0cb.png)

Yes I have being able to reproduce the same crash using a windows 10 hebrew version I am amazed how everything looks so different in hebrew now that I know the issue I will work on a patch that supports not only hebrew versions but all rtl languages

**Comment by Krytan** [comment] 2023-05-06 16:50
@chezfo That should fix the issue

**Comment by chezfo** [comment] 2023-05-06 20:05
How am I supposed to confirm this? 
 Do I need to install a new version to test this?

**Comment by Josh65-2201** [comment] 2023-05-06 20:07
There hasn't been a fixed released yet. You would have to build it from the PR above. If you don't know how that's fine you can test it when it in the preview build.

**Comment by chezfo** [comment] 2023-05-06 20:10
אני לא מתכנת, כך שאין לי את הידע לפתור בעיות.
אני יכול לבדוק גירסאות לכל היותר.

**Comment by Krytan** [comment] 2023-05-06 20:17
It's alright I asked you because you have a RTL(Right To Left) windows system I could replicate the issue by changing the flowdirection in the program to RTL and fixing it based on that but I haven't tested in a windows environment with RTL but it should work the same way

**Comment by yaira2** [comment] 2023-06-05 19:09
@chezfo this issue should be resolved in the upcoming v2.5 release.

**Closed by yaira2** 2023-06-05 19:09 UTC
Labels: bug
