### ISSUE TITLE
Folders not recognized as already pinned

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#3024] opened 2021-01-14 16:18 UTC
**The bug**
When a folder is already pinned, its context menu does not show that it can be unpinned, rather offers to pin (which though does nothing)

**To Reproduce**
Pin a folder to the sidebar, then navigate to its parent, select the already pinned folder, open the context menu, "Pin to Sidebar" will be shown always.

**Expected behavior**
The context menu for already pinned folders should show "Unpin from Sidebar" 

**Desktop (please complete the following information):**
OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
App version: 1.0.0.0
Hardware: Processor Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz
Installed RAM 12.0 GB (11.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Comment by gave92** [comment] 2021-01-14 16:49
This issue was marked as resolved a long time ago -> #1160 Might be a regression

**Comment by gave92** [comment] 2021-01-14 17:11
I can't reproduce it, is this how you're doing the procedure?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/9673091/104624422-d5147100-5693-11eb-913f-de14ff2e00b6.gif)
Does it seem to happen with an folder?

**Comment by Hefaistos68** [comment] 2021-01-14 17:25
Exactly like that. My result: 
![Files - pin](https://user-images.githubusercontent.com/8855055/104626088-63392900-568d-11eb-8031-61268a05c556.gif)

Type of folder doesnt make a difference

**Comment by yaichenbaum** [comment] 2021-01-15 15:39
@Hefaistos68 This behavior was recently changed and is now available in the Microsoft Store with v1.1. Please let us know if you can still reproduce this issue after updating to v1.1.

**Closed by yaichenbaum** 2021-01-15 15:39 UTC
Labels: bug, triage approved

**Comment by Hefaistos68** [comment] 2021-01-15 17:17
Confirmed to be working correctly in v1.1
