### ISSUE TITLE
Crash when I click "Extract"

### ISSUE THREAD

**Issue by IMX-Otaku** [files-community/Files#12470] opened 2023-05-28 06:20 UTC
### Description

I tried to use the Files app's archive extraction feature, but the app crashed

### Steps To Reproduce

1. Search a compressed file (7z, zip, etc)
2. Right click on the file
3. Select any extraction option

### Requirements

- eg. Fix crash that occurs when I'm trying to extract a compressed file

### Files Version

2.4.71.0

### Windows Version

Windows 10 22H2

### Log file

[debug.log](https://github.com/files-community/Files/files/11583800/debug.log)

**Comment by Josh65-2201** [comment] 2023-05-28 12:26
Thanks for the report. I am unable to reproduce this, Can you give the following information.
- When you say search do you mean you opened the archive and selected a file or are you using the search bar? If so is it inside or outside the archive?

**Comment by Josh65-2201** [comment] 2023-06-18 09:49
@IMX-Otaku Can you answer the above questions please.

**Comment by yaira2** [comment] 2023-07-03 20:51
@IMX-Otaku thank you for reporting this issue, I'm not able to repro this on my side but before closing this issue, can you confirm it's resolved in v2.5.10?

**Closed** 2023-07-06 19:56 UTC
Labels: bug, more-info
