### ISSUE TITLE
Columns Layout: Column width adjustment by dragging divider

### ISSUE THREAD

**Issue by dsolimini** [files-community/Files#7863] opened 2022-01-21 17:45 UTC
### What's the Problem?

When using Columns Layout, the width of each column is fixed, which makes it difficult to distinguish between file and folder names over ~20 characters long.  
![image](https://user-images.githubusercontent.com/98179326/150570748-2351cc53-4c43-4f02-ae39-49607bc27e92.png)
![image](https://user-images.githubusercontent.com/98179326/150571110-fe0f2b50-be3b-4479-9dc0-1b981f34d939.png)

The only way to identify if you are on the right file/folder is to mouseover and wait for the tooltip to appear and then slowly move from entry to entry. As a result, it can be very fiddly and time consuming to find the appropriate file/folder while using this Layout, which is unfortunate because it is otherwise a very useful interface. 

Even when there is plenty of space to the right of the current column, it still cuts off the files/folders at an arbitrary point.
![image](https://user-images.githubusercontent.com/98179326/150571674-d82db853-5e2f-4764-926a-6f57c43626cf.png)
 

### Solution/Idea

The width of any individual column in Columns Layout should be adjustable with the mouse. 
1. Mousing over the dividing line should change the cursor to the double-headed arrow and permit the user to drag the divider to the right or left as needed. 
2. Double-clicking on the divider should auto-size the column to match the length of the longest file name in the folder shown to the left. (If parsing out that value is challenging, it could be to match the longest _visible_ file name.)
3. The column width setting for a given folder should be remembered from session to session. 

The width of the current, or right-most column in Column layout should be the width of the available window space to the right. 

### Alternatives

1. Speed up the tooltip reveal delay for filenames that are cut off in columns layout to be immediate on mouseover.
2. Permit horizontal scroll of columns with long file names. (Though this gets very messy when columns layout itself has a horizontal scroll bar after enough columns/folders are opened in the view.

### Priorities

| Capability | Priority |
|:--------|:-------|
| Mousing over the divider/dividing line between columns in the Columns Layout should change the cursor to the double-headed arrow and permit the user to drag the divider as needed, changing the width of the column to the left of the respective divider. | Must|
| Double-clicking on the columns dividing line should auto-size the column to match the length of the longest file name in the folder shown to the left. (If finding that value is challenging, it could more simply match the longest _visible_ file name.) | Should|
| The column width setting for a given folder should be remembered from session to session.  | Should |
| The width of the current, or right-most column in Column layout should be the width of the available window space to the right.  | Should|

### Files Version

2.1.2.0

### Windows Version

Windows 11 21H2 22000.376

**Comment by gave92** [comment] 2022-01-21 18:23
Merging with #7863

**Comment by jeriss-cloud-center** [comment] 2022-07-01 10:14
Any idea of this feature could be implemented?

I imagine a setting "Automatically adjust the multi-column width" and this setting would automatically define the width of the column depending on the length of the files in the folder. It would save lots of space for columns with short file name and allow proper identification of files with long file name.

**Comment by andrefromsbg** [comment] 2022-12-21 14:43
> Any idea of this feature could be implemented?
> 
> I imagine a setting "Automatically adjust the multi-column width" and this setting would automatically define the width of the column depending on the length of the files in the folder. It would save lots of space for columns with short file name and allow proper identification of files with long file name.

yeah this would be the best solution! +1

**Comment by Rpurplebeatle** [comment] 2023-01-04 09:05
It would also be great to be able to adjust the size of the preview window!

**Comment by Josh-65** [comment] 2023-01-04 09:06
That's already possible

**Comment by ferrariofilippo** [comment] 2023-01-15 21:38
Duplicate of #6534

**Closed** 2023-01-15 21:38 UTC
Labels: feature request
