### ISSUE TITLE
Bug: Files is unable to load more then 3 drives on homepage and sidebar

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#12981] opened 2023-07-19 21:43 UTC
### Description

2.3.14 showed all the drives. Now 2.3.16 only show B, C and D

### Steps To Reproduce

1. Have more then 3 drives
2. Open Files
3. See others missing

### Requirements

- Show all drives

### Files Version

2.4.16.0

### Windows Version

10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/12100345/debug.log)

**Comment by yaira2** [comment] 2023-07-19 21:50
@0x5bfa it seems like this is from the splash screen work.

**Comment by Josh65-2201** [comment] 2023-07-19 22:11
I have found it only happens when I safely eject a drive but don't actually remove it from the system. Any drive letter beyond the ejected one wont load.

**Comment by yaira2** [comment] 2023-07-19 22:24
Is this fixed in v2.5.17?

**Comment by 0x5bfa** [comment] 2023-07-19 23:21
> @0x5bfa it seems like this is from the splash screen work.

What do you mean? Splash screen work isn't even merged.

**Comment by yaira2** [comment] 2023-07-19 23:27
v2.5.16 included the splash screen for testing purposes.

**Comment by hishitetsu** [comment] 2023-07-20 00:17
It seems a regression caused by #12931. The following code seems to fail to get the volume label.
https://github.com/gave92/files-uwp/blob/0ca7278581bb3a6b7fbb91cc9b06be12bd6b91d6/src/Files.App/Helpers/Storage/DriveHelpers.cs#L140-L153

**Comment by yaira2** [comment] 2023-07-20 00:19
@0x5bfa I apologize, this isn't from the splash screen. Sorry for the confusion 😊

**Comment by hishitetsu** [comment] 2023-07-20 00:26
I will prepare a quick fix.

**Closed** 2023-07-20 01:34 UTC
Labels: bug
