### ISSUE TITLE
Save from Gmail

### ISSUE THREAD

**Issue by SN1985** [files-community/Files#13473] opened 2023-10-05 01:35 UTC
### Description

When I save files from Gmail(Web) to "files", the "files" software crashes everytime.

### Steps To Reproduce

1. open gmail with google chrome on my PC.
2. open a mail attached files on gmail.
3. drag a file from gmail to "files".
4. "files" software crashes.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.21.0

### Windows Version

edition Windows 10 Pro ver.	22H2 installed on ‎2022/‎05/‎13 OS 	19045.3448 Windows Feature Experience Pack 1000.19044.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/12811363/debug.log)

**Comment by Josh65-2201** [comment] 2023-10-05 17:55
Thanks for the report, I've added this to the project board.

**Comment by SN1985** [comment] 2023-10-09 23:19
No, I don't use preview ver..
Already is the problem solved in pre. ver.?

**Comment by Josh65-2201** [comment] 2023-10-09 23:34
He's asking you to download and test the preview build to see if the issue is still there.

**Comment by SN1985** [comment] 2023-10-09 23:58
The result was the same in pre.ver.

2023年10月10日(火) 8:34 Josh65-2201 ***@***.***>:

**Comment by yaira2** [comment] 2023-10-17 20:52
This should be fixed in the next update.

**Closed** 2023-10-17 20:52 UTC
Labels: bug, more-info
