### ISSUE TITLE
List pinned folders from Favorites in taskbar jumplist

### ISSUE THREAD

**Issue by xezrunner** [files-community/Files#5577] opened 2021-07-27 13:24 UTC
**Is your feature request related to a problem?**
Currently, right-clicking the Files icon in the taskbar shows no folders.

**Describe the solution**
As per File Explorer's implementation, right-clicking the icon in the taskbar should show recent, or more preferably pinned folders.
The jump list saves time as it provides much quicker access to pinned folders without having to launch then navigate within the app.

**Describe alternatives you've considered**
None.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| Show folders from Favorites within the taskbar jump list | Must |
| Manually pin folders to just the jump list | Should |
| Customize items that appear in the jump list | Could |

**- Manually pin folders to just the jump list**
This might be complicated, as Windows 11 does not support drag-and-drop in the taskbar (yet).

-----

**System Information**
 - OS Version: Windows 11 21H2 build 22000.100 (co_release)
 - App version: 1.9.15.0

**Additional information**
File Explorer's jump list:
![image](https://user-images.githubusercontent.com/8061077/127161470-ce9af60c-52f3-476c-af12-3d2e8f14ff7f.png)

Files app's current jump list:
![image](https://user-images.githubusercontent.com/8061077/127162721-2a818201-19c5-4ccb-a3f7-cdcd80f078d6.png)

**Comment by xezrunner** [comment] 2021-07-27 13:39
Sort-of related to #4338 and #3311, although both seem to assume that the jump list already has folders.
I have not seen folders in the jump list yet.

**Comment by gave92** [comment] 2021-07-27 18:20
Thanks for this report. Treating this as "bug" as recent folders are supposed to be shown on the taskbar

**Comment by xezrunner** [comment] 2021-08-11 12:44
A few days ago, I accidentally discovered that the option for Show recently open items ... in Windows Settings -> Personalization -> Start actually includes taskbar jump lists too:
![image](https://user-images.githubusercontent.com/8061077/129030493-33c78fea-5cac-4bd6-a12d-13567b831b58.png)

With it on, recent folders do show up in Files:
![image](https://user-images.githubusercontent.com/8061077/129030626-0796b7d5-4a82-4275-8a84-c4e988225b10.png)

However, the original suggestion still stands - pinned folders should show separately from recents, regardless of this option being on or off.

**Comment by ferrariofilippo** [comment] 2023-01-15 21:48
As already said in comments, duplicate of #3311

**Closed** 2023-01-15 22:05 UTC
Labels: feature request
