### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by KazBrekker1** [files-community/Files#3087] opened 2021-01-16 16:30 UTC
**Describe the bug**
**_Files_** doesn't open the Linux system's directories from any of the WSL shells.

**Steps to reproduce the behavior:**
1. Go to a WSL  shell  (I Use ZSH shell and an Ubuntu subsystem)
2. Type explorer.exe "directory" or files.exe "directory"

**Expected behavior**
Opening the File app in the specified dir

**Additional context**

- I Sat up _**Files**_ to be my default app using the steps provided on the repo.
- I downloaded _**Files**_ from MSStore
- I'm using WSL 2 (Ubuntu)
- Using `which files.exe` in the shell it correctly outputs where **_Files_** is located

**Comment by gave92** [comment] 2021-01-16 16:46
Are you able to open any UWP apps from WSL command line? I don't think it's supported
Does the following work instead? `cmd.exe /c "files "c:\\users\\marco""`

**Comment by KazBrekker1** [comment] 2021-01-16 17:32
This cmd command defaults to the window's directory even when specifying the wsl home's absolute path

And **_Files_** doesn't Launch when I write `files.exe "anyDIR"`, not even the default windows explorer.

**Comment by gave92** [comment] 2021-01-16 17:44
This works for me from WSL bash: `cmd.exe /c files.exe "\\\\wsl$\\ubuntu\\home"` -> escaped backslash

**Comment by KazBrekker1** [comment] 2021-01-16 19:47
When I used this:

- The terminal froze and I couldn't even escape/quit to be able to type commands again
- I couldn't cd into the WSL Directories from another instance of the terminal using the path above ("\\\\wsl$\\ubuntu\\home")

More info:
I can use `explorer.exe "directory name"` in this terminal and it works normally

**Comment by gave92** [comment] 2021-01-16 19:53
Sorry, I don't think this is something we can fix as the same seem to apply to any other window store app.

**Comment by DiegoMagdaleno** [comment] 2021-01-17 23:41
@gave92 there is a fix for this, but I wasn't able to even build the project by itself, well I was able to build it but not the test command line arguments;

TDLR: A rewrite of the way Files parses the command line arguments should make this work

**Comment by gave92** [comment] 2021-01-17 23:47
@DiegoMagdaleno thanks cool! Feel free to open a PR with the changes (even untested) 👍

**Comment by gave92** [comment] 2021-07-23 09:44
Is this still an issue? I can confirm that `cmd.exe /c files.exe "c:\\" &` works fine for both WSL1 and WSL2

**Closed** 2021-08-08 16:56 UTC
Labels: bug, needs-triage
