### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by PimTournaye** [files-community/Files#7088] opened 2021-11-26 17:37 UTC
### Description

Files is crashing and not getting beyond it's splash / logo screen. It was working fine a couple of hours before, no idea what's causing this.

### Steps To Reproduce

Open Files any number of ways
- crash
Reboot
Open Files any number of ways 
 - crash

### Expected behavior

It should not crash and open the folder or file I'm wanting to look at

### Files Version

2.0.34

### Windows Version

Edition	Windows 10 Home Version	21H2 Installed on	‎18/‎08/‎2021 OS build	19044.1387 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7610133/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7610134/debug_fulltrust.log)

**Comment by gave92** [comment] 2021-11-26 18:33
Thanks for the report. Unfortunately the log files did not pickup the cause of the issue. I suggest you simply try the usual: restart PC/reinstall the app.

**Comment by PimTournaye** [comment] 2021-11-26 22:53
Reinstalling did fix the issue, but I still wonder what might've caused this all of sudden. Maybe this could be already be fixed in the new release.

**Comment by gave92** [comment] 2021-11-26 23:46
Glad it works! Closing this for now, please let us now if it happens again.

**Closed by gave92** 2021-11-26 23:46 UTC
Labels: bug, more-info
