### ISSUE TITLE
Properties details page text boxs dont show unless hovered over

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#5636] opened 2021-07-31 13:46 UTC
### Description

as title says

### Expected behavior

The box should always be there

### Files Version

1.9.17

### Windows Version

10.0.19043.1110

**Comment by josh-65** [comment] 2021-09-08 15:05
This seem to happen for any text box in the properties menu (Details view)

**Comment by Josh-65** [comment] 2022-01-30 19:47
This now only applys to the details page

**Comment by yaichenbaum** [comment] 2022-03-06 17:44
This issue should be resolved in `main`. (the details page is by design)

**Closed by yaichenbaum** 2022-03-06 17:44 UTC
Labels: bug, triage approved
