### ISSUE TITLE
Network Shortcuts

### ISSUE THREAD

**Issue by Weishaar88** [files-community/Files#4508] opened 2021-04-08 14:55 UTC
**Explain the bug**
Files does not show network shortcuts. I have a folder that has shortcuts to the different projects on our server that I manage. When I open the shortcuts folder in Files, it is empty. In windows explorer, the shortcuts are present and functional.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
When I open my "00 Project Shortcuts" folder, I should see shortcuts to the various project folders I manage.

**Logfile**
There is no error or log that is going to show the issue. It is the absence of the shortcuts.

**Screenshots**

![Files vs WinX](https://user-images.githubusercontent.com/82163190/114048160-ebc00380-984f-11eb-801a-e117f40cda1d.png)

**System Information**
 - OS Version: Windows 10
 - App version: 1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment] 2021-04-08 18:34
Is the folder containing the shortcuts inside a network share?

**Comment by duke7553** [comment] 2021-10-13 23:28
@Weishaar88 I'm pretty sure this is intended to be a duplicate of #2436, so I'll close one this now to consolidate the discussion.

@gave92 or myself will reopen this one if you think that #2436 is different feedback.

**Closed by duke7553** 2021-10-13 23:28 UTC
Labels: feature request
