### ISSUE TITLE
Restore files is not working correctly

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5525] opened 2021-07-25 14:50 UTC
**Explain the bug**
When restoring a deleted file in the Recycle Bin, when it returns to its original location, it loses its format. In the video below, it shows the problem in practice.

**To reproduce**
1. Delete a file (tested with .txt file, located on the desktop)
2. Go to Recycle Bin
3. Right click with the mouse and select option Restore
4. Return to the location of the restored file
5. See the error

**Expected behavior**
Normally, when the file is restored, it should not lose its original format.

**Screenshots**

https://user-images.githubusercontent.com/78214358/126903276-5dab79be-7e24-4e1b-8fef-46e347c57752.mp4

**System Information**
 - OS Version: Windows 10 Home
                       21H1
                       19043.1110
                       Windows Feature Experience Pack 120.2212.3530.0

 - App version: v1.9.13.0

**Comment by gave92** [comment] 2021-07-25 20:59
Could you try the following?
1. Open Files
2. Open Task manager and kill the process called "FilesFullTrust.exe"
3. Try to delete and restore some files

Are files restored with the extension?

**Comment by esibruti** [comment] 2021-07-26 10:01
@gave92 As strange as it sounds, I was going to test its resolution but out of curiosity, I decided to test it to see if the problem persisted... Well, it just doesn't do anymore.

**Comment by gave92** [comment] 2021-07-26 11:28
Soo you can't reproduce the issue anymore? That's good, I'm gonna close this. If the issue comes back pleas e let us know!

**Closed by gave92** 2021-07-26 11:28 UTC
Labels: bug, triage approved
