### ISSUE TITLE
Bug: Right clicking a file displays disabled options to open in new tab

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#16626] opened 2024-12-20 16:42 UTC
### Description

Starting in v3.8.10, right clicking a file will incorrectly display options to open in a new tab.

### Steps To Reproduce

1. Right click a file
2. Notice the 'open in new tab' & 'open in new window' options are displayed

### Files Version

v3.8.10

### Windows Version

Windows 11

### Log File

NA

**Comment by ferrariofilippo** [comment] 2024-12-20 19:22
This is caused by #16484 and by how `ContextMenuFlyoutItemViewModelBuilder.Build()` works.
If no value is assigned to the `IsVisible` property and `IsExecutable` is set to `false`, then the command is not shown.
Since we are now assigning an explicit value to `IsVisible` the case above is bypassed.
To address this issue we can either:
- Move back `UserSettingsService.GeneralSettingsService.ShowOpenInNew...` to the `IsExecutable` property of commands
- When `IsVisible`  is set in the flyout builder, we should always use `UserSettingsService.GeneralSettingsService.ShowOpenInNew... && That_Command.IsExecutable`

I'd go with the first option since the latter may cause similar bugs in the future

**Closed** 2024-12-22 00:40 UTC
