### ISSUE TITLE
Pin to start missing on V1.5 from MS store

### ISSUE THREAD

**Issue by SD-5** [files-community/Files#4302] opened 2021-03-25 16:58 UTC
I believe the title is sufficient to understanding my problem 

I am trying to mine my project folder to my start menu so that I do not have to go into the app and then find it like in V1.3

![image](https://user-images.githubusercontent.com/81379563/112512021-e2806280-8d8a-11eb-95bc-877b45a87719.png)

![image](https://user-images.githubusercontent.com/81379563/112512333-2ffccf80-8d8b-11eb-8f07-097849c463ee.png)

**Comment by yaichenbaum** [comment] 2021-03-25 17:33
Duplicate of #4284.

**Closed by yaichenbaum** 2021-03-25 17:33 UTC
Labels: bug
