### ISSUE TITLE
Crash when renaming folders in column view

### ISSUE THREAD

**Issue by riverstone01** [files-community/Files#12108] opened 2023-04-18 03:20 UTC
### Description

When renaming folders in column view the screen bounces around as you type and then the app crashes. It doesn't always happen, but regularly.

### Steps To Reproduce

1. Click on Layout and choose Columns.
2. Click on folder to rename.
3. Start typing to rename folder.
4. Crash.

### Requirements

Fix crash that occurs when renaming folders in column view.

### Files Version

2.4.61.0

### Windows Version

Windows 11 Pro 22H2 22621.1555

### Log file

Original debug file is 93 MB but copied some of today's log. 
[debug.txt](https://github.com/files-community/Files/files/11257583/debug.txt)

**Comment by yaira2** [comment] 2023-04-18 03:32
@riverstone01 thank you for reporting this issue, can you test if the issue is still present in v2.4.62?

**Comment by hishitetsu** [comment] 2023-04-18 03:50
This should be fixed by #11986. (Thanks to @ferrariofilippo)

**Comment by yaira2** [comment] 2023-04-18 04:20
@riverstone01 this will be fixed in the next release.

**Closed** 2023-04-18 04:20 UTC
Labels: bug, more-info

**Comment by riverstone01** [comment] 2023-04-18 08:59
> @riverstone01 this will be fixed in the next release.

No probs! Thanks very much for the replies.
