### ISSUE TITLE
Adding a way to change the default keyboard shortcuts

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Files#2501] opened 2020-12-01 09:47 UTC
I always want to optimize my productivity and that means that I like to unify the keyboard shortcuts in my tools. However, in Files, there is no way currently to change the keyboard shortcuts.

I suggest adding a menu to the settings called "Keyboard shortcuts" which will have a layout like this: 
Action (Close Tab) | keyboard shortcut (Ctrl+W)
To change the shortcut, the user needs to click on the keyboard shortcut cell, and press the new shortcut.

An alternative solution could be a bit more technical, and that would be making a JSON file to store all of the shortcuts, and allowing the user to change it manually.

In both solutions, the UI of the app should change dynamically so for example, changing the shortcut of the Cut action would change it in the context menu as well.

**Comment by yaichenbaum** [comment] 2020-12-01 13:09
Duplicate of #1660.

**Closed by yaichenbaum** 2020-12-01 13:09 UTC
Labels: feature_request, needs-triage
