### ISSUE TITLE
Bug: Files sometimes crashes when loading many thumbnails, video or images

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#12581] opened 2023-06-10 15:37 UTC
### Description

When under the circumstances of big enough amount of different thumbnails ( say, program installers, photos ), Files will randomly freeze or even crash without any errors ( such as displaying "Files has encounter unknown issues" at windows notification bar ).
At first I thought it has someting to do with the drive itself, but checked with HDD utility such as CrystalDiskInfo with no issue whatsoever, and Windows Explorer behaves totally normal too.

### Steps To Reproduce

1. Make up a folder or attach a drive with with many files with different thumbnails or icons ( e.g. installers, camera memory cards )
2. Open it with Files ( layout doesn't matter ), and the error may come up

*The error may _not_ come up at any time--it's a bit random.

### Requirements

Files should load the icons/thumbnails without crashing ( say, put loading process into another thread, etc. )

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11712742/debug.log)

**Comment by Josh65-2201** [comment] 2023-06-25 09:35
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment] 2023-11-10 18:59
@jh961202 is this still an issue in v3.0.3? If you can still reproduce the issue, please upload the updated log file so we can take a closer look.

**Comment by JJSax** [comment] 2023-11-13 18:54
I just tested again on my issue #13384 and I no longer crash when following my steps in the same folder I was in and got linked to this issue.

I did reduce the number of items in that folder from 2500 to 522 since then so perhaps that could be the reason.

**Comment by yaira2** [comment] 2023-11-13 21:12
Thanks for the update, it's likely that it was fixed by one of the many fixes included in v3. If the issue happens again (or any other issue), please let us know and we'll see if we can fix it.

**Closed by yaira2** 2023-11-13 21:12 UTC
Labels: bug, help wanted, more-info, crash
