### ISSUE TITLE
Sidebar items' pressed effect persists when released while outside of control

### ISSUE THREAD

**Issue by XeZrunner** [files-community/Files#1052] opened 2020-06-13 22:03 UTC
**Describe the bug**
Holding a menu item in the sidebar, then moving the cursor/pointer outside of the control and letting go will result in the highlight effect persisting until the control is pressed again.

**To Reproduce**
1. Open the app.
2. Click or tap, and keep holding an item in the left sidebar.
3. Move the mouse or your finger/pointer outside of the menu item control.
4. Let go of the mouse button or your finger/pointer.

**Expected behavior**
The highlight effect should not persist when letting go of it.

**Screenshots**
![A GIF showing off the issue.](https://i.imgur.com/EJVmTL5.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.329
 - App version: v0.9.2.0

**Additional context**
This issue is also present within the Settings sidebar.
This issue does not occur with other controls in the application.

**Comment by duke7553** [comment] 2020-06-18 09:33
This is reproducible in v0.10.2

**Comment by tsvietOK** [comment] 2020-06-18 13:36
This is Navigation View bug, same bug exists in XAML Controls gallery app.

**Comment by yaichenbaum** [comment] 2020-10-19 17:59
@tsvietOK Is there an issue on their repo?

**Comment by tsvietOK** [comment] 2020-10-19 18:10
@yair100 As mentioned [here](https://github.com/microsoft/microsoft-ui-xaml/issues/3085#issuecomment-671054773) this bug should be resolved in pre-release version of microsoft-ui-xaml library.

**Comment by yaichenbaum** [comment] 2020-10-19 18:22
Thank you for the update, I am closing this issue since it will be fixed in the new release of WinUI.

**Closed by yaichenbaum** 2020-10-19 18:22 UTC
Labels: bug, help wanted, triage approved
