### ISSUE TITLE
Cannot paste in Files

### ISSUE THREAD

**Issue by zackBRAVE** [files-community/Files#4575] opened 2021-04-13 09:11 UTC
**Explain the bug**
Cannot paste items in Files.

**To reproduce**
1. Cut or copy items in Files
2. Paste them in Files
3. Nothing happen
4. Paste them in File Explorer or on desktop
5. Successfully pasted
6. Can undo by Ctrl-z

**Expected behavior**
Just paste them in Files.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6302534/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6302535/debug_fulltrust.txt)

**System Information**
 - OS Version: 
版本	Windows 10 专业教育版
版本号	20H2
安装日期	‎2021-‎03-‎06
操作系统内部版本	19042.867
体验	Windows Feature Experience Pack 120.2212.551.0
 Windows 10 20H2 19042.867
 - App version: 1.5.0.0

**Additional comment**
I use NVMe RAID0, I'm not sure if this is a problem

**Comment by winston-de** [comment] 2021-04-13 17:33
Thanks for filing this issue.
Could you please test if paste does not work through the layout context menu option, through ctrl+v, or both?

**Comment by zackBRAVE** [comment] 2021-04-13 17:36
> Thanks for filing this issue.
> Could you please test if paste does not work through the layout context menu option, through ctrl+v, or both?

both

**Comment by winston-de** [comment] 2021-04-13 17:49
Thanks for this additional info. This is likely a duplicate of #3615.

**Closed by winston-de** 2021-04-13 17:49 UTC
Labels: bug
