### ISSUE TITLE
Remember ordering rules on different folders

### ISSUE THREAD

**Issue by Dogacel** [files-community/Files#2610] opened 2020-12-15 20:48 UTC
In the file explorer, each folder has its own rule for ordering/sorting its content. For example when I enter downloads tab, I would like to see downloads in the order of date modified. But when I return back to documents. I want to see my documents ordered by name. Now this app only remembers a single rule and applies it whenever I visit.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by XPoppyX** [comment] 2020-12-15 21:16
Duplicate of #530

**Closed** 2020-12-15 21:31 UTC
Labels: feature_request
