### ISSUE TITLE
Bug: Can't resize window using the top border

### ISSUE THREAD

**Issue by DominoKorean** [files-community/Files#10813] opened 2022-12-22 15:09 UTC
### Description

When holding the window with the mouse to shrink or expand it vertically, the window is not resized and only moves.
Horizontal can be resized normally.

### Steps To Reproduce

Grab and move the horizontal part of the window

### Steps to fix

Let Files adjust the window freely

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Pro 22H2

### Relevant Assets/Logs

https://user-images.githubusercontent.com/110039366/209162812-3f6a110e-2c28-489a-a99b-3816f5c626e7.mp4

**Comment by yaira2** [comment] 2022-12-22 17:03
Seems to be an issue with the drag area as it works to resize from the bottom of the window.

**Comment by hecksmosis** [comment] 2023-01-02 18:06
Resizing works on the top only on the minimize, maximize and close buttons

**Comment by yaira2** [comment] 2023-03-19 21:12
@Poker-sang is this solvable with the drag regions helper or is this a WinAppSdk issue?

**Comment by Poker-sang** [comment] 2023-03-20 12:54
@yair100 Both. I just tested it.

Actually, it could be resized vertically, but the resize border on the top is too thin to hold.

If we `SetTitleBar` instead of my helper then we can make a thick resize border at the top of window (just like the Horizontal ones). But the top of the `TabView` cannot be grabbed any more.

In fact. This issue is caused by `ExtendsContentIntoTitleBar`. There are two properties, They are:
* `AppWindow.ExtendsContentIntoTitleBar`
* `Window.ExtendsContentIntoTitleBar`

### When we use `Window.ExtendsContentIntoTitleBar`, we should write:
```xaml
<SolidColorBrush x:Key="WindowCaptionBackground">Transparent</SolidColorBrush>
<SolidColorBrush x:Key="WindowCaptionBackgroundDisabled">Transparent</SolidColorBrush>
```
```cs
window.ExtendsContentIntoTitleBar = true;
window.SetTitleBar(titleBar);
```
It looks like:
* green represents drag zone
* red represents resize border
![image](https://user-images.githubusercontent.com/62325494/226339974-49eba31f-6d61-4ee8-9a75-8f03d5454cca.png)
It has:
* Normal resize border, but not long enough to cover the top of the window.
* Small close, maximize, minimize buttons.
* Toolbar below the title bar.

### When we use `AppWindow.ExtendsContentIntoTitleBar`, we should write:
```cs
appWindow.TitleBar.ExtendsContentIntoTitleBar = true;
appWindow.TitleBar.SetDragRectangles(rects);
appWindow.TitleBar.ButtonBackgroundColor = Colors.Transparent;
appWindow.TitleBar.ButtonInactiveBackgroundColor = Colors.Transparent;
appWindow.TitleBar.ButtonHoverBackgroundColor = ((SolidColorBrush)App.Resources["SystemControlBackgroundBaseLowBrush"]).Color;
appWindow.TitleBar.ButtonForegroundColor = ((SolidColorBrush)App.Resources["SystemControlForegroundBaseHighBrush"]).Color;
```
It looks like:
![image](https://user-images.githubusercontent.com/62325494/226342645-db48c192-855b-4e49-83be-d424baa2e8e9.png)
It has:
* Thin resize border, and has normal length.
* Normal close, maximize, minimize buttons.
* Toolbar in the title bar.

### If we use both:
It looks like:
![image](https://user-images.githubusercontent.com/62325494/226343738-2b774b80-11a3-4446-8c26-72b8513cff2f.png)
It has:
* Both of the resize borders above, behaves just like File Explorer
* All of the buttons above (I don't know how to fix it).
* Toolbar below the title bar.

BTW, I prefer to use `Window.ExtendsContentIntoTitleBar`, what do you think?

**Comment by yaira2** [comment] 2023-08-30 15:24
This issue is fixed in the development branch and will be included in the next release.

**Closed by yaira2** 2023-08-30 15:24 UTC
Labels: bug
