### ISSUE TITLE
Bug: Files unable to eject external drives

### ISSUE THREAD

**Issue by Arcatis** [files-community/Files#16365] opened 2024-10-18 17:21 UTC
### Description

No option to eject the drive anywhere

### Steps To Reproduce

Plug in external drive
attempt to eject it via Files

### Requirements

Fix it so that you are able to eject external drives with a button

### Files Version

3.7.11.0

### Windows Version

Windows 10

### User ID

fc529297-c526-4a5a-bd5c-eedd41429622

### Log File

[debug.log](https://github.com/user-attachments/files/17438736/debug.log)

**Comment by Lamparter** [comment] 2024-10-18 17:28
This is a feature in Files; I think this issue is a duplicate of #10154.

**Comment by Josh65-2201** [comment] 2024-10-18 17:30
Thanks for the feedback, We're tracking this in #10154. You can check there or click subscribe in the right sidebar for updates.

**Closed by Josh65-2201** 2024-10-18 17:30 UTC
