### ISSUE TITLE
Bug: Git columns causing CPU to increase

### ISSUE THREAD

**Issue by soleon** [files-community/Files#12737] opened 2023-06-26 05:02 UTC
### Description

Performance of listing files in any folder in a git repository is abysmal for me to say the least. As soon as I open a git folder, CPU maxes out for a short period of time while the UI freezes/stutters intermittently, making the app unusable.

Sometimes, switching from one folder to another in the same git repository also freeze the app for a few seconds to a few 10 seconds before the content of the folder actually changes.

During these freezes, nothing seemed to have been logged to the debug.log file, I have attached it anyway.

I noticed repetitive `COMExceptions` in the log with the message "由于超时时间已过，该操作返回", they translate to "This operation returned because the timeout period expired".

See the following screenshot for the CPU utilisation over 60 seconds opening a folder containing 108 folders/files.
![image](https://github.com/files-community/Files/assets/780800/e6f0c115-71c9-4f62-9cab-b3fa714ae3d3)

### Steps To Reproduce

Open any folder in a git repository.

### Requirements

At least provide an option to disable native git integration, in case if this is a rare case that only happens to my git repo or on my PC.

### Files Version

2.5.10.0

### Windows Version

Windows 11 Pro 22H2 OS Build 22621.1848 Windows Feature Experience Pack 1000.22642.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/11863905/debug.log)

**Comment by yaira2** [comment] 2023-06-28 19:16
Thank you for your feedback, we're looking into this.

**Comment by yaira2** [comment] 2023-06-28 22:59
The CPU seems to spike for a couple seconds when opening any type of folder, this is something we're definitely working on but it doesn't seem to be specific to Git.

**Comment by soleon** [comment] 2023-06-28 23:56
Thanks @yaira2. I have done a bit more testing on different computers. The UI freeze was consistent across all devices. However, I found that it happens a lot worse to the git folder in my screenshot. Other git folders had similar symptom, but they weren't freezing as bad.

This folder in a rather large repo. I've tried copying all files in the folder to a new repo and that folder was swift and responsive. Looks like it has something to do with the size of the repo.

**Comment by yaira2** [comment] 2023-06-29 02:59
How many branches does this repo have?

**Comment by soleon** [comment] 2023-06-29 03:03
850... I know, we haven't done a great job to keep it tidy 😅

**Comment by yaira2** [comment] 2023-06-29 03:10
I think that might be the cause, @ferrariofilippo any thoughts?

**Comment by ferrariofilippo** [comment] 2023-06-29 19:00
That might be the case, I remeber @hecksmosis reported something similar in one of the first PRs (I don't remember exactly the issue, but it was related to repos with +100 branches)
I'll try to figure out which part is taking the most time to execute

**Comment by jason919** [comment] 2023-07-14 23:46
is it possible to disable the git integration completely?  it freezes completely when I go to a large git folder. I tried to set false to "show git columns", but it doesn't disable git

**Comment by Josh65-2201** [comment] 2023-07-15 00:38
There isn't a setting for git integration. The setting your changing is for the columns in details view only.

**Comment by ferrariofilippo** [comment] 2023-07-15 13:59
We can temporarily add that and, maybe, something like `Paths excluded from git` (which would let the user specify which paths should not be treated as git repositories)

To address the issue I think we should somewhot limit the number of branches loaded (we could add a search bar?)

**Comment by jason919** [comment] 2023-07-16 16:18
the worst case is that Files tries to reopen after I kill it in Task Manager, then it freezes with the same folder, stuck in a death loop.
so this is not just a feature request, but also a fix for a death trap.

**Comment by yaira2** [comment] 2023-07-16 17:35
> To address the issue I think we should somewhot limit the number of branches loaded (we could add a search bar?)

@ferrariofilippo can it be limited to the 15 most recent branches?

**Comment by ferrariofilippo** [comment] 2023-07-16 20:07
> @ferrariofilippo can it be limited to the 15 most recent branches?

I'll try

**Comment by yaira2** [comment] 2023-07-19 14:36
@ferrariofilippo that's a very good improvement, we can take it a step further and only load the branches when the flyout is opened but let's start with limiting to the 15 most recent branches.

**Comment by ferrariofilippo** [comment] 2023-07-19 16:17
> @ferrariofilippo that's a very good improvement, we can take it a step further and only load the branches when the flyout is opened but let's start with limiting to the 15 most recent branches.

We need someone with a "real" large repo to test this (mine was created *ad hoc* and its branches are already sorted by latest commit).
Loading time may vary a lot on a "real" repo.
I tried to refactor the code so that it would get only the `HEAD` branch, but still I got an improvement of only `0.1 seconds` on average. I think this is caused by my repo, on "real" ones that might change a lot

**Comment by yaira2** [comment] 2023-07-21 01:50
@soleon can you check if there is an improvement in v2.5.20?

**Comment by soleon** [comment] 2023-07-21 02:13
@yaira2 I'm still getting a lot of dead locks or UI freezes in 2.5.20 when I jump between different folders in this big repo. CPU wasn't maxed out but was still relatively high for most of the time. The UI froze before any git columns and icons of the files/folders in some of the bigger folders were populated.
![image](https://github.com/files-community/Files/assets/780800/b4b464b1-ff3b-4d34-bee7-5227273c85ee)
![image](https://github.com/files-community/Files/assets/780800/5cae0ab3-3342-4240-b236-639a21967ece)

**Comment by yaira2** [comment] 2023-07-21 03:23
Thank you for the updated report

**Comment by yaira2** [comment] 2023-07-21 03:26
Is this repo open source? I'd like to try and reproduce this on my side.

**Comment by yaira2** [comment] 2023-07-21 04:03
I was able to reproduce this after switching between a number of different folders in the Files repo.

**Comment by soleon** [comment] 2023-07-21 08:28
@yaira2 unfortunately this is a proprietary repo ☹️ glad that you were able to reproduce it 🙂

**Comment by rudolphos** [comment] 2023-08-21 21:16
Similar issue on Windows 10. CPU usage is around 20-30% after opening Files app and browing folders and scrolling. Tried doing the same on native File explorer and at max it was maybe 5%.

**Comment by yaira2** [comment] 2023-09-03 20:42
@soleon we made some improvements to auto hide the git columns in the latest preview build, can you check if this issue is resolved when using the default settings?

**Comment by leonzhou-smokeball** [comment] 2023-09-04 06:53
@yaira2 tested in 2.5.25.0, same problem still persists regardless of if I hide all Git columns or not. I could see the Git Status column by default in this version, and I hid it by right clicking on it > Git > uncheck Git Status. This column comes back after going to a different folder. The same performance issue persisted even after I manually hid the Git Status column and restarted Files.

**Comment by yaira2** [comment] 2023-09-28 22:34
I just tested with and without the Git columns and the cpu usage is about the same. Can you try cloning the Files repo and seeing how it compares to the Git repo you were previously testing with?

**Comment by soleon** [comment] 2023-09-28 22:57
Tested in 2.5.29.0, the same performance issue persists in the proprietary repo I need to work with every day, which has over 800 branches. The Files repo is completely fine, probably because it only has 8 branches.

Is it not technically feasible to provide a setting to turn off git integration in this app?

**Comment by SemyonL** [comment] 2023-10-04 23:08
Have git repo with few years history and a lot of branches and enormous number of files. CPU is not really spiking working with the repo, but the UI becomes unresponsive when I navigate inside the folders of the repo (scroll does not work, freezes, selecting folder takes like 10+ sec etc). So, navigating inside the repo is just painful experience and I'd say impossible...
![image](https://github.com/files-community/Files/assets/15038488/4d508053-7b6d-4aaf-b9d9-5431330f98f5)

That's good thing that Files tries to integrate with git, but it is very bad thing that UI becomes unresponsive. To me it can spike CPU, do whatever it needs to in the backgroud, but UI should be always responsive no matter what and allow to navigate within the repo folders.

Version: 2.5.29.0

**Comment by ferrariofilippo** [comment] 2023-10-10 20:55
> ferrariofilippo is it possible that it's still enumerating all the branches in the background?

At the moment, the last 15 branches used are cached. To get them, we need to enumerate and sort them all. I think we should not change this approach to keep the `switch branch` flyout responsive.
I guess that making this task a low-priority one might reduce CPU spikes and lag

**Comment by yaira2** [comment] 2023-10-10 21:01
> I guess that making this task a low-priority one might reduce CPU spikes and lag

We should do this and see what the impact is. I suspect it won't be enough, but it'll be good to make some progress on this before v3.

**Comment by mon-jai** [comment] 2023-10-15 10:06
Maybe we could move the git operations to a separate thread, and update the UI when the result is ready?

The UI is buggy for me when opening a folder containing a git repository.

**Comment by mon-jai** [comment] 2023-10-15 10:08
Maybe we could move the git operations to a separate thread, and update the UI when the result is ready?

The UI is laggy for me when opening a folder containing a git repository.

**Comment by SemyonL** [comment] 2023-10-17 10:20
> I guess that making this task a low-priority one might reduce CPU spikes and lag

I believe this won't be enough, because even if it is low priority it will still block the UI thread, so the UI will become ether unresponsive or laggy. Git operations are not that cheap and fast especially for big repositories with thousands of files or long history, because getting commit ids for each file is resource intensive task and libgit does not do perform well with it compared to git.exe. I believe putting all git operations to a separate thread will solve the UI responsiveness issue and freezes.

**Comment by ferrariofilippo** [comment] 2023-10-27 14:37
I'll use this branch to test possible fixes:
https://github.com/ferrariofilippo/Files/tree/Git_Tests

If you want to help me, you may test changes and see if anything gets better (or worse), especially with large repos

**Comment by mon-jai** [comment] 2023-10-27 19:02
@ferrariofilippo I don't have Visual Studio and C# SDK installed in my machine.

Can you help build a `.appinstaller` file for testing?

**Comment by ferrariofilippo** [comment] 2023-10-27 20:51
> Can you help build a `.appinstaller` file for testing?

@yaira2 how can I do that?

**Comment by mon-jai** [comment] 2023-10-27 21:15
Maybe with https://github.com/files-community/Files/pull/13586? (I am not sure)

**Comment by yaira2** [comment] 2023-10-29 14:41
@mon-jai we don't have appinstaller files for dev builds.

**Comment by hez2010** [comment] 2023-10-29 14:49
We definitely need to optimize how we traverse the git history. Instead of looking up the commit info file by file, we would better to get it done once for all per repo.

**Comment by mon-jai** [comment] 2023-10-29 17:21
＠yaira2 How can I help testing it without installing Visual Studio and C# SDK?

> @mon-jai we don't have appinstaller files for dev builds.

Maybe we can setup a GitHub Actions workflow to compile appinstaller files on push?

**Comment by yaira2** [comment] 2023-10-29 18:16
App installer files require setting up a server in the backend, anyways, that's beyond the scope for this issue.

**Comment by mon-jai** [comment] 2023-10-29 18:45
If that is the case, how can I help testing it without installing Visual Studio and C# SDK?

**Comment by yaira2** [comment] 2023-11-07 21:33
@soleon can you check if there is an improvement in #13608?

**Comment by soleon** [comment] 2023-11-08 06:59
@yaira2 I get an error at [line 298 of GitHelpers](https://github.com/ferrariofilippo/Files/blob/Git_Tests/src/Files.App/Utils/Git/GitHelpers.cs#L298): `LibGit2Sharp.LibGit2SharpException: 'request failed with status code: 401'` after navigated to one of the folders in my proprietary git repo. This crashes the whole app.

**Comment by ferrariofilippo** [comment] 2023-11-08 07:28
> @yaira2 I get an error at [line 298 of GitHelpers](https://github.com/ferrariofilippo/Files/blob/Git_Tests/src/Files.App/Utils/Git/GitHelpers.cs#L298): `LibGit2Sharp.LibGit2SharpException: 'request failed with status code: 401'` after navigated to one of the folders in my proprietary git repo. This crashes the whole app.

I'll see if I can fix it

**Comment by ferrariofilippo** [comment] 2023-11-08 10:11
@soleon can you try again? I should have fixed the crash

**Comment by soleon** [comment] 2023-11-08 22:32
@ferrariofilippo @yaira2 the crash bug is fixed in latest [Git_Tests](https://github.com/ferrariofilippo/Files/tree/Git_Tests) branch. But the same problem persists, when browsing any folder in the large git repo, the UI becomes unresponsive, freezes everywhere, the app is unusable.

Also noticed that after I closed the app, the process stayed in the background, so VS didn't exit debug mode until I killed the process. Not sure if this is the expected behaviour.

**Comment by yaira2** [comment] 2023-11-08 22:43
I suggest closing the process and testing when the debugger isn't attached.

**Comment by soleon** [comment] 2023-11-08 22:46
@yaira2 unfortunately, I tested running the app without VS or debugger attached, same freezing issue everywhere browsing the git repo.

**Comment by yaira2** [comment] 2023-11-08 22:47
Can you comment on the PR?

**Comment by yaira2** [comment] 2023-11-23 22:10
I want to thank everyone for their patience on this issue. We're excited to share that the issues have been resolved in our dev branch and will be included in one of the next releases. Additionally, the improvements work even without disabling the Git features on the status bar.

As of now, the status column will still be enabled by default in the Details Layout, but it can be turned off for even better performance.

**Comment by yaira2** [comment] 2023-11-23 22:12
I want to thank everyone for their patience on this issue. We're excited to share that the issues have been resolved in our dev branch and will be included in one of the next releases. Additionally, the improvements work even without disabling the Git features on the status bar. Please thank @ferrariofilippo for their hard work on these improvements!

**Closed** 2023-11-24 01:54 UTC
Labels: bug, help wanted
