### ISSUE TITLE
the transfer percentage is not shown.

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#2659] opened 2020-12-21 19:47 UTC
the percentage is always at zero or complete (100%)
![Captura de tela 2020-12-21 164130](https://user-images.githubusercontent.com/51864325/102816099-335b7600-43ac-11eb-9127-84bbbbc030af.jpg)

**Comment by gave92** [comment] 2020-12-21 19:50
Duplicate of #2244

**Closed by gave92** 2020-12-21 19:50 UTC
Labels: bug
