### ISSUE TITLE
Tabs disappear when app size is two small

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4367] opened 2021-03-29 20:48 UTC
**Explain the bug**
when the window gets too small tab disappear. Same size when the sidebar collapses.

**Expected behaviour**
Tabs should still be displayed maybe smaller or have one tab displayed with an arrow showing the other ones.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6224418/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6224419/debug_fulltrust.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/112897473-9198a300-90d7-11eb-8376-8572d81e07a7.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: v1.5.2.0

**Comment by duke7553** [comment] 2021-03-29 20:55
@josh-65 This is by design as part of the adaptive multitasking behavior. 

You can override this behavior in multitasking settings.

**Comment by duke7553** [comment] 2021-03-29 20:56
I'll close this now, but please open another ticket if you find bugs or would like to suggest a feature that wasn't already reported.

**Closed by duke7553** 2021-03-29 20:56 UTC
Labels: bug, wontfix
