### ISSUE TITLE
Preview File ?

### ISSUE THREAD

**Issue by neztxs** [files-community/Files#4113] opened 2021-03-16 16:57 UTC
**Is your feature request related to a problem? Please describe.**
Nope. i just want to say can you make some folder preview for it and also preview from other file?

**Describe the solution you'd like**
--

**Describe alternatives you've considered**
--

**Additional context**
![image](https://user-images.githubusercontent.com/63047804/111348712-07057c00-86b3-11eb-864f-06278a716123.png)

yes .. like Windows Explorer, which makes it easier for users to find out files more easily and can see a little preview of each file and folder

**Comment by yaichenbaum** [comment] 2021-03-16 17:01
Duplicate of #3326.

**Closed by yaichenbaum** 2021-03-16 17:01 UTC
