### ISSUE TITLE
Files unexpectedly closed while using...

### ISSUE THREAD

**Issue by NDEnterpriser** [files-community/Files#10837] opened 2022-12-24 10:32 UTC
### Description

All of sudden the app closed while using, and a message saying "We've run into a problem"

### Steps To Reproduce

It happend all of a sudden

### Steps to fix

It should be fixed...

### Files Version

Version: 2.4.2.0

### Windows Version

Windows 10 21H2 19044.2006

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10298380/debug.log)

**Comment by QuaintMako** [comment] 2022-12-24 10:48
Could you describe what you were doing when Files crashed? While the logs can point us to some problems, a procedure would be of use as well. Also, are you able to reproduce it?

**Comment by hecksmosis** [comment] 2022-12-24 11:13
This looks like some kind of firewall issue, with the DNS not resolving the domain name

**Closed** 2023-01-06 03:28 UTC
Labels: bug, more-info
