### ISSUE TITLE
Application crashes when attempting to show folder properties in system partition

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#2583] opened 2020-12-11 15:38 UTC
**Describe the bug**
Files crashes when trying to get folder property in system partition.

**To Reproduce**
1. Go to application
2. Click open system partition
3. Try to get any folder properties
4. Application crashes inmediately.

**Expected behavior**
To show the property of the selected folder.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.685 Windows Feature Experience Pack 120.2212.551.0]
 - App version: [v0.21.5.0]

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5680091/debug.txt)

**Comment by yaichenbaum** [comment] 2020-12-11 17:57
Duplicate of #2537.

**Closed by yaichenbaum** 2020-12-11 17:57 UTC
Labels: bug
