### ISSUE TITLE
No longer showing files in Windows 10 build 19041.610

### ISSUE THREAD

**Issue by mdfarragher** [files-community/Files#2181] opened 2020-10-30 15:34 UTC
**Describe the bug**
Files Preview is no longer showing files. It used to work fine until I upgraded Windows to build 19041.610, Since then, Files is no longer showing any files. 

**To Reproduce**
1. Upgrade Windows to build 19041.610
2. Start Files Preview (Microsoft Store version)
3. Files window opens up but is not showing any folders in the left bar.
4. Click on a shortcut folder (Documents or Pictures or ....)
5. File list appears but is empty.

**Expected behavior**
Obviously I expect the app to work normally ;)

**Screenshots**

Home screen:
![image](https://user-images.githubusercontent.com/18468174/97723457-1ac99080-1acc-11eb-9af8-827a05605d2f.png)

After clicking on Documents:
![image](https://user-images.githubusercontent.com/18468174/97723653-519fa680-1acc-11eb-99b3-70d28c62f80f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19041.610
 - App version: 0.18.0.0 (installed from Store)

**Additional context**
Sometimes when I start up the app I get different behavior: the app shows folders in the left bar (Desktop, Downloads, Documents etc) but hangs right away. Clicking anywhere does nothing and I get a wait mouse cursor. I kept the app running for 10 minutes but the app never unfreezes. 

**Log file**
After clicking on the ' Open log location' button, the app hangs for 7 minutes. Then the folder opens with the debug files. See the timestamps in the last two lines of debug.txt. 

Debug.txt: 
2020-10-30 16:07:23.9682|INFO|Files.App|App launched|
2020-10-30 16:07:24.7212|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed|
2020-10-30 16:20:32.3496|INFO|Files.App|App activated|
2020-10-30 16:20:33.1628|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed|
2020-10-30 16:21:03.0113|INFO|Files.App|App launched|
2020-10-30 16:28:29.8291|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed|

Debug_fulltrust.txt:
2020-10-30 16:07:25.1062|INFO|FilesFullTrust.QuickLook|QuickLook detected: True|
2020-10-30 16:20:33.4718|INFO|FilesFullTrust.QuickLook|QuickLook detected: True|
2020-10-30 16:28:30.2541|INFO|FilesFullTrust.QuickLook|QuickLook detected: True|

**Comment by mdfarragher** [comment] 2020-11-01 10:14
Hoo boy, you're right. Disconnected Z: network drive pointing to a cloud share that has been removed. My Windows update was a coincidence because it happened at the same time the share got deleted.

So I guess it's not a bug. 

But maybe Files can only scan the drives on startup and not try to read them right away? That would prevent the hang on startup and mimic the Windows explorer behavior.

**Comment by gave92** [comment] 2020-11-01 10:44
@mdfarragher thanks for confirming this. Files currently has issues with disconnected network drives.
I'm closing this as duplicate of #2144

**Closed** 2020-11-01 10:45 UTC
Labels: duplicate
