### ISSUE TITLE
Context Menu Instability

### ISSUE THREAD

**Issue by geetanshpancholi** [files-community/Files#5599] opened 2021-07-28 06:47 UTC
**Explain the bug**
When i right click in empty space in any drive (not recycle bin), the context menu kind of breaks, more in the video.

**To reproduce**
1. Go to 'Any drive (C:\, D:\ etc)'
2. Right-Click on empty space.
3. See the error

**Expected behavior**
I expected it not to crash and be consistent.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6890870/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6890871/debug_fulltrust.log)

**Screenshots**
Take a video instead,,,

https://user-images.githubusercontent.com/78640436/127276529-bed87a70-4c10-4988-95a4-1046ab5e66b0.mp4

**System Information**
 - OS Version: Windows 11 (Version 21H2; Build 22000.100 )
 - App version: v1.9.15.0

**Additional comment**
This is a permanent problem, i.e., it remains even after system restart.

**Comment by gave92** [comment] 2021-07-28 07:49
Thanks for this report. Closing this as caused by a WinUI issue.

**Closed** 2021-07-28 07:49 UTC
Labels: bug

**Comment by geetanshpancholi** [comment] 2021-07-30 04:17
This has been fixed in the latest update! Thanks!
