### ISSUE TITLE
Thumbnail appear blurred/pixelated

### ISSUE THREAD

**Issue by iseeghosts** [files-community/Files#2685] opened 2020-12-24 09:07 UTC
Blurred thumbnails for many files, probably scaling issues.

**PDF, Videos etc. Files associated with app like Adobe reader or VLC, appear blurred**
Probably a scaling issue after switching to grid view, issue is only with files and not folders, seems to affect (around) first 15 files.

**To Reproduce**
1. Open any folder/location in Files Preview app
2. Switch to grid view (I tried with medium)
3. Thumbnails will be highly pixelated

**Expected behavior**
Scaled thumbnails of the files

**Screenshots**
![image](https://user-images.githubusercontent.com/34771316/103076877-b66f0d00-45f4-11eb-9728-afa7ab202fb1.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 21277.1000
 - App version: v0.23.0.0

**Additional context**
Problem doesn't occur after restart

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5738943/debug_fulltrust.txt)

**Comment by gave92** [comment] 2020-12-24 10:06
Duplicate of #2660

**Closed by gave92** 2020-12-24 10:06 UTC
Labels: bug
