### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by AnphirAddoN** [files-community/Files#2065] opened 2020-10-10 20:47 UTC
To be a beta works perfect really is something to be grateful for all the effort they are doing to achieve such a good file browser, has aesthetics and good functionality, I would like very much to improve in the consumption of resources. At the moment it is my default file browser, thank you very much for the app.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment] 2020-10-11 18:47
@AnphirAddoN Please give us a bit more info on this one. 

- Does it always use too much RAM?

- How about for specific scenarios only like loading a large folder?

- Does memory usage free itself over time compared to what I'd expect from other apps?

Please answer these question and get back to us with the specific details.

**Comment by pitchtheripoff** [comment] 2020-10-19 16:31
Hey, I agree with this. The app uses too much RAM for a file explorer. 58 MB, to be exact. This is way too much especially when compared to the stock Windows 10 File Explorer.
Of course it frees itself once closed but still, this is kind of a problem when not using tabs or using more than 5 tabs.

**Comment by Jaiganeshkumaran** [comment] 2020-10-26 03:46
For me pictures folder, this app consumes over 200 MB in tiles view compared to just 60 in File Explorer. Also, it's very slow in loading in some layout modes.

**Comment by IGoodVibe** [comment] 2020-10-28 19:12
Its uses 60MB with only New Tab opened, the more tabs i open higher the RAM it uses, around 10-15MB for each new tab and that goes up really fast. With the exact same folder oppened in the base Windows Explorer it uses 1/4 of it.
The folders are Program Files, Program Files(x86), Downloads and Downloads again.
Files: 124,3Mb
Explorer: 30,1Mb
Hope i provided more detail about it.

**Comment by duke7553** [comment] 2020-11-30 22:27
> the more tabs I open higher the RAM it uses

This issue is currently being tracked on the WinUI repo as: https://github.com/microsoft/microsoft-ui-xaml/issues/3597

**Comment by d2dyno1** [comment] 2020-12-06 20:25
Maybe because the code is not optimized?

**Comment by duke7553** [comment] 2020-12-08 22:03
@d2dyno1 We have many optimizations in place, but this WinUI ticket is tracking the TabViewItem free-on-close issue. It is a known defect in the TabView control. 

With that said, if you see other areas to optimize, please let us know so we can assign this to you 😀

**Comment by d2dyno1** [comment] 2020-12-08 22:04
> With that said, if you see other areas to optimize, please let us know so we can assign this to you 😀 

Soon...

**Comment by duke7553** [comment] 2020-12-08 22:05
Making this as ongoing because we've made improvements in this area previously, but would still like to consider community feedback as we investigate this problem. This may very well be a "death by a thousand papercuts" scenario, but we are aware of several root causes.

**Comment by duke7553** [comment] 2021-03-07 05:33
We just became aware of a problem with the folder icon SVGs in GridView layout causing memory usage to be inflated 50 percent more than it needed to be. A PR is currently being reviewed to fix that problem as part of our ongoing effort to keep memory usage in check.

**Comment by IGoodVibe** [comment] 2021-03-07 05:50
Thanks for letting us know about that, I'll probably go back to files soon
because of it.

Em dom, 7 de mar de 2021 02:33, Luke Blevins <notifications@github.com>
escreveu:

**Comment by duke7553** [comment] 2021-03-09 02:00
@IGoodVibe We're always improving based on feedback. Give it a try again and let us know! We still haven't fixed all of them yet, but hope to do more work on this in the future.

**Comment by FOkvj** [comment] 2021-05-27 15:27
but it still runs slowly.

**Comment by Erquint** [comment] 2021-12-03 23:26
![Screenshot](https://i.imgur.com/FqdxTyh.png)
I see people reporting numbers around 60 MB…
I just installed it and it's already **half-a-gigabyte** with a couple handfuls of tabs!
And it lags like all hell, taking seconds for a reaction to every click…

**Comment by yaichenbaum** [comment] 2021-12-05 01:31
@Erquint It depends on how many tabs you have open, if you have any ideas on how to fix the memory leaks, please open a PR, we've been having a lot of trouble with this.

**Comment by Erquint** [comment] 2021-12-06 20:42
Of course it does. Files is obviously caching an obscene amount of redundant data for each tab. I won't dive into your sprawling managed codebase. But I'd advise you start with profiling: make tools to reflect clearly all of the data that is stored in memory and work from there to cull, prune and generalize as much of it as you can.

**Comment by yaichenbaum** [comment] 2021-12-06 20:57
> Of course it does. Files is obviously caching an obscene amount of redundant data for each tab. I won't dive into your sprawling managed codebase. But I'd advise you start with profiling: make debugs to reflect clearly all of the data that is stored in memory, its purpose and structure and work from there to cull, prune and generalize as much of it as you can.

@Erquint we've done that many times, unfortunately some of the larger memory leaks trace back to the WinUI library. Microsoft recently announced some fixes that will be shipped and possibly backported to older versions of Windows but we don't know when they will be available. There are memory leaks in the Files codebase that we can fix and we're going our best to do so.

**Comment by d2dyno1** [comment] 2021-12-06 22:52
@Erquint If you happen to find any, make sure to keep us notified!

**Comment by starkgate** [comment] 2021-12-07 09:44
> @Erquint we've done that many times, unfortunately some of the larger memory leaks trace back to the WinUI library. Microsoft recently announced some fixes that will be shipped and possibly backported to older versions of Windows but we don't know when they will be available. There are memory leaks in the Files codebase that we can fix and we're going our best to do so.

I'm glad you're taking it seriously. Files has brilliant features and looks beautiful, but performance still feels sluggish / not as fluid as the default explorer. For me that's it's biggest drawback.

**Comment by barkermn01** [comment] 2022-01-25 23:48
> We just became aware of a problem with the folder icon SVG in GridView layout causing memory usage to be inflated 50 percent more than it needed to be. A PR is currently being reviewed to fix that problem as part of our ongoing effort to keep memory usage in check.

Just on this would it not be better to use multisize `.ico` files vs SVG?

**Comment by THEBOSSMAGNUS** [comment] 2022-02-03 19:27
For me it's about 100mb of ram and 0.2% cpu. But sometimes go up to 300mb for a wile. I think that is quite good, but a improvmante is apreciated.

**Comment by DEADSEC-SECURITY** [comment] 2022-02-04 13:48
For the tab issue wouldnt, it is possible for Files to suspend a tab if it's inactive for more than n time? Could be an option in settings too. This would reduce CPU/RAM consumption since it wouldn't be using those resources for inactive tabs, and after you enter the tab it would reload everything in that tab to memory again. 
I use this system in my browser to reduce consumption and works very well and I don't mind at all it has to reload some tabs that are inactive when I reopen them.

**Comment by yaichenbaum** [comment] 2022-03-08 05:39
Thank you for your feedback, we're continuously working to improve the resource usage of Files.

**Closed by yaichenbaum** 2022-03-08 05:39 UTC
Labels: triage approved, feature request

**Comment by Erquint** [comment] 2022-04-14 19:46
Issue closed without a progress report or a link to relevant release changelog.
Are users to assume that this has been solved and they can go back to trying Files again or is it simply a case of impatient moderation?

**Comment by yaichenbaum** [comment] 2022-04-14 20:08
@Erquint we're continuously working to improve the resource usage of Files.

**Comment by lukeblevins** [comment] 2022-04-14 20:16
@Erquint This wasn't intended to signal anything or trigger user assumptions. Correcting the memory usage issue is an ongoing effort and could continue to be. This is despite the numerous efforts we've made to improve the situation such as reducing clutter in the visual tree, changing our item thumbnail display format, and lazily loading extended item properties. 

Regarding the issue you faced with multiple tabs open, this is an [OS bug](https://github.com/microsoft/microsoft-ui-xaml/issues/3597) in Windows that affects all WinUI apps including Files.

Likewise, if you do encounter elevated memory usage, under a specific condition, that hasn't been reported yet--we'd love to hear about it in a new issue report. If you need help determining whether your specific problem meets the validity bar for a new issue, feel free to message an org member first for guidance.

With that said, we have made progress in a number of ongoing efforts with each release. Feel free to check our release notes for specific details on those efforts.
