### ISSUE TITLE
The type of file changed after I rename some file

### ISSUE THREAD

**Issue by ColbertBrave** [files-community/Files#2317] opened 2020-11-12 02:10 UTC
When I rename some files, the file type will change to "file" instead of the original file type. Please consider solving it. I have to open the native win 10 file explorer every time I need to rename some file. Thanks a lot.

**Comment by gave92** [comment] 2020-11-12 08:01
Happens if you have the option to show the file extension disabled

**Comment by XPoppyX** [comment] 2020-11-12 10:10
Duplicate of #873

**Closed** 2020-11-12 11:27 UTC
Labels: duplicate
