### ISSUE TITLE
Bug: Directly opening library files invokes explorer.exe

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14302] opened 2023-12-27 06:31 UTC
### Description

When a user directly open a library file, it opens in Windows Explorer instead of in the Files, even if Files is set as the default file manager. 

### Steps To Reproduce

1. Set Files as the default file manager
2. Open `~\AppData\Roaming\Microsoft\Windows\Libraries`
3. Double-click on any library (`.library-ms`) file
4. The library opens in explorer.exe
(Note: “Right-click -> Open in new tab” works fine)

### Requirements

The library should open in Files like a common folder

### Files Version

3.0.16.0

### Windows Version

10.0.19045.3803

### Log File

.

**Comment by SakuraKade** [comment] 2023-12-27 10:22
I have managed to reproduce the issue partially but in my case, it does not open when I double-click the Library files.
Just to let you know, opening in new tab works as expected.

I will try to diagnose and fix the issue.

**Comment by SakuraKade** [comment] 2023-12-27 12:33
It looks like opening library folders is not supported yet so it falls back on explorer.exe to open it.

It looks like I can add this feature fairly easily.

**Comment by SakuraKade** [comment] 2023-12-27 12:40
On second thought it looks like someone forgot to add this for double-clicking.

**Comment by Josh65-2201** [comment] 2023-12-27 13:19
Thanks for the report, I've added this to the project board.

**Comment by SakuraKade** [comment] 2023-12-27 13:27
I traced the issue back to this method
```cs
// File: BaseStorageFolder.cs
public static IAsyncOperation<BaseStorageFolder> GetFolderFromPathAsync(string path)
{
	return
		AsyncInfo.Run(async (cancellationToken)
			=> await ZipStorageFolder.FromPathAsync(path) ?? await FtpStorageFolder.FromPathAsync(path) ?? await ShellStorageFolder.FromPathAsync(path) ?? await SystemStorageFolder.FromPathAsync(path));
}
```

There is a missing implementation here.
It does not know how to handle paths to library files.

**Comment by yaira2** [comment] 2023-12-27 15:13
@SakuraKade thanks for the investigation, would you like to work on a fix?

**Comment by SakuraKade** [comment] 2023-12-27 15:33
I am not familiar with the codebase, but I can work on a fix if it gets some pointers.

**Comment by SakuraKade** [comment] 2023-12-27 17:12
Looks like I have to continue tomorrow.

**Comment by SakuraKade** [comment] 2023-12-27 19:52
For later reference where should I add the fix?
Should I add it as another StorageFolder type or
should I implement the fix into one of the existing ones?

**Comment by d2dyno1** [comment] 2023-12-28 00:03
Preferably, try adding it to one of the existing ones 🙂

**Comment by SakuraKade** [comment] 2023-12-28 16:50
This fixes the original problem but needs more testing and refinement.
For now, this is just a draft.
Fork: https://github.com/SakuraKade/Files/tree/fix-for-issue-%2314302

````cs
File: SystemStorageFolder.cs

public static IAsyncOperation<BaseStorageFolder> FromPathAsync(string path)
{
	if (path.EndsWith(".library-ms"))
	{
		// Load xml
		var xml = System.IO.File.ReadAllText(path);
		var doc = new System.Xml.XmlDocument();
		doc.LoadXml(xml);

		// Get the first url tag
		var resolveString = doc.GetElementsByTagName("url")?[0]?.InnerText;
		if (resolveString == null)
			return null;

		// Check if it is a search query
		if (resolveString.StartsWith("search-ms:"))
		{
			// Remove search-ms: from the path
			resolveString = resolveString.Substring(10);

			// Check if the path is a folder
			if (System.IO.Directory.Exists(resolveString))
			{
				// Return the folder
				return AsyncInfo.Run<BaseStorageFolder>(async (cancellationToken) => new SystemStorageFolder(await StorageFolder.GetFolderFromPathAsync(resolveString)));
			}
		}

		// Check if it is a known folder
		if (resolveString.StartsWith("knownfolder"))
		{
			// Get everything between the { and }
			var guid = resolveString.Substring(resolveString.IndexOf('{') + 1, resolveString.IndexOf('}') - resolveString.IndexOf('{') - 1);
			_ = InteropHelpers.SHGetKnownFolderPath(new System.Guid(guid), 0, System.IntPtr.Zero, out var pathPtr);
			string? targetPath = Marshal.PtrToStringUni(pathPtr);

			if (targetPath == null)
				return null;

			return AsyncInfo.Run<BaseStorageFolder>(async (cancellationToken) => new SystemStorageFolder(await StorageFolder.GetFolderFromPathAsync(targetPath)));
		}
	}

	return AsyncInfo.Run<BaseStorageFolder>(async (cancellationToken) => new SystemStorageFolder(await StorageFolder.GetFolderFromPathAsync(path)));
}
````

````cs
File: InteropHelper.cs

[DllImport("shell32.dll")]
public static extern int SHGetKnownFolderPath([MarshalAs(UnmanagedType.LPStruct)] Guid rfid, uint dwFlags, IntPtr hToken, out IntPtr ppszPath);
````

**Comment by yaira2** [comment] 2023-12-29 15:10
It might be worth looking at how libraries are opened from the sidebar to see if there is any code that can be reused.

**Comment by SakuraKade** [comment] 2023-12-29 21:31
@yaira2 Do you know where that code is located?

**Comment by SakuraKade** [comment] 2023-12-30 13:20
I found something suitable from LibraryManager.cs ListUserLibraries() at line 90
and adapted it for this.

````cs
public static IAsyncOperation<BaseStorageFolder> FromPathAsync(string path)
{
	if (path.EndsWith(ShellLibraryItem.EXTENSION))
	{
		try
		{
			using var shellItem = new ShellLibraryEx(Shell32.ShellUtil.GetShellItemForPath(path), true);
			if (shellItem is ShellLibraryEx library)
			{
				var libraryItem = ShellFolderExtensions.GetShellLibraryItem(library, path);
				var firstFolder = libraryItem?.Folders.FirstOrDefault();

				if (firstFolder != null)
				{
					return AsyncInfo.Run<BaseStorageFolder>(async (cancellationToken) => new SystemStorageFolder(await StorageFolder.GetFolderFromPathAsync(firstFolder)));
				}
			}
		}
		catch (Exception e)
		{
			App.Logger.LogWarning(e, null);
		}
	}

	return AsyncInfo.Run<BaseStorageFolder>(async (cancellationToken) => new SystemStorageFolder(await StorageFolder.GetFolderFromPathAsync(path)));
}
````

**Comment by yaira2** [comment] 2023-12-31 00:36
Is it ready for a PR?

**Comment by SakuraKade** [comment] 2023-12-31 12:31
Almost just need to clean up the usings and rebase.

**Comment by SakuraKade** [comment] 2023-12-31 15:04
It's ready

**Comment by yaira2** [comment] 2024-01-09 21:17
@SakuraKade thank you for the fix! This issue will be resolved in the next update.

**Closed by yaira2** 2024-01-09 21:17 UTC
Labels: bug
