### ISSUE TITLE
Can't open file in Files if opening it from Visual Studio context menu

### ISSUE THREAD

**Issue by v-zubritsky** [files-community/Files#3213] opened 2021-01-21 14:35 UTC
**Describe the bug**
`Files` crashes, when using `Open containing folder` context action in `Visual Studio`. The same action works as expected in `Explorer`.

**To Reproduce**
1. Open `Visual Studio`;
2. Open any solution;
3. Open any file in the solution explorer;
4. Click `Open containing folder` context action on the file tab. 

**Expected behavior**
`Files` is opened in the requested directory and specific file is focused.

**Actual behavior**
`Files` splashscreen appears for a moment. Error notification is displayed inside `Visual Studio` then.

**Screenshots**
<img width="274" alt="VisualStudio_UI" src="https://user-images.githubusercontent.com/5411526/105364340-1d8cdb00-5c0e-11eb-95f5-bdbcc1e2283c.png">
<img width="290" alt="VisualStudio_Error" src="https://user-images.githubusercontent.com/5411526/105364338-1cf44480-5c0e-11eb-9677-c6fdaffa1221.png">

**Desktop (please complete the following information):**
OS Name:     Windows
OS Version:  10.0.18363
OS Platform: Windows
RID:         win10-x64
Files version: 1.1.0.0
Visual Studio version: Visual Studio Community 2019 16.8.3

**Additional context**
Tried to find any other apps with similar file explorer integration – a few works as expected, seems like `Visual Studio` is the only crashing so far. File isn't focused though even if directory is opened (and that's actually sth else to look into, as it's quite bugging). 

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5849943/debug.txt)

**Comment by gave92** [comment] 2021-01-21 19:36
Are you opening visual studio as administrator?

**Comment by v-zubritsky** [comment] 2021-01-22 08:35
@gave92 yes

**Comment by gave92** [comment] 2021-01-22 08:47
@v-zubritsky well, don't xD visual studio will try to launch Files as administrator too, but UWP apps can't do that.

Closing this as duplicate of #3117 (same  cause)

If starting VS as normal user does not fix the issue please let us know and we'll reopen this issue

**Closed by gave92** 2021-01-22 08:47 UTC
Labels: bug

**Comment by v-zubritsky** [comment] 2021-01-22 08:55
@gave92 Could confirm, it works from non admin VS. Unfortunately it's not an option for me.

Any plans for the `Files` to be distributed as a desktop app? (dunno the specifics, so can't guess whether it's possible at all).
Also should I create another issue for file not being focused after it's opened? Haven't found any similar requests in the repo.
