### ISSUE TITLE
Bug: OneDrive status isn't displayed when Always on demand is turned off

### ISSUE THREAD

**Issue by Thane5** [files-community/Files#12183] opened 2023-04-24 11:31 UTC
### Description

There seems to be an issue where OneDrive file-status icons are so tiny that they are almost unreadable:

Interestingly, they sometimes initially seem to have the correct size, but in such a case, the file for some reason has a low-resolution thumbnail or filetype icon.
![image](https://user-images.githubusercontent.com/13683581/233981686-86f9f568-ce09-46cc-a00d-c13164c5c9e6.png)

Then, when i hit "F5" to refresh the window, it generates a proper thumbnail, and displays the small OneDrive icons. 
![image](https://user-images.githubusercontent.com/13683581/233981704-a8279979-af17-4241-8227-aa994d39e795.png)

However at other times, pressing F5 is not necessary, as it displays the high-res thumbnail and tiny icons right away. I guess that specifically could also be considered a seperate issue.

### Steps To Reproduce

1. Open a OneDrive folder with files in it
2. Set "Layout" to "Medium sized symbols" to see the previews or file-type icon
3. If the thumbnails are blurry, hit F5 to refresh the current folder.

### Requirements

1. Make sure that the icons are always displayed at a size where they are well readable
2. Make sure that the thumbnails/file-type icons always have a consistent resolution, preferably the high-quality version by default, without requiring F5 to be pressed.

### Files Version

2.4.66.0

### Windows Version

10.0.22621.1555

### Log file

[debug.log](https://github.com/files-community/Files/files/11309826/debug.log)

**Comment by yaira2** [comment] 2023-04-24 18:05
@Thane5 thank you for reporting this issue, I can't reproduce this in OneDrive but it's interesting to note that I see the outline versions of the icons.
![image](https://user-images.githubusercontent.com/39923744/234079534-80983094-7e93-4ace-b616-45278c74c179.png)

**Comment by Thane5** [comment] 2023-04-26 08:03
That's weird, i've never seen these icons before. Do you have Insider builds enabled in the OneDrive settings? 
I do not and my version is Build `23.076.0409.0001 (64-Bit)`

**Comment by Jay-o-Way** [comment] 2023-04-26 14:37
Who's on Windows 10 and who on 11?

**Comment by Josh65-2201** [comment] 2023-04-26 14:38
There both on Windows 11

**Comment by yaira2** [comment] 2023-09-21 21:43
@Thane5 this issue appears to be resolved in the latest preview build, can you give it a try and confirm if it's fixed for you as well? https://files.community/download/preview

**Comment by Thane5** [comment] 2023-09-22 11:08
I just downloaded the insider preview, and i immediately noticed that the OneDrive icons are still tiny once the file icon has finished loading. 

Then a bit later, i also managed to run into the same bug that i initially submitted here (though this time when i switched into the "tiled" view):
Here, the loading process again seemed to have gotte stuck, and there was a "loading" symbol displayed at the top left that would not go away on its own.
![Screenshot 2023-09-22 130052](https://github.com/files-community/Files/assets/13683581/e640403d-c5c6-4975-908c-80089693fed6)

Once i hit F5 to reload, that was gone and all the icons remaind sharp, but unfortunately with the tiny OneDrive icons.
![Screenshot 2023-09-22 130132](https://github.com/files-community/Files/assets/13683581/aaa12a72-078d-45c9-8e1b-cf5bff4bf129)

**Comment by yaira2** [comment] 2023-09-22 16:08
That's odd, in my case the icons are displayed like this.
![image](https://github.com/files-community/Files/assets/39923744/348ee035-752a-409d-9d35-c49635f75fff)

@gave92 do you have any ideas why this is happening?

**Comment by mdtauk** [comment] 2023-09-22 16:31
Those icons would be part of the icon overlay API

**Comment by Thane5** [comment] 2023-10-16 11:48
It really is strange that you are seeing these very different icons. I've looked at two other windows 11 systems, and they only show my colored icons as well. 

Also, is that last screenshot from windows explorer or from the files app? I am wondering because my files beta app can not display this "status" column:
![image](https://github.com/files-community/Files/assets/13683581/f2c72e3f-89d9-4855-b05f-83f6aee45dbc)

**Comment by yaira2** [comment] 2023-11-21 22:42
@Thane5 is this also an issue in the details layout?

**Comment by Thane5** [comment] 2023-11-22 09:51
In the detailled list view, the icons seem to be a little bit bigger. But still not well readable.
![image](https://github.com/files-community/Files/assets/13683581/2d75fd1e-9500-4fb3-953d-ffff076368c0)

**Comment by hez2010** [comment] 2023-11-22 10:34
What's the version of your OneDrive client?

**Comment by Thane5** [comment] 2023-11-22 11:00
Build 23.226.1031.0003 (64-Bit)

**Comment by yaira2** [comment] 2023-11-22 15:11
What about in the status column?

**Comment by yaira2** [comment] 2023-11-22 18:24
It should be visible by default but if not, you can right click the column headers and toggle "Status".

**Comment by Thane5** [comment] 2023-11-22 18:55
Unless i am missing something here, I'm pretty sure i don't have this option. 
It almost feels like we are talking about two different programs here.

https://github.com/files-community/Files/assets/13683581/6facd542-e67c-4ad8-8980-4e0c6046b401

**Comment by yaira2** [comment] 2023-11-22 19:04
Can you try updating your OneDrive client?

**Comment by Thane5** [comment] 2023-11-22 19:15
Since OneDrive can not be updated manually, i enabled the preview builds for it. After doing so and restarting my PC, this seems to have messed up my OneDrive integration into Windows explorer - the status icons are now completely gone. I'll definitely go back to stable builds again.

The "Status" option is still not there either.

**Comment by yaira2** [comment] 2023-11-22 19:26
You can download the latest version of OneDrive from here https://support.microsoft.com/en-us/office/onedrive-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0?ui=en-us&rs=en-us&ad=us

**Comment by Thane5** [comment] 2023-11-22 19:31
I ran the installer and it said i would have to uninstall the existing OneDrive installation first. But since i am on build 23.231.1107.0002 and the installer is only at 23.204.1008.0002, my OneDrive must already be running the latest version.

**Comment by yaira2** [comment] 2023-11-22 19:33
Before you said `23.226.1031.0003` , can you clarify which build you're currently using?

**Comment by Thane5** [comment] 2023-11-22 19:36
After disabled the OneDrive preview builds, it reset me to version 23.231.1107.0002.

![image](https://github.com/files-community/Files/assets/13683581/f83e2413-d991-4d68-909c-6b918639c43c)

**Comment by Thane5** [comment] 2023-11-22 19:58
Ah, it seems that the column appears only if i enable the "Files on demand" feature. But that doesnt explain why i had these small sync icons previously. I'll see if they come back after this on demand feature has turned itself off again.

**Comment by yaira2** [comment] 2023-11-22 20:54
That's good to know, the small sync icons are provided as part of the File Explorer thumbnail system. The icons in the status column are manually detected by Files and should be more reliable but we'll have to see if we can enable them when "Files on demand" is turned off.

**Comment by yaira2** [comment] 2024-01-26 01:11
@Thane5 apparently this is by design. The OneDrive status is only available when Files On Demand is enabled. https://answers.microsoft.com/en-us/msoffice/forum/all/missing-onedrive-status-column/d93f3868-7d28-4fcb-b86e-22b55860e6b9.

Regarding the mini/blurry icons, we're tracking the issue in #10493. You can add a comment or click the subscribe button to be notified of any changes.

**Closed by yaira2** 2024-01-26 01:11 UTC
Labels: bug
