### ISSUE TITLE
Bundles Not Saved and Can't Add More

### ISSUE THREAD

**Issue by pc-v2** [files-community/Files#5395] opened 2021-07-09 22:22 UTC
**Explain the bug**
1. The bundles not saved after closing the app
2. Can't add more bundles
3. Can't rename it

**To reproduce**
1. Enable Bundles Widget
2. Add folder or things to bundles
3. Add more bundles (this one is not appear)
4. Exit the app
**Expected behavior**
The bundles should stay and can add more than one

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6794133/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6794134/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/58063311/125141179-7f022100-e13e-11eb-92a8-31deceb8008d.png)

**System Information**
 - OS Version: Windows 10 21H2 21390.2025
 - App version: v1.5.62

**Comment by yaichenbaum** [comment] 2021-07-11 02:53
Duplicate of #5255.

**Closed by yaichenbaum** 2021-07-11 02:53 UTC
Labels: bug
