### ISSUE TITLE
Layout Per Folder Feature Request

### ISSUE THREAD

**Issue by Brandon-Hughes-MSCS** [files-community/Files#2114] opened 2020-10-18 18:48 UTC
**Is your feature request related to a problem? Please describe.**
Setting a Layout setting on one folder switches all folders i view to switch to that layout. so for downloads i normally use details and photos i use small thumbnails. but i have to consistently switch the layout.

**Describe the solution you'd like**
Make it so that each folder can have a its each own layout saved. so every time i go back to that folder it has that layout and same with other folders.

**Describe alternatives you've considered**
easier to access layout switcher rather than right clicking and selecting layout.

**Additional context**
This app is amazing in its current stat, just having that layout issue makes it a bit frustrating to use.

**Comment by XPoppyX** [comment] 2020-10-18 19:04
Duplicate of #530

**Closed** 2020-10-18 19:06 UTC
Labels: feature_request
