### ISSUE TITLE
Context Sub-menus remain on screen when switching apps

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#6922] opened 2021-11-15 11:21 UTC
### Description

When an sub menu of the context menu is showing and for any reason the active app is switched (taskbar, popup window, etc) the context menu is hidden but the submenu remains until the next time a context menu is shown. The sub menus from the drives pane are even stacking up and not hiding ever again.

![image](https://user-images.githubusercontent.com/8855055/141773357-e9aa39f1-3271-4178-bcb5-c0841c26c25d.png)

### Steps To Reproduce

right click on any item that can show a context menu, hover the mouse over any item that has a sub menu until the submenu shows up, then click on another app in the taskbar, then switch back to files. The submenu still shows up and hides only when another context menu is invoked.

### Expected behavior

close all menus when losing focus, or alternatively keep all menus open.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by gave92** [comment] 2021-11-15 20:02
Could be a WinUI issue but we should be able to fix this by listening to the Closing event of the main menu and close all submenus.

**Comment by yaichenbaum** [comment] 2022-10-13 16:43
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by Josh-65** [comment] 2022-10-13 16:46
Don't think so I can't reproduce with the steps given.

**Closed** 2022-10-13 16:51 UTC
Labels: bug, more-info
