### ISSUE TITLE
Theme mode returns to "Windows Default" when restarting the app

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3291] opened 2021-01-25 15:53 UTC
When I change the theme mode then I close and open the app again, it is back to "Windows default"
_Nothing useful in the log_

![theme](https://user-images.githubusercontent.com/61259627/105729213-c0de3880-5f0b-11eb-84a6-e89326648713.gif)

**Comment by Ein-Tim** [comment] 2021-01-26 16:00
Not reproducible on my machine

**Comment by XPoppyX** [comment] 2021-01-26 16:18
What version, microsoft store or dev?

**Comment by Ein-Tim** [comment] 2021-01-26 17:19
Microsoft Store. Are you on dev? If yes, sorry, I'm new to Files so I did not know that Dev version bugs and normal version bugs are not collected separately (or are labeled in some way)

**Comment by yaichenbaum** [comment] 2021-01-26 20:06
@winston-de Can this be from the changes you recently made to fix the issue with the preview pane opening at the wrong time?

**Comment by winston-de** [comment] 2021-01-26 20:13
@yaichenbaum I don't see how. All I did in my changes was move from using a VisualStateManager to adjust the layout of the preview pane (in ```ModernShellPage.xaml```) to instead doing it programmatically. I didn't change any of the code for settings.
I'll double check anyway, though.

**Comment by winston-de** [comment] 2021-01-26 20:47
@yaichenbaum Yeah, it doesn't look the issue was introduced in that PR. 
I think the issue may be caused by the [selected theme property's](https://github.com/files-community/Files/blob/5f686bf611770cea02dc746a7d41fb5be1acd938/Files/Helpers/ThemeHelper.cs#L44) setter and getter saving to and reading from two different locations, but I'm not certain.

**Comment by tsvietOK** [comment] 2021-01-26 21:45
I think it is because of 0e937777bfbafdb30f5ebe1c398a0e98f6bb754a

**Comment by yaichenbaum** [comment] 2021-01-26 23:33
> @yaichenbaum Yeah, it doesn't look the issue was introduced in that PR.
> I think the issue may be caused by the [selected theme property's](https://github.com/files-community/Files/blob/5f686bf611770cea02dc746a7d41fb5be1acd938/Files/Helpers/ThemeHelper.cs#L44) setter and getter saving to and reading from two different locations, but I'm not certain.

Thanks for checking it out, it looks like @tsvietOK found the issue.

**Comment by AndyMDoyle** [comment] 2021-01-27 17:42
Looking in to this now.

**Comment by yaichenbaum** [comment] 2021-02-14 00:06
@XPoppyX This issue should be resolved with #3321.

**Closed** 2021-02-14 00:05 UTC
Labels: bug, triage approved
