### ISSUE TITLE
Dragging files from 7Zip File Manager will result in UWP app crash

### ISSUE THREAD

**Issue by GreatRequest** [files-community/Files#2176] opened 2020-10-30 02:18 UTC
**Describe the bug**
I use 7Zip to unzip most of my files, as I'm sure you are aware there are two ways to unzip the files one is to do it through the context menu and the other is by opening the file directly in the 7Zip File Manager (if you need only one file from the zip like in my case). I was trying to export one file but as soon as I dragged the file to the UWP explorer it crashed.

**To Reproduce**
1. double click on any zip file (like .zip, .rar, .7zip), 7Zip File Manager should open.
2. Drag any file from the zipped folder to the desktop or the document folder

**Expected behavior**
UWP App Crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Business Insider Preview
 - OS Version: 2004
 - OS Build: 20241.1005
 - App version: [v0.11.0]

**Additional context**
I guess this is something to do with how Windows handles temp files since it got to first unzip them to a temp location and than pull them to the dir you dropped it in.

**Log file**
here is the most interesting part:
```
2020-07-20 02:16:34.8786|ERROR|Files.App|Path cannot be the empty string or all whitespace.
Parameter name: path|System.ArgumentException: Path cannot be the empty string or all whitespace.
Parameter name: path
   at System.IO.Directory.GetParent(String) + 0xb3
   at Files.BaseLayout.<>c.<List_DragOver>b__63_0(IStorageItem) + 0x1c
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1, Func`2) + 0xb7
   at Files.BaseLayout.<List_DragOver>d__63.MoveNext() + 0x158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_10[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x1279be0

```
[log.zip](https://github.com/files-community/Files/files/5462580/log.zip)

**Comment by yaichenbaum** [comment] 2020-10-30 16:52
Duplicate of #2023.

**Closed by yaichenbaum** 2020-10-30 16:52 UTC
Labels: bug
