### ISSUE TITLE
Bug: Installing multiple fonts triggers multiple UAC prompts

### ISSUE THREAD

**Issue by D-Maxwell** [files-community/Files#14503] opened 2024-01-21 00:29 UTC
### Description

I believe the title says it all.
Trying to run Files as an elevated process beforehand does not solve this as it calls external powershell scripts.

### Steps To Reproduce

1. Download font bundle
2. Extract
3. Select all
4. Install for all users

### Requirements

Permission should only be asked for once.
Perhaps calling a single script wherein lies a single loop, given paths to all selected files, could do the job ?

### Files Version

3.1.1.0

### Windows Version

10.0.19045.2788

### Log File

[debug.log](https://github.com/files-community/Files/files/13999601/debug.log)

**Comment by yaira2** [comment] 2024-01-21 00:32
This was supposed to have been done with #14024

**Comment by D-Maxwell** [comment] 2024-01-21 00:39
> This was supposed to have been done with #14024

This is, from my quick glance at the linked issue, unrelated.
I have not reported any crash, but rather a major annoyance that renders a context menu entry practically useless, by spamming the user with UAC prompts. (plus the tiny yet significant delay between each prompt, this effectively locked my machine (twice, because I thought I could fix it, so I tried once more) for multiple minutes)

**Comment by yaira2** [comment] 2024-01-21 00:41
The crash was caused by running multiple scripts at the same time, the fix was to only run a single script as you suggested so I'm surprised that the issue is back.

**Comment by yaira2** [comment] 2024-02-06 21:47
This issue should be resolved in the dev branch and will be included in the next release.

**Closed by yaira2** 2024-02-06 21:47 UTC
Labels: bug
