### ISSUE TITLE
Modern File Manager not showing correct folder size

### ISSUE THREAD

**Issue by StauceanuSamuel** [files-community/Files#8585] opened 2022-03-05 18:26 UTC
### Description

Hey everyone.
These days i found an issue with files app - modern file manager. The issue is that the folder size is not displayed correctly.

I have attached below 2 screenshot where you can see that the same folder has 2 different size.
I am the only one with this problem? If so, how can i fix this problem?

Regards,
Samuel

### Expected behavior

For example: This folder (xilinx) should have been the same size regardless of file explorer i use. (about 65 gb).

### Files Version

Version: 2.1.15.0; OS Version: 10.0.22000.527

### Windows Version

Windows 11 Pro 21H2 22000.527

### Relevant Assets/Logs

![156881765-fa502ca7-0a13-40d1-95e7-50e20e7dcd71](https://user-images.githubusercontent.com/82712305/156894780-ca873b47-37b0-436e-9b9c-00188d254a67.png)

![156881768-23263380-e0a3-40c9-aa56-ae36616dae6c](https://user-images.githubusercontent.com/82712305/156894783-ffde6c60-efa8-44ca-9b2d-01c187702fe7.png)

**Comment by Josh-65** [comment] 2022-03-05 21:47
Have you tried checking on files/folder that are not on the C drive

**Comment by cinqmilleans** [comment] 2022-03-05 21:48
Thanks for your feedback. Could you give more information. What does this folder contain? Is the difference caused by uncounted sub-elements (hidden, system, ...)? Does File Explorer's count seem consistent to you for its actual content? Does this folder contain symbolic links?

**Comment by StauceanuSamuel** [comment] 2022-03-05 21:52
My bad. Seems that is showing the correct size but it took aprox. 8 minutes to scan the entire program. This test was made on my laptop (asus rog strix g713).

![image](https://user-images.githubusercontent.com/82712305/156900844-eaa1a125-fa65-4032-a84c-cf1bcf050d7d.png)
@Josh-65 no because i have only drive C (500 gb). I will get an SSD next week (1 Tb) and i will use it as partition D.

**Comment by Josh-65** [comment] 2022-03-05 21:56
Oh there used to be a loading icon to say it was scanning.

**Comment by StauceanuSamuel** [comment] 2022-03-05 21:57
> Thanks for your feedback. Could you give more information. What does this folder contain? Is the difference caused by uncounted sub-elements (hidden, system, ...)? Does File Explorer's count seem consistent to you for its actual content? Does this folder contain symbolic links?

That folder contain a program (vivado xilinx), a software suite produced by Xilinx for synthesis and analysis of hardware description language (HDL). 

 Does this folder contain symbolic links? ---> I don't think it contains. :)

**Comment by StauceanuSamuel** [comment] 2022-03-05 22:07
> Oh there used to be a loading icon to say it was scanning.

If i right click and hit properties i see a size:
![image](https://user-images.githubusercontent.com/82712305/156901321-8783bd02-fda0-4bf6-8cbe-1b3d9091644f.png)
(no loading icon) after a while the size increases, radicaly. 🙂
I realized that it finished scanning when the result was written in brackets, like this : 
![image](https://user-images.githubusercontent.com/82712305/156901249-becd455e-152b-4821-9b60-6b90b3f544bb.png)

**Comment by Josh-65** [comment] 2022-03-06 00:48
Since this isnt an issue any more i will close this but il make a new one for adding the loading icon back.

**Closed by Josh-65** 2022-03-06 00:48 UTC
Labels: bug
