### ISSUE TITLE
Maintain Sidebar state 

### ISSUE THREAD

**Issue by TDMatthews** [files-community/Files#6469] opened 2021-10-12 19:20 UTC
### Description

Settings allow for sections in the sidebar to be toggled on and off. It is desirable to maintain tsidebar stat (expanded / collapsed) between sessions. Currently closing the application when maximized does not maintain current state and all panels open minimized.

### Steps To Reproduce

- Set a default folder and set 'show drives section' to true.
- Expand drives
- maximize window and close app
- relauch app and drive section is collapsed

### Expected behavior

expanded / collapsed state should be maintained regardless of window state

### Files Version

2.0.13.0

### Windows Version

Windows 11

**Comment by wonrax** [comment] 2021-11-09 06:20
I think Files is remembering the sidebar state, but it's not expanding it correctly when you open a new session. The proof is you have to click twice to make the item expand (gif).

Steps to reproduce:
- Expand Favorites (or anything expandable) in the sidebar
- Close and reopen Files
- The current state of Favorites is expanded, but not visually expanded
- Have to click twice to visually expand the item (the first click is to collapse, and the second click eventually expands the item)

![](https://media.giphy.com/media/c2RzPdsR2woSZeqC2q/giphy.gif)

Version: 2.0.34.0
OS Version: 10.0.22000.282

**Comment by d2dyno1** [comment] 2021-11-12 19:20
Related #4128

**Comment by yaichenbaum** [comment] 2021-11-12 19:39
@d2dyno1 isn't this a duplicate of #4128?

**Comment by d2dyno1** [comment] 2021-11-12 19:54
> @d2dyno1 isn't this a duplicate of #4128?

@yair100 Nope, this issue is about sections not being extended after reopening the app.

**Comment by Korkman** [comment] 2022-01-23 15:44
![grafik](https://user-images.githubusercontent.com/3186931/150685683-3e81f814-3d60-4b46-a2bd-26a4a4da4d7a.png)
![grafik](https://user-images.githubusercontent.com/3186931/150685859-32b91ee6-2787-407b-9b5e-6b2426947894.png)

Definitely some race happening. Note the arrow directions. Up should be expanded, down should be closed. Only when I expand or collapse all items it works as expected.

**Comment by hanskokx** [comment] 2022-01-24 22:33
![Animation](https://user-images.githubusercontent.com/1911919/150876222-42b43260-87d2-4014-b455-75acd5c2b7a9.gif)

**Comment by yaichenbaum** [comment] 2022-04-26 00:45
This issue should be resolved with #9004

**Closed** 2022-04-26 00:44 UTC
Labels: bug, triage approved
