### ISSUE TITLE
Bug: Information about free and used disk space is not displayed completely in several languages

### ISSUE THREAD

**Issue by BiosNod** [files-community/Files#16396] opened 2024-10-28 11:36 UTC
### Description

Issue :
![Image](https://github.com/user-attachments/assets/43ffb83c-478f-446f-8e8c-3806914e2c19)

This issue occurs in the following languages:
![Image](https://github.com/user-attachments/assets/ef6c338a-ab6a-4c01-beb4-1b29d000b85a)
![Image](https://github.com/user-attachments/assets/a08faf16-44c0-44a4-9ea2-058df8d13536)
![Image](https://github.com/user-attachments/assets/f4ef2908-113a-4e23-ad49-860d2d452217)
![Image](https://github.com/user-attachments/assets/81fc42dc-c837-47de-99ef-a056e81fa87c)
and many others...

May be the problem is also slightly related to the appearance of the "i" button when there is little memory left on the disk:
![Image](https://github.com/user-attachments/assets/75305d94-7bd4-4905-b460-d38ce250f4e9)
But in some languages, even without the "i", there are dots:
![Image](https://github.com/user-attachments/assets/7a62c785-8af6-46ad-829e-1ddcaff2789f)

### Steps To Reproduce

1. Change to some language with big words
2. Keep a little space on the disk
3. See dots "..." instead of full size

### Requirements

- see full info about disk
- don't use dots "..." and just use word-wrap if possible or better Increase the width of all tiles with disks so that the text fits on all of them without word-wrap and so that all tiles have the same width
- don't show "i" button  (this causes the information color bar and text to shift) - may be make absolute position at the top right corner

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5011

### Log File

[debug.log](https://github.com/user-attachments/files/17541657/debug.log)
Guess debug log is useless

**Comment by yaira2** [comment] 2024-10-28 14:35
Supporting multiple languages in an app presents many challenges. We strive to balance this by designing the UI to accommodate various languages, ensuring text wraps onto a second line if there's not enough space. However, in some instances, we must trim the text. When this happens, we add a tooltip so you can hover over it to see the full content.

In this specific case, the issue is primarily caused by the information icon, as you rightly pointed out. I believe this can be resolved by ensuring the icon doesn’t reduce the text area's size. While some text may still be trimmed in certain scenarios, the majority will be visible, and the tooltip will provide the remaining details.

**Closed** 2024-10-28 14:55 UTC

**Comment by yaira2** [comment] 2024-10-28 14:57
I've implemented the changes mentioned above. It's worth noting that this is a temporary fix, as we are currently working on a redesign of the home page. The new design should address these issues more effectively.
