### ISSUE TITLE
Grouping or Sorting doesnt not apply to individual folders

### ISSUE THREAD

**Issue by khushrxnx** [files-community/Files#2297] opened 2020-11-10 15:44 UTC
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

**Describe the bug**

When you try to sort a folder in a particular way, every single folder in the application is sorted in the same order. This might even come under a feature suggestion but not sure if its a bug.

**Expected behavior**

It will be great if there was a way to individually sort each folder! Example: I like to sort my Downloads folder by Date and most of my other folders by Name.

**Screenshots**

![Screenshot (1746)](https://user-images.githubusercontent.com/67862114/98695920-9fe65c80-238c-11eb-8a31-3ae607cbd6df.png)

![Screenshot (1745)](https://user-images.githubusercontent.com/67862114/98695936-a379e380-238c-11eb-90d6-473241b83bea.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.541
 - App version: v0.20.0

**Comment by XPoppyX** [comment] 2020-11-10 15:53
Duplicate of #530

**Closed** 2020-11-10 16:38 UTC
Labels: bug
