### ISSUE TITLE
Office and other apps open behind Files

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5291] opened 2021-06-21 02:30 UTC
**Explain the bug**
When users right click on a Microsoft Word Files, ending in `.docx` extension, it will show up a bunch of options such as Edit, New, Print, Open, etc. When I try to click on Edit Button, it opens the document behind the app.

**To reproduce**
1. Right click on a Microsoft Word Document (`.docx`)
2. Click on Edit Option
3. See the error

**Expected behavior**
Documents which are opened via `Edit` Command must be previewed in front the app.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**

https://user-images.githubusercontent.com/69080584/122699207-293f0500-d273-11eb-847b-85c8c05eec63.mp4

**System Information**
 - OS Version: Windows 10 21H1 19043.1055
 - App version: 1.5.0.0

**Additional comment**
Does this problem happen again after restarting the app? Yes this issue also occurs after I have restarted the app.

**Comment by yaichenbaum** [comment] 2021-06-21 03:04
@gave92 can you confirm if this is resolved in `main`?

**Comment by gave92** [comment] 2021-06-21 07:16
I cannot reproduce it on main, but then I never could. I'm not sure my solution works in this case.

**Comment by stanleyowen** [comment] 2021-07-19 14:15
Hi, I have recently update to v1.5.67.0, however this issue is still reproduceable on Edit Command in Microsoft Word. Can you please confirm it?

https://user-images.githubusercontent.com/69080584/126174179-d6c42723-d780-4c0a-9d83-d2b2f713dce5.mp4

**Comment by gave92** [comment] 2021-07-19 17:00
- Do you find this happening also on double click?
- What about right-click + open (first icon at the top of the menu)?
- When it opens in the background does it's icon "flash" on the taskbar?

**Comment by stanleyowen** [comment] 2021-07-20 03:22
1. Do you find this happening also on double click? No, this issue only occurs in Edit Command (as Described in the Title)
2. What about right-click + open (first icon at the top of the menu)? Nope.
3. When it opens in the background does it's icon "flash" on the taskbar? Nope.

As this issue only occurs on Edit Command, I think it will be good categorized as Priority Level 4 (Low). Just to make sure every details have the good functionality.

**Comment by gave92** [comment] 2021-07-20 19:49
No way, I can't reproduce this :/ Only way to cause the issue for me is to click on the Files window immediately after selecting the "Edit" menu.

**Comment by stanleyowen** [comment] 2021-07-21 09:05
> I can't reproduce this :/ Only way to cause the issue for me is to click on the Files window immediately after selecting the "Edit" menu.

Oops my bad, I think I have made an ambiguous title for this issue. That is actually what I mean.

**Comment by Josh-65** [comment] 2022-09-08 21:26
Is this still an issue in 2.3.11.0 or above?

**Comment by yaichenbaum** [comment] 2022-09-08 21:59
It's hard to know since the issue only happens some of the time, let's leave this issue open to see if any more reports come in.

**Comment by gave92** [comment] 2022-09-09 05:47
Hopefully fixed as of #9857

**Closed** 2022-09-09 14:07 UTC
Labels: bug, more-info
