### ISSUE TITLE
Hidden files & folders doesn't update until page refreshed

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#2868] opened 2021-01-06 16:49 UTC
**Describe the bug**
When hidden files & folders are enabled, and you turn that switch off and return to your files, you still see the hidden files until you refresh the page.

**To Reproduce**
1.Turn on "Show hidden files and folders".
2. Make sure you have some hidden files and folders, and open the location that contains them.
3. Return to settings, and turn off "Show hidden files and folders".
4. When you return to your files, the hidden files do not disappear until the page is refreshed.

**Expected behavior**
I expected the hidden files to disappear again when the setting was off, without me having to manually refresh it.

**Screenshots**
https://user-images.githubusercontent.com/76794507/103796096-cdf6be80-5014-11eb-9550-87ec6f3f998f.mp4

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042.685)
 - App version: 0.23.1.0

**Additional context**
Even after restarting the app, the issue is still present.

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5777032/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5777033/debug_fulltrust.txt)

**Comment by gave92** [comment] 2021-01-06 16:51
Duplicate of #2857

**Closed by gave92** 2021-01-06 16:51 UTC
Labels: bug
