### ISSUE TITLE
set lateral menu to always open in reduced mode

### ISSUE THREAD

**Issue by baldaiacharles** [files-community/Files#4500] opened 2021-04-07 22:51 UTC
Every time I open files, I have to click on the upper left for it to go from expanded lateral menu to small, it would be nice to configure it to always open the way I prefer it. 

this is what e mean to expanded 
![image](https://user-images.githubusercontent.com/70418775/113944210-8d0c7280-97da-11eb-8174-a9a577733d3c.png)

and this is small
![image](https://user-images.githubusercontent.com/70418775/113944242-9dbce880-97da-11eb-84a2-23159216daaa.png)

**Comment by yaichenbaum** [comment] 2021-04-08 00:02
@nvi9 Can you see if this issue is resolved in `main`?

**Comment by nvi9** [comment] 2021-04-09 09:01
> @nvi9 Can you see if this issue is resolved in `main`?

@yair100 I can reproduce the same in `main`.
It seems to be set by the `NavigationView` control when loading, either the setting what stores the open state was `true` or `false`:

1. this property is set to `true` by the binding on the control https://github.com/files-community/Files/blob/abde6e2adc71abdc735e80f1d7bb3f4ff2985b17/Files/UserControls/SidebarControl.xaml.cs#L55-L65
2. what updates the setting here https://github.com/files-community/Files/blob/abde6e2adc71abdc735e80f1d7bb3f4ff2985b17/Files/ViewModels/AdaptiveSidebarViewModel.cs#L42-L58

**Comment by yaichenbaum** [comment] 2022-03-08 16:37
This issue appears to be resolved in `main`.

**Closed by yaichenbaum** 2022-03-08 16:37 UTC
Labels: investigate
