### ISSUE TITLE
Bug: Show checkboxes when selecting items isn't applying in the grid layouts

### ISSUE THREAD

**Issue by FF69B3** [files-community/Files#12181] opened 2023-04-24 06:16 UTC
### What feature or improvement do you think would benefit Files?

It only work in details mode,this is bug?

### Steps to reproduce

- Turn off option to show checkboxes when selecting items
- Switch to grid layout
- Select an item
- Checkbox is visible 

### Steps to fix
Only show checkbox when explicitly hovering over it

### Files Version

2.4.67

### Windows Version

10.0.22621.1485

**Comment by yaira2** [comment] 2023-04-24 11:53
> It only work in details mode,this is bug?

What only works in details mode?

**Comment by FF69B3** [comment] 2023-04-24 13:57
@yair100  settings-folders-show checkbox when selecting items

**Comment by hishitetsu** [comment] 2023-04-24 23:58
I can't reproduce it.
![image](https://user-images.githubusercontent.com/66369541/234140134-b2051f62-9456-4d4a-be9c-76dde5164e8a.png)

**Comment by yaira2** [comment] 2023-04-25 00:00
What happens if you select a single file?

**Comment by hishitetsu** [comment] 2023-04-25 00:00
No problem.
![image](https://user-images.githubusercontent.com/66369541/234140341-83dfccf8-3501-4108-b8b4-e861a7a37f91.png)

**Comment by yaira2** [comment] 2023-04-25 04:38
> I can't reproduce it. The checkbox is shown only when explicitly hovering over it.

This is what we decided upon but after trying this out for a couple of days, I can see why this is causing confusion.

**Comment by yaira2** [comment] 2023-04-30 22:47
@FF69B3 this issue will be resolved in one of the next releases (most likely v2.5).

**Closed** 2023-04-30 22:46 UTC
Labels: bug, good first issue
