### ISSUE TITLE
Feature: Select correct file when using "Open file location"

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#9390] opened 2022-06-11 18:02 UTC
**Reequipment**
- Right clicking on a recent item or shortcut and clicking on "Open file location" should select the file when the location is opened.
- The selected item should be scrolled into the view

### Files Version

2.3.0.0

**Comment by gave92** [comment] 2022-06-11 18:04
Could you confirm whether the file is really not highlighted or the issue is "just" that the list does not scroll down to it?

**Comment by MalteTasler** [comment] 2022-06-13 01:47
I have to correct myself, it does indeed get highlighted. It just does not scroll to that position. I apologize.

**Comment by MalteTasler** [comment] 2023-02-23 02:19
should this be merged with https://github.com/files-community/Files/issues/6382 ? @yair100 @Josh-65

**Comment by yaira2** [comment] 2023-08-06 14:45
@MalteTasler this feature is implemented in the dev branch and will be included in the next release.

**Closed** 2023-08-06 14:44 UTC
Labels: feature request
