### ISSUE TITLE
Add Better Downloads

### ISSUE THREAD

**Issue by EpixyKing101** [files-community/Files#2017] opened 2020-10-01 17:32 UTC
Hello, I've been using Files for a while, and on thing I always hate is the downloads area in the application. It's nothing like the one in normal File Explorer. For example, I'll sort it by date, but the folders **ALWAYS APPEAR AT THE BOTTOM**.
![image](https://user-images.githubusercontent.com/72221097/94842738-9999b380-03d0-11eb-9ad2-c9e879cd1afa.png)
And this is Files:
![image](https://user-images.githubusercontent.com/72221097/94842932-d1a0f680-03d0-11eb-9c13-dcef6b90e230.png)
But if I scroll to the bottom(which I hate doing):
![image](https://user-images.githubusercontent.com/72221097/94843054-0319c200-03d1-11eb-8589-5bbe7b706c4a.png)
Then I see it. Is there a way to make it look better, or can you add better support for this? Over all, it's a great app, especially now that the right click issue is fixed, but this is just the one thing the bugs me. Thanks!

**Comment by yaichenbaum** [comment] 2020-10-01 20:41
Duplicate of #131.

**Closed by yaichenbaum** 2020-10-01 20:41 UTC
Labels: feature_request, needs-triage
