### ISSUE TITLE
Trying to open folder was extremely slow, and then the whole Files window disappeared

### ISSUE THREAD

**Issue by eamodio** [files-community/Files#3373] opened 2021-01-31 21:07 UTC
**Describe the bug**
I tried to open/switch to few folders, and it was really slow -- the progress indicator spun for at least a few seconds (and this is on a very fast local SSD). And on the 3rd folder I tried to open, it just spun for 10+ seconds until the window completely disappeared. While I haven't been able to reproduce the extreme slowness since, the app still feels quite slow to switch to folder (worse for the first time the folder was visited).

Opening the same folder in explorer is instant, but it takes 1-4s now. I don't remember this slowness before 1.2.

**To Reproduce**
1. Switch between folders

**Expected behavior**
Switch between folders quickly and not crash

**Desktop (please complete the following information):**
- OS Version: [10.0.19042 Build 19042]
- App version: [v1.2.0.0]

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5900641/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5900642/debug_fulltrust.txt)

**Comment by R3voA3** [comment] 2021-01-31 23:49
Same as in #3380

**Comment by hez2010** [comment] 2021-02-01 05:37
@yair100 I think this might be caused by persistent cache in previous version.
We have changed the cache behavior to store only limited entries, but if users upgrade Files from previous version, they still have old full cache entries in SQLite which leads to long loading time for the first time (cache entries will be updated after first time loaded). This may explain why the performance is worse for the first time the folder was visited.

@eamodio Could you try removing `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\cache.db` and restart Files to see if it helps?

**Comment by eamodio** [comment] 2021-02-01 06:21
Tried that, and I'm not sure I'm seeing much of a difference (maybe slightly?). I also tried with and without caching, and also don't notice too much of a difference -- with caching I don't see it painting the icons of the folders/files when I switch into a folder, but it still takes it 1-2s to show anything.

Another thing I noticed, is that when switching to a folder. When the parent folder is scrolled down and then you try to switch into a child (double-click or enter), it seems to re-paint the parent folder, scrolled to the top, then switches to the child. And then if you go back to the parent, it paints the parent scrolled to the top and then scrolls down.

**Comment by hez2010** [comment] 2021-02-01 06:27
> but it still takes it 1-2s to show anything.
@eamodio Did the progress indicator appear during this "1-2s"?

**Comment by eamodio** [comment] 2021-02-01 06:28
Yeah

**Comment by R3voA3** [comment] 2021-02-01 09:30
Seems like resetting the app improves the performance, making it better, yet not great.

**Comment by Msouza91** [comment] 2021-03-17 00:14
I wouldn't be so sure this issue is related to cache from previous version, I installed files just this week and am experiencing this same problem, trying to move files around or swtching between folders and had crashes or very slow file operations like renaming or deleting.

**Comment by yaichenbaum** [comment] 2021-03-17 00:28
@Msouza91 Please open an issue and include the logs if the app crashes so that we can investigate the issue.

**Comment by Msouza91** [comment] 2021-03-17 03:21
Many of the settings and labels in my version of the app are in arabic, I did not find where to save the log file, is it something I have to enable before the issue happens?

**Comment by gave92** [comment] 2021-06-01 17:58
Closing as folder enumeration speed is improved in main (#4922). Cause for crash during load was also fixed (new details view)

**Closed by gave92** 2021-06-01 17:58 UTC
Labels: bug
