### ISSUE TITLE
Bug: Custom font not used in item preview pane

### ISSUE THREAD

**Issue by i-dont-know-username** [files-community/Files#12027] opened 2023-04-09 12:02 UTC
### Description

![image](https://user-images.githubusercontent.com/110698934/230771125-7e11d0fa-35d0-45b5-9039-c5d82f3067f6.png)
The underlined bits of text are not using the font set in the Settings file

### Steps To Reproduce

1. Set a custom font
2. Open the preview pane

### Requirements

A custom font to be set

### Files Version

2.4.61.0

### Windows Version

10.0.25336.1000

### Log file

[debug.log](https://github.com/files-community/Files/files/11185352/debug.log)

**Comment by yaira2** [comment] 2023-04-14 15:24
@i-dont-know-username thank you for reporting this issue.

**Comment by MrFrawsty** [comment] 2023-04-29 04:30
While looking at this and the other custom font issue I noticed that the Details page uses custom fonts and the general page only partially does. Neither the security or Hashes page use any custom fonts. I'm assuming all the pages should be using custom fonts for all the text? Or is it by design? Thanks! I've attached two images to show what I mean. If this is a totally separate issue I can open one up.

![Files_Properties](https://user-images.githubusercontent.com/26210780/235283429-d99f1fca-be3d-4a80-b7dd-271332e4174c.png)
![Files_General](https://user-images.githubusercontent.com/26210780/235283452-f20f363d-9830-4397-b84e-9a20134c7ef7.png)

**Comment by QuaintMako** [comment] 2023-06-04 17:58
Possible to be assigned to this issue please?

**Comment by QuaintMako** [comment] 2023-06-06 14:00
@MrFrawsty I'm creating a new issue for the inconsistencies you've seen in the Properties window : #12553

**Comment by yaira2** [comment] 2023-06-08 02:58
This issue will be fixed in the upcoming v2.5 release.

**Closed** 2023-06-08 03:21 UTC
Labels: bug, good first issue
