### ISSUE TITLE
Bugs: Opening folders that use the "group by" option opens them scrolled down

### ISSUE THREAD

**Issue by rafaelsouzams** [files-community/Files#6186] opened 2021-09-20 00:47 UTC
### Description

The download folder always takes a while to fully load, and it never starts at the top of the page, I always have to go up to see what's up there!

### Steps To Reproduce

https://user-images.githubusercontent.com/25182245/133948470-4e98940c-f6b3-46db-bfcb-6521f6f4fecc.mp4

### Expected behavior

Load faster and on the first item on the list!

### Files Version

v2.0.13.0

### Windows Version

Windows 10 21H1 19043.1237

**Comment by gave92** [comment] 2021-09-20 05:45
Also #5825, @5819

**Comment by Darhagonable** [comment] 2021-10-30 19:55
One can reproduce this consistently on any system by doing the following:
- Go to C:\Windows\System32
- Sort by date modified, descending
- Refresh
- See how one is now not longer at the top of the directly

**Comment by MrMazzone** [comment] 2022-01-10 00:18
Just saw this.  Closing my issue #7516

**Comment by sguergachi** [comment] 2022-12-05 22:17
This bug is leading me to use File Explorer now because everytime I open a downloaded file from a web browser, it opens in Files and takes around 1 min to fully load the latest downloaded files.

Has anyone found a workaround?

**Comment by Josh-65** [comment] 2022-12-05 22:18
There isn't one. You will have to wait until someone takes a look at the code and fixes it

**Comment by Josh65-2201** [comment] 2024-06-25 10:51
Can you see if this is an issue in 3.5. https://files.community/download

**Comment by sguergachi** [comment] 2024-07-02 21:09
Seems a lot better on 3.5! Would call it fixed for me!

**Closed** 2024-09-01 02:10 UTC
Labels: bug, needs - additional info
