### ISSUE TITLE
Top bar of Files is not being coloured on light color

### ISSUE THREAD

**Issue by BanCrash** [files-community/Files#5498] opened 2021-07-23 13:58 UTC
**Explain the bug**
The top bar has no color at all on light color. Dark color works well though. It's an odd bug since I don't see no one else talking about this...

**To reproduce**
1. Open Files
2. Check the top bar

**Expected behavior**
Should have the right colors.

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6869228/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6869229/debug_fulltrust.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/11770760/126792337-ea9bec1b-2e07-49dc-8728-f47288bf5f93.png)

**System Information**
- OS Version: Windows 10 Pro 21H1 19043.1110 / Windows Feature Experience Pack 120.2212.3530.0
- App version: 1.9.12.0 and last main, I have the issue on both versions.

**Additional comment**
Restarting the app and even the computer didn't solve the issue.

**Comment by mmischitelli** [comment] 2021-07-23 14:09
I fear this is by design. I'm not sure but it should be the fallback colour of the new Mica brush on W10.

**Comment by gave92** [comment] 2021-07-23 16:09
The fallback color was removed in #5482 I think, @winston-de is it possible to bring it back?

**Comment by winston-de** [comment] 2021-07-23 16:42
I removed the conditional xaml statement because it was causing crashes on startup (``could not find resource of key RootBackgroundBrush``). Anyway, the colors do seem to be off (in the windows 11 preview too), I'll make a pr to fix them.

**Comment by yaichenbaum** [comment] 2021-07-25 02:48
This issue should be resolved with #5507.

**Closed by yaichenbaum** 2021-07-25 02:48 UTC
Labels: bug, fixed
