### ISSUE TITLE
Admin permission prompt not showing + screen flickers when changing between tabs in settings

### ISSUE THREAD

**Issue by swolenutz1951** [files-community/Files#4275] opened 2021-03-24 15:07 UTC
Main problem: Tasks that require admin permissions do not trigger the prompt when creating new files, pasting etc.
Another problem: When moving between tabs in the settings interface the window flickers 

**To reproduce main**
1. Go to a folder that requires admin access
2. Try and create a new folder / file etc
3. No prompt is displayed 

**To reproduce 2nd issue**
1. Open Files
2. Open settings
3. Move between options on left

**System Information**
 - OS Version:  Windows 10 20H2 19042.870
 - App version: v1.5

**Comment by yaichenbaum** [comment] 2021-03-24 15:31
Duplicate of #2513.

**Closed by yaichenbaum** 2021-03-24 15:31 UTC
Labels: bug

**Comment by swolenutz1951** [comment] 2021-03-24 15:36
Apologies I never seen this in my search!

How about the screen flickering?

**Comment by yaichenbaum** [comment] 2021-03-24 15:43
@swolenutz1951 Can you upload a screen recording of that?

**Comment by swolenutz1951** [comment] 2021-03-24 16:03
Not the best quality, but u can see a slight flickering on the right side.
On my end the flicker is a lot more prominent.

https://user-images.githubusercontent.com/81313695/112342685-57d03280-8cba-11eb-9d41-4f773d157aaa.mp4

**Comment by yaichenbaum** [comment] 2021-03-24 16:12
@swolenutz1951 I see what you're talking about, it might just be a platform issue since we aren't doing anything special here. It might also have to do with the specifications of the device because I don't see the issue on my end.
