### ISSUE TITLE
Store sort criteria per folder

### ISSUE THREAD

**Issue by Sigurdur42** [files-community/Files#2247] opened 2020-11-06 07:58 UTC
I really would like to have the sort order of folders per folder. Some folders I do need alphabetically sorted while others are sorted by date. 
Can you (maybe optional) enable that the sort order is simply stored per folder once the user changes it?

**Comment by XPoppyX** [comment] 2020-11-06 10:07
Duplicate of #530

**Closed** 2020-11-06 13:38 UTC
Labels: feature_request
