### ISSUE TITLE
Miller Columns

### ISSUE THREAD

**Issue by JanKrulak** [files-community/Files#2601] opened 2020-12-14 10:44 UTC
Dear Developers,

I have been using Files 0.21.1.0 barely 24hrs and I must say, that I love it. However, there is still some room for improvement in my opinion. 

The features which I miss are Miller Columns similar to mac Finder, and a preview by pressing the space key similar to Mac, or Seer does the same. 

Kind regards,

Jan Krulak

**Comment by Dylan-Osborne** [comment] 2020-12-14 10:57
If I'm correct the Miller Columns request is the same as #147. I think it's also being worked on at the moment. 

Files supports previews when pressing space through integration with QuickLook. You can install QuickLook from the [Microsoft Store](https://www.microsoft.com/en-us/p/quicklook/9nv4bs3l1h4s?activetab=pivot:overviewtab)

**Comment by JanKrulak** [comment] 2020-12-14 11:01
Thank you for the response!
Kind regards,
Jan
    On Monday, 14 December 2020, 10:57:25 GMT, Dylan Osborne <notifications@github.com> wrote:  
 
 


If I'm correct the Miller Columns request is the same as #147. I think it's also being worked on at the moment.

Files supports previews when pressing space through integration with QuickLook. You can install QuickLook from the Microsoft Store

**Comment by gave92** [comment] 2020-12-14 11:42
Closing this as duplicate of #147

**Closed by gave92** 2020-12-14 11:42 UTC
Labels: feature_request
