### ISSUE TITLE
Bug: Files crashes if startup folder is wsl directory

### ISSUE THREAD

**Issue by ElinLiu0** [files-community/Files#15772] opened 2024-07-07 16:48 UTC
### Description

I want to call the `files.exe` binary directly from my WSL Ubuntu vm,it can call but will be crash.
Instead of using `files.exe` in WSL Ubuntu vm,using `explorer.exe` just wokring fine as expect.
Just like below:

https://github.com/files-community/Files/assets/75596885/fe2bd0aa-3931-4568-b466-a71ecc2e0d4e

### Steps To Reproduce

1.Install a WSL Distro on your machine
2.Call `files.exe` directly in WSL Distro

### Requirements

Files will be start with a called wsl path.

### Files Version

3.5.0.0

### Windows Version

10.0.22631.3810

### Log File

N/A

**Comment by Josh65-2201** [comment] 2024-07-07 17:02
Thanks for the report, can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

**Comment by ElinLiu0** [comment] 2024-07-07 17:04
> Thanks for the report, can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.

[debug.log](https://github.com/user-attachments/files/16120089/debug.log)
Here it it mate,the original log.Hope you guys can fix that :)

**Comment by 0x5bfa** [comment] 2024-07-07 17:18
Log has nothing to indicate a crash occurred.

- Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?
- Check if you can call Files via `files.exe` from command prompt

**Comment by ElinLiu0** [comment] 2024-07-07 17:22
> Log has nothing to indicate a crash occurred.
> 
> * Could you try to find Files app from `Windows logs` > `Application` > sort by `Source` > `.NET Runtime` in Event Viewer?
> * Check if you can call Files via `files.exe` from command prompt

Sorry i don't understand.Where can i find Windows logs for you?

**Comment by Josh65-2201** [comment] 2024-07-07 17:24
It's in event viewer you can open that from the start menu search

**Comment by ElinLiu0** [comment] 2024-07-07 17:28
> It's in event viewer you can open that from the start menu search

![image](https://github.com/files-community/Files/assets/75596885/a1602aee-a6e2-4eaa-8c61-40b41a3e4b2a)
Only one error i can found here.

**Comment by ElinLiu0** [comment] 2024-07-07 17:30
> It's in event viewer you can open that from the start menu search

Also there a lot of warnning like this:
![Uploading image.png…]()

**Comment by 0x5bfa** [comment] 2024-07-07 17:30
The time this exception occurred is the same when you launched the app via the alias ‘files.exe’?

And image isn’t uploaded fully please wait a bit til the url gets generated.

**Comment by ElinLiu0** [comment] 2024-07-07 17:30
> It's in event viewer you can open that from the start menu search

Also there is a lot of warnning here:
![image](https://github.com/files-community/Files/assets/75596885/48d108a8-5449-4829-a54a-dab4276e488a)
Is it matter with this issue?

**Comment by ElinLiu0** [comment] 2024-07-07 17:32
> The time this exception occurred is the same when you launched the app via the alias ‘files.exe’?

Sure.

**Comment by ElinLiu0** [comment] 2024-07-07 17:33
> The time this exception occurred is the same when you launched the app via the alias ‘files.exe’?

![image](https://github.com/files-community/Files/assets/75596885/f53b4f1f-903f-48fe-b3a3-a317869aa87c)

**Comment by 0x5bfa** [comment] 2024-07-07 17:35
> Please also try preview version https://files.community/download

**Comment by Qin-shihuang** [comment] 2024-07-08 04:49
The issue can be triggered as follows in Powershell:

```
PS C:\Users> cd \\wsl.localhost\Arch\
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Arch> files.exe .
```

Arch is the name of any WSL distribution.

So the issue is related to the working directory being a WSL directory.

**Comment by ElinLiu0** [comment] 2024-07-08 04:54
> The issue can be triggered as follows in Powershell:
> 
> ```
> PS C:\Users> cd \\wsl.localhost\Arch\
> PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Arch> files.exe .
> ```
> 
> Arch is the name of any WSL distribution.
> 
> So the issue is related to the working directory being a WSL directory.
那这个事情就很邪门了，它能加载WSL的虚拟机文件树，但是不能在WSL中调用？😂

**Comment by yaira2** [comment] 2024-07-25 19:55
@Qin-shihuang can you navigate to the location in question if you open Files first?

**Comment by Qin-shihuang** [comment] 2024-07-26 01:53
@yaira2 Yes, in that case Files works well
![image](https://github.com/user-attachments/assets/c56dea67-d368-4d06-a582-9ba0b440de25)

**Comment by yaira2** [comment] 2024-07-26 01:59
Thank you for checking

**Comment by yaira2** [comment] 2024-09-09 17:18
> The issue can be triggered as follows in Powershell:
> 
> ```
> PS C:\Users> cd \\wsl.localhost\Arch\
> PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Arch> files.exe .
> ```
> 
> Arch is the name of any WSL distribution.
> 
> So the issue is related to the startup directory being a WSL directory.
> 
> Files stuck at `Files.App\Helpers\Application\AppLifecycleHelper.cs:140`, in `ConfigureHost`.

@Qin-shihuang do you know if there is a specific service causing the issue?

**Comment by Qin-shihuang** [comment] 2024-09-11 07:04
> do you know if there is a specific service causing the issue?

I'm not sure.

**Comment by yaira2** [comment] 2024-12-19 00:50
A fix will be included in the next release

**Closed** 2024-12-19 00:49 UTC
Labels: crash
