### ISSUE TITLE
unable to drag and drop files into browser for uploading

### ISSUE THREAD

**Issue by shriramnat** [files-community/Files#3282] opened 2021-01-25 02:59 UTC
The experience of using Files is hindered pretty much by the fact taht i am not able to upload files by dragging from files and dropping into a browser. it would be great to have this functionality

**Comment by Shomnipotence** [comment] 2021-01-26 11:52
Yes we need this feature

**Comment by winston-de** [comment] 2021-01-28 19:47
This should already be possible, I just tested it now and it works. What browser are you using?

**Comment by LoZeno** [comment] 2021-02-01 14:24
@winston-de 
> 
> This should already be possible, I just tested it now and it works. What browser are you using?

I am using version 1.2.0.0 of Files, and I can't drag files from Files and drop them onto any browser (I tried Firefox, Firefox Developers Edition, Chrome and Edge); I can't drag files from a pane to another, nor can I drag files from a root directory into a subdirectory.
In short, it doesn't look to me like ANY drag-and-drop is possible, not just to upload to browsers. @winston-de , is there a setting to switch on to have drag-and-drop enabled?

**Comment by winston-de** [comment] 2021-02-01 17:43
@LoZeno There is not, it should always be enabled. However, you do have to select the item you wish to drag before you can drag it, like this:

https://user-images.githubusercontent.com/59544401/106496017-3d739880-6471-11eb-9f80-b8c9733b0026.mp4

Could that have been your issue?

**Comment by shriramnat** [comment] 2021-02-01 18:14
> @LoZeno There is not, it should always be enabled. However, you do have to select the item you wish to drag before you can drag it, like this:
> 
>  8mb.video-Ov6-5JuLdtY8.mp4 
> Could that have been your issue?

THAT WAS IT - you had to first click to select and then click and drag again..i just tested it and it works for me as well..

however - that's super unintuitive though - idk what it takes to make it a single drag+drop gesture but that would be a super nice to have or at least some sort of tutorial at the beginning to tell ppl this is how it's done.

**Comment by LoZeno** [comment] 2021-02-01 18:21
> 
> 
> @LoZeno There is not, it should always be enabled. However, you do have to select the item you wish to drag before you can drag it, like this:
> 8mb.video-Ov6-5JuLdtY8.mp4
> 
> Could that have been your issue?

@winston-de Yes, that is my issue - I would have never figured out that I would need to click first to select the item, before dragging.

Thanks for that, now I know how it works. However, and I mean this in the most constructive way possible, this pattern breaks every established convention about drag-and-drop, no other application or OS that I know of requires to select a file with a click before clicking _again_ to drag. I agree with @shriramnat that this way is definitely unintuitive, especially compared to the native File Explorer in Windows.

**Comment by winston-de** [comment] 2021-02-01 18:39
@LoZeno @shriramnat 
Glad I could help. I agree that the current drag in drop is a bit unintuitive, and there is an issue open to address this, #673.

**Comment by KAMiKAZOW** [comment] 2021-03-07 13:00
Shouldn't this be closed as dupe of #673 then?

**Comment by winston-de** [comment] 2021-03-07 17:01
> Shouldn't this be closed as dupe of #673 then?

Probably.
@yair100?

**Comment by yaichenbaum** [comment] 2021-03-07 17:08
Merging with #673.

**Closed by yaichenbaum** 2021-03-07 17:08 UTC
Labels: feature request, triage approved
