### ISSUE TITLE
Feature: Warn the user about invalid tag name

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#11293] opened 2023-02-14 15:43 UTC
### What feature or improvement do you think would benefit Files?

When entering a name for a tag, some names makes the creation impossible. However, no information is displayed as to why the name is invalid.

The information should be given to the user and so should the reasons too.

### Requirements

- When the name used in the tag box in invalid, write a text underneath the text box to warn the user of the issue. 

### Files Version

Version 2.4.33.0

### Windows Version

W10 Home 22H2 19045.2251

**Comment by yaira2** [comment] 2023-02-14 15:46
What about a text block underneath the textbox? I think this is a little less "scary" but still get's the point across.

**Comment by yaira2** [comment] 2023-02-14 18:15
There is already an IsNameValid property, we can use a converter to invert the value and show the textblock when it's false.

**Comment by heftymouse** [comment] 2023-02-15 04:42
Could I work on this?

**Comment by meilluer** [comment] 2023-02-24 17:47
what makes a tag name invalid?

**Comment by yaira2** [comment] 2023-02-24 17:48
If it's a duplicate of another tag name or if the name is blank.

**Comment by meilluer** [comment] 2023-02-24 18:33
> If it's a duplicate of another tag name or if the name is blank.

finally where can i find all the predefined  tags names?

**Comment by meilluer** [comment] 2023-02-25 05:33
using namespace std;

int main() {
    string name;

    Console.WriteLine("Enter Tag name:");

    getline(Console.ReadLine(), name);

    if (name.empty()||name.find_first_not_of(' ') == string::npos) {
       Console.WriteLine( "NOT a valid name: tag name either empty or all spaces") ;
    }

    else if(name="Home","Work","important","photos"){
        Console.WriteLine("NOT a valid name: tag name alrady exist");
    }

    return 0;
}

this is what i came up with thus far i am having difficulty in incorporating this into program also i want to import all the stored tag names to check if they exist in in else if condition

**Comment by Josh-65** [comment] 2023-02-25 13:48
This is already being worked on. You can see the linked pull request and status of this issue.

**Comment by meilluer** [comment] 2023-02-26 05:18
> Could I work on this?

hello! are you working on this issue? i would like to contribute  my take on this issue but need help, can we connect on discord to futher discuss this issue?

**Comment by yaira2** [comment] 2023-02-26 05:23
@meilluer It's already being worked on.

**Closed** 2023-03-22 15:31 UTC
Labels: feature request, good first issue
